### PR TITLE
-Added eliminated getter and meter/discrepancy init to Empire Python API

### PR DESCRIPTION
**Pull request by geoffthemedio**
-Removed automatic meter init and updating in AIInterface turn init.
-Added code to init meters and discrepancies to Python code, except if empire has been eliminated.

### CODE REVIEW

**Comment by Vezzra** [comment]
Changes look fine, as far as I can tell, test runs ok on OSX. Unless someone of the AI team has any onjections, I guess that's fine for merge.

**Comment by geoffthemedio** [comment]
lacking any objections...

**Comment by Vezzra** [comment]
Is there a reason to keep the branch or did you just forget to delete it...?

**Comment by Cjkjvfnby** [comment]
Why not to run it in c code and skip call of generate orders?

**Comment by Vezzra** [comment]
I guess to give AI programmers more flexibility when handling eliminated empires...?

**Comment by geoffthemedio** [comment]
It's easier and doesn't require another recompile this way... and I suppose it might be clearer to Python coders what happening in the event it unexpectedly occurs.

**Pull request merged**
