### PR TITLE
Increase research and build costs for carriers

### PR DESCRIPTION
**Pull request by MichaelCourtney**
Unfortunately the forum is down and I can't open a discussion thread, hopefully people with an opinion will see it here.

This started with a question in my head about robotic interference shields, but when I compared them to other shields they seemed to be good value (12 robotics will match a plasma shield with less cost/shield). Then I asked whether shields are too expensive? Maybe, maybe not, but reducing their cost would just make direct weapons weaker and push more people towards carriers.

Carriers are the dominant choice in MP, it seems most players feel they are the best value for PP and RP. Proposed change is +5 PP/hanger. +25% RP on the base hanger tech, +20% RP on fighter 2, +10% RP on fighter 3 and no change to fighter 4.

### CODE REVIEW

**Comment by agrrr3** [comment]
hi i think this needs more details/analysis

+5 PP is a 50% cost increase for interceptor hangars (10PP) and only a 25% cost increase for heavy bombers (25PP).
balance slant/buff for the heavier hangars seems weird. are interceptors being used in MP? making those more expensive makes fighters more efficient (by making one of  the defensive options more expensive)

NB: the cost calculation for a carrier includes launch bay and hangar cost (and the different fighters were balanced against each other taking that into account). i also tried to give an incentive to use different carrier layouts (e.g. with hangar capacity higher than launch bay capacity), but adding something for the players like the grav pulse weapon (e.g. as a core part) which shoots down fighters only in the second bout might be more effective for that; boosting flak and/or interceptors would also decrease fighter efficiency. one idea would be to allow flak in internal slots - empires researching carriers are "supposed" to put interceptor hangars there; direct weapon researchers have that slot open (not sure though if having a hidden asteroid filled up with flak makes any sense). 

As part of the analysis I would ask: what is full launch cost in PP per fighter now and after the change? interceptor cost needs also to be balanced against flak (note that interceptors are also decoys soaking striker/bomber damage).

if increasing PP cost, i am also rather for increasing the hangar costs.
better would be to buff the defensive options. make flak useful (not sure how), add the grav pulse weapon for early use with the composite spatial flux hull (not sure where to put the unlock).

**Comment by MichaelCourtney** [comment]
Yes, I'm not sure the details are right either. Sounds like the forum will be back up soon. Some quick comments:

It looks like a 50% increase on interceptors, the reality is the interceptor part is a tiny portion of total ship cost. A linear cost increase keeps 2 strike fighters inline with bomber + interceptor.

I only touched hangers as single hanger carriers like the robotic seemed better balanced then double hanger symbiots and asteroids.

Flaks are great on the good pilots. Eawax and Mu Ursh flaks fire at 5x a round.

**Comment by agrrr3** [comment]
> It looks like a 50% increase on interceptors, the reality is the interceptor part is a tiny portion of total ship cost. A linear cost increase keeps 2 strike fighters inline with bomber + interceptor.

? you did not suggest a linear increase

do people in MP use interceptors and flak? 

If those are not considered good options in a meta where  there are lots of fighters/"everybody" uses fighters, that is an indication those need a buff.

 
> Flaks are great on the good pilots. Eawax and Mu Ursh flaks fire at 5x a round.

Yes, I also think flak are great options. A fighter downed in bout 2 only does a third its maximum damage.
Do players use flak -and if not- why not?

We could add a automation tech which adds +1 shot (but does not necessarily stack with pilot ability).

What we are missing is also an analysis/plot how many shots one needs to down e.g. 80% of fighters in a bout (because of overkilling/hitting the same fighter multiple times). Then we had a reference point how to compare the power of number of fighter vs anti-fighter shots.

**Comment by MichaelCourtney** [comment]
> > It looks like a 50% increase on interceptors, the reality is the interceptor part is a tiny portion of total ship cost. A linear cost increase keeps 2 strike fighters inline with bomber + interceptor.
> 
> ? you did not suggest a linear increase

Perhaps a poor choice of words. My main points were that currently 2 strike carriers is the same cost as 1 bomber + interceptor carrier and that remains the same (also remains the same if its a direct proportional increase) and that the actual increase for the whole ship is much closer together. For a double hanger symbiot its 20% on an interceptor and 12% on a heavy bomber. With a direct % increase on a heavy bomber it'd be 30%. For a static its 16% and 11% (or 26% with a proportional increase). Heavy bombers are the least used carrier, they don't need the nerf.

> do people in MP use interceptors and flak?
> 
> If those are not considered good options in a meta where there are lots of fighters/"everybody" uses fighters, that is an indication those need a buff.

DrKosy had flaks last MP. People usually use strike fighters, or a bomber/interceptor combination. Flaks are probably rarer then interceptors but I've also used them. I find them good as a cheap anti-fighter option. People also use flux lances all the time. Seems every ship that has a spare internal slot for them seems to have 1.

**Comment by MichaelCourtney** [comment]
Pretty sure it was decided to handle this in a different way. Superseded by:

https://github.com/freeorion/freeorion/pull/4941

**Pull request closed without merging**
