### PR TITLE
Always Enable Screensaver

### PR DESCRIPTION
**Pull request by geoffthemedio**
Should address complaints in https://github.com/freeorion/freeorion/issues/613#issuecomment-294443063

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@Voker57 @l29ah Comments / feedback?

**Comment by Voker57** [comment]
Fine by me, as I don't need screensaver disabling functionality at all.

// Why comment-out, not delete?

**Comment by geoffthemedio** [comment]
@Voker57 @l29ah bump?

**Comment by l29ah** [comment]
It works.

**Comment by Vezzra** [comment]
Alright, closing this as resolved.

**Comment by Vezzra** [comment]
Sorry, thought this was an issue that had been resolved. 😳  Reopened the PR.

Which means, as the PR apparently works, can it be merged?

**Pull request merged**
