### PR TITLE
Exclude data for universe generator from checksum

### PR DESCRIPTION
**Pull request by o01eg**
This allows to tune universe generator without desyncing checksum with client.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I'm uncertain about whether this makes sense. The spawn rate and limit are part of the parsed data, so do make some sense to include in the checksums. Part of the point is to verify that everything is scripted as expected and not modded, which includes span conditions during universe generation. That said, the spawn rate and limit don't affect the game after galaxy gen, and galaxy gen could be modded without affecting any scripted content checksums...

**Comment by o01eg** [comment]
> Part of the point is to verify that everything is scripted as expected and not modded,

I suppose it's OK for the game to be modded nowadays.

**Comment by geoffthemedio** [comment]
> it's OK for the game to be modded

Modded unexpectedly, I mean. If the client has the same mod applied, it will give the same checksum.

**Comment by agrrr3** [comment]
I think it could make a little sense to have a way to check the generated galaxy if you know the galaxy seed. if the seed, the generation scripts and input do create a different galaxy you could diff it.

I think a "wrong" galaxy should not prevent from playing.

The use case I guess o01eg wants to support is modding the galaxy without having to push the code to all clients (which is a hassle currently)

**Pull request merged**
