### PR TITLE
give Megalith effects different stacking groups

### LINKED ISSUE #4669: Megalith doesn't increase Infrastructure by 30, it sets it to 30
* **FreeOrion Version**:
0.5
* **Operating System**:
Linux
* **Fetched as** 
Flatpak

Description
-----------
Well the title pretty much sums it up. I built a megalith on my capital and the infra started dropping from 46 to 30.

### PR DESCRIPTION
**Pull request by geoffthemedio**
Probably fixes #4669

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I suppose @Vezzra should wait for some confirmation that this actually worked before picking to release

**Comment by Vezzra** [comment]
Ok, I'll wait - give me a heads up when it's ok to do the cherry picking...

**Comment by MXB2001** [comment]
I edited the changes into my copy of FO (0.50) and it works as far as the infrastructure goes although I was surprised to see that the megalith 30 seems to have replaced the palace bonus rather than adding to it (which the text seems to imply but maybe should not?). The 1 turn meter change does take 2 turns though that may be the usual freeorion "turn order effect" since the meter does change all the way on the second turn but not on the first turn after the focus change.

**Comment by Vezzra** [comment]
Is that good enough as a confirmation that the fix works, or should I wait for more feedback before doing the cherry picking?

**Comment by agrrr3** [comment]
megalith effect was confirmed (on last weeks build i guess) by blueaward
https://freeorion.org/forum/viewtopic.php?t=12858&sid=d9fb1ba887c0dc89e5cd2180afb67314

**Comment by Vezzra** [comment]
Cherry picking done: 75517b4b14cb451c18268c81e6c894726840d6ee

**Pull request merged**
