### PR TITLE
Don't save game with incorrect turn number

### PR DESCRIPTION
**Pull request by o01eg**
Could be backported to 0.4.10.2

### CODE REVIEW

**Comment by geoffthemedio** [comment]
could you elaborate on or make more specific the commit message? as written, it's not clear what is meant and it can be interpreted different ways...  Some info about when this could occur, or that you don't know when but have observed that for some reason something happens that leads to an "incorrect" turn number being saved, and what actually "incorrect" means, would be better...

**Comment by o01eg** [comment]
@geoffthemedio Sometimes the server saves game with -65535 as turn number. It often happens if the server lacks free space, and saves incomplete file, and then loads it.

**Comment by Vezzra** [comment]
> Could be backported to 0.4.10.2

Is the issue this PR addresses something sufficiently serious? There are probably a lot of things that could be backported, but for 0.4.10.2 we're trying to keep things to a minimum, so...

**Comment by geoffthemedio** [comment]
> @geoffthemedio Sometimes the server saves game with -65535 as turn number. It often happens if the server lacks free space, and saves incomplete file, and then loads it.

OK, can you put that in the commit message and probably also in a comment in the code where the check is done, saying that in the case that such an invalid turn number is found, saving is skipped since something has already gone wrong, so it doesn't make sense to create a broken save...?

**Comment by o01eg** [comment]
@Vezzra No, it mostly fixes consequences of other issues.

**Comment by Vezzra** [comment]
@o01eg, well, I'll leave the decision whether to backport this to the 0.4.10 release branch or not to @geoffthemedio and you. I don't think it's necessary, but if you want to include it, I won't object.

**Comment by o01eg** [comment]
@Vezzra Yes, it doesn't fix anything very important.

**Pull request merged**
