### PR TITLE
Nerf pop-based bonuses (-50% to -80%) to reduce snowballing

### PR DESCRIPTION
**Pull request by Oberlus**
Early, small bonuses are halved.
Big bonuses are divided by five.
Some are in between.

Techs like Quantum Networking or Solar Orb. Gen. (in blue star) no longer cause a sharp spike in the output graph.

Maximum pop-based bonus goes down from aprox. 3.2 to 1.0 (including the initial 0.2 per pop for average species).

In the following tables:
- RP prev. refers to the sum of RP required to unlock the tech/building.
- RP and turns refer to the actual tech that grants the bonus or unlocks the building that does it.
- Turns prev. refers to the minimum number of turns required to unlock the tech/building (hence it is not the sum of turns of all prerequisites). For Black Hole Power Generator this assumes PR #2940.
- Focus: needs research/industry focus.
- Bld.: it is a building.
- Rstrc.: special restrictions apply for the bonus to be granted.
- Bonus (and Before): calculated with respect to standard RESEARCH_PER_POP and INDUSTRY_PER_POP (currently both are 0.2).
- Total: sum of bonus for end-game considering the expected average in case of system-dependent bonuses and the best bonuses in case of mutually-exclusive (total accounts for the bonuses in italics).

RESEARCH

Tech or Building | RP prev. | Turns prev. | RP | Turns | Focus | Bld. | Rstrc. | Bonus | Before
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
*Algorithmic Elegance* | 0 | 0 | 24 | 3 | Yes | No | No | 0.05 | 0.1
*Quantum Networking* | 334 | 17 | 400 | 6 | Yes | No | No | 0.1 | 0.5
*Distrib. Thought Comp.* | 656 | 11 | 150 | 5 | No | No | No | 0.1 | 0.1
Distrib. Thought Comp. (psi) | 206 | 11 | 150 | 5 | No | No | No | 0.1 | 0.1
Stellar Tomography (black hole) | 1134 | 23 | 250 | 6 | Yes | No | No | 0.2 | 1
(neutron) | 1134 | 23 | 250 | 6 | Yes | No | No | 0.15 | 0.75
*(blue/white)* | 1134 | 23 | 250 | 6 | Yes | No | No | 0.1 | 0.5
(yellow/orange/red) | 1134 | 23 | 250 | 6 | Yes | No | No | 0.05 | 0.2
*Collective Thought Net.* | 1034 | 23 | 800 | 7 | Yes | One | Yes | 0.1 | 0.5
*Enclave of the Void* | 1856 | 28 | 300 | 5 | Yes | One | No | 0.15 | 0.75
*Energy Metabolism* | 2488 | 27 | 400 | 15 | Yes | No | No | 0.2 | 0.5
**Total** |   |   |   |   |   |   |   | 0.8 | 2.95

INDUSTRY

Tech or Building | RP prev. | Turns prev. | RP | Turns | Focus | Bld. | Rstrc. | Bonus | Before
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
*Robotic Production* | 0 | 0 | 24 | 3 | Yes | No | No | 0.05 | 0.1
*Fusion Generation* | 24 | 3 | 48 | 3 | Yes | No | No | 0.05 | 0.2
Solar Orbital Gen. *(blue/white)* | 260 | 10 | 200 | 8 | Yes | One | No | 0.15 | 0.4
(yellow/orange) | 260 | 10 | 200 | 8 | Yes | One | No | 0.1 | 0.2
(red) | 260 | 10 | 200 | 8 | Yes | One | No | 0.05 | 0.1
Industrial Center I | 24 | 3 | 60 | 4 | Yes | One | No | 0.05 | 0.2
II | 84 | 7 | 300 | 5 | Yes | One | No | 0.1 | 0.4
*III* | 384 | 12 | 1000 | 7 | Yes | One | No | 0.15 | 0.6
*Collective Thought Net.* | 1034 | 23 | 800 | 7 | Yes | One | Yes | 0.1 | 0.5
*Energy Metabolism* | 2488 | 27 | 400 | 15 | Yes | No | No | 0.1 | 0.2
Hyperspatial Dam | 334 | 17 | 400 | 5 | Yes | One | Yes | 0.2 | 1
*Black Hole Gen.* (available) | 1744 | 18 | 300 | 4 | Yes | One | No | 0.2 | 1
(create) | 2444 | 37 | 300 | 4 | Yes | One | No | 0.2 | 1
**Total** |   |   |   |   |   |   |   | 0.8 | 3

Edit: rebalanced also the pop-based, empire-wide specials:
- Computronium Moon: down to 0.05 from 0.2, monster buffed to SM_GUARD_2, or Moderate Tech Ancient Guardians when Specials:None or AI_Aggression:Beginner.
- Honeycomb: down to 0.1 from 0.5, defend them with High Tech Ancient Guardians when Specials:None or AI_Aggression:Beginner.

### CODE REVIEW

**Comment by Oberlus** [comment]
@Vezzra I request your review.

**Review by Vezzra — COMMENTED** [review]
I strongly suspect that those values will need to be nerfed even more, but I guess what you've come up with here is a good start. Anyway, only playtesting will give us a feeling how much these adjustmenst will affect resource production, and help us decide how the numbers need to be tweaked further.

One thing, though, which I think should also be adjusted, are the pop based boni provided by specials. If those remain unchanged, I expect them to be somewhat unbalanced compared to the boni provided by techs and buildings, as the nerfs there have been quite substantial.

Lastly, I expect these changes to affect AI performance a lot, therefore I think this should be merged post-release. @freeorion/ai-team, can anyone of you comment on this?

**Comment by Oberlus** [comment]
> only playtesting will give us a feeling how much these adjustmenst will affect resource production, and help us decide how the numbers need to be tweaked further.

Agree. I encourage merging this (even for v0.4.10 release) to get feedback from more players.
The strongest effects of this changes are late game, which should not create big gameplay changes, apart from making the winning empire less winning.
However, the nerf of the early game boosts might have deeper effects on gameplay, because homeworlds now are even more important (produce more than what you can get with colonization).
Particularly, it could make more interesting than currently to focus on early tech military and go for conquest (so that you get homeworlds, powerhouses), than to spend more time on tech development.
The flat bonuses have not been changed, particularly because of the above, so that peaceful expansion with NAI, AA and GGG is as interesting (or even more) than before.



> One thing, though, which I think should also be adjusted, are the pop based boni provided by specials. If those remain unchanged, I expect them to be somewhat unbalanced compared to the boni provided by techs and buildings, as the nerfs there have been quite substantial.

Agree. This applies to Computronium Moon and Honeycomb, the only ones that are empire-wide.
I'll add to this PR another commit for those. Should come accompanied with a boost to the monsters of Computronium, too easy even for current values.
The other specials, that only affect a single planet, are not that much of a problem, IMO.

**Comment by Oberlus** [comment]
First comment updated with the changes for Computronium Moon and Honeycomb.

I've added two new macros: GUARD_MONSTER_2 and _3, to balance the above specials, which where agreed to be too easy to get (in any settings, for the Computronium Moon, or when set to no monsters, for the Honeycomb)
[Related thread](https://www.freeorion.org/forum/viewtopic.php?f=15&t=11431).

@agrrr3 Could you give a quick look at the latest commit to see if I did something wrong with the new macros? I got no errors, but still.

**Comment by agrrr3** [comment]
> @agrrr3 Could you give a quick look at the latest commit to see if I did something wrong with the new macros? I got no errors, but still.

Looks good to me

**Pull request merged**
