### PR TITLE
Native/Special Defense Tweaks

### PR DESCRIPTION
**Pull request by MichaelCourtney**
https://freeorion.org/forum/viewtopic.php?f=15&t=12316

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
A note about (https://github.com/freeorion/freeorion/pull/3722/commits/446488e252c8f76cd0c26b3a10177ed8b6b310dc). If I remove the probability check all snowflake/juggernaut nests end up with cloud cover, but only some Kraken Nests will have it. I am not sure why that happens.

**Comment by MichaelCourtney** [comment]
The probability here is about 35% on a Gisguff colony. It could be scaled up or down. I'm also not sure if there's a cleaner way to write this. I added the Pop factor as some natives no longer seem to be research or industry focused by default.

FORTICATION_PROBABILITY
'''0.07 * (0.1 * Source.TargetPopulation + Source.TargetResearch + Source.TargetIndustry + 0.33 * Source.TargetInfluence)'''

**Comment by MichaelCourtney** [comment]
Also its possible to separate out less controversial changes if you wish. For example I could put the restriction of 57s to no greater then medium in its own commit.

**Comment by Oberlus** [comment]
> FORTICATION_PROBABILITY '''0.07 * (0.1 * Source.TargetPopulation + Source.TargetResearch + Source.TargetIndustry + 0.33 * Source.TargetInfluence)'''

For a species not PP/RP/IP focused it's 0.1*pop +0 +0 +0.33*0 = 0.9 for pop 9, 2.5 for pop 25.
For PP or RP focused: 0.1*pop + 0.2*Species_Trait*pop = 0.3*ST*pop = 2.7, 7.5
For IP: 0.1*pop + 0.33*sqrt(pop) = 1.9, 4.17 

What about using just TargetPopulation, optionally with factors for selected species trait?

`FORTICATION_PROBABILITY '''0.02 * Source.TargetPopulation'''`

**Comment by MichaelCourtney** [comment]
> > FORTICATION_PROBABILITY '''0.07 * (0.1 * Source.TargetPopulation + Source.TargetResearch + Source.TargetIndustry + 0.33 * Source.TargetInfluence)'''
> 
> For a species not PP/RP/IP focused it's 0.1_pop +0 +0 +0.33_0 = 0.9 for pop 9, 2.5 for pop 25. For PP or RP focused: 0.1_pop + 0.2_Species_Trait_pop = 0.3_ST_pop = 2.7, 7.5 For IP: 0.1_pop + 0.33*sqrt(pop) = 1.9, 4.17
> 
> What about using just TargetPopulation, optionally with factors for selected species trait?
> 
> `FORTICATION_PROBABILITY '''0.02 * Source.TargetPopulation'''`

Could do. Using the target research was a way of avoiding having to check a lot of tags. Is the species good research? very good research? ultimate research? good industry? great industry?

Hence just looking at the research/industry/influence meter. Though natives on defense/growth focus does throw a spanner in the works.

**Comment by MichaelCourtney** [comment]
I guess there's also Max(Pop factor, RP/PP/IP factor) with the 2 equal for a standard RP/PP native?
Edit: Small note, the natives aren't at max. pop on turn 1 when it checks.

**Comment by Oberlus** [comment]
> I guess there's also Max(Pop factor, RP/PP/IP factor) with the 2 equal for a standard RP/PP native? Edit: Small note, the natives aren't at max. pop on turn 1 when it checks.

I guess the formula you have in the commits is OK.
Use Target Population to avoid the "natives aren't at max"?

**Comment by MichaelCourtney** [comment]
> > I guess there's also Max(Pop factor, RP/PP/IP factor) with the 2 equal for a standard RP/PP native? Edit: Small note, the natives aren't at max. pop on turn 1 when it checks.
> 
> I guess the formula you have in the commits is OK. Use Target Population to avoid the "natives aren't at max"?

I wasn't sure which I preferred, there's a certain logic to not fully grown colonies not having their defenses up.  RP/PP are still going to be based on current population. Guess it doesn't matter though, it'll just default to max. pop in that case. I'll change it then squash the relevent commits together.

**Comment by geoffthemedio** [comment]
Is this done / ready, or is there relevant discussion still ongoing on the forums?

**Comment by MichaelCourtney** [comment]
Yes its ready.

**Pull request merged**
