### PR TITLE
Fix Godot Android setup on CI

### LINKED ISSUE #4336: Android Builds Failing
https://github.com/freeorion/freeorion/actions/runs/3613945375/jobs/6090282988

Probably not related to that banch's changes...

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #4336

### CODE REVIEW

**Comment by bend-n** [comment]
not needed anymore

**Comment by bend-n** [comment]
i wonder if i should do tags and stuff to prevent this...

**Comment by geoffthemedio** [comment]
test builds have an annotation:
````
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
````

Otherwise I see green checks.

**Comment by bend-n** [comment]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

[not my fault](https://github.com/bend-n/godot-actions/commit/e07f4fba9b2e1acf9044c295fd26a3e45349d7fa), and not related to this prs changes.

**Comment by o01eg** [comment]
> test builds have an annotation

Looks like it from `suisei-cn/actions-download-file`, I'll try to update it.

**Comment by bend-n** [comment]
Why use `suisei-cn/actions-download-file`? just `run: wget url -O tmp.zip && unzip tmp.zip -d ../`

**Comment by o01eg** [comment]
@bend-n Partially for universal use between different OS on CI.

**Pull request merged**
