### PR TITLE
AI: Add fleet target to its name.

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
As human I cant see enemy fleet name so it will not affect gameplay.

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
I am a bit reluctant to count on fleet name visibility not changing-- I think that while you have been here ship name visibility has changed, for example.  I presume the purpose of this is to facilitate review of logging info by tacking this bit of extracted mission info to the fleet name?  What I would suggest instead is that rather than submitting a true rename order, you set some info purely within the extend_free_orion_AI_interface code, which you can then access when printing fleet info.

**Comment by MatGB** [comment]
Shipname visibility hasn't changed, but there was general (I think) agreement it should do. Fleetname visibility is fairly pointless and I wouldn't see any benefit of revealing it (I rarely, if ever, change my fleetnames these days), so it'd almost certainly be fine, but it's not my area at all.

**Comment by Dilvish-fo** [comment]
> Shipname visibility hasn't changed

it's a minor point of FO history, I suppose, but I'm pretty sure that at least for monsters it has -- you didn't used to see their names; I'm pretty the thing that changed was visibility handling.

**Comment by MatGB** [comment]
Ah, yes, that has changed, it was when, um, someone rescripted the shipnaming system across the board and made some of the names lists not used by certain things. But, that's for independent monsters, not for enemy ships/fleets. I'd like ships to also be visible in the same way, but don't see any reason at all to reveal fleet names, especially if there's a use for them your side, but if there's a different (better?) way to do it, well, your call.

**Comment by Dilvish-fo** [comment]
> especially if there's a use for them your side

Well, so far I don't see any use on the AI side to change the actual name of the fleet, but Cj can explain that if he thinks there is.

**Comment by geoffthemedio** [comment]
Something about "AI" in this PR name / commit description would be helpful.

**Comment by Cjkjvfnby** [comment]
It is done to make logging more simple.  Current name `Fleet 15` is not useful. :)

I did not notice any difference between name and current mission (I check them both) but I see fleets that never have any mission (`Colony fleet`)

 I see this PR as chip upgrade of logs.  If you don't like it just close this pr.

**Comment by Dilvish-fo** [comment]
It seems to me it would be a pretty small adaptation to store this info on the AI side of the interface, and still have it print out with (or instead of) the fleet name, if you really want that.  But it's also easy to just print out the mission target when you want it.  I really don't like the idea of encoding the mission targets into the actual C++ side fleet name.

> I see fleets that never have any mission (Colony fleet)

Ah, don't you just mean "that hadn't _yet_ had a mission' ?  Colony Fleets still get missions-- they aren't somehow navigating to planets and colonizing them without the AI giving them a mission are they?  Sometimes it can take quite a while for a suitable colony target to be found.

**Pull request closed without merging**
