### PR TITLE
Simplify AI client

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR replaces the `AIBase` interface and subclasses with direct calls from boost::python.  That interface were assumingly used during the C++ to Python AI implementation migration before v0.3 times.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I think the idea was to have an implementation-independent interface for AIs, rather than baking in / assuming that the only supported AI is one implemented in Python.

**Comment by adrianbroher** [comment]
Do you see any non Python-AI implementation?  Do you see a need for a non-Python AI implementation?  What is the gain of having complex code over something that most certainly will never be created?

Keep it simple.

**Comment by geoffthemedio** [comment]
I wasn't objecting to the changes, but explaining the idea behind the old design...

**Comment by adrianbroher** [comment]
> I wasn't objecting to the changes, but explaining the idea behind the old design...

Ah, ok.  Sorry, I misunderstood your reply.

**Pull request merged**
