### PR TITLE
Generate NSIS installer for Windows

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by Vezzra** [comment]
>     * Now it misses `..\..\vcredist_x86.exe`. Which one is used?

The most recent one you can get from MS should do it. AFAIK the most recent version includes all "redistributables" needed by sufficiently recent apps build with MS VS.

I've attached the version I currently use for the FO installer package:
[vcredist_x86.exe.zip](https://github.com/freeorion/freeorion/files/9733497/vcredist_x86.exe.zip)

**Review by Vezzra — COMMENTED** [review]
Otherwise looks reasonable - as far as I'm able to tell, that is... 😉

**Comment by o01eg** [comment]
I'll try to use https://github.com/freeorion/freeorion/files/9733497/vcredist_x86.exe.zip as source in Github Actions.

**Comment by o01eg** [comment]
@Vezzra Could you check installer generated in https://github.com/freeorion/freeorion/actions/runs/3207186911 ?

**Comment by Vezzra** [comment]
Will try to get to that tomorrow (Monday).

**Review by Vezzra — APPROVED** [review]
The installer created by the Github action works flawlessly. Even the filename of the installer executable is exactly the same as when I run the build procedure on my Windows system.

(The only thing is that the installer executable gets packaged into a ZIP archive and needs to be unzipped. For uploading to SourceForge it would be better if the executable could be used, and not the ZIP archive.)

**Comment by o01eg** [comment]
> (The only thing is that the installer executable gets packaged into a ZIP archive and needs to be unzipped. For uploading to SourceForge it would be better if the executable could be used, and not the ZIP archive.)

This is how Github Actions artifacts works. SF deploy will push .exe file.

**Pull request merged**
