### PR TITLE
Updated the Planetary Garrison techs:

### PR DESCRIPTION
**Pull request by Deepsloth**
- Planetary Garrison 1 and 3 will no longer be affected by species modifier.
- Planetary Garrison 2 and 4 will now grant 0.2 troops per population.

### CODE REVIEW

**Comment by Deepsloth** [comment]
Updated the PR as discussed here:http://www.freeorion.org/forum/viewtopic.php?f=28&t=9567&start=28

**Comment by Dilvish-fo** [comment]
Sloth, this seems to have gotten into conflict with current master somewhere.  Could you please rebase this branch on top of current master? (And be sure to note that in the conversation here once you have.)

**Comment by Deepsloth** [comment]
I've created a new and clean PR.

**Comment by Dilvish-fo** [comment]
for history/reference, the new PR is #200

**Pull request closed without merging**
