### PR TITLE
Fix zero division in shield factor calculation see #3257

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
It is a rare issue that was reported by user. I have extracted logic to a separate function and add a protection for case when number of shots is zero.  It is not clear why does it happens, maybe  because of some species treats. Issue was introduced on turn 721, maybe it was some impure which was almost destroyed and its stats was not very actual.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I don't think we plan another v0.4.10 bugfix release, so not sure what you mean with the cherry-pick-for-release tag...

**Comment by Cjkjvfnby** [comment]
> I don't think we plan another v0.4.10 bugfix release

This issue was reproduced in the released version.

**Comment by geoffthemedio** [comment]
I guess we can pick it into the v0.4.10 release branch anyway, even if no release is planned? @Vezzra ?

**Comment by Vezzra** [comment]
Well, of course we could cherry pick it to the 0.4.10 release branch regardless if we actually do another bugfix release for 0.4.10. However, in that case what should we set the milestone to? 0.4.10.2 doesn't exist yet. 0.5 would be misleading if we do 0.4.10.2.

It's probably better to just keep the "cherry-pick for release" tag, which I'm going to check whatever the next release will be. At that point we'll know for sure and can set the right milestone (and do the cherry picking then).

**Pull request merged**
