### PR TITLE
Separate GalaxySetupData into dedicated TU and refactoring

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR separated the `GalaxySetupData` struct into a different translation unit. It also:

* ~~Moves the code responsible for loading the galaxy setup from the options database into the `GalaxySetupData::LoadFrom` method.~~
* ~~Moves the code responsible for saving the galaxy setup into the options database into the `GalaxySetupData::SaveTo` method.~~
* ~~Removes various `GalaxySetupData::*` getters and use instead the existing `GalaxySetupData::GetSetupData(GalaxySetupData&)` method.~~
* ~~Moves the code responsible for calculating the hash from the galaxy setup seed into the `GalaxySetupData::GetSeedHash` method.~~
* ~~**Possible Bugfix**: the seeding calculation within the Server FSM used an `int` to store the seed when loading a save game. This may has truncated the hash seeded the game, whereas everywhere else an unsigned int was used or the interfaces expect an unsigned.  Now all locations `unsigned int`s to store the hash.~~
* ~~Replaced the `GalaxySetupData::SetSeed(const std::string&)` with `GalaxySetupData::PinSeed`.  The function still checks if the now assigned `GalaxySetupData::m_seed` holds a special `"RANDOM"` token or is empty and replaces it with a new and random token.~~
* ~~Removed the per-attribute copying in `LoadEmpireSaveGameData` with a call to the copy constructor of `GalaxySetupData`.~~
* Removed the `m_` prefix for all `GalaxySetupData` attributes as those attributes are public accessible.  Backwards compatibility with serialization is preserved by keeping the names of the `boost::serialization` name-value pairs.

### CODE REVIEW

**Comment by adrianbroher** [comment]
What is the status on this PR?

**Comment by adrianbroher** [comment]
Updated to master.

**Comment by geoffthemedio** [comment]
needs another rebase...

**Comment by adrianbroher** [comment]
Updated to master.

**Comment by geoffthemedio** [comment]
with this applied, quickstarting gets stuck with the client messages window saying "Generating Universe".
[freeoriond.log](https://github.com/freeorion/freeorion/files/4742430/freeoriond.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/4742431/freeorion.log)

**Comment by adrianbroher** [comment]
Noted, will take a look at it later.

**Comment by adrianbroher** [comment]
I cannot reproduce this.  The game starts up fine from both the "Quick Start" button and `-q` command line.

**Comment by geoffthemedio** [comment]
Rebuilt from a clean solution and got the same result.

**Comment by adrianbroher** [comment]
Dropped everything except moving the struct into a separate TU and removing the `m_` attribute prefix.

**Comment by geoffthemedio** [comment]
Game starts with 0 AIs, but if I add 1 AI in single player setup, it hangs at "Generating Universe".

[freeorion.log](https://github.com/freeorion/freeorion/files/4842776/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/4842777/freeoriond.log)

**Comment by adrianbroher** [comment]
I drop this PR then because I cannot be bothered to guess what is wrong with Windows.

**Pull request closed without merging**
