### PR TITLE
Link planet density setting to nebulae planet creation.

### PR DESCRIPTION
**Pull request by dbenage-cx**
Issue #628 

Separate effectgroup for each planet density setting, for nebulae planet creation macro.

Feedback requested on desired outcome of each setting.

### CODE REVIEW

**Comment by Vezzra** [comment]
Bump... anyone game to test this?

**Comment by Vezzra** [comment]
Bump the second... if no one has time to test this I understand (I too won't have time for that), however, then I'm going to merge this one blindly (code looks reasonable).

**Comment by MatGB** [comment]
Appears to work fine

**Comment by MatGB** [comment]
Of course, immediately after it goes live in a Test release I spot the problem
sidepanel-nebula

All the planets have the same number. Can't see immediate problem, ideas?

**Comment by dbenage-cx** [comment]
I missed that the stringtable entry was fixed:
[en.txt:162](https://github.com/freeorion/freeorion/blob/master/default/stringtables/en.txt#L162)

> assumes no previous planets present, so the created planet will be the Systemname I planet...
> NEW_PLANET_NAME
> %1% I

(asteroids too)
Needs to be incremental somehow, will start looking into a proposal.

**Pull request merged**
