### PR TITLE
Improved slot positions of ship hulls.

### PR DESCRIPTION
**Pull request by Deepsloth**

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
I agree that a lot of the new placements seem visually nicer.  I hesitate over one aspect -- it seems like in the past, the sequence of slots in the hull specification would correspond to the visual layout going left-to-right and top-to-bottom, which has some benefits for those (admittedly rarish) times when a ship specification is being made manually (like for a monster fleet).  Perhaps that's not enough to be concerned with, and perhaps the "rule" was already broken and I just didn't notice, but I thought we should at least discuss the issue a bit here.  It could be that you simply do another pass and reorder the slots to fit the new visual layout (though then perhaps many people's saved designs will be invalid, I'm not sure what happens then).

**Comment by Deepsloth** [comment]
The "rule" has already been broken several times. For example SH_LOGISTICS_FACILITATOR, SH_ASTEROID, SH_SCATTERED_ASTEROID, SH_CRYSTALLIZED_ASTEROID, ...
Considering these scripts actually define the number of different slots, the ordering of external first, then internal and lastly core makes much more sense, because a scripter can see the slot distribution at a glance and isn't forced to search and count the 2 internal slots hidden between 15 external ones.

**Comment by MatGB** [comment]
Oh, I like this, this must've taken you ages to check and position, well done.

Does remind me how ugly the Sentient artwork is, might be OK within, say, the Robotics line, but it's nowhere near as cool as the rest of the Organic stuff.

**Comment by MatGB** [comment]
Oh yeah, works fine with savegames and saved designs, my Titans look pretty cool int eh design window now.

**Pull request merged**
