### PR TITLE
Refactor python parser for single-parameter math functions

### PR DESCRIPTION
**Pull request by o01eg**
Follows up #3862

### CODE REVIEW

**Comment by geoffthemedio** [comment]
why?

**Comment by o01eg** [comment]
@geoffthemedio Those tokens not used in existing FOCS files so I removes them in a hope to reduce needed compilation resources. Also I moves their implementation to Python parser so it won't be lost they will be needed somehow.

**Comment by Vezzra** [comment]
@o01eg, superseded by which PR?

**Comment by o01eg** [comment]
@Vezzra By #3853

**Pull request closed without merging**
