### PR TITLE
Fix mklink usage on windows

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
With fbfae4348c4bfb2e953ce77dab10c0218e1bd470 on master,
````
  -- Executing cmd /C mklink /J test-scripting C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\test-scripting at C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\Release
  -- mklink result 0 output Junction created for test-scripting <<===>> C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\test-scripting
   error 
  -- Executing cmd /C mklink /J default C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\default at C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\Release
  -- mklink result 0 output Junction created for default <<===>> C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\default
   error 

````

**Comment by o01eg** [comment]
Yes, I'm not sure why it doesn't work without cmd /C but at least it works now.

**Comment by geoffthemedio** [comment]
When I start freeorion, I get a bunch of parse errors in the log file...
````
20:50:46.446554 {0x0000639c} [debug] client : GGHumanClientApp.cpp:357 : Started background parser thread
20:50:46.446554 {0x0000639c} [info] client : NamedValueRefManager.cpp:45 : NamedValueRefManager::NameValueRefManager constructs singleton 015614D0
20:50:46.453554 {0x0000649c} [error] client : Parse.cpp:221 : Exception caught regex parsing script file C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default\scripting/common\named_values.focs.txt: boost::filesystem::weakly_canonical: The system cannot find the file specified
20:50:46.455555 {0x0000649c} [error] client : Parse.cpp:166 : C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default/scripting/common/named_values.focs.txt: Unresolved macro reference: RESEARCH_PER_POP
20:50:46.455555 {0x0000649c} [error] client : Parse.cpp:166 : C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default/scripting/common/named_values.focs.txt: Unresolved macro reference: SHIP_STRUCTURE_FACTOR
20:50:46.459556 {0x00006cbc} [error] client : Parse.cpp:221 : Exception caught regex parsing script file C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default\scripting/policies\ALLIED_REPAIR.focs.txt: boost::filesystem::weakly_canonical: The system cannot find the file specified
20:50:46.461556 {0x00006cbc} [error] client : Parse.cpp:166 : C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default/scripting/policies/ALLIED_REPAIR.focs.txt: Unresolved macro reference: SPECIES_LIKES_OR_DISLIKES_POLICY_STABILITY_EFFECTS
20:50:46.465557 {0x00005a28} [error] client : Parse.cpp:221 : Exception caught regex parsing script file C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default\scripting/species\SP_ABADDONI.focs.txt: boost::filesystem::weakly_canonical: The system cannot find the file specified
20:50:46.465557 {0x000088d0} [error] client : Parse.cpp:221 : Exception caught regex parsing script file C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default\scripting/ship_hulls\asteroid\SH_ASTEROID.focs.txt: boost::filesystem::weakly_canonical: The system cannot find the file specified
20:50:46.466557 {0x00005a28} [error] client : Parse.cpp:166 : C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default/scripting/species/SP_ABADDONI.focs.txt: Unresolved macro reference: HAS_INDUSTRY_FOCUS
20:50:46.466557 {0x00005a28} [error] client : Parse.cpp:166 : C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default/scripting/species/SP_ABADDONI.focs.txt: Unresolved macro reference: HAS_RESEARCH_FOCUS
[...]
20:50:46.521571 {0x000088d0} [error] client : ReportParseError.cpp:92 : C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default\scripting/ship_hulls\asteroid\SH_ASTEROID.focs.txt:17:21: Parse error.  Expected (?-i:buildtime) here:
        Slot type = External position = (0.70, 0.50)
        Slot type = External position = (0.47, 0.80)
        Slot type = Internal position = (0.40, 0.50)
        Slot type = Internal position = (0.55, 0.50)
    ]
    buildcost = 20.0 * [[FLEET_UPKEEP_MULTIPLICATOR]] * [[SHIP_HULL_COST_MULTIPLIER]]
                     ^
    buildtime = 2
    tags = [ "ASTEROID_HULL" "PEDIA_HULL_LINE_ASTEROIDS" "AVERAGE_FUEL_EFFICIENCY" ]
    location = And [
        Planet
        Contains And [
````

**Comment by o01eg** [comment]
> When I start freeorion, I get a bunch of parse errors in the log file...
> 
> ```
> 20:50:46.459556 {0x00006cbc} [error] client : Parse.cpp:221 : Exception caught regex parsing script file C:/Users/g_top/Desktop/FOSDK11_Godot/FreeOrion/build/Release/default\scripting/policies\ALLIED_REPAIR.focs.txt: boost::filesystem::weakly_canonical: The system cannot find the file specified
> ```

I suppose either `boost::filesystem::weakly_canonical` don't accept links, or different slashes somehow break it.

Will this error gone if you delete links and instead copy folders here?

**Comment by o01eg** [comment]
Maybe it because it's Directory Junction instead of symbolic links?

**Comment by o01eg** [comment]
It looks like support should be fixed in boost 1.74 https://www.boost.org/users/history/version_1_74_0.html

```
    Removed compile-time checks for support for symlinks and hardlink on Windows. Instead, a runtime check is used. (PR#142)
    Fixed handling of reparse points in canonical and read_symlink on Windows. This also affects other algorithms that involve canonical and read_symlink in their implementation. (PR#100, #85, #99, #123, #125)
    Fixed that read_symlink on Windows could potentially fail or cause failures elsewhere with a sharing violation error, if the same symlink was opened concurrently. (#138)
    Fixed that is_symlink(directory_entry) would always return false, even if the directory entry actually referred to a symlink. (PR#148)
```

**Comment by geoffthemedio** [comment]
Seems to work OK with the updated SDK

**Comment by o01eg** [comment]
@geoffthemedio Nice. Could you try to call `ctest`? Not sure if it will work but maybe we could enable some unit tests on Windows.

**Comment by geoffthemedio** [comment]
> @geoffthemedio Nice. Could you try to call `ctest`?

````
C:\Users\g_top\Desktop\SDK12_2017\FreeOrion>ctest
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]
````

> maybe we could enable some unit tests on Windows.

The Boost tests can already can be run...

**Comment by o01eg** [comment]
Test builds only with `-DBUILD_TESTING=On`

**Comment by geoffthemedio** [comment]
> Test builds only with `-DBUILD_TESTING=On`

also in the MSVS project files, but I'm not sure what your point is...

**Comment by o01eg** [comment]
I wanted to see how it will work with unit tests with CMake. Then maybe later on CI after new SDK will be used.

**Pull request merged**
