### PR TITLE
Various Fixes and Tweaks

### PR DESCRIPTION
**Pull request by geoffthemedio**
pull request to provoke more test builds...

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
In the stubs we have a special class `StringSet2`:

```python
@property
    def availablePolicies(self) -> StringSet2: ...
```

According to usage, it could be StringSet (Set[str]).  Currently only `__iter__` and `__contains__` method are used.

Could you change the return type or rename this method to reflect its uniqueness?

**Comment by geoffthemedio** [comment]
> According to usage, it could be StringSet (Set[str]).

I don't know what this means.

> Currently only `__iter__` and `__contains__` method are used.

What is the relevance of this information?

> Could you change the return type ...

Internally, `StringSet` and `StringSet2` are different types. The API could copy the contents into a `StringSet` before returning, but the idea of having `StringSet2` as a separate class was to avoid doing that.

> ... or rename this method to reflect its uniqueness?

Rename `availablePolicies` ? I'm not sure how to rename it or what about the internal difference between `StringSet` and `StringSet2` would be relevant to convey.

**Comment by Cjkjvfnby** [comment]
> What is the relevance of this information?

These are python functions that are used.  This is a magic method that is called implicitly when you do something like `x in my_set` (`my_set.__contains__(x)`)  or `set(my_set)` (iterate over set).

In other words that is the public interface of the collection. This interface is equal to the public interface of the `StringSet`.  


> Internally, StringSet and StringSet2 are different types

Yes, but for the API this does not really matter. In PythonAI it's exactly the same types.

> The API could copy the contents into a StringSet before returning, but the idea of having StringSet2 as a separate class was to avoid doing that.

Not sure what side of API you mean.  PythonAI does not mutate StringSet, since it does not have methods for it.

> Rename availablePolicies ? I'm not sure how to rename it or what about the internal difference between StringSet and StringSet2 would be relevant to convey.

Sorry I mean class StringSet2 , not the method.  


API has two classes that implement exactly the same interface.  In terms of an API design, this is a bad practice, since it might confuse users/developers.

If you could get rid of that duplication on the API level it would be great.  If complicated refactoring is needed let's keep it as is.  I'll add a hack on skeleton generation.

**Comment by geoffthemedio** [comment]
try with ea872bd ? Result of `availablePolicies()` should be a `StringSet` instead of a `StringSet2`...

**Comment by Grummel7** [comment]
> try with [ea872bd](https://github.com/freeorion/freeorion/commit/ea872bdad6fb50f4a772464a027f3ca62def2c10) ? Result of `availablePolicies()` should be a `StringSet` instead of a `StringSet2`...

The only reason StringSet2 exists at all, is because `Empire::m_available_policies` has the special type `std::set<std::string, std::less<>>`

Is there a good reason, why it is not simply `std::set<std::string>`. Both definitions should do the same, don't they?

**Comment by geoffthemedio** [comment]
Yes there is, and no they don't (in C++ land).

Specifying `std::less<>` lets a `set` or other sorted container use heterogenetous lookup, to search for contents that compares equal even if it's not the same exact type. For example, if I want to check if a `set<string>` contains an item with the same value as a `string_view`, without specifying the `std::less<>` comparison operator type, it defaults to a comparison operator that forces a `string` object to be constructed to do the comparison, but with `std::less<>`, it can do the comparison without the extra construction.

The default was used for originally setting up the code, since it's the default, and since in previous versions there was no option to enable heterogeneous lookup.

For data that gets (de)serialized, it's not trivial to switch to the new type and maintain serialization compatability.They are also considered separate types for purposes of the Python API, and just exposing the `std::less<>` variant of `set<string>` was less work that writing a bunch of serialization code to handle the conversion when loading old data.

**Comment by geoffthemedio** [comment]
> try with [ea872bd](https://github.com/freeorion/freeorion/commit/ea872bdad6fb50f4a772464a027f3ca62def2c10) ? Result of `availablePolicies()` should be a `StringSet` instead of a `StringSet2`...

@Cjkjvfnby ?

**Comment by Cjkjvfnby** [comment]
> @Cjkjvfnby ?

I am waiting for this merged into the master.

**Comment by geoffthemedio** [comment]
> > @Cjkjvfnby ?
> 
> I am waiting for this merged into the master.

Now?

**Comment by Cjkjvfnby** [comment]
Looks great:

https://github.com/freeorion/freeorion/pull/4318/files#diff-e85c5d4d5625015acca3dfc45765eacdd71735baaba89303a3e300c2fe6a4bfaL157

**Pull request merged**
