### PR TITLE
Fix tech list filling.

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Added stable adding remaining items implementation. 

This is a fix for the issue mentioned in https://github.com/freeorion/freeorion/issues/3143#issuecomment-676805330

I have not tested it yet, I want to get some feedback before it.  (I have not played the game for some time, so I am not an expert in AI tuning)

This PR definitely will change AI behavior, but I m not sure if it will cause any noticiblae changes.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@agrrr3 any comment?

**Comment by agrrr3** [comment]
i do not completely understand what this is supposed to fix/what the problem is.

**Comment by geoffthemedio** [comment]
@Cjkjvfnby could you elaborate on the purpose of this?

**Comment by geoffthemedio** [comment]
@Cjkjvfnby could you elaborate on the purpose of this?

**Comment by Cjkjvfnby** [comment]
> i do not completely understand what this is supposed to fix/what the problem is.

This fixes the order or adding the remaining techs.  

The old version of the code added all remaining tech in pseudo-random order by converting the `list` to `set`. This approach may provide different orders of tech on different machines.

Before [w1, w2, w3] could be added as one of `[w1, w2, w3], [w1, w3, w2], [w2, w1, w3], [w2, w3, w1], [w3, w1, w2], [w3, w2, w1]`

After changes [w1, w2, w3] will be always added in [w1, w2, w3] order. 

Since new order is one of the possible old orders, this PR does not need extra balancing.

**Pull request merged**
