### PR TITLE
Cleanup species macroses

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
A bunch of cosmetic changes that will reduce the diff for the species' conversion

### CODE REVIEW

**Comment by geoffthemedio** [comment]
looks OK, but double check if test expected checksums need updating

**Comment by o01eg** [comment]
It changes checksum for old parser. But Python already calculates it so I prefer to have formulas which produces those values.

**Comment by Cjkjvfnby** [comment]
These focus formulas will gone after we finish migrations.  I am not sure which value they brought, but I see the ham, that this produces extra noise in diffs.

Python just evaluates this values in runtime, so for parser it just a number.

**Comment by Vezzra** [comment]
@Cjkjvfnby, closed as invalid/superseded/...?

**Comment by Cjkjvfnby** [comment]
Closed as not actual.

**Pull request closed without merging**
