### PR TITLE
[FOCS] Convert VOLP

### PR DESCRIPTION
**Pull request by MichaelCourtney**

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
I am also doing the conversion, probably we will have some conflicts since macros are involved a lot.  

Here is my changes in macroses:  https://github.com/freeorion/freeorion/pull/4619

There are a couple of blockers because API is missed. 
1) https://github.com/freeorion/freeorion/pull/4610
2) Compare visibilities.  (Not yet addressed)

**Comment by MichaelCourtney** [comment]
> I am also doing the conversion, probably we will have some conflicts since macros are involved a lot.

I noticed and figured I'd come from the other direction Volp, Ugmors, Trith... I generally watch the commit log so I'll try and correct for any conflicts

**Comment by Cjkjvfnby** [comment]
In my changes, I have stopped at `SP_MISIORLA` I'll submit the PR as soon as I'll get the https://github.com/freeorion/freeorion/pull/4603 merged.

**Comment by MichaelCourtney** [comment]
Superseeded

**Comment by Vezzra** [comment]
@MichaelCourtney, superseded by which PR or commit(s)?

**Comment by MichaelCourtney** [comment]
superseded by 
https://github.com/freeorion/freeorion/pull/4603

**Pull request closed without merging**
