### PR TITLE
Hostless quickstart

### PR DESCRIPTION
**Pull request by o01eg**
Implements `quickstart` options for multiplayer hostless server.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
So is this still a work in progress, or tentatively done?

Looks like it will need a rebase regardless, possibly again after other merges...

**Comment by o01eg** [comment]
It's still a work in progress until extracted PR will be merged.

**Comment by o01eg** [comment]
Rebased. All extracted PR was merged. This PR is ready for review and merge.

**Comment by o01eg** [comment]
Rebased. Fixed conflicts.

**Pull request merged**
