### PR TITLE
Cleanup logger calls. Part 1

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Remove error log prefixes that match name of file.

According to search with `ErrorLogger\(\) << "\w*::` there is still 480 lines that should be checked.

### CODE REVIEW

**Comment by Vezzra** [comment]
Ok, after a first cursory glance at the diff it seems that with only a few exceptions all those references you want to remove here are not really references to the source file name, but actually namespace or class identifiers, which I suggested _not_ to remove ([quoting from the discussion](https://github.com/freeorion/freeorion/pull/403#issuecomment-159911331) of PR #403):

> I'd say, unless it's namespace or class identifier indicating scope, it should be removed. In case of `PythonServerWrapper` I'd say that's clearly a reference to the source file and is redundant information now that can be removed.
> 
> Namespace and class identifier however should be kept.

Of course, in all the cases covered by this PR, these namespace/class identifiers also match the source file name, but I thought that, at least for a first pass, we's concentrate on purely source file references (meaning, not references that also match namespace/class scope). `PythonServerWrapper` would be an example of such a case.

Regarding the removal of namespace/class scope identifiers that match the source file name, I'd prefer to at least keep class names. Namespace identifiers we can probably remove too. As that's kind of a programming style decision, our program lead should have the final call here - @geoffthemedio?

**Comment by geoffthemedio** [comment]
I have no strong preference...

**Comment by Cjkjvfnby** [comment]
So you say that `Namespace` and `Class Identifier` and `File name` use same syntax in logs.

If I cant tell if it class or namespace or just file I need to check code, and this duplicated log entry will not help me.  So I feel that removing both namespaces and filenames is reasonable.

Should I revert all files that have `class <filename>` entry in it?

**Comment by Vezzra** [comment]
> So you say that `Namespace` and `Class Identifier` and `File name` use same syntax in logs.

Yes. Not ideal probably, but that's how it is (ATM).

> So I feel that removing both namespaces and filenames is reasonable.

@geoffthemedio has expressed no strong preference, so I guess we can agree on that.

> Should I revert all files that have class <filename> entry in it?

Yep. So that means, everywhere where a log message contains a member function reference which is qualified by the corresponding class name, keep the class name even if it's the same as the source file name. For example:

```
ErrorLogger() << "Empire::ProductionCostAndTime was passed a ProductionItem with an invalid BuildType";
```

This line should be kept as is, as `Empire` is a reference to the class here. However:

```
ErrorLogger() << "AIInterface::UpdateResearchQueue : couldn't get empire with id " << empire_id;
```

Here "AIInterface::" can be removed, as it's a reference to the namespace and also the file name of the source file.

**Comment by geoffthemedio** [comment]
To complicate the options more, but be a bit more useful, you could always have the text in the log correspond to something that can be explicitly searched for in the code. So perhaps if ClassName::FunctionName appears in the function definition, then put that it, but if it's an function defined where it's declared, so there's no ClassName:: before the function name at the definition, then leave out the ClassName since including it would make a search for the combination fail....?

**Comment by Vezzra** [comment]
> but if it's an function defined where it's declared, so there's no ClassName:: before the function name at the definition, then leave out the ClassName since including it would make a search for the combination fail....?

Hm, isn't that only the case with member functions that contain only very simple code, like getters returning a member variable? Anything sufficiently complex to catch errors and log them wouldn't have the function definition where it's declared I thought... or do you have an example for what you are referring to here?

**Comment by geoffthemedio** [comment]
There are numerous GUI classes that have all their functions fully defined within their class definitions. This often occurs if the class doesn't appear in a header, but just in a source file to be used locally. These aren't always trivial functions.

**Comment by Vezzra** [comment]
Ok, I see... so, for searching purposes your suggestion makes sense. However, as you pointed out yourself already, it will make the process of cleaning up the redundancies even more complicated, and I wonder if it's really worth it - after all, we're talking about those log messages here which have a source file name and line number reference now anyway, no need to be able to search for the function name I'd say.

Personally I'd prefer to have the fully qualified function name of a class member function in the log messages. In some cases this might give you that extra bit of info just from glancing at a log message to better tell where it came from (I'm thinking of member functions that are implemented by several different classes - if you only have the member function name itself, you can't immediately tell which one exactly it is).

Anyway, your call - what's the final verdict? So @Cjkjvfnby knows how he shall proceed :smiley:

**Comment by geoffthemedio** [comment]
you / he can decide. see above re: lack of preference

**Comment by Vezzra** [comment]
Well, you came up with the last suggestion, that's why I asked :wink: 

Anyway, in this case lets stick with what I [suggested above](https://github.com/freeorion/freeorion/pull/407#issuecomment-160592326), that is, keep class names and remove the rest. @Cjkjvfnby, you can proceed accordingly :smiley:

**Comment by Cjkjvfnby** [comment]
I force push changes. 

My IMHO that  adding `class::method` should not be part of user coding. This can lead to mistakes.

And there is such mistake example: https://github.com/freeorion/freeorion/blob/master/client/ClientApp.cpp#L128 

I don't know if it is possible in C++

**Comment by Cjkjvfnby** [comment]
I made other fixes in separate commits.

I make look on whole project and don't plan to add any more changes.

May be someone can start C++ style page on wiki there he clarify how loggers should be used? 

There is some place that looks strange for me:
https://github.com/Cjkjvfnby/freeorion/blob/master/UI/CombatReport/CombatLogWnd.cpp#L102
https://github.com/Cjkjvfnby/freeorion/blob/master/UI/CombatReport/GraphicalSummary.cpp#L714

**Comment by geoffthemedio** [comment]
Probably in those cases, code was copied / moved from elsewhere, and the logger calls not updated.

There is a wiki page, but it needs updating: http://freeorion.org/index.php/Code_Standards

**Comment by Vezzra** [comment]
> My IMHO that adding class::method should not be part of user coding. This can lead to mistakes.

Well, it has it pros and cons. Having the (class::)function name in the log message might give you a better idea where an error has occurred than source file name and line number only (on a quick first glance that is, of course you can always look up the source file).

> I don't know if it is possible in C++

I assume you mean if it's possible in C++ to insert the function name by a macro like the source file name and line number. As far as I have seen from, there is another macro, `__func__` IIRC, but apparently this isn't standardized as universally as the other two, so I'm reluctant to rely on it (I may be wrong on that account though, didn't research that thoroughly).

**Comment by geoffthemedio** [comment]
**func** doesn't work for me

There is also

`#include <boost/current_function.hpp>`
then use `BOOST_CURRENT_FUNCTION`

but it appears to evaluate to "(unknown)" for me.

**Pull request merged**
