### PR TITLE
Sneaky species have easy planetary stealth tech

### PR DESCRIPTION
**Pull request by agrrr3**
This PR is basically a reminder Mat asked for in http://www.freeorion.org/forum/viewtopic.php?f=6&t=10382&p=89404#p89404

The discussion was about changing how laenfa work so they have it easier to hide their outposts (to have a species for which hidden expansion works).

* Laenfa are sneaky and have only good stealth
* All research cost for planet stealth is halved for sneaky species

TODO:
* Description in stealth techs
* AI adjustments for/against sneaky species
* somewhere else: slow stealth changes

### CODE REVIEW

**Comment by dbenage-cx** [comment]
@agrrr3 marking *wip* due to TODO, and guessing *help wanted* for AI adjustments?  please note if neither is the case

**Comment by agrrr3** [comment]
Playing a game with 120 planets and 6 AI. Trying hidden expansion. Didnt find a lot of Laenfa places to colonize, had to invade some natives instead. Also needed Wanted to save some RP by focussing on hiding instead of defense or ships, but didnt work out because i had to defend my natives. Got planetary ash in turn 68, now maybe I will have a chance for further expansion.

**Comment by Vezzra** [comment]
@freeorion/ai-team, how difficult will it be to adjust the AI to these additions/changes?

**Comment by Morlic-fo** [comment]
In regard to this PR in particular, no AI adaptations seem to be needed. However, the AI does not really understand or handle stealth well as of now. In particular, notice issue #1762.

Researching planetary stealth early (earlier than the AI researches detection which isn't really early) is kind of an invincibility hack. It kind of is already but this PR could potentially make that problem more prominent.

Your call if you think that is an issue or not.

**Comment by Vezzra** [comment]
Ok, that should be good enough to leave this as optional for 0.4.8.

**Comment by st-pa-fo** [comment]
not sure if i'm reading this right. all thats really missing is description in stealth techs* and help is wanted since ai issue deemed to be ok? how do i help then? @agrrr3

* and maybe put that formula parametrized in just one single place instead of copy/pasting

**Comment by agrrr3** [comment]
wow, this is old. I would welcome getting this into master for playtesting by the community.

**Comment by geoffthemedio** [comment]
needs a rebase

**Pull request merged**
