### PR TITLE
[FOCS] Update tech typing

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
- Add typing to the tech
- Add typing to the tests
- Remove extra build-ins from pyproject.toml.   That means when a new keyword for FOCS is added you need to add an entry in pyi file for it. 

@o01eg, I don't expect any review here, just tagging you to be aware of it.

### CODE REVIEW

**Review by o01eg — CHANGES_REQUESTED** [review]
Currently it fails with `ModuleNotFoundError: No module named 'focs'`

**Comment by Cjkjvfnby** [comment]
> Currently it fails with ModuleNotFoundError: No module named 'focs'

The linting environment and execution environment are different.    I don't think that we should have a copy of focs, it will be hard to support.

Do you think it will be easy to add this folder to Python path of tests or link it on file system level?

**Comment by o01eg** [comment]
For test better try to add a Python path.

**Comment by Cjkjvfnby** [comment]
> For test better try to add a Python path.

Can it be done from the outside or need to change some C++ code?

Moved techs to a separate review: https://github.com/freeorion/freeorion/pull/4701

**Comment by o01eg** [comment]
@Cjkjvfnby I suppose it in c++ part. I need to think how to do it better.

**Comment by Cjkjvfnby** [comment]
> @Cjkjvfnby I suppose it in c++ part. I need to think how to do it better.

Let's put this to the backlog,  I'd prefer to finish with tech that is convertible (#4603) and missing features (#4651) to convert the rest tech first.

**Comment by o01eg** [comment]
@Cjkjvfnby Suddenly got idea to not make `focs` module available from the game or tests but instead catch and ignore import exceptions.

**Review by o01eg — CHANGES_REQUESTED** [review]
Could you just catch and ignore `ModuleNotFoundError` exception? Maybe check if it's about `focs` module to ignore.

**Comment by o01eg** [comment]
CI suddenly stopped to run at least windows unit tests.

**Comment by Cjkjvfnby** [comment]
> CI suddenly stopped to run at least windows unit tests.

The job (detect_changed_files), does not consider these changes as required for C++ build.  I'll fix it.

**Review by o01eg — APPROVED** [review]

**Pull request merged**
