### PR TITLE
Simplify CMake buildsystem

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR:

* raises the minimum required version to CMake 3.5, which is the version provided by Ubuntu 16.04.
* Lets CMake decide which is the correct standard library to link on MacOS, when we request a specific C++ version.
* Hide all non explicit exported symbols on unix-like platforms by default, which reduces the library size of GiGi and GiGiSDL (other components had this flag already enabled for some time).
* Use the suggested modern CMake approach of using export targets to define dependencies to external targets instead of manually fiddeling with include directories, compile defines and libraries to link.
* Use a more recent CMake upstream FindBoost.cmake to locate the correct Boost Python component, respecting the Python 2/3 version while keeping platform naming oddities out of sight and mind.

### CODE REVIEW

**Comment by adrianbroher** [comment]
Supersedes also #2744

**Comment by adrianbroher** [comment]
@Vezzra please verify if the built .app is still working as intended.

**Comment by Vezzra** [comment]
@adrianbroher,

> please verify if the built .app is still working as intended.

It is 👍

**Comment by geoffthemedio** [comment]
So is this OK to merge then?

**Comment by o01eg** [comment]
@adrianbroher  GG doesn't see Glew headers on windows.

**Comment by adrianbroher** [comment]
CMake is not officially supported on Windows anyway, so what is the point?

**Comment by geoffthemedio** [comment]
Presumably the windows issue can be fixed when needed...

**Pull request merged**
