### PR TITLE
Imperial Stockpile Alt

### PR DESCRIPTION
**Pull request by geoffthemedio**
Based off https://github.com/freeorion/freeorion/pull/1710

Reworks the wasted resources tooltips to have layout like the main resources tooltips. Resolves some rebase issues.

Remaining issue is the layout of the production info window.
wasted_res_info

### CODE REVIEW

**Comment by Vezzra** [comment]
@geoffthemedio, thanks for picking that up. I've been starting to wonder how to proceed with the 0.4.8 release if development on this remained stuck.

Anyway, continuing development on this with a branch in the main repo instead of a forked one is probably a good idea. After all, it's *the* major feature of 0.4.8, and that makes collaborating easier.

Consequently I propose to let this PR supersede #1710, and close #1710 accordingly. Anyone any objections? @agrrr3?

**Comment by agrrr3** [comment]
no objections. happy somebody picks it up.  go for it :)

Am 29.10.2017 14:04 schrieb "Vezzra" <notifications@github.com>:

**Comment by geoffthemedio** [comment]
I've reworked the resource info window layout, and I think it looks reasonable now. If testing, make sure to delete config.xml and anything relevant in persistent_config.xml, as it affects some layout changes (resource info window size).

Is it reasonable to merge this now, or does AI support need to be implemented first?

**Comment by dbenage-cx** [comment]
From default config (1024x768), looks like the icons need some adjustment: (PR vs master)
PR 1024x768
master 1024x768

If the layout should still be presentable at 800 x 600, master has some jumbling too, so it could be handled outside this PR.
PR 800x600
master 800x600

**Comment by Vezzra** [comment]
> Is it reasonable to merge this now, or does AI support need to be implemented first?

I guess it will be easier for the AI team to work on the AI support for the new feature once it's merged into master, so I vote for merging now - @freeorion/ai-team?

Also, I expect that the inital content @agrrr3 has created which enables/makes use of the new mechanics in the game might need some serious revision/polishing. AFAIK there hasn't been any substantial design discussion about the actual content, and given @agrrr3's preferences I suspect that they have made access to the stockpile mechanic far too easy.

Might be wrong on that though, but in order for a broader audience to test this and give their feedback, it would be good to have it in master ASAP.

**Comment by Vezzra** [comment]
> If the layout should still be presentable at 800 x 600

Seriously...? 😉😉😉

**Comment by agrrr3** [comment]
Am 02.11.2017 1:42 nachm. schrieb "Vezzra" <notifications@github.com>:


Also, I expect that the inital content @agrrr3 <https://github.com/agrrr3>
has created which enables/makes use of the new mechanics in the game might
need some serious revision/polishing....

...in order for a broader audience to test this and give their feedback, it
would be good to have it in master ASAP

i think this is crucial.  discussion needs to be started based on game
world facts.

i found it rarely useful enough for my use cases as is, but maybe there are
other playing styles which indicate nerfing. surprise me :)

another consideration: i think in the past you would rather err on the
overpowered side for new key features so people start using them.

**Comment by Vezzra** [comment]
> i think this is crucial. discussion needs to be started based on game world facts.

Yep, absolutely.

> another consideration: i think in the past you would rather err on the overpowered side for new key features so people start using them.

That might be a viable apporach in some cases for test builds, but not in a stable release. Especially if the overpowered feature is game changing on the level the Imperial Stockpile mechanic is. So, we can start with things as they are now (which is why I'm for merging soon), but for the release we need to get things at least somewhat properly balanced.

**Comment by Dilvish-fo** [comment]
> I guess it will be easier for the AI team to work on the AI support for the new feature once it's merged into master, so I vote for merging now - freeorion/ai-team?

Sounds good to me.

**Pull request merged**
