### PR TITLE
Remove unnecessary inheritance in Universewrapper

### PR DESCRIPTION
**Pull request by Cjkjvfnby**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
In master I'm getting a universe generation error that appears to be due to this. Reverting the commit fixes it.
````
13:23:05.836761 {0x00008918} [error] server : CommonFramework.cpp:150 : Traceback (most recent call last):
13:23:05.836761 {0x00008918} [error] server : CommonFramework.cpp:150 :   File "C:/Users/g_top/Desktop/FOSDK11/FreeOrionAlt2/default/python\common\listeners.py", line 42, in wrapper
    res = funct(*args)
13:23:05.836761 {0x00008918} [error] server : CommonFramework.cpp:150 :   File "C:/Users/g_top/Desktop/FOSDK11/FreeOrionAlt2/default/python/universe_generation\universe_generator.py", line 199, in create_universe
    universe_statistics.log_planets()
13:23:05.836761 {0x00008918} [error] server : CommonFramework.cpp:150 :   File "C:/Users/g_top/Desktop/FOSDK11/FreeOrionAlt2/default/python/universe_generation\universe_statistics.py", line 233, in log_planets
    pid, planet.name, planet.systemID, planet_type, list(planet.specials), planet.speciesName, buildings
13:23:05.836761 {0x00008918} [error] server : CommonFramework.cpp:150 : Boost.Python.ArgumentError: Python argument types in
    None.None(planet)
did not match C++ signature:
    None(class PopCenter {lvalue})
````

**Comment by geoffthemedio** [comment]
@Vezzra if doing test builds before @Cjkjvfnby responds, please use the previous commit c66fe2e94db92b3

**Comment by geoffthemedio** [comment]
I don't want to wait for a response any longer, so I reverted this. Please resubmit after fixing the error...

**Comment by Cjkjvfnby** [comment]
> I don't want to wait for a response any longer, so I reverted this. Please resubmit after fixing the error...

Sorry for the long delay.  I think reverting is the best solution anyway. I prefer to fixing without a deadline.  It's my goal to write one feature per commit, so in general, reverting is often a solution. Feel free to revert without waiting for me.

I'll analyze the reasons later this or next week.

**Comment by Cjkjvfnby** [comment]
The problem is in the    
```cpp
.add_property(
   "speciesName",
   make_function(&PopCenter::SpeciesName,
   py::return_value_policy<py::copy_const_reference>())
)
```

But I don't have enough knowledge to fix it.

**Comment by geoffthemedio** [comment]
Does it work to just write `&Planet::SpeciesName`?

If not, a lambda should work, like `+[](const Planet& p) -> const std::string& { return p.SpeciesName(); }` instead of `&PopCenter::SpeciesName`

**Pull request merged**
