### PR TITLE
Russian translation: stockpile transfer, custom game rules and others.

### PR DESCRIPTION
**Pull request by Bestary**
Translated info about stockpile transfer, custom game rules menu, options' headers and some other minor editions.

There are 2 game rules left untranslated (I still did not understand what they do): ^_^' here they are:

```
RULE_PRODUCTION_QUEUE_FRONTLOAD_FACTOR
Turn PP overcommit
desc: Percentage of PP overcommitment per item build turn to build in time.

RULE_PRODUCTION_QUEUE_TOPPING_UP_FACTOR
Final PP overcommit
desc: Percentage of PP overcommitment on final item build turn to build in time.
```

### CODE REVIEW

**Comment by geoffthemedio** [comment]
This pull request has repeats of commits that are already in master, which leads to the conflicts. Have you fetched and rebased the branch against master since the previous pull request was merged?

**Comment by Dilvish-fo** [comment]
Because the earlier commits were merged via squash merges, a simple rebase won't really clean it up so well since he will have to again do conflict resolution and will likely be left with little scraps of commits (depending on how the conflict resolution goes), we already went through that once last time.

@Bestary really you should start by first making sure your master branch is fully updated, then make a new branch from that.  And then in general that would be your starting point for new work.  In this case since you have already made a new commit (or 2?) that you would probably like to salvage, cherry pick just that/those new commit(s) into the new branch. 

then you could either make a new PR from that new branch (simplest/safest), or else do a hard reset of this branch to that branch, if you are up to that.

**Comment by Bestary** [comment]
@Dilvish-fo, ok, I think it will better to create fully fresh branch. I don't know, can I use this pull request or not, so I'll just create new pull request.

**Comment by Vezzra** [comment]
@Bestary, if you open the new PR which replaces this one, don't forget to post a reference to the new PR here ("Superseded by #[number of new PR]"), and also put a reference to this PR here into the description of the new PR ("Supersedes #[number of this PR]").

**Comment by Vezzra** [comment]
@Bestary, never mind, I've seen you've opened the superseding PR already, I'll go ahead and put in the references myself.

**Comment by Vezzra** [comment]
Superseded by #2258.

**Comment by Cjkjvfnby** [comment]
IMHO references between PR useful only when the old one has useful comments about content.  Not about workflow and git, like this one. 

@Bestary, usually I do the next steps to fix such cases: 

- merge master to branch  (`git merge master`, I assume that you start your day with syncing you master with freeorion master)
- reset your commits but leave your changes (`git reset master`)
- add and commit your changes (use `git add -p` to add only part of changes)
- force push to the branch (avoid creating the second PR)
PS. you can always create local branch as the backup before any experiments. (`git branch backup1`)

**Comment by Vezzra** [comment]
> IMHO references between PR useful only when the old one has useful comments about content. Not about workflow and git, like this one.

If a PR is marked as superseded, it's always good to put in a reference to the follow-up PR. Although most likely no one is going to look at the superseded PR ever again, in case someone does, it might be important to know if a superseding PR actually exists and which one it is.

Of course we could come up with a set of rules/policies when such a reference should be posted and when it can be omitted, but as adding such a reference is such a trivial action, so that would be overly complicated.

Hence it's project policy, when one PR supersedes another, to add references to both PRs to each other.

**Comment by Dilvish-fo** [comment]
>  to add references to both PRs to each other.

and to perhaps clarify/simplify- if you add a reference from PR_A to PR_B, github automatically adds the back-reference from PR_B to PR_A

**Pull request closed without merging**
