### PR TITLE
Replace flake8 with ruff

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Ruff is a modern linter that was inspired by flake8, isort, pyupgrade and many other tools.  And it's really fast. 

This PR replace the flake8 in pre-commit and CI. 

There is a file cmake\FindFlake8.cmake that allows running the linter from the console.  I am not sure if this is used by someone.  Also since that time, pre-commit was added to the repo, so it kind of replaces manual calls.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@o01eg , I am going to merge these changes, and I want to keep you in the loop.  The consequence of this merge is that calling flake8 manually will provide a lot of errors since I have removed the config files.

As I mentioned at the meeting a recommended way is to install pre-commit, and just commit code instead of checking it manually.  The hook will run linters and formatters and fix some things that are possible to fix automatically and report others.  Then you will need to add changes to the stage and commit things again.

You could find instructions for it here: https://github.com/freeorion/freeorion/pull/4462

As an alternative, you could use `ruff .` instead of flake8.

**Comment by o01eg** [comment]
@Cjkjvfnby Thanks, it's fine. I'll change my scripts as this PR will be merged.

**Comment by Cjkjvfnby** [comment]
>  I'll change my scripts as this PR will be merged.

What kind of scripts are you using?

**Comment by o01eg** [comment]
> What kind of scripts are you using?

That:

```bash
#!/bin/bash
~/.local/bin/black default/scripting/ --no-color -t py37 --config ~/devel/freeorion/pyproject.toml && \
~/.local/bin/isort default/scripting/ --py 37 --settings-path ~/devel/freeorion/pyproject.toml && \
~/.local/bin/black test-scripting/ --no-color -t py37 --config ~/devel/freeorion/pyproject.toml && \
~/.local/bin/isort test-scripting/ --py 37 --settings-path ~/devel/freeorion/pyproject.toml && \
./fo_unittest_parse --run_test=TestPythonParser/parse_species --log_level=warning && \
FO_CHECKSUM_SPECIES_NAME=SP_BEIGEGOO FO_CHECKSUM_SPECIES_VALUE=2465945 ./fo_unittest_parse --run_test=TestPythonParser/parse_species_full --log_level=message && \
FO_CHECKSUM_TECH=7544048 FO_CHECKSUM_BUILDING=8808243 FO_CHECKSUM_POLICY=8559903 FO_CHECKSUM_SHIP_HULL=8986067 FO_CHECKSUM_SHIP_PART=3728020 FO_CHECKSUM_SPECIES=5045233 FO_CHECKSUM_SPECIALS=3672180 FO_CHECKSUM_NAMED_VALUEREF=3103810 FO_CHECKSUM_FIELD=5633696 FO_CHECKSUM_SHIP_DESIGN=878449 FO_CHECKSUM_ENCYCLOPEDIA=1125744 ./fo_systemtest_game --run_test=TestChecksum/compare_checksum --log_level=warning && \
~/.local/bin/flake8 --config=${HOME}/devel/freeorion/tox.ini default/scripting/ && \
~/.local/bin/flake8 --config=${HOME}/devel/freeorion/tox.ini test-scripting/
find default/scripting/species/ -iname "*.focs.txt" | sort | xargs -I '{}' grep -nH "^\W\+name = " {} | wc -l
find default/scripting/species/ -iname "*.focs.txt" | sort | xargs -I '{}' grep -nH "^\W\+name = " {} | head -n 5
```

**Comment by Cjkjvfnby** [comment]
You could simplify your scripts a bit. 

- Black handles list of paths 
  ```
  black default/scripting/ test-scripting/
  ```
- If you run it from the root freeorion directory, it will find the pyproject.toml itself
- `-t py37` is extracted from pyproject.toml, you don't need to specify it manually
- isort, is not needed (actually it does not work [1])
- ruff also supports a list of paths
- ruff also find pyproject.toml in current dir
- ruff read python version from pyproject.toml

1 - to make import sorting work with ruff remove that lines in a file
```
"default/scripting/*" =  ["I"]
"test-scripting/*" = ["I"]
```
run `ruff . --fix` in the root freeorin folder, it will reformat almost all files.

**Comment by Cjkjvfnby** [comment]
oops, merging this will affect all isort calls (not more settings so default will be used) ,  https://github.com/freeorion/freeorion/pull/4472/files

**Comment by o01eg** [comment]
> If you run it from the root freeorion directory, it will find the pyproject.toml itself

I prefer to work from build directory with compiled binaries as I need to call unit tests too.

Also I suppose import sorting either with ruff or with isort should be included to CI even for FOCS scripts.

**Pull request merged**
