### PR TITLE
Correct damage boost by techs Laser-3, Plasma-3, DeathRay-3

### PR DESCRIPTION
**Pull request by agrrr3**
Laser-3, Plasma-3, DeathRay-3 applied a +1 damage boost to Mass Driver instead of the correct ones 2,3, and 5 to Laser, Plasma, and DeathRay parts.

### CODE REVIEW

**Comment by agrrr3** [comment]
fix for blue-award's report at #4941

**Comment by agrrr3** [comment]
definitely necessary for 0.5.1

**Comment by Grummel7** [comment]
> definitely necessary for 0.5.1

This is only relevant for 0.5.1, if https://github.com/freeorion/freeorion/commit/741ec8eb024278e82dd3d8cf893ab1b6386fcce2 is merged to 0.5.1 first.

**Comment by agrrr3** [comment]
> This is only relevant for 0.5.1, if [741ec8e](https://github.com/freeorion/freeorion/commit/741ec8eb024278e82dd3d8cf893ab1b6386fcce2) is merged to 0.5.1 first.

@Grummel7  as far as I am aware there is no separate branch for 0.5.1 yet. so master is currently 0.5.1

**Pull request merged**
