### PR TITLE
Remember window positions.

### PR DESCRIPTION
**Pull request by mel-odious**
Allows most non-self-positioning CUIWnd subclasses to save their position/size, visibility, pinned/minimized status to the OptionsDB, which is written to config.xml and saved between executions.  To enable this for new windows, pass a config_name parameter to the CUIWnd constructor.  Only one window can have any given name at a time (logs an error and doesn't let the second window save/load the options).  No more rearranging the design window again and again!

Makes windows go to the top of the z-order when activated via toolbar button.

Keeps separate positions for windows in fullscreen and windowed modes and auto-repositions them in response to windowed/fullscreen changes, which helps deal with the fact that FO will only start in fullscreen mode if '-f' is specified on the command line (shouldn't it save this to the OptionsDB?)... not everyone will get around to setting that up, you might forget to start it in fullscreen mode one time, you might just want to play it in a window one time... your fullscreen layout won't be lost.

Adds a button to OptionsWnd to reset all window properties.  As long as this option is checked (or if '-w' is specified) any existing or newly-created windows will use their default position and size, overwriting what's in the DB.  Useful if the UI somehow breaks badly, could also delete the <windows> section from config.xml.

Commits f23541c, 77af188 and 1bf3b2b allow the top-level panels in the map view remember their state when the production/research/design windows are opened, so the sitrep panel, pedia panel, objects list etc. don't need to be re-opened every time you switch to those windows.  Haven't discussed this change on the forums but it was simple to add and relies on changes in this branch, so I put it here for people to test.

### CODE REVIEW

**Comment by magnate** [comment]
Thank you!!

**Comment by mel-odious** [comment]
OK, I'm considering splitting out the "keep other panels open when using the production/research/design windows" commits into a new branch and making a forum thread to discuss it, since it's likely to clutter up the changes here + it would benefit from wider discussion, I think.

**Comment by Vezzra** [comment]
Works like a charm, and I'd like this very much to go in for 0.4.5.

One issue, however (at least on OSX), which is actually an issue that already existed before, and is made worse by this new feature: When you resize the app window, the side panel on the map, the production screen, the design screen etc. keep the layout as it has been initialized for the orginal app window size. This is an age old minor flaw that usually had been solved by just closing and restarting FO after resizing the app window.

However, with this new feature, that workaround doesn't work anymore. Because the position and size of all those windows is persistent now, it doesn't get reset when relaunching FO, so you can't force them to be reset to the new app window size anymore, short of manually removing the "windows" section from config.xml, which is more annoying and tedious than just deleting the file (he latter does not work, because this also resets the app window size, and here we go again... :smirk:)

So, as a follow up to this PR we need to do something about that problem in order to include this new feature into 0.4.5.

Any ideas what we can do? Can this be fixed easily?

**Comment by geoffthemedio** [comment]
That would be resolved by docking windows to / within other windows, as has been discussed. In the case of windows at the edge of the screen, they would be docked to that edge and move with it when resized. Beyond the scope of this pull request, though.

**Comment by mel-odious** [comment]
There's a command line switch '-w' or '--window-reset' and a toggle on the UI page of the options window for that.

**Comment by Vezzra** [comment]
> Beyond the scope of this pull request, though.

No question, but will nonetheless be needed for this PR to be accepted for 0.4.5. Having to start FO, maximize the app window, close, open up config.xml in a text editor, deleting the "windows" section, saving, restarting FO just to get a useable standard layout, or to have to rearrange all those windows manually isn't really acceptable...

So, either we can do that quickly enough for 0.4.5, or we can come up with a stop-gap solution to the problem that can be implemented quickly enough. Or this feature, as nice as it would be to have it, will have to wait.

**Comment by Vezzra** [comment]
> There's a command line switch '-w' or '--window-reset' and a toggle on the UI page of the options window for that.

That should be sufficient... I'll have to take a look at that.

**Comment by mel-odious** [comment]
Bear in mind that it currently resets to the default positions _as calculated based on the app size when FO was last launched_ (because those calculations are in the constructors of various container Wnds) so one would still need to restart FO to calculate the 'standard' layout for the new app size.  I could allow it to recalculate those positions and sizes at any time but that would involve moving those calculations out of various constructors into helper functions & I don't want to go ahead and do that unless people think it's a good idea.

**Comment by Vezzra** [comment]
Yep, that toggle on the UI page of the options dialog does the trick. Still not ideal, because players need to be aware that they need to do that after a app window resize instead of restarting the app. So I foresee a lot of complaints about that.

Nevertheless, good enough to accept that PR for 0.4.5. As it works very well otherwise (as far as my brief tests have shown), I'd say ripe for merge... opinions?

**Comment by mel-odious** [comment]
I have a question to resolve and then possibly another commit to push, writing that comment now...

**Comment by Vezzra** [comment]
> so one would still need to restart FO to calculate the 'standard' layout for the new app size

Ok... didn't notice that, but have to test again. No more time right now although, so I'll report back later.

**Comment by geoffthemedio** [comment]
The reset window position toggle should probably be a button.

**Comment by mel-odious** [comment]
There needs to be some persistent state for dynamically-created modal windows to know that they need to fall back on their defaults instead of using stored values.  I could disable this feature for modal windows altogether but that would mean that the object list filter window would remain a pain to use until it's made movable and not-modal.

**Comment by geoffthemedio** [comment]
You can't just reset the stored values to their defaults when the button is pressed?

**Comment by mel-odious** [comment]
For non-modal windows, yes, because they're all constructed when the app starts so the option change signal (or button pressed signal) can be connected to them then.  Modal windows are constructed dynamically when they are opened so we can't connect the signal to their LoadOptions() function if they're not open at the time.

**Comment by geoffthemedio** [comment]
What if you set the currently stored values in the relevant options? Then the next time a modal window is opened, it would use those values, no? If there are any (other) modal wnds open, presumably the optionswnd wouldn't be visible for the button to be clicked...

**Comment by mel-odious** [comment]
I could do that if, say, the CUIWnd class had a static set<string> of all window names that have been registered but I wanted to avoid adding members to classes where possible (which is why I added the ".exists" option to prevent name clashes).  Otherwise, there's no way of getting a list of currently-registered options out of the DB to find out which windows have been registered.  Could add another OptionsDB function to get iterators into a list of options that match a substring ("UI.windows." in this case) but that would be overkill, I imagine. (eta: or just a const ref to OptinsDB::m_options I guess)

**Comment by mel-odious** [comment]
> If there are any (other) modal wnds open, presumably the optionswnd wouldn't be visible for the button to be clicked...

I'd rather not make assumptions like that and have it break later...

**Comment by geoffthemedio** [comment]
Would it actually matter if another modal wnd is open? If it was, wouldn't it exist and be able to respond to a signal to reset its position...?

**Comment by mel-odious** [comment]
It would work for any modal windows that are open at the time, yes.  I just don't want other programmers to add dynamically constructed windows and then wonder why the "reset defaults" button doesn't work for their window if it's not open at the time...

**Comment by geoffthemedio** [comment]
I suppose this can all wait, as the ability to in-gui reset isn't a top priority. But I think adding iterators or other ways to access the already-registered options is reasonable.

**Comment by mel-odious** [comment]
I'd like a better solution for it, but yes, it can wait until the prerequisite work is done (e.g. functions to recalculate default positions, finding arbitrary options in the OptionsDB)

([I replied to another comment before but it might have been lost in a flood of notifications so I'll link it here](https://github.com/mel-odious/freeorion/commit/f23541c75cd51f139a739fc530cb90dce5c1fbe5#commitcomment-12183634))

**Comment by mel-odious** [comment]
I've added an options window toggle to enable/disable hiding other windows when the production window is open, but it currently doesn't hide the messages and empires windows.  Previously, these would stay open so I was wondering if there was some previous decision to keep it that way or if I should hide those windows along with all the others.

**Comment by geoffthemedio** [comment]
Hiding them all seems fine...

**Comment by mel-odious** [comment]
I'll clean up this branch tomorrow, it's far too late to do so right now.

**Comment by mel-odious** [comment]
OK, the branch has been rebased and cleaned up, the overall diff is the same as it was beforehand and is ready for merge, as far as I can tell.  It "works" in that I've dealt with any unexpected behaviour that's been reported and it's possible (but awkward) to recalculate the default window positions after changing the app size.  I'd like to make that second part much less awkward (and I think I know how to do so, see below), but I'm thinking of putting that in a seperate PR so that this feature can be merged in time for 0.4.5.  The follow-up PR might also be ready in time, but I can't guarantee that...

What I'd like to do from here is: split the calculation of default window positions from the MapWnd, BuildDesignatorWnd, TechTreeWnd, DesignWnd and ClientUI constructors so that those defaults can be recalculated at any time based on the current app size.  This would address @Vezzra's concerns about being able to reset to the default layout after changing the app size.

The second thing would be to add a way to find OptionsDB options that match some substring ("UI.windows.") and a) set and apply the defaults for the ones that have been registered using the calculations mentioned above, b) remove the ones that haven't been registered (currently, this includes modal windows that haven't been opened yet) so that there are no stored values to use and they fall back on the defaults when they are eventually opened.  This would allow the 'reset window positions' option to be a button in the options window instead of the current awkward toggle.

Thoughts?

**Comment by Vezzra** [comment]
>  The follow-up PR might also be ready in time, but I can't guarantee that

[I've extended the deadline for the creation of the release branch by a week](http://www.freeorion.org/forum/viewtopic.php?p=79317#p79317), do you think that will be enough? Because...

> What I'd like to do from here is: split the calculation of default window positions from the MapWnd, BuildDesignatorWnd, TechTreeWnd, DesignWnd and ClientUI constructors so that those defaults can be recalculated at any time based on the current app size.

...this seems rather important. Right now, you have to quit, restart and set the toggle in the options dialog to reset the default window sizes/positions after an app window resize. Lets say, that's bearable, but far from ideal. If we can get in what you propose here for 0.4.5, that would go a long way to make this better.

But if that's too much even for the delayed deadline, no problem. What you've accomplished here is already a really big step, this feature has been requested repeatedly since forever. Thumbs up! :smiley:

> Thoughts?

As far as I'm concerned, by all means, go ahead!

**Comment by mel-odious** [comment]
Thanks! :smile: 
I've done what I mentioned above, plus I included a toggle to _always_ reposition windows when the app size changes alongside the button to reposition them.   It's all a bit of a hack but I'll have a PR up soon to see what the others say about it.

**Comment by Vezzra** [comment]
> I included a toggle to always reposition windows when the app size changes alongside the button to reposition them

Ah, now that's a very good idea! :+1:

**Pull request merged**
