### PR TITLE
Let AI scrap Gateway to the void

### LINKED ISSUE #2715: AI owned Gateway to the Void causes self-pwnage
[Bug reported by spikethehobbit on the forum](https://www.freeorion.org/forum/viewtopic.php?f=28&t=11490):

### Environment

* **FreeOrion Version**: 2019-12-16.cf05826

### Description

An AI player captured an outpost on the same turn that a Gateway to the Void was completed there. The AI then kept trying to reinforce that system with predictable results.

### Suggestion

If the AI manages to capture a GttV, it should sell it if it doesn't want it.

### PR DESCRIPTION
**Pull request by Morlic-fo**
Resolves #2715

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I don't consider this release blocking, but if there's an RC2, then this could presumably go in? @Vezzra not sure how to tag accordingly.

**Comment by TheSilentOne1** [comment]
Should the AI also scrap concentration camps if it conquers them? In multiplayer it's often used as a strategy to prevent an enemy from acquiring your species.

**Comment by Morlic-fo** [comment]
There is already dedicated code for Concentration Camp handling which may also scrap it.

**Comment by Vezzra** [comment]
> I don't consider this release blocking, but if there's an RC2, then this could presumably go in? @Vezzra not sure how to tag accordingly.

Sounds reasonable. Tagging as "cherry-pick for release" is fine in such cases.

**Pull request merged**
