### PR TITLE
added a (yellow, 3-flanged) mouseover indicator for unexplored systems

### PR DESCRIPTION
**Pull request by Dilvish-fo**
It has come up in forum discussions that it can matter whether or not you have explored a system, but that the UI currently does not make this status information available to you.   The normal system mouseover overlay has 4 white flanges, with this PR if you have not explored the system then the mouseover overlay instead has 3 yellow flanges.  I think the icon is reasonable but I don't claim it to be any better than reasonable.  If someone wants to post a different icon to propose, feel free to do so, but please don't ask me to create a different icon myself.

unexplored system

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
I have felling that most users will miss that.    `unexplored` instead of name or icon near name looks better for me.

PS. I don't remember how mouseover works, screenshot tells me that it highlight more than one planet.

**Comment by Dilvish-fo** [comment]
> I have felling that most users will miss that. unexplored instead of name or icon near name looks better for me.

It should wind up making it into the guide, or many people won't figure it out, true enough.   We definitely don't want to replace the name because that could be referenced in other places & they might need to know (and be entitled to know) what the name of the system is.  A tooltip would be a different approach that could be fine, but it would be a totally different implementation.

> PS. I don't remember how mouseover works, screenshot tells me that it highlight more than one planet.

You explore systems, not planets (even if planets are something you might discover while exploring a system).

**Comment by geoffthemedio** [comment]
A line of text on the sidepanel indicating "Unexplored" when that is the case would be fairly simple to implement, and would be helpful independently of whether a mouseover indicator such as proposed here is added. Such text would look like the star/system type text already on the sidepanel.

**Comment by Deepsloth** [comment]
I would really like a tooltip for systems. It could also show the number of planets after exploring. And maybe specials.

**Comment by Dilvish-fo** [comment]
Ok, well it's not clear that everyone would really like this-- sounds like some people would prefer some kind of tooltip, or sidepanel indicator.  So I've made this subject to an OptionsDB options and widget so those people who don't like it could turn it off.

**Pull request merged**
