### PR TITLE
Rename GG's client class HumanClientApp to GGHumanClientApp

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
If you're planning to add other HumanClientApp variants, would it make sense for the GG-specific stuff to be moved into a derived class, and common stuff kept in a `HumanClientApp` class?

I'm not sure how much of the existing code that uses the `HumanClientApp` class could be still used with another window manager, but perhaps it's some?

Otherwise, seems fine...

**Comment by o01eg** [comment]
@geoffthemedio I think it will be simpler to move GG-unrelated code to new common `HumanClientApp`.

We got code copied code in `ClientAppFixture` from tests and it will be in a Godot client as well.

**Comment by geoffthemedio** [comment]
Would you do that instead of this then, or separately later and still would merge this now?

**Comment by o01eg** [comment]
Yes, I want inheritance looks like `GGHumanClientApp` -> `HumanClientApp` -> `ClientApp` instead of some `HumanClientApp` -> `CommonHumanClientApp` -> `ClientApp`.

**Review by Vezzra — APPROVED** [review]
Builds and runs ok on my Mac.

**Comment by geoffthemedio** [comment]
> Yes, I want inheritance looks like `GGHumanClientApp` -> `HumanClientApp` -> `ClientApp` instead of some `HumanClientApp` -> `CommonHumanClientApp` -> `ClientApp`.

So will you do that instead or separately later and want to merge this now?

**Comment by o01eg** [comment]
@geoffthemedio Yes, I would like to merge it now and make next changes later. Currently I want to prioritize python parsing.

**Comment by geoffthemedio** [comment]
I get conflicts when I try to pull this on top of master...
````
>git pull https://github.com/o01eg/freeorion.git rename-human-client-app
From https://github.com/o01eg/freeorion
 * branch                rename-human-client-app -> FETCH_HEAD
warning: Cannot merge binary files: msvc2017/FreeOrion/FreeOrion.vcxproj (HEAD vs. 7b54a14f6487122d4dcc12ee18afc160097c4280)
Auto-merging msvc2017/FreeOrion/FreeOrion.vcxproj
CONFLICT (content): Merge conflict in msvc2017/FreeOrion/FreeOrion.vcxproj
Automatic merge failed; fix conflicts and then commit the result.
````

**Comment by o01eg** [comment]
@geoffthemedio Rebased it.

**Pull request merged**
