### PR TITLE
New default font Roboto ver. 2.001101 (2014)

### PR DESCRIPTION
**Pull request by Ouaz**
- Add Roboto-Regular as new default font for text and title
- Add Roboto-Bold as new default bold font
- Increase font default sizes (16pt for text, 17pt for title)
- Move fonts to a dedicated folder

Discussion: http://freeorion.org/forum/viewtopic.php?f=28&t=10158

### CODE REVIEW

**Comment by adrianbroher** [comment]
Please add next time a link to the discussion.

**Comment by Cjkjvfnby** [comment]
> The font family supports all Latin, Cyrillic, and Greek characters in Unicode 7.0

Is it cover all languages that have stringtables?

**Comment by Ouaz** [comment]
> Is it cover all languages that have stringtables?

See dbenage-cx post here: http://freeorion.org/forum/viewtopic.php?p=84919#p84919

**Comment by dbenage-cx** [comment]
@Cjkjvfnby curious where you see this statement?  It looks misleading (and incorrect for Greek).

**Comment by Cjkjvfnby** [comment]
@dbenage-cx, I googled this font and find it in description https://github.com/google/roboto/

**Comment by dbenage-cx** [comment]
Ah, thank you.  To note, the version posted in this PR (and comparisons I've made) are for Version `2.001101; 2014` with 1250 glyphs.  The latest release of this font is `v2.134` with 3387 glyphs (unhinted).

**Comment by Vezzra** [comment]
Any reason not to use the latest version? If it's more "glyph-complete"?

**Comment by Vezzra** [comment]
Test on OSX looks good... I even have the impression that several visual glitches which turned up with the increased default font size seem to be gone with the new font. If that turns out to be actually the case, then this is a major improvement 😃

**Comment by Ouaz** [comment]
@Vezzra 

> Any reason not to use the latest version? If it's more "glyph-complete"?

I had tested the latest version, it's actually more "glyph-complete", but unfortunately, the font itself looks bad in FO...
Because there has been a lot of modifications between the version in this PR and the latest version:

roboto_cmp

As you can see, the newest font version is much more condensed and has less weight. I only made a comparison between sitrep windows, but it's even worse in the other UI areas (particularly in Design Windows)

That's why I chose the 2014 version, even if there are less glyphs.

Note: if I set to 16pt, it's too big then (the "narrowness" doesn't look good at all):

roboto_last_16

**Comment by Cjkjvfnby** [comment]
`Roboto` is family of the fonts (As I understand from description) may be it is possible to choose other style?

**Comment by Ouaz** [comment]
Oh yeah, sorry, I forgot to indicate the font style in the description: Roboto-Regular.

Roboto-Bold is used as the bold font (Pedia article titles, System names in the sidepanel, and some other ones).

**Comment by Vezzra** [comment]
Ah, ok, I see.

Well, apparently all the glyphs currently in use are covered, so if nobody has any objections left, I guess we can merge?

**Comment by adrianbroher** [comment]
> Well, apparently all the glyphs currently in use are covered […]

Didn't check in game, but the [Glyph list](https://github.com/google/roboto/blob/master/res/glyphlist.txt) from the Roboto repository doesn't list at least `⟳    U+27F3  CLOCKWISE GAPPED CIRCLE ARROW` so I assume it doesn't exist? I haven't checked the other string tables yet so there are maybe more missing glyphs.

Also backup of my little helpers:

shell command:

``` bash
perl -C -ne'print grep {!$a{$_}++} /\X/g' default/stringtables/*.txt | ./unicode-names.py
```

unicode-names.py

``` python
#!/usr/bin/python
import sys, unicodedata

for ch in sys.stdin.read().decode('utf-8'):
    try:
        print "%c\tU+%04X\t%s" % (ch, ord(ch), unicodedata.name(ch))
    except ValueError:
        print "%c\t U+%04X\t%s" % (ch, ord(ch), "<not listed in unicodedata>")
```

**Comment by Ouaz** [comment]
> Didn't check in game, but the Glyph list from the Roboto repository doesn't list at least ⟳ U+27F3 CLOCKWISE GAPPED CIRCLE ARROW so I assume it doesn't exist?

Oh... good catch, I missed this one.

Unfortunately, this missing glyph causes a UI display glitch (in Production Queue Panel):

prod_queue_icon

> I haven't checked the other string tables yet so there are maybe more missing glyphs.

For my part, I've checked only the special letters/signs from main european alphabets (cf. http://www.freeorion.org/forum/viewtopic.php?p=84931#p84931). AFAIK, none is missing though.

**Comment by Ouaz** [comment]
I added  ⟳ U+27F3 and ⟲ U+27F2 in Roboto-Regular font file (with FontForge). 

unicode_27f2_27f3

The clockwise arrow displays now correctly in the Production Queue:

queue_prod_font_mod

However, can someone test on Mac the new Roboto-Regular font file (here  8b534fd), just to be sure it displays also correctly. Thanks.

**Comment by dbenage-cx** [comment]
Nice work Ouaz.
Using the above script, I only see 5 missing glyphs:
3 are only used on one single line, under star names: [en.txt:14860](https://github.com/freeorion/freeorion/blob/master/default/stringtables/en.txt#L14860)
`ṛ`(U+1e5b), `ȍ` (U+020d),`̋` (U+030b)
2 were recently dropped from en.txt and remain only as comments in de.txt:3175 and fr.txt:4865
`△` (U+25b3), `▽` (U+25bd)
I'd opt to remove them from the stringtables, assuming `Tàuṛa̋ṛȍ` is the Hausa word meaning star.

**Comment by dbenage-cx** [comment]
Don't see any issues on OS X 10.7 (build 2016-08-09.42dc1a3, manual font addition), the added glyph displays on production screen.

**Comment by adrianbroher** [comment]
@Ouaz What is the version of the font you're using here? Please document this in the commit message.

I don't want to waste my time with manually checking the glyph completeness when I can just check the glyph list inside the Roboto repository for the corresponding font version.

**Comment by Ouaz** [comment]
@adrianbroher 

> What is the version of the font you're using here? Please document this in the commit message.

Yes, sorry. I used the version 2.001101 (2014). The latest version doesn't look good in FO (cf. my https://github.com/freeorion/freeorion/pull/843#issuecomment-238099337)

I updated the commit title and message.

@dbenage-cx 

> Using the above script, I only see 5 missing glyphs:
> 3 are only used on one single line, under star names: en.txt:14860
> ṛ(U+1e5b), ȍ (U+020d),̋ (U+030b)
> 2 were recently dropped from en.txt and remain only as comments in de.txt:3175 and fr.txt:4865
> △ (U+25b3), ▽ (U+25bd) 
> I'd opt to remove them from the stringtables, assuming Tàuṛa̋ṛȍ is the Hausa word meaning star.

Nice, thanks for the report. We're almost there, then.

**Comment by Cjkjvfnby** [comment]
@Ouaz, did you try versions between version 2.001101 (2014) and current?  May be choose looking same but with max number of letters?

**Comment by adrianbroher** [comment]
I've checked the font version again found the following glyphs missing:

Roboto-Regular.ttf

```
△ U+25B3  ✗ WHITE UP-POINTING TRIANGLE
▽ U+25BD  ✗ WHITE DOWN-POINTING TRIANGLE
ṛ U+1E5B  ✗ LATIN SMALL LETTER R WITH DOT BELOW
    U+030B  ✗ COMBINING DOUBLE ACUTE ACCENT
ȍ  U+020D  ✗ LATIN SMALL LETTER O WITH DOUBLE GRAVE
    U+20E0  ✗ COMBINING ENCLOSING CIRCLE BACKSLASH
```

Roboto-Bold.ttf

```
⟳ U+27F3  ✗ CLOCKWISE GAPPED CIRCLE ARROW
△ U+25B3  ✗ WHITE UP-POINTING TRIANGLE
▽ U+25BD  ✗ WHITE DOWN-POINTING TRIANGLE
ṛ U+1E5B  ✗ LATIN SMALL LETTER R WITH DOT BELOW
    U+030B  ✗ COMBINING DOUBLE ACUTE ACCENT
ȍ  U+020D  ✗ LATIN SMALL LETTER O WITH DOUBLE GRAVE
    U+20E0  ✗ COMBINING ENCLOSING CIRCLE BACKSLASH
```

@dbenage-cx already has pointed out that we don't need U+25B3 or U+25BD anymore and deleting the offending star name _Tàuṛa̋ṛȍ_ takes care of U+1E5B, U+030B and U+020D.

This leaves U+20E0, used in UI/EncyclopediaDetailPanel.cpp:298 and UI/EncyclopediaDetailPanel.cpp:307.  I have no idea what they are used for. @Dilvish-fo maybe can shed some light into that.

**Comment by Ouaz** [comment]
@adrianbroher 

> This leaves U+20E0, used in UI/EncyclopediaDetailPanel.cpp:298 and UI/EncyclopediaDetailPanel.cpp:307. I have no idea what they are used for.

That's weird because `U+20E0 ('COMBINING ENCLOSING CIRCLE BACKSLASH')` is also missing in DejaVuSans 2.34 (font version used currently in FO), according to FontForge (and Charmap). So, I assume this glyph is not displayed in FO.

dejavusans2-34_missing_20e0

@Cjkjvfnby 

> did you try versions between version 2.001101 (2014) and current? May be choose looking same but with max number of letters?

I searched for more recent versions than 2.001101 (2014) and older than 2.134 (2016), but I only found one:
- Roboto 2.001047 (2015) ; 3386 glyphs

Unfortunately, 2.001047 looks as bad in FO as the most recent version 2.134, compared to 2.001101 (same modifications that I listed in my https://github.com/freeorion/freeorion/pull/843#issuecomment-238099337 - less weight, narrower style, slightly smaller line height).

It seems 2.001101 is definitely the best version.

EDIT:

> Roboto-Bold.ttf
> ⟳ U+27F3  ✗ CLOCKWISE GAPPED CIRCLE ARROW

I also added U+27F2 and U+27F3 in Roboto-Bold (clockwise gapped circle arrow), but I didn't commit, because I think it's not necessary, as the -Bold font is only used (AFAIK) for System names and Pedia article titles.

**Comment by Vezzra** [comment]
Status on this? Have the most pressing issues with the new font suffciently addressed so we can merge? If not, hurry up if you want to get it in for the release. I'm removing the "Release v0.4.6" milestone, because I don't want to delay/block the release for this. As nice as it would be to have it in, it's definitely not something critical.

**Comment by geoffthemedio** [comment]
Re-bump...

**Comment by Ouaz** [comment]
Pending modifications:
- Remove star name `Tàuṛa̋ṛȍ` in the english stringtables  (or replace it by `Tauraro`) 
- AdrianBroher [pointed out](https://github.com/freeorion/freeorion/pull/843#issuecomment-240451664) that `U+20E0 ('COMBINING ENCLOSING CIRCLE BACKSLASH')` is missing in Roboto-Regular font, but [this glyph](http://www.fileformat.info/info/unicode/char/20e0/index.htm) is also missing in the DejaVuSans font currently used in FO (2.34), so I think it is not displayed anyway.
  This glyph is used [here](https://github.com/freeorion/freeorion/blob/master/UI/EncyclopediaDetailPanel.cpp#L298) and [here](https://github.com/freeorion/freeorion/blob/master/UI/EncyclopediaDetailPanel.cpp#L307) in FO code.

Otherwise, on my part, the PR is ready to merge.

EDIT: I added `U+20E0 ('COMBINING ENCLOSING CIRCLE BACKSLASH')` to my local Roboto-Regular font file, but I didn't commit, as I can't check if the glyph is correctly displayed in FO (I don't know where it is supposed to be displayed and under which conditions -somewhere in Pedia species articles?-)

**Comment by Vezzra** [comment]
> Remove star name `Tàuṛa̋ṛȍ` in the english stringtables (or replace it by `Tauraro`)

Done: 490a3f3557046cb7ccf3217164cd8f1049e1e766

I suggest adding the missing glyph, commit the thing and merge the PR (provided that's the only remaining issue with the new font). If it's that difficult to find out if/where it's used, it can't be that important.

**Comment by geoffthemedio** [comment]
What does the "⃠ even do in the GUI? When I paste it into chat, I get a quote mark, and I don't ever see it in the pedia text.

**Comment by adrianbroher** [comment]
> What does the "⃠ even do in the GUI? When I paste it into chat, I get a quote mark, and I don't ever see it in the pedia text.

As far as I know it's not a regular glyph, but a 'combining enclosing' one. This means that the character in front is taken and the combining character is overlayed on top of the other one. Like this:



And regarding the 'what it does': No idea. References are [UI/EncyclopediaDetailPanel.cpp:298](https://github.com/freeorion/freeorion/blob/master/UI/EncyclopediaDetailPanel.cpp#L298) and [UI/EncyclopediaDetailPanel.cpp:307](https://github.com/freeorion/freeorion/blob/master/UI/EncyclopediaDetailPanel.cpp#L307).

**Comment by adrianbroher** [comment]
> I suggest adding the missing glyph

I advise against it. The combining encosing marks need special metrics to do their overlay magic as far as I understand.

**Comment by Vezzra** [comment]
Well, then merge as is, unless there is anything else that hasn't been addressed. Apparently that glyph isn't actually used.

**Comment by adrianbroher** [comment]
> Well, then merge as is, unless there is anything else that hasn't been addressed.

Is there a reason to keep the DejaVu fonts? They are not referenced anymore.

> Apparently that glyph isn't actually used.

It is, but as a sorting key apparently to separate existing homeworlds from non existing ones.  I replaced it with a zero width space locally and I didn't notice any change in the order so I will replace the character  sometime in the future.

**Comment by geoffthemedio** [comment]
A comment in the code explaining the purpose would also be helpful.

**Comment by Vezzra** [comment]
> Is there a reason to keep the DejaVu fonts?

Probably not. @geoffthemedio, any reason to keep them?

**Comment by Ouaz** [comment]
I kept the DejaVuSans font files because of Geoff's statement:

"The 3 existing font files are collectively ~2.5 MB (including the two that are seemingly never used?), so I don't see a need to remove them to add the new default font file / files."

> http://www.freeorion.org/forum/viewtopic.php?p=84928#p84928

On the other hand, we can keep DejaVuSans fonts as available font files for unsupported stringtable languages (chinese, hebrew, or whatever...), if in the future, someone needs a more "glyph-complete" font file.

**Comment by Vezzra** [comment]
Okay, if we should keep the DejaVu fonts is actually a separate issue, not reaching a consensus there should not keep this PR from being merged. So unless there is anything else left that needs to be addressed, I'd say leave the DejaVu fonts for now, go ahead and merge.

We can always remove them in a second step. Personally I'd prefer to remove them, we have this habit of leaving obsolete stuff around (be it keeping files that are no longer used, commented out code etc.) and accumulating clutter. Which IMO isn't really necessary when working with a VCS where a complete history of everything is kept.

**Comment by geoffthemedio** [comment]
I'd keep them for people who want to use languages that Roboto doesn't support. The unused oblique and bold-oblique font files can be disposed of, though.

**Comment by adrianbroher** [comment]
> I'd keep them for people who want to use languages that Roboto doesn't support.

We don't have any language that isn't supported by Roboto. Also wouldn't the Noto font be the natural choice here?

**Comment by Ouaz** [comment]
> Also wouldn't the Noto font be the natural choice here?

When I looked for a new font, I tried the Noto font (Version 1.06, 2415 glyphs), and made some comparison screenshots. Although Noto looks good in FO,  it has a "lighter" style/weight than Roboto (very good for printing, but not so much for reading text on a screen) and a too big line height (compare "Planetary Cloaking Device" or "Neutronium Synthesizer" in the Producible Items table)

prod_window

map_window

Overall, Roboto has much impact and is less tiring to read, due to its true "Regular" style (Noto has rather a "Book" style).

But if the unsupported glyphs really becomes a problem in the future, Noto will be the solution.

**Pull request merged**
