### PR TITLE
Species policy preferences

### PR DESCRIPTION
**Pull request by MichaelCourtney**

### CODE REVIEW

**Comment by hifron** [comment]
What about some maluses, overhead it could not be alone...

**Comment by MichaelCourtney** [comment]
That should be the lot of them. Some are a bit arbitrary but I guess that can be fixed later if anyone disagrees

**Comment by hifron** [comment]
researchable...

**Comment by geoffthemedio** [comment]
@Oberlus any comment?

I guess you already 👍

**Pull request merged**
