### PR TITLE
lower the min unfocused FPS to 0.1

### PR DESCRIPTION
**Pull request by l29ah**
It lowered the CPU consumption considerably on my laptop compared with 1.
Couldn't test with smaller values because of the rounding in the UI.

### CODE REVIEW

**Comment by Oberlus** [comment]
I got this when starting freerion after last update, and it seems related to this PR:

`[0x00007f018687b8c0] [info]    OptionsDB::SetFromXMLRecursive() : while processing config.xml the following exception was caught when attempting to set option "video.fps.unfocused": bad lexical cast: source type value could not be interpreted as target`

Using Ubuntu 16.04.

**Comment by geoffthemedio** [comment]
Does that continue happening even after deleting config.xml ?

I don't get that line, but it may be related to number conversions working differently with different compilers or standard libraries...

**Comment by Oberlus** [comment]
> Does that continue happening even after deleting config.xml ?

After deleting config.xml I no longer get that message.
Then, after rearranging the windows to my like and exiting FO I get the message again when I restart FO.
The game works fine anyway and I don't feel FO is using more or less CPU than before (I mean, fans are not noisy).

**Comment by geoffthemedio** [comment]
Try after https://github.com/freeorion/freeorion/commit/f15151b6961cd4f7520c6722593abce0819a2435

**Comment by Oberlus** [comment]
> Try after [f15151b](https://github.com/freeorion/freeorion/commit/f15151b6961cd4f7520c6722593abce0819a2435)

That solved my problem.

**Comment by Vezzra** [comment]
@geoffthemedio, I assume f15151b6961cd4f7520c6722593abce0819a2435 should be cherry picked into the release branch, too?

**Pull request merged**
