### PR TITLE
Cleanup buildings

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
I am playing with the idea to create dedicated enums for each building type. 

I have moved shipyard enums to a separate Enum, IMHO this looks better in the code since names became shorter without losing any information.

Enum could not be inherited, so I move base functions to a separate class.

@Grummel7 what do you think?

PS. These changes are related to the code, so they should be merged only after review.  There is no time pressure on that PR.

### CODE REVIEW

**Comment by Grummel7** [comment]
I guess the new enum should be called ShipyardType to fit in.

In my current development, I'll iterator over all building types.  Is there an easy way to iterator over two enums? Otherwise you should provide maybe a tuple with all types.

The PR would be an elegant way to get rid of AIDependencies.SHIP_FACILITIES.
Logically it's a bit weird, though. Shipyards are buildings, after all. The doc string of BuildingType should at least mention that shipyards have their own class and ShipyardType should have a doc-string as well.

Code wise I see no problem with this.

**Comment by Cjkjvfnby** [comment]
> 
> In my current development, I'll iterator over all building types. Is there an easy way to iterator over two enums? 


```python
from enum import Enum
from itertools import chain


class Foo(Enum):
    A = 1
    B = 2

class Boo(Enum):
    C = 3
    D = 4


for x in chain(Foo, Boo):
    print(x)
```

**Comment by Cjkjvfnby** [comment]
> I guess the new enum should be called ShipyardType to fit in.

We use BuildingType to avoid confusion with the building class in C++ interface.  Shipyard is not used so we could claim it. The same for other specific building types.

**Comment by Cjkjvfnby** [comment]
Reorganize dos in a slightly different way.

**Comment by Cjkjvfnby** [comment]
@Grummel7 , could you take a second look?

**Review by Grummel7 — CHANGES_REQUESTED** [review]
Since it is already merged, you could as well fix this line to use a chaining of both types:
https://github.com/freeorion/freeorion/blob/d75dd157b0feb76ac9be38120907a250eb2ef117/default/python/AI/colonization/calculate_stability.py#L85

Apart from that, I still think it is okay.

**Comment by Cjkjvfnby** [comment]
Opps, forget to push the last commuit.

**Pull request merged**
