### PR TITLE
Removed MSVC 2010 project files.

### PR DESCRIPTION
**Pull request by geoffthemedio**
Any objection to removing this?

### CODE REVIEW

**Comment by TheSilentOne1** [comment]
Fine by me, I use MSVC 2013.

**Comment by adrianbroher** [comment]
> Any objection to removing this?

No, course not. One less solution to maintain.

**Comment by Vezzra** [comment]
And one less SDK. I've also switched to MSVC 2013, so as far as I'm concerned, scrap it.

**Comment by Vezzra** [comment]
I've removed the MSVC 2010 SDK from sourceforge (moved it to the "Old Versions" folder), [posted a notification](http://freeorion.org/forum/viewtopic.php?f=9&t=1787&p=82685#p82685) that support for MSVC 2010 has been dropped in the [Windows SDK thread](http://freeorion.org/forum/viewtopic.php?f=9&t=1787) on the forum, and updated the ["Compile In Windows" wiki page](http://freeorion.org/index.php/Compile_In_Windows) accordingly.

**Pull request merged**
