### PR TITLE
Reworked priorities and grooming

### PR DESCRIPTION
**Pull request by Oberlus**
A rework of the priorities macros names that
- Ensures/facilitates that all Set(Current)Meter effects execute after all SetTargetMeter/SetMaxMeter calls (except for last priority overrides).
- Adds first and second scaling priorities for all SetTarget<meter> calls, with steps in between. 

Also
- Removed references to DEFAULT_PRIORITY (and the inclusion of priorities.macros wherever possible).
- Grooming.

[Forum thread](https://www.freeorion.org/forum/viewtopic.php?p=103690#p103690).

Further work on effects priorities will depend on this PR.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
seems reasonable, but probably needs some substantial testing...

**Comment by Oberlus** [comment]
> probably needs some substantial testing...

I'm in a game turn 230, no problems so far. Current meter regeneration are OK, no surpirses in TargetMeters.

Most changes are a macro renaming with no effective change in game.
There are few changes that alter master's priorities, like ensuring all Set(Current)Meter are called after last SetTargetMeter, and to those I am paying more attention, with no issues to report for now.

I'll play another game with less hassle to be sure.

**Comment by Oberlus** [comment]
This will be good to merge once #3195 and #3170 are merged and I solve probable merge conflicts.

**Comment by Oberlus** [comment]
Good to merge.

**Comment by geoffthemedio** [comment]
needs rebase

**Comment by Oberlus** [comment]
Good to merge (unless AI unittests fail)

**Pull request merged**
