### PR TITLE
Join all flake8 configs and tasks together

### PR DESCRIPTION
**Pull request by Cjkjvfnby**

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@o01eg looks like we are using almost the same rules for lining different parts of code.  

Merging them together will simplify managing a bit. 

What do you think?

**Comment by o01eg** [comment]
It's fine but parser builtins should not be applied to non-parser Python code. Can we override it?

**Comment by Cjkjvfnby** [comment]
> It's fine but parser builtins should not be applied to non-parser Python code. Can we override it?

Yes.  Now we have a single config file and in the AI linting, we override additional builtins to empty list.

**Comment by o01eg** [comment]
I suppose fix commits could be squashed.

**Comment by Cjkjvfnby** [comment]
> I suppose fix commits could be squashed.

Squash and merge is my default option for merging. They will be squashed.
изображение

**Pull request merged**
