### PR TITLE
Named Values for Influence and follow-ups

### PR DESCRIPTION
**Pull request by Oberlus**
- Named Values for Influence modifiers
- Follow-ups and grooming
- Addition of Research Focus encyclopedia page
- Improvement of descriptions of some policies

Follows up #3216

### CODE REVIEW

**Comment by Oberlus** [comment]
Ehmm... This includes the commits from #3216. I'll rebase after it has been merged.

**Comment by Oberlus** [comment]
The smoketests failed because the job exceeded the maximum log length and was terminated.
The logs are huge due to lots of named value debugging info.

**Comment by o01eg** [comment]
@Oberlus Successful tests don't produce logs, I suppose there was something failing.

**Comment by Oberlus** [comment]
> Successful tests don't produce logs, I suppose there was something failing.

Smoketests run in my local finished with no errors. Dunno what's going on.

**Comment by o01eg** [comment]
I suppose it isn't issue with PR but with master. I've launched tests many times and sometimes I get 
```
[warn] ai : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 215410 != client 2208271

[warn] ai : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 215410 != client 6123322

[warn] test : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 2208271 != client 215410
```

**Comment by agrrr3** [comment]
> I suppose it isn't issue with PR but with master. I've launched tests many times and sometimes I get
> 
> ```
> [warn] ai : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 215410 != client 2208271
> 
> [warn] ai : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 215410 != client 6123322
> 
> [warn] test : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 2208271 != client 215410
> ```

do i understand correctly that that means that there were differences in the contents of the three registries?

**Comment by Oberlus** [comment]
@agrrr3 I can reproduce starting multiplayer game in localhost.

**Comment by o01eg** [comment]
> do i understand correctly that that means that there were differences in the contents of the three registries?

@agrrr3 No, for the same content manager produce different checksums.

**Comment by agrrr3** [comment]
> > do i understand correctly that that means that there were differences in the contents of the three registries?
> 
> @agrrr3 No, for the same content manager produce different checksums.

my guess is that the invariants are part the checksums. but these are subject to race conditions without a bigger refactoring.
if that is so a reasonable workaround would be to take the invariants out of the checksums as those are derived anyway.
the clean solution would be to initialise the invariants after parsing is done. another solution would be to initialise invariants on first use - introducing a "m_invariants_initialized" flag into all valuerefs

**Comment by agrrr3** [comment]
Actually the invariants are not part of the checksum. But m_constant_expr in Operation is and that is derived like the invariants. So I will remove that from the checksums for consistency.

**Comment by geoffthemedio** [comment]
> another solution would be to initialise invariants on first use - introducing a "m_invariants_initialized" flag into all valuerefs

not a great idea as it could a probably inlinable / simple function into a test / branch...

**Comment by Oberlus** [comment]
There is a problem with stringtables: the empty strings I removed (the ones ending with _FLAT) are not being substituted by the calculated values. It seems the fix for that didn't work or I'm confused and it wasn't merged. @agrrr3 @geoffthemedio should I add the empty strings back?

**Comment by geoffthemedio** [comment]
Just fix it properly... No need for a temporary workaround.

**Comment by Oberlus** [comment]
> Just fix it properly... No need for a temporary workaround.

Agree. I'm sorry I can't help with that.
@agrrr3 

Edit: meanwhile, this is good to merge. The named values not working will be fixed with someone else's PR addressing the empty strings issue in the backend.

**Pull request merged**
