### PR TITLE
Add More Named values for pedia

### PR DESCRIPTION
**Pull request by MichaelCourtney**
Update to

https://github.com/freeorion/freeorion/issues/3958

There is still more of them to do

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
hmm, don't really understand the linters and tests.

**Comment by geoffthemedio** [comment]
@Cjkjvfnby @o01eg any help with the linter failure?

**Comment by o01eg** [comment]
@geoffthemedio I think it was fixed in https://github.com/freeorion/freeorion/pull/4258

**Comment by MichaelCourtney** [comment]
> @geoffthemedio I think it was fixed in #4258

Seems so. Rebased on latest master and they all pass

**Pull request merged**
