### PR TITLE
[CI] Add merge to weekly release to the merge to master

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
I have created a separate workflow for merge to master and pull requests. 
For the merge to master I have added one more step that is responsible for merging master to the weekly build and require manual approval.

This will allow releasing code by just finding the most latest build in the master and pressing the button.  This step has one difference from the manual merge to the weekly build:  you could do it only when all tests are passed.  Because of test flakiness, I won't say that this is a big benefit. Good old manual merge and pus are still in place, so this should not be a problem.

As a result, we will have 3 levels of reusable workflows, this is a bit too much, but let's leave a bit with it and decide later if we should simplify it.

PS. I am going to merge this branch without a review because the main feature is working on merging to the master. 
If something won't be nice we could always revert these changes.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
Hi @freeorion/developers !

After merging this PR we got a new feature, on each merge to master you will have an option to release the weekly build, just by pressing the approve button.  If this workflow is not approved it will be failed in 30 days.  

изображение

The option to do a release only from UI is nice, but I didn't anticipate that it produces so much noise, by sending notifications on each merge to the master. 

What is your opinion should we keep it or remove it?
As an alternative, I can make this a manual dispatch task.

https://github.com/freeorion/freeorion/actions/runs/5006105931

**Comment by geoffthemedio** [comment]
I'm not sure what difference the notification is making... one needs to click the button regardless. What would making it a "manual dispatch task" change other than removing the notifications?

**Comment by Vezzra** [comment]
Personally I don't mind the extra notifications as long as I can just ignore them (that is, delete them without having to do anything else).

What I need still to work is that if I push the `weekly-test-builds` branch the CI workflows building and deploying the weekly test builds (Windows installer, Windows binaries only package and macOS DMG package) will run like they did until now. Meaning, preferrably without any further intervention by me.

Or will I have to go to some Github page to press a confirmation button for the actual deployment to happen? In that case I'd really appreciate a notification once the workflows are complete and the confirmation button is available. Those workflows can take quite some time, and it would be annoying if I have to check into Github to see if the workflows have completed and the button is already there.

If that notification contains a direct link to the Github page with that button, that would be even better.

But the optimal solution would be if all I have to do is push the `weekly-test-builds` branch, like it worked until now... 😃

**Comment by Cjkjvfnby** [comment]
> I'm not sure what difference the notification is making... one needs to click the button regardless. What would making it a "manual dispatch task" change other than removing the notifications?

I'd say nothing. 


> What I need still to work is that if I push the weekly-test-builds branch the CI workflows building and deploying the weekly test builds (Windows installer, Windows binaries only package and macOS DMG package) will run like they did until now. Meaning, preferrably without any further intervention by me.

This workflow is run only on the master.  When you press the button it will just merge `master` to `weekly-test-builds`.  Merge will trigger another workflow, the same as manual merge.   The idea is that you could choose any master build, check the build status, and approve it, to make a release.

**Comment by o01eg** [comment]
Should we create merge commit in `weekly-test-build` branch instead of fast-forward it?

**Comment by geoffthemedio** [comment]
> create merge commit

why?

**Comment by Cjkjvfnby** [comment]
Also, the action on the weekly build is not triggered when the merge is from another action using GITHUB_TOKEN. 

To fix it need to create PAT (personal access token) with some permissions.
https://github.com/orgs/community/discussions/25702#discussioncomment-3248819

@geoffthemedio could you help with that?

PS. manually push still should trigger the action.

**Comment by Vezzra** [comment]
> > create merge commit
> 
> why?

I want to second that sentiment - why create merge commits? `weekly-test-builds` isn't really a branch, I only use it as a ref. When I push the weekly test builds, I reset the `weekly-test-builds` ref to current master (or, when we're in the process of getting a release out, to the current release branch HEAD) and then (force) push it.

With that workflow, any merge commits will be left dangling. While that isn't really an issue, it's still unnecessary...?

**Pull request merged**
