### PR TITLE
Adjust fuel values and efficiency formula so hull info is correct in …

### PR DESCRIPTION
**Pull request by alleryn**
…pedia

### CODE REVIEW

**Comment by alleryn** [comment]
Hopefully fixes https://github.com/freeorion/freeorion/issues/2541

**Comment by agrrr3** [comment]
I see that you updated 22 hull files. Which fits the expected count (3+13+6). 
Code looks also good to me :) Let's merge ;)

```
for f in GREAT GOOD AVERAGE BAD; do echo $f ; grep --exclude ship_hulls.macros -e "tags.*${f}_FUEL" -r default/scripting/ship_hulls/ -l  | wc -l; done
GREAT
3
GOOD
13
AVERAGE
11
BAD
6
```

**Comment by agrrr3** [comment]
Not sure if pedia should be updated somewhere to explain this(?)

**Comment by alleryn** [comment]
> Not sure if pedia should be updated somewhere to explain this(?)

What is 'this'?

**Comment by alleryn** [comment]
Should i try changing the fuel values to something like, e.g. scout with 2 base fuel and great = 4* efficiency:

BaseFuel = 2
fuel = BaseFuel * [(If HasTag Great_Effic) * 4 + (If HasTag Good_Effic)*2 + ...]

?

Just a thought.  Probably not really useful, and not sure if it would cause any problems.

**Comment by alleryn** [comment]
> > Should i try changing the fuel values...
> 
> What would be the reason for that? Looks like you want to test for all tags instead of just the one the hull is expected to have? Why?

My intention was to improve readability.  RIght now the fuel efficiency is masked in the value of fuel ascribed to the hull, and the "Base Fuel" for that hull is never defined.  

I skipped a step above but i was thinking something like

BaseFuel = 2
Fuel = BaseFuel*[[Fuel Efficiency]]
Fuel Efficiency = '''(If HasTag Great_Effic) * 4 + (If HasTag Good_Effic)*2 + ... '''

I don't know if there's any real reason to retain that BaseFuel value (there isn't any reason now... it would be 'futureproofing'), but that was my thought process.

> 
> One change I would test is replacing `Object id = Source.ID` with just `Source`.

I can test that ~~later today~~ in the near future.
 
> And I didn't really understand the purpose of the `HasTag name = "@1@_FUEL_EFFICIENCY"` other than it was a safety check for scripting errors, but could that condition be put into the activation condition of the effectsgroup instead?

@agrrr3 ?

**Comment by geoffthemedio** [comment]
> I don't know if there's any real reason to retain that BaseFuel value (there isn't any reason now... it would be 'futureproofing')

Seems unnecessary

**Comment by agrrr3** [comment]
> > Not sure if pedia should be updated somewhere to explain this(?)
> 
> What is 'this'?

This is: Change to how fuel / fuel efficiency works.

I grepped myself and both FUEL_REFUEL_EFFICIENCY_TEXT and METER_FUEL_VALUE_DESC refer to base fuel which gets scaled which is not true anymore.

**Comment by agrrr3** [comment]
> > And I didn't really understand the purpose of the `HasTag name = "@1@_FUEL_EFFICIENCY"` other than it was a safety check for scripting errors

You understood the purpose. Only the emphasis on hard-to-catch scripting errors is missing in your description. 


> > , but could that condition be put into the activation condition of the effectsgroup instead?
>
> @agrrr3 ?

As with this PR base fuel is gone, the check is not really helpful anymore. Without base fuel modified by efficiency you only see the discrepancy if you have additional fuel effects and care about those.

So I would rather put it in the activation condition of another effect writing a sitrep. The feature I am trying to emulate is a fail-fast assert which checks the condition after loading the FOCS files and stops the game from starting - but we do not have such a feature.

**Comment by agrrr3** [comment]
> As with this PR base fuel is gone, the check is not really helpful anymore. Without base fuel modified by efficiency you only see the discrepancy if you have additional fuel effects and care about those.

I read the macro again and I was wrong - the fuel should still be set to zero if right tag is missing. So it can stay like it is (besides the simplifying the source id check) and suffices IMHO

> > > , but could that condition be put into the activation condition of the effectsgroup instead?

No. If that check was in the activation condition max fuel would not be set to zero but would stay at hull fuel level and we would miss the error. 

It could be put in the activation condition of another effect but I guess that would be overkill.

**Comment by agrrr3** [comment]
Change in METER_FUEL_VALUE_DESC
```The effective amount of fuel a <encyclopedia ENC_SHIP_DESIGN>Ship Design</encyclopedia> is scaled by the [[encyclopedia FUEL_EFFICIENCY_TITLE]] of the [[encyclopedia ENC_SHIP_HULL]]. Fuel efficiency modifies the base fuel capacity of a <encyclopedia ENC_SHIP_DESIGN>Ship Design</encyclopedia> which depends on the [[encyclopedia ENC_SHIP_HULL]] used, but it can also be increased using some [[encyclopedia ENC_SHIP_PART]]s.```
to 
```The effective amount of fuel a <encyclopedia ENC_SHIP_DESIGN>Ship Design</encyclopedia> depends on the base fuel of the hull and additional fuel effects scaled by the [[encyclopedia FUEL_EFFICIENCY_TITLE]] of the [[encyclopedia ENC_SHIP_HULL]]. Fuel efficiency modifies the effective fuel capacity of fuel effects for example extra fuel given by [[encyclopedia ENC_SHIP_PART]]s.```

**Comment by geoffthemedio** [comment]
>  Fuel efficiency modifies the effective fuel capacity of fuel effects for example extra fuel given by [[encyclopedia ENC_SHIP_PART]]s.

Fuel efficiency changes the effective capacity of fuel [[encyclopedia ENC_SHIP_PART]]s and will multiply any other fuel-modifying effects.

**Comment by alleryn** [comment]
> One change I would test is replacing `Object id = Source.ID` with just `Source`.

Seemed to work fine.

**Comment by alleryn** [comment]
> I grepped myself and both FUEL_REFUEL_EFFICIENCY_TEXT and METER_FUEL_VALUE_DESC refer to base fuel which gets scaled which is not true anymore.

Added agrrr3 and geoffthemedio's changes to METER_FUEL_VALUE_DESC and edited FUEL_REFUEL_EFFICIENCY_TEXT.

**Comment by alleryn** [comment]
Still to do (at least):

- 
> And I didn't really understand the purpose of the `HasTag name = "@1@_FUEL_EFFICIENCY"` other than it was a safety check for scripting errors, but could that condition be put into the activation condition of the effectsgroup instead?

There was discussion here: https://www.freeorion.org/forum/viewtopic.php?p=97786#p97786 but it's unclear to me where it landed.

- Add Fuel Efficiency to stringtable for every hull

**Comment by Morlic-fo** [comment]
This will also need AI adjustments:
https://github.com/freeorion/freeorion/blob/master/default/python/AI/ShipDesignAI.py#L1037

**Comment by agrrr3** [comment]
> This will also need AI adjustments:
> https://github.com/freeorion/freeorion/blob/master/default/python/AI/ShipDesignAI.py#L1037

Should be something like changing `self.design_stats.fuel *= self._hull_fuel_efficiency()`
to `self.design_stats.fuel = (self.design_stats.fuel - self.hull.fuel ) * self._hull_fuel_efficiency() + self.hull.fuel`

**Comment by agrrr3** [comment]
> `HasTag name = "@1@_FUEL_EFFICIENCY"`

Looks fine to me

>     * Add Fuel Efficiency to stringtable for every hull

just adjust the string tables entries of all hulls accordingly. I think it would be good for players to have the fuel efficiency information in 0.4.9 and I do not see a more generic solution coming up in the next week(s)

**Comment by alleryn** [comment]
> just adjust the string tables entries of all hulls accordingly. I think it would be good for players to have the fuel efficiency information in 0.4.9 and I do not see a more generic solution coming up in the next week(s)

It's unlikely i'll have time to do this in the next month.

Do the other changes look acceptable?  Perhaps i should rebase and we can merge, and someone else can pick up the rest?

**Comment by agrrr3** [comment]
It would be great if you could apply and test the AI change.

I think the current changes look good and I consider it an acceptable risk that the hull descriptions would be not perfect in 0.4.9

**Comment by alleryn** [comment]
> It would be great if you could apply and test the AI change.

I don't foresee having the time to do this in at least the next two weeks (could be longer).

**Comment by agrrr3** [comment]
Note this PR also mitigates a problem I just found. A negative fuel bonus scales the wrong way (being better means less max fuel). I just thought we do not have negative fuel bonus, but forgot species BAD_FUEL is there (which for an great efficiency ship should lead to -1 max fuel). 
For Scylior without the PR this should lead to - with the PR it is an acceptable -2 fuel (so 6 instead of 8)
I will open a separate issue for fixing BAD_FUEL with fuel efficiency.

**Comment by agrrr3** [comment]
I put the AI changes into #2621 and tested. I suggest merging and doing a followup PR for hull info.

Note if the hull info is done manually it should probably happen after fixing #2620

**Comment by geoffthemedio** [comment]
Superceded by #2621

**Pull request merged**
