### PR TITLE
Workaround for Combat Log Crash #3763

### PR DESCRIPTION
**Pull request by geoffthemedio**
layout is messed up, but it doesn't crash for me...

### CODE REVIEW

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/843371910c228e7d6c816ee19914a39e6db419c0

**Comment by Vezzra** [comment]
@geoffthemedio, should 843371910c228e7d6c816ee19914a39e6db419c0 be cherry-picked to the release branch?

**Comment by geoffthemedio** [comment]
it's from april so probly already in

**Comment by Vezzra** [comment]
Oops, of course - sorry, didn't look at the date...

**Pull request closed without merging**
