### PR TITLE
GCS tweak (rebased again)

### PR DESCRIPTION
**Pull request by mel-odious**
This is the branch from [this PR](https://github.com/freeorion/freeorion/pull/60) that I rebased to take into account changes to master since I submitted the first PR.  It rebased without any conflicts and runs fine.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
You just re-submitted a new PR without redoing the commits? My comment on the other PR was about how some people prefer not to have stuff like "Remove commented out code from previous commit.", or successive commits that add and then remove changes. Doesn't need to be, and shouldn't be, squashed into a single commit, but could be re-committed as fewer cleaner commits.

**Comment by mel-odious** [comment]
Oh, I see.  I thought you were talking about changes we both made to the same lines...  Apologies.

**Comment by geoffthemedio** [comment]
If it rebases to master fine, and github says it can be merged, then there's no need to resubmit it just for that...

**Comment by mel-odious** [comment]
I thought you were referencing my comment about using a more recently-rebased version to make the history cleaner.

**Comment by mel-odious** [comment]
Anyway, redoing the commits will take some manual work so I can put up a new PR when I've finished that and tested that it works the same, is that OK?  Again, sorry for polluting the pull requests ;)

**Pull request closed without merging**
