### PR TITLE
Music separate title and play follow up(with sound launch twice fix)

### LINKED ISSUE #3350: Add title screen song that is different from the in-game song
Feature request
===============

Idea
----

Please add something in the title screen code that looks for a different song than the current one. If it's not defined, have it go back to the current behavior (where it plays only one song). This allows the option of adding a title screen song, but if a title screen song doesn't show up, then it wont be silent.

Gain
----

A title screen song would be nice. I hope to write it. I haven't written it yet.

Discussion
----------

[Forum link](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11959)

### PR DESCRIPTION
**Pull request by hifron**
Fixes https://github.com/freeorion/freeorion/issues/3350 and superseeds https://github.com/freeorion/freeorion/pull/3358 by Geoff . This PR is also with fix of music starting twice on FreeOrion program start due OpenAL sound problems errors in current FO sound implementation.

In next PRs I want to enable to have theme dirs and then also species/empires music, but not in this PR.

Some unrelated problem with Python background parsing causing some unresponding window in some Linuxes, but this problem is not caused by this PR and may be solved by increasing timeout for a few seconds(see article on Medium)...
[Medium article about recent changes in Ubuntu/Fedora about waiting for response](https://medium.com/@mathnodes/remove-the-annoying-force-quit-wait-dialog-in-fedora-ubuntu-ca97157ccd08)

### CODE REVIEW

**Comment by Vezzra** [comment]
Can anyone take a look at this...?

**Comment by hifron** [comment]
rebased on master, but Ubuntu Hirsuite docker image(21.04) build failed, because Ubuntu 21.04 is out of support...

**Comment by o01eg** [comment]
> MacOS 10.15 also would be removed by Github by August 30...

It could affect SDK builds.

**Comment by hifron** [comment]
@o01eg @geoffthemedio @Vezzra There is option by docker to use ubuntu-latest and to use Github: ubuntu-latest or macos-latest (currently ubuntu-20.04 LTS, only LTS, Ubuntu 22.04 LTS waiting to be more tested, [MacOS 12=XCode 14 is still in beta, but Xcode 13.4 should be supported also](https://github.com/actions/virtual-environments/issues/5702) and is not latest) and [Docker latest](https://hub.docker.com/_/ubuntu) is not the same as [Github latest](https://github.com/actions/virtual-environments).

In Github latest list of systems there is list for each system what is supported like [MacOS 11](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) for latest supported XCode 13.2.1(default) and min version 11.7

[Github MacOS 10.15 removal](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/), Ubuntu Hirsuit was removed by the end of april, practically today...

**Comment by Vezzra** [comment]
@hifron, concerning the removal of the macOS-10.15 image, we're already working on this. Building the SDK with macOS-11 seems to work, and I've also been able to build and run current FO master on macOS 10.14 with an SDK built on macOS-11 (see my comment [here](https://github.com/freeorion/freeorion-sdk/pull/106#pullrequestreview-1055352102)).

**Comment by Vezzra** [comment]
To quote myself:

> Can anyone take a look at this...?

**Comment by hifron** [comment]
On current master together with Separate title and in-game music track options patch, this PR doesn't work...

**Comment by Vezzra** [comment]
@hifron, closed as abandoned, superseded, ...?

**Comment by hifron** [comment]
if someone could continue ..., he have reference to original pull request by Geoff or to this PR and it is also linked to its issue which Geoff implemented and I found some OpenAl sound issue and fixed them in this PR, but this PR is now abandoned if not merged.

**Comment by Vezzra** [comment]
Ok, then I'll mark this as abandoned. @geoffthemedio, if you want to keep this PR, just reopen and merge it.

**Pull request closed without merging**
