### PR TITLE
Add some convenient hotkeys

### PR DESCRIPTION
**Pull request by vincele**
Add shortcut to exit to desktop
Add shortcut to quit current game to IntroScreen
Add shortcut to toggle fullscreen : ALT-ENTER

The quit and exit ones aren't currently bound to any keys

Signed-off-by: Vincent Legoll vincent.legoll@gmail.com

### CODE REVIEW

**Comment by vincele** [comment]
This is currently compiling...

**Comment by Dilvish-fo** [comment]
Compiles and works fine for me.  Do you use ccache to help speed up compiling? I've given it a few GB of cache space and it really helps a lot; this only took about a minute.

**Comment by vincele** [comment]
Yes I use ccache, but I'm on and old slow laptop, and my cache is full of compilings from a somewhat diverged repo, so all is rebuilt for trunk and take about half an hour...

But it just finished, I'll test it and report there in a few minutes...

Even if you already merged it :-)

**Comment by vincele** [comment]
Looks OK

**Pull request merged**
