### PR TITLE
(AI)Correct some detection values

### PR DESCRIPTION
**Pull request by MichaelCourtney**
These have been wrong, since this commit:

https://github.com/freeorion/freeorion/commit/fd013a621955fc9dcd810cad0ade9aac6cf3d4ea

I assume the value for Sentient Hull has been wrong for longer

### CODE REVIEW

**Comment by o01eg** [comment]
Are those values available from design data?

**Comment by MichaelCourtney** [comment]
> Are those values available from design data?

I'm not sure. But certainly the ship design window reads them "somehow". Some of those values come from macros in the scripting, which I assume is the reason the AI is currently using hard coded values.

**Review by Cjkjvfnby — APPROVED** [review]
I don't how to extract this data from the FOCS scripts.

**Comment by geoffthemedio** [comment]
> I don't how to extract this data from the FOCS scripts.

A ShipDesign's baseline detection from its hull and parts should be accessible as the `detection` property: https://github.com/freeorion/freeorion/blob/master/python/UniverseWrapper.cpp#L591

This value isn't presently exposed for hulls, it seems, though: https://github.com/freeorion/freeorion/blob/master/python/UniverseWrapper.cpp#L665-L668 so I made a pull request to just add that: #4916

**Pull request merged**
