### PR TITLE
Visibility ValueRefs

### PR DESCRIPTION
**Pull request by geoffthemedio**
Adds a Visibility ValueRef type, including an EmpireObjectVisibility lookup. Includes parsing. Also some related Dump function tweaks.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
One potential issue is that order of effects execution may be partly lost, in that only the last-executed effect will be remembered, which sets which ValueRef to evaluate later to get the final visibility for the object. Will that be a problem in practice?

**Comment by Dilvish-fo** [comment]
> ...only the last-executed effect will be remembered...Will that be a problem in practice?

It seems to me it could be a problem if an effect granting max(Partial, Value) were being overwritten by one granting just max(Basic, Value), and I think such situations could be encountered with current content.  Instead of having ```EmpireObjectVisValueRefMap``` record a single entry for each target object, how about having it keep a vector of entries for each target object?

(edited to correct which visibilities map I was referring to)

**Comment by geoffthemedio** [comment]
Just adding a vector of ValueRef to evaluate in order for each object would be OK, and would automatically keep track of the order (and thus effect priorities) of effects applied to each object. But is it expected that there would be cases where the Visibility would be determined using a statistic, which needs to be evaluated at a particular time with respect to other effects setting visibility? This whole system already complicates things a bit with doing that, as the gamestate at the time the effect is run and the time when the visibilities are evaluated will be potentially different, but I think that just has to be accepted... But it could be set up to to run through all the saved ValueRefs in a particular oder, to ensure that effect priorities are respected between different objects, not just per-object. But perhaps that's unnecessary complication for now?

**Comment by Dilvish-fo** [comment]
> But is it expected that there would be cases where the Visibility would be determined using a statistic, which needs to be evaluated at a particular time with respect to other effects setting visibility? 

Well, it's not something that I myself expect.  I do expect that it would be sufficient to simply note these kinds of constraints/limitations/complications in the [SetVisibility subsection](http://www.freeorion.org/index.php/FOCS_Scripting_Details#SetVisibility) I just added to the FOCS Scripting Details wiki page.  For now I also added a link back to here.  Please double check it to see I got the new parsing description right.

> But perhaps that's unnecessary complication for now?

Seems so to me.

**Comment by geoffthemedio** [comment]
Storing and evaluating the vector of ValueRefs for visibility should be implemented now. Quick test with some simple visibility-granting effectsgroups on humans seems to work.

**Pull request merged**
