### PR TITLE
[UI/About] clean up

### PR DESCRIPTION
**Pull request by VPeruS**
Buttons now have shared layout code.
Created difference between border_size and space between info text and buttons.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Looks reasonable. Built and ran OK for me on Wiindows, so disregarding the failed AppVeyor test.

**Comment by VPeruS** [comment]
Maybe it was better to remove destructor completely, as it's not marked as virtual and mark class as final?

**Comment by geoffthemedio** [comment]
Apparently marking derived class destructors as virtual is not recommended: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final

> If a base class destructor is declared virtual, one should avoid declaring derived class destructors virtual or override.

I don't immediately see why they suggest that, though... it doesn't seem to be addressed in the surrounding points.

Making the class final seems reasonable.

**Comment by VPeruS** [comment]
Yeah, if inheritance chain is long then to ensure that class definition is correct you will need to find base class, and it will be tedious

**Comment by VPeruS** [comment]
There is some disscussion about c128 https://github.com/isocpp/CppCoreGuidelines/issues/721

> 1.  If the base class dtor is virtual, both virtual and override on the derived class dtor are used only for the documentary purposes and from this point of view they're equivalent. However the latter is more consistent with the normal methods and hence, IMHO, slightly preferable.
> 2. If the base class dtor is not virtual, the use of virtual is most likely a programmer error and hides a bug such as one illustrated in a previous comment, while the use of override is a compile-time error and so is strongly preferable.

**Comment by geoffthemedio** [comment]
sounds more reasonable

**Pull request merged**
