### PR TITLE
Restore parallel species parsing

### PR DESCRIPTION
**Pull request by o01eg**
Fixes startup slowness found in https://freeorion.org/forum/viewtopic.php?p=115054#p115054

I expect it to be merged to release branch right after split.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
seems to work

presumably the Python parsing could be done in a single detached thread / asynchronously to the rest of setup / rendering, though

**Comment by o01eg** [comment]
> presumably the Python parsing could be done in a single detached thread / asynchronously to the rest of setup / rendering, though

Not sure how to implement such thing as it still should generate single `Pending` structure. Reversion looks simple solution.

**Comment by geoffthemedio** [comment]
Presumably it would return a single Pending struct containing all the Python parsed results.

I'm not suggesting doing that now.

**Comment by o01eg** [comment]
I've re-read it and Python FOCS parser already uses it's own background thread. 

https://github.com/freeorion/freeorion/blob/84dd38e1ec41bf507efd2dd20097492937ae7ed7/client/human/GGHumanClientApp.cpp#L363

**Comment by o01eg** [comment]
When I read first I though it was proposal to parse old FOCS files asynchronously and Python FOCS files synchronously even for same structures.

**Comment by geoffthemedio** [comment]
> I've re-read it and Python FOCS parser already uses it's own background thread.

It launches a thread, but then appears to immediately wait on it returning before continuing execution...
````
    std::promise<void> barrier;
    std::future<void> barrier_future = barrier.get_future();
    std::thread background([this](auto b){
        DebugLogger() << "Started background parser thread";
        PythonCommon python;
        python.Initialize();
        StartBackgroundParsing(PythonParser(python, GetResourceDir() / "scripting"), std::move(b));
    }, std::move(barrier));
    background.detach();
    barrier_future.wait();             // <=== here. not sure I understand what this is doing, but it appears to make the whole threaded evaluation pointless...
````

**Comment by o01eg** [comment]
It was placed here because of https://github.com/freeorion/freeorion/pull/3415

**Review by Vezzra — APPROVED** [review]
Works on macOS

**Pull request merged**
