### PR TITLE
Make python into freeorioncommon dependency

### PR DESCRIPTION
**Pull request by o01eg**
Also uses python library version to find MacOS python folder.

Extracted from #3211.

Follows up #3371 but could be merged separately.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Is Python actually a common library dependency?

**Comment by o01eg** [comment]
It wasn't but it will be one after migration to python parser. Also I found out another usage of python here for MacOS so I decided to extract into separate PR.

Actually the only case when server and AI disabled is Android experimental build. So it isn't some additional dependency.

**Review by Vezzra — APPROVED** [review]
I can build, run and launch a default quickstart game with this PR on macOS.

**Comment by geoffthemedio** [comment]
seems fine

**Pull request merged**
