### PR TITLE
State

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
I extract module level variables and code to set and get them to single module.

Next step will be extracting `ColonizationAI.survey_universe` to method of this module. 

I want this to be merged in this release.

I did not assign this to exact person but want to hear all @freeorion/ai-team comments.

### CODE REVIEW

**Comment by Vezzra** [comment]
Well, that is just @Morlic-fo (besides yourself), as @Dilvish-fo is still MIA...

**Comment by LGM-Doyle** [comment]
As always the code is elegantly done.

I like the getters and setters.

I'm concerned with moving the variables out of ColonisationAI.

With the variables in ColonisationAI, there is better encapsulation.  It is clear that ColonisationAI controls and is responsible for those variables.  In a global state with many variables it is no longer clear which module controls which variable.

Why not put the getters and setters in ColonisationAI?

It would prevent other modules from interfering with the variables and provide better encapsulation.

Either way the code looks well written to me.

**Comment by Cjkjvfnby** [comment]
Thank you.

> Why not put the getters and setters in ColonisationAI?

Because they are not belong to colonization, whole `ColonizationAI.survey_universe` is not belong to colonization.  

> It would prevent other modules from interfering with the variables and provide better encapsulation.

This variables are note belong to single module.

**Comment by LGM-Doyle** [comment]
Sorry.

I thought that all of the setting was being done in one file and the getting was being done in many files.

Encapsulation seemed natural from the code.

**Pull request merged**
