### PR TITLE
Improve GG::ListBox and derived classes.

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This PR improves the performance of `ListBox` based classes.

It refactors `ListBox` so that it will not layout rows that are not
visible.  It does this by adding `PreRender()` to both the `ListBox::Row`
and `ListBox` itself.  To use this functionality fully any classes derived
from `ListBox::Row` must do their initialization in their `PreRender()`.  

Additionally, the `ClientSize()` now correctly accounts for the scroll
bars.

This functionality replaces `ListBox::Row::AdjustLayout()`, which was a
toned down version of `PreRender()` that operated with some lexical scope
to suppress re-layout.  This cause of unpredictability when using
`ListBox::Row` because some operations where immediate and others not.

`ListBox` based classes are upgraded/fixed to work with the new functionality.

### CODE REVIEW

**Comment by adrianbroher** [comment]
Requires #989 and rebase.

**Comment by geoffthemedio** [comment]
rebase?

**Comment by LGM-Doyle** [comment]
Rebased and next.

**Comment by geoffthemedio** [comment]
Breaks player droplists in the multiplayer lobby...
player_drop

**Comment by geoffthemedio** [comment]
Sitrep layout is missing the last few rows, depending on window size and row heights, after resizing the window.

sitrep

**Comment by geoffthemedio** [comment]
Crash when I clicked Colonize. Stack:

```
>   ObjectPanel::Refresh() Line 1300    C++
    ObjectListBox::UpdateObjectPanel(int object_id=230480936) Line 2114 C++
    ObjectListBox::ObjectStateChanged(int object_id=466) Line 2264  C++
    boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void,boost::_mfi::mf1<void,MapWnd,FleetButton const *>,boost::_bi::list2<boost::_bi::value<MapWnd *>,boost::_bi::value<FleetButton *> > >,void>::invoke(boost::detail::function::function_buffer & function_obj_ptr={...}) Line 139  C++
    boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > >(const boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > & connectionBody={...}) Line 120   C++
    boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> >::dereference() Line 82    C++
    boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > first={...}, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > last={...}) Line 58 C++
    boost::signals2::detail::signal_impl<void __cdecl(void),blocking_combiner<boost::signals2::optional_last_value<void> >,int,std::less<int>,boost::function<void __cdecl(void)>,boost::function<void __cdecl(boost::signals2::connection const &)>,boost::signals2::mutex>::operator()() Line 246 C++
    Ship::SetColonizePlanet(int planet_id=453) Line 604 C++
    ColonizeOrder::ExecuteImpl() Line 550   C++
    Order::Execute() Line 39    C++
    OrderSet::IssueOrder(boost::shared_ptr<Order> order={...}) Line 24  C++
    SidePanel::PlanetPanel::ClickColonize() Line 2135   C++
    boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > >(const boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > & connectionBody={...}) Line 120   C++
    boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> >::dereference() Line 82    C++
    boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > first={...}, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > last={...}) Line 58 C++
    boost::signals2::detail::signal_impl<void __cdecl(void),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(void)>,boost::function<void __cdecl(boost::signals2::connection const &)>,boost::signals2::mutex>::operator()() Line 246 C++
    GG::Button::LClick(const GG::Pt & pt=<struct at NULL>, GG::Flags<GG::ModKey> mod_keys={...}) Line 149   C++
    GG::Wnd::HandleEvent(const GG::WndEvent & event={...}) Line 1185    C++
    GG::GUIImpl::HandleMouseButtonRelease(unsigned int mouse_button=0, const GG::Pt & pos={...}, int curr_ticks=210013) Line 521    C++
    GG::GUI::HandleGGEvent(GG::GUI::EventType event=LRELEASE, GG::Key key=GGK_UNKNOWN, unsigned int key_code_point=0, GG::Flags<GG::ModKey> mod_keys={...}, const GG::Pt & pos={...}, const GG::Pt & rel={...}, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > * text=0x00000000) Line 1142 C++
    GG::SDLGUI::HandleSystemEvents() Line 692   C++
    HumanClientApp::HandleSystemEvents() Line 827   C++
    GG::ModalEventPump::operator()() Line 114   C++
    GG::SDLGUI::Run() Line 890  C++
    mainSetupAndRun() Line 286  C++
```

Screen at the time:
click_colonize_crash

**Comment by LGM-Doyle** [comment]
Thanks for testing even though it seems broken.

I am seeing very different results.

I can't duplicate the crashes.  I've played at least a dozen games and +2000 turns with this PR.  I rebased Fighters onto this PR, with no crashes.  

I can duplicate the Multiplayer lobby problem.  I did only did a basic multiplayer start test, so I missed that problem.

I can not duplicate the SitRep problem.  My sitrep goes to SuperTester Takeover the same as master.

I will go through the stack trace and try to figure out why your experience is so different than mine.

**Comment by geoffthemedio** [comment]
After a full clean + rebuild, I'm not getting any crashes now.

With the sitrep, you need to widen it so the entries shown are one line each, and then resize the window. After scrolling, they all render, until the next resize.

**Comment by LGM-Doyle** [comment]
I was glad when I saw that a clean rebuild fixed the crashes.  

I had peered at every function in that stack trace wondering how it was a) causing the crash, b) related to the ListWnd changes and c) so different between Windows and linux. 

I've fixed the MultiplayerLobbyWnd and the SitRepPanel problems.

The SitRepPanel problem was that ListWnd::PreRender() was using a member function to determine the last visible row, which in turn was using the row heights from before prerender.   On my machine the problem was not obvious at my default font size.

**Comment by geoffthemedio** [comment]
The lobby wnd is better, but the layout of the player droplist doesn't look very good, and the height of the droplist is too small.
droplist
I also committed stuff to master that makes fleetwnd.cpp need a rebase.

**Comment by LGM-Doyle** [comment]
I've rebased to master and fixed the problems with drop list.

**Comment by geoffthemedio** [comment]
Better, though the non-dropped part of droplists is still a bit lower than it should be... looks off / misaligned.
droplist1
droplist2
droplist3

**Comment by LGM-Doyle** [comment]
I don't see exactly what you mean., and I don't want to be guessing and moving the pieces one pixel at a time.

I don't think that the main control (part with the arrow) has moved from its original location.

Do you want the main control or the drop list moved?

Where do you want it moved?

What edges/parts to you want aligned?

If I were to guess I would move the dropped list 1 pixel left and 2 pixels down. to align the left edge of the dropped list with the left edge of the main control and to place the top edge of the dropped list on the pixel below the shadow of the main control.

**Comment by geoffthemedio** [comment]
I mean the item in the main part of the dropbox control that shows regardless of whether it is open or not. It appears centred too low in the control. Not sure if this is related to your changes, though if you're in that code already and it is fixable, that would be preferable.

**Comment by LGM-Doyle** [comment]
Now I understand what you mean.  I'll see if I can fix it.

**Comment by LGM-Doyle** [comment]
I've centered the selected item in the control.  It moved it up by 3 pixels with the default font options.  Any more movement and the side panel focus dropdown looks off center.

**Comment by geoffthemedio** [comment]
With this applied, the order of ships being drag-dropped isn't preserved in the dragged rendering... Not a huge issue, I suppose, but a bit confusing...
before
after

**Comment by geoffthemedio** [comment]
I never liked using the rows' on-screen positions in the sort function for their pointers, so if the only way to resolve that would be reverting your modified sorting, then it's fine as is...

**Comment by LGM-Doyle** [comment]
I think that I have restored the previous behavior where drag drop preserves the selected ordering.  I did not intentionally change that.

**Comment by LGM-Doyle** [comment]
Thanks for your time and your patience with this review.

**Pull request merged**
