### PR TITLE
Python unit tests

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This is implementation of infrastructure for `offline` tests for out python code (AI, universe generation, turn events). 

I took changes introduced by @LGM-Doyle in  #677 and make them windows friendly. 

Testing code that required c++ interface is still possible with use of [mock](https://pypi.python.org/pypi/mock) or other libraries.

I expect that this feature will be used by small number of python developers. But if person want to write tests for his code, we should not throw this test away.  

Tested on win7x64

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@freeorion/ai-team,  what do you think?  If I did not get any objections this week, I will merge it.

**Comment by Cjkjvfnby** [comment]
@freeorion/ai-team, can someone check that this work on linux and mac?

**Comment by Vezzra** [comment]
Did test run on OSX, results (using the command line options you recommend in the readme file, `-v --tb long`):

```
======================================================================================================== test session starts =========================================================================================================
platform darwin -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
cachedir: .cache
rootdir: /Users/user/SoftwareProjekte/FO/src/default/python/tests, inifile: 
collected 5 items 

AI/test_parse_ai_tag_grade.py::test_parse_weapon_tag_positive PASSED
AI/test_parse_ai_tag_grade.py::test_parse_weapon_tag_negative PASSED
common/test_print_utils.py::test_print_in_columns PASSED
common/test_print_utils.py::test_simple_table PASSED
common/test_print_utils.py::test_empty_table PASSED

====================================================================================================== 5 passed in 0.03 seconds ======================================================================================================
```

Will also do tests on Linux, will take a while...

**Comment by Vezzra** [comment]
Ok, test results on Linux (Ubuntu 15.10), same command line options:

```
============================================================================== test session starts ===============================================================================
platform linux2 -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python2.7
cachedir: .cache
rootdir: /home/user/SoftwareProjekte/FO/src/default/python/tests, inifile: 
collected 5 items 

AI/test_parse_ai_tag_grade.py::test_parse_weapon_tag_positive PASSED
AI/test_parse_ai_tag_grade.py::test_parse_weapon_tag_negative PASSED
common/test_print_utils.py::test_print_in_columns PASSED
common/test_print_utils.py::test_simple_table PASSED
common/test_print_utils.py::test_empty_table PASSED

============================================================================ 5 passed in 0.06 seconds ============================================================================
```

**Pull request merged**
