### PR TITLE
Fixes installation layout of snap package

### PR DESCRIPTION
**Pull request by o01eg**
Also adds launch test to CI

### CODE REVIEW

**Comment by o01eg** [comment]
@agrrr3 Could you test those snap changes? They should help with https://github.com/freeorion/freeorion/pull/3339#issuecomment-818591171 

Launch on CI raises some issues but I suppose it could be ignored because it shows `freeorion` finds its libraries.

**Comment by agrrr3** [comment]
Tried cfa45431c and i could play a game (research UI was partly broken, but probably that is not from your changes)

 latest/edge:      2021-04-14.cfa45431c     2021-04-14 (197)

**Comment by o01eg** [comment]
@agrrr3 Nice, I'll merge it then and rebase #3339 over it to see if `godot3-runner` will be placed in the same directory as `freeoriond`.

**Comment by geoffthemedio** [comment]
> research UI was partly broken, but probably that is not from your changes

not related to this pull request at least

@o01eg it appears to be caused by #3379

Issue is that the tech screen category buttons are missing. Possibly they are now created before the categories are parsed somehow...?

**Comment by o01eg** [comment]
> Issue is that the tech screen category buttons are missing. Possibly they are now created before the categories are parsed somehow...?

I'll look into it. Is it some Heizenbug which appears sometime?

**Comment by geoffthemedio** [comment]
it was consistently present after #3379 but partly fixed by 082f01a93e9c by reworking the UI code

**Comment by o01eg** [comment]
Yes, I see all tech category buttons deactivated when open tech window but all techs visible. When I click on button it activates and techs remain visible. When I make second click button deactivates and techs hidden too.

`TechManager::CategoryNames` protected with `TechManager::CheckPendingTechs` so it shouldn't return empty categories never except parse errors.

**Comment by o01eg** [comment]
@geoffthemedio  Do I correctly understand sometimes they are empty?

**Comment by geoffthemedio** [comment]
No, not "sometimes". Test the version before 082f01a since that mostly papers over the issue.

That said, maybe it's fine with additional fixes after that commit...

**Comment by o01eg** [comment]
I reverted https://github.com/freeorion/freeorion/commit/082f01a93e9cd3d643c755f6916bdf13570aba01 and throw exceptions if categories or categories buttons are empty.

It raises pretty often even on main menu.

**Comment by o01eg** [comment]
```
Thread 1 "freeorion" received signal SIGABRT, Aborted.
0x00007ffff6096d51 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6096d51 in raise () from /lib64/libc.so.6
#1  0x00007ffff6080536 in abort () from /lib64/libc.so.6
#2  0x00007ffff640288e in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6
#3  0x00007ffff640e7c6 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6
#4  0x00007ffff640e831 in std::terminate() () from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6
#5  0x00007ffff640eac3 in __cxa_throw () from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6
#6  0x00007ffff7841173 in TechManager::CategoryNames[abi:cxx11]() const (this=<optimized out>) at /mnt/another/srcs/GIT/freeorion/universe/Tech.cpp:376
#7  0x0000555555b864df in TechTreeWnd::LayoutPanel::CompleteConstruction (this=0x5555569568b0) at /mnt/another/srcs/GIT/freeorion/UI/TechTreeWnd.cpp:1121
#8  0x0000555555b8b9e5 in GG::Wnd::Create<TechTreeWnd::LayoutPanel, GG::X, GG::Y> () at /mnt/another/srcs/GIT/freeorion/GG/GG/Wnd.h:347
#9  TechTreeWnd::CompleteConstruction (this=0x5555573975c0) at /mnt/another/srcs/GIT/freeorion/UI/TechTreeWnd.cpp:2015
#10 0x0000555555ae7007 in GG::Wnd::Create<TechTreeWnd, GG::X&, GG::Y&, bool&> () at /mnt/another/srcs/GIT/freeorion/GG/GG/Wnd.h:347
#11 ResearchWnd::ResearchWnd (this=0x55555739d040, w=..., h=..., initially_hidden=<optimized out>) at /mnt/another/srcs/GIT/freeorion/UI/ResearchWnd.cpp:417
#12 0x00005555559e04cb in GG::Wnd::Create<ResearchWnd, GG::X, GG::Y> () at /mnt/another/srcs/GIT/freeorion/GG/GG/Wnd.h:326
#13 MapWnd::CompleteConstruction (this=<optimized out>) at /mnt/another/srcs/GIT/freeorion/UI/MapWnd.cpp:1488
#14 0x00005555557fe562 in GG::Wnd::Create<MapWnd> () at /mnt/another/srcs/GIT/freeorion/GG/GG/Wnd.h:347
#15 0x00005555557e5218 in ClientUI::GetMapWnd (this=this@entry=0x555556231d80) at /mnt/another/srcs/GIT/freeorion/UI/ClientUI.cpp:664
#16 0x00005555556e421b in GGHumanClientApp::HandleWindowResize (this=0x7fffffffc770, w=..., h=...) at /mnt/another/srcs/GIT/freeorion/client/human/GGHumanClientApp.cpp:1094
```

**Comment by geoffthemedio** [comment]
From my testing, the issue was that the TechWnd is constructed before the techs are parsed and available, so it was creating no tech category buttons, which caused problems later since it never refreshed allowing for new categories. The changes in 082f01a add later refreshing, allowing for changing (or delayed parse of) categories, but perhaps there should be some additional fix to the parsing?

**Comment by o01eg** [comment]
Something wrong with `TechManager::CheckPendingTechs` because I think it shouldn't return before techs parsed. Maybe some checks missing here.

**Comment by o01eg** [comment]
In a truly parallel approach we shouldn't block UI thread while awaiting things to be parsed but instead make parser notify others about parse finished and just draw progress bar for user.

**Comment by o01eg** [comment]
```
(gdb) p GetTechManager()
$2 = (TechManager &) @0x7ffff7fb4800: {
  m_pending_types = {<boost::optional_detail::optional_base<Pending::Pending<std::tuple<boost::multi_index::multi_index_container<std::unique_ptr<Tech, std::default_delete<Tech> >, boost::multi_index::indexed_by<boost::multi_index::ordered_non_unique<boost::multi_index::tag<TechManager::CategoryIndex, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Tech, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, &Tech::Category>, mpl_::na>, boost::multi_index::ordered_unique<boost::multi_index::tag<TechManager::NameIndex, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Tech, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, &Tech::Name>, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<std::unique_ptr<Tech, std::default_delete<Tech> > > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<TechCategory, std::default_delete<TechCategory> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<TechCategory, std::default_delete<TechCategory> > > > >, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, 
      m_storage = {dummy_ = {data = '\000' <repeats 95 times>, aligner_ = {<No data fields>}}}}, <No data fields>},
```

It looks like UI thread accesses tech manager while `m_pending_types` not yet initialized with `TechManager::SetTechs` and skips awaiting in `TechManager::CheckPendingTechs`.

What is the point of using `std::async(std::launch::async, ...)` to call parsers if UI blocks for them?

Also we have branch if "scripting/techs" directory missing so `TechManager::SetTechs` may be never called.

**Comment by o01eg** [comment]
Simple solution is to move `barrier` resolution to techs parser so UI thread will be blocked until techs parsed.

Edit: Opened PR #3415

**Comment by geoffthemedio** [comment]
> What is the point of using `std::async(std::launch::async, ...)` to call parsers if UI blocks for them?

Probably all the parsers were set up the same way without detailed checking if any were needed earlier.

**Pull request merged**
