### PR TITLE
Clean up en.txt.

### PR DESCRIPTION
**Pull request by wheals**
For some reason GitHub doesn't want to show the diff in the web viewer, so you have to download it to check it out. You can also check out [the raw diff](https://github.com/wheals/freeorion/commit/1164333511850a0e68926712da6eb077f829139c.diff).

@Vezzra again, I think it would be nice if this could make it into 0.4.5. Pretty sure that there won't be any unintentional consequences... :wink:

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
I applied the PR commit as a cherry pick (without re-committing it) and then used my IDE integrated diff viewer, which will clearly show just small intra-line changes, such as you have a great deal of here.   Some changes are good. The good changes are however tremendously bogged down with pointless stylistic changes, not all of which do I prefer over the original.  In some cases in fact, I preferred the original, but not enough to want to actually get into editing or debating such things.

I finally got fed up with spending my time reviewing large numbers of pointless stylistic changes though, about a third of the way through the changes, at line 3903, where `Supply lines can also be used...` [to refill ship fuel] was changed to `Supply lines are also used...` 

If anyone else wants to pick up the review from that point on, I am willing to vouch that the preceding portion is reasonable enough to not be worth quibbling about, and has at least some level of net positive value.

**Comment by wheals** [comment]
I guess I did go overboard with those. I admit I'm probably overfond of commas ^^

**Comment by Vezzra** [comment]
I leave the decision what to do with this PR to the native speakers, pls also give your opinion on if this should go into 0.4.5.

**Comment by Vezzra** [comment]
Um, how do you guys want to proceed with that PR?

**Comment by Ouaz** [comment]
Yeah, if this PR is granted, don't commit it too late (not saturday evening for example, a few hours before the possible deadline for RC1). Except the small intra-line changes (commas, uppercase letter), there's a bunch of good changes that will require some time to be brought to the other stringtables (fr in my case ^^). Thanks!

**Comment by MatGB** [comment]
I had planned on digging out the email notifs in the hope it would have a link to a Diff, which it does, so I'm looking over it now, given the size it'll take me a bit to review but assuming no problems I'll commit it at some point next 24 hrs. @Ouaz if it's mostly stylistic changes don't worry massively about keeping fr.txt up to date from it, if you've read it you'll know of substantive changes better'n me though.

**Comment by Ouaz** [comment]
My bad, you're right, MatGB. Comparing the files again, there's not so much changes that require a big translation work, my one-week memories were wrong. :p

**Comment by MatGB** [comment]
I have some minor issues, a couple personal stylistic preferences (I loathe the Oxford Comma, using it is a last resort that should only be necessary if a sentence can't be reworded to be clearer, adding it in when it's not needed for clarity goes against style guidelines, including the Oxford style guidelines).

But I'm not sold on the need for removing the Reason For Staying part of all the can't colonise species that had one, removing the subheads would be a stylistic change that I wouldn't necessarily object to but I'm not keen on happening without actual discussion (they were introduced by the previous species-lead and while we haven't got one formally at the moment I'm not keen on removing deliberately included work of a predecessor without at least some discussion).

I'm continuing to read through but I'm not keen on all of this.

**Comment by wheals** [comment]
It seemed to me that the Oxford comma was the standard throughout the file already, so I thought I was just standardizing.

The "Reason for Staying" sections felt rather forced to me; I think it's better to introduce the idea of why a non-spacefaring race prefers to stay at home inside the more descriptive sections of the species information rather than bludgeoning the reader with it, so to speak. It's nice to have the information, but the heading reads awkwardly. One alternative would be renaming it something less informal than "Staying," maybe?

**Comment by wheals** [comment]
I'm willing to post a shorter version of this, with just things I'd really want to see change, if that's necessary to get it into 0.4.5.

**Comment by Ouaz** [comment]
Be hurry then, the first RC is planned for next monday (Aug 24th). ;)

**Comment by Vezzra** [comment]
@wheals, if you want to put up the shorter version you mentioned, pls do so ASAP. I plan to release RC1 on Monday, and the other native speakers need some time so they can do at least  some quick review. If they approve of these changes, I'm certainly willing to cherry pick them into the release branch.

This should be finished until Sunday at the latest.

**Comment by wheals** [comment]
OK. This removes the changes to species descriptions and most of the really minor questionable changes.

**Comment by MatGB** [comment]
Had completely forgotten about this, sorry, busy few weeks, am reviewing new version now.

(for what it's worth, I'm not a particularly good proofreader do don't notice certain things one way or the other, but I personally loath the Oxford Comma, would remove it in other places if I'd noticed it, but specifically noticed the additions because the first two were both added to text I personally originally wrote)

**Comment by MatGB** [comment]
Yup, that's fine, good job and you spotted stuff I'd overlooked several times.  

I think we need to work on a styleguide for the English version, when I started work on it there wasn't even an agreement on which version of English we should use let alone what sub-styles. One for the Wiki, probably.

**Comment by wheals** [comment]
@Vezzra If you could cherry-pick now/soon, it would be much appreciated :)

**Comment by Vezzra** [comment]
Done, 7848bfed403d7c3e63e494fbcb1b97937022af14.

**Pull request merged**
