### PR TITLE
Appdata metainfo

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR is the successor to PR #1657 

* Updated metainfo file to follow [Appdata metainfo specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html), following the [Guide for GUI application upstream maintainers](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps).
* Provides metainfo for the FreeOrion client, other components may follow at a later date.

The problem with the screenshots still exists. I don't want to rely on uploaded wiki files as permanent URLs.  Any suggestions here? @geoffthemedio noted that those could be hosted on the server directly?

The corresponding `adrianbroher/appdata-xml` branch is a stale version of this branch.  It can now be deleted.

### CODE REVIEW

**Comment by adrianbroher** [comment]
We may be able to piggyback on the debian screenshot service instead of hosting our own: https://screenshots.debian.net/package/freeorion

**Comment by geoffthemedio** [comment]
> The corresponding `adrianbroher/appdata-xml` branch is a stale version of this branch. It can now be deleted.

done

**Comment by geoffthemedio** [comment]
I put a few screenshots (1600x1200, .png and .jpg) here: https://www.freeorion.org/screenshots/

**Comment by adrianbroher** [comment]
Screenshots should be 16:9 ratio and png, see [the Guideline](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) within the **⁠&lt;screenshots/&gt;** section for more details and best practice.

**Comment by adrianbroher** [comment]
Also a version and time agnostic name would probably better?  Those image will be displayed during installation and search and we probably don't want outdated images to be shown and pinned by the url.

Otoh: The metainfo data should probably be updated anyway with every release.

**Comment by geoffthemedio** [comment]
Replaced with some 1600x900 .png files.

**Comment by adrianbroher** [comment]
Updated the screenshots, removed the stale german translation and fixed a typo in the markup.

Ready to merge.

**Pull request merged**
