### PR TITLE
Minor fixes for Pedia regarding Imperial Stockpile

### PR DESCRIPTION
**Pull request by alleryn**
Fixes a typo that stopped the Imperial PP Use Limit article from displaying and alters the Industry article to account for new Stockpile mechanic.

### CODE REVIEW

**Comment by alleryn** [comment]
fr.txt could use an update to the METER_INDUSTRY_VALUE_DESC if anyone is so inclined.

**Comment by geoffthemedio** [comment]
For fr.txt ping @Ouaz

**Comment by Ouaz** [comment]
> fr.txt could use an update to the METER_INDUSTRY_VALUE_DESC if anyone is so inclined.

Hello alleryn, don't bother yourself to update values in the fr.txt file, I check the new en.txt commits each week, and update the FR file before the weekly build release. ;)

When it's about key modifications like in #1882, it's ok to update the FR file in the same time though.

Here's the FR translation for line 5093:

`Any un-allocated Industry is converted via the [[metertype METER_IMPERIAL_PP_TRANSFER_EFFICIENCY]] and added to the Imperial Stockpile.`

`L'Industrie qui n'est affectée à aucun projet durant un tour est convertie selon le [[metertype METER_IMPERIAL_PP_TRANSFER_EFFICIENCY]] et ajoutée au Stock Impérial.`

Good work, btw!

**Comment by alleryn** [comment]
> Hello alleryn, don't bother yourself to update values in the fr.txt file, I check the new en.txt commits each week, and update the FR file before the weekly build release. ;)

Understood, and thank you for the translation.

**Comment by alleryn** [comment]
rebased to add update to fr.txt

**Pull request merged**
