### PR TITLE
Fix the extra space in ListBoxes after the end of the content.

### PR DESCRIPTION
**Pull request by wheals**
The comment said that it wasn't a big deal, but it really looks bad IMO. I
don't see what is to be gained by allowing the last entry to be on top.

### CODE REVIEW

**Comment by wheals** [comment]
To clarify, before:
j23xt2z
And after:
lj8hyib

**Comment by geoffthemedio** [comment]
Has a problem...

scrolls

**Comment by wheals** [comment]
I think that should fix it. I wasn't sure if there was a problem with horizontal scrolling so I left it alone.

**Comment by wheals** [comment]
I used `+= -padding` to make it clear that the intent is to increase total_y_extent. How about `+= std::abs(Value(padding))`?

**Comment by geoffthemedio** [comment]
That would be better. Even better would be to rename the variable to make it clear that it's (I think?) the extra space needed to ensure the bottom row is fully shown.

**Comment by Dilvish-fo** [comment]
This still doesn't entirely solve the problem,  I'll add a screenshot in just a minute.  *\* edited after I realized a misunderstanding I had.

**Comment by Dilvish-fo** [comment]
here's the screenshot showing insufficient scrolling: scrolling

**Comment by Dilvish-fo** [comment]
It could be that this case I found may be a preexisting problem related to how/when it determines it needs the bars.  So perhaps no need to hold this up for it.  I do agree with Geoff about renaming that variable, perhaps even slightly changing the handling of it.  Rather than starting out "padding" at total client size and decrementing until you get below 1, perhaps  start out "extent_needed" at zero and increment until you get at or above the client size, and then add extent_needed-client size

**Comment by Dilvish-fo** [comment]
One more thing I feel compelled to mention: your intro to this PR implies that the code comment had indicated this was a minor bug, which you are now fixing, but that is not at all the case.  The comment says the code might look odd, but that the behavior is desired.

> The comment said that it wasn't a big deal, 

versus

```
    // This probably looks a little odd.  We only want to show scrolls if they
    // are needed, that is if the data shown exceed the bounds of the client
    // area.  However, if we are going to show scrolls, we want to allow them
    // to range such that the first row/column shown can be any of the N
    // rows/columns.  Dead space after the last row/column is fine.
```

It's fine to propose changing the intended behavior of things, but it should be acknowledged as such, and not characterized as fixing a known bug just because you don't like the behavior.

**Comment by wheals** [comment]
I ended up rewriting the code for adding padding entirely; the old one wasn't doing exactly what I wanted it to do. I also went ahead and squashed and rebased all the commits and edited the message to make what was going on more.

**Comment by geoffthemedio** [comment]
Another quirk, observed with the objects list. Have enough items in a list to have a scroll bar, and scroll at least one tick down. Resize the window so a scrollbar isn't needed. The box enclosing the scrollbar remains, but the tab disappears.

(Hopefully this isn't related to my recent adjustments to Scroll rendering...)

**Comment by Dilvish-fo** [comment]
I think part of the calc for determining when scrollbars is needed is a little off, which could put the slot up there when barely not needed, but then the code for deciding how big to make the bar decides not to put it in the slot at all.  I was going to wait until this was finished to make that change, but I'll try to do it and put it up as a PR, so you guys can decide if you want to put it in before or after this one.  I think it might very well clear up this issue you just mentioned.

**Comment by geoffthemedio** [comment]
Did not intend to do that merge... something weird happened with local checkout and switching, apparently. But I suppose it's not a major problem, and Dilvish's new change can go in later...

**Comment by Dilvish-fo** [comment]
wheals, an issue has come up from this: http://www.freeorion.org/forum/viewtopic.php?p=79695#p79695

**Comment by geoffthemedio** [comment]
Not sure if that is really an issue with these changes, or just the kludgy way the tech list is implemented...

**Comment by Vezzra** [comment]
> Not sure if that is really an issue with these changes, or just the kludgy way the tech list is implemented...

My guess would be the latter...

**Comment by Dilvish-fo** [comment]
> Not sure if that is really an issue with these changes, or just the kludgy way the tech list is implemented...

The cause is very clearly this PR, though that doesn't mean that our solution can't be to change the tech list.  This PR mischaracterized itself as a bug-fix but  in fact was all about changing the explicitly intended behaviour of GG::ListBox, which it turned out the tech list relied upon to have reasonable interaction.  

It could still be that the preferred fix at this point is to make the tech list resizable; hopefully wheals can tackle that cleanup.

**Comment by wheals** [comment]
How about making the tech tree list shorter? I have a commit that does that locally now -- the list shrinks just enough that the panel can be put on the bottom without blocking anything. It looks a bit funny if you drag the panel up, but as an interim solution it seems to work.

Sorry about making this sound more like a bugfix than it really was -- when I first thought about the behaviour and wanted to fix it, I couldn't imagine why it would be useful (though now I've seen that it had its advantages).

**Comment by MatGB** [comment]
There is another issue, and I've only just twigged that this change is causing it.

On the Production Window, queued items can't now be scrolled up, meaning that the drop down allowing you to make a batch of 1/2/3/4/5/10/20/50/99 items of the same type at the same time, or to have the same item repeat a lot, can't now be used to have more than 5 of an item or to have more than 5 repeats.

The only way to queue more than this for the last item is to either a) right click the item, move it to the top, scroll up, select the amount you need, right click and move it down again, b) queue extra unwanted items, change the numbers you want then delete the unwanted items or c) drag the item up the queue a bit, change the number you want, drag it down again. Given that moving things on the production queue can still cause occasional crashes, none of these options is optimal.

You need to have at least 2 items worth of space in the blank area, preferably three, just space for one item in the gap isn't enough for the numbers dropdown.

A different fix would be for the numbers dropdown to detect it's off the screen and move up, but I think that's a different 'unexpected behaviour' UI issue anyway.

**Comment by wheals** [comment]
Ouch. I think that's a problem even without this, in case you have just enough queue entries to almost reach the bottom, but not enough to make there be any scrollbar (see [example](http://i.imgur.com/YunidMd.jpg)).

Nevertheless, I worry that there might be more issues. Maybe my commits should just be reverted in the release branch in case anything else comes up, and we can try to fix the tech list and the dropdowns in trunk?

**Comment by MatGB** [comment]
It's always been a problem if you had a queue that was just there, which was fairly easily solved by resizing the window temporarily, I complained about that before but it was an edge case as you had to have exactly that number of things, whereas with this it's whenever you have more, which is far more common.

To be 100% honest, I never saw the long space as a problem but I can see it sort of can be in some cases, definitely think remove from Release and try to solve overall problems, unless a fix is there for that can be implemented easily.

**Comment by Vezzra** [comment]
Hm, reverting this in the release branch and taking care of all the issues involved in master looks like the simplest solution. Anyone any objections?

**Comment by Dilvish-fo** [comment]
It does sound like reverting would be the most prudent choice at least for Release branch.

I'd be a bit inclined to say it should be reverted in the master branch as well, and this PR could be reopened or a new one made.  It was purely someone's aesthetic preference that prompted the PR to begin with, and since it is having non-trivial complications I see no reason for it to be in the master branch unless/until those complications are resolved.

**Comment by Vezzra** [comment]
Ok, I've reverted the commit on the release branch, 1b97eb8c56f017811774161f5419226c116248c0.

As for reverting it on master and reopening the PR, that sounds reasonable, no objections from my side. I leave the final decision to you, though.

**Comment by Dilvish-fo** [comment]
We also just had a player complaint about the ProductionQueue issue, on the boards, so I've reverted it from master as well.   

It seems to me that a reasonable solution could be to allow some maximum number of blank lines, like the lesser of 4 lines or 1/4 the height of the listbox.  Something like that should probably be able to accommodate these situations where extra scrolling was functional.  Or, perhaps back to my idea of an extra constructor parameter about how much extra space to allow.

**Comment by geoffthemedio** [comment]
I think the amount of extra space being a controllable option, at constructor or by a mutator, would make sense. Sometimes extra space is useful, such as the production queue, but other times it's unnecessary, such as in drop lists.

**Pull request merged**
