### PR TITLE
remove macos-12 actions

### PR DESCRIPTION
**Pull request by geoffthemedio**
Due to #5019 update the MacOS runners used in actions

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg Building with MacOS14 fails with:
````
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**Comment by o01eg** [comment]
I'm not sure, may be architecture should be installed separately or MacOS 14 enforces to use ARM.

**Comment by o01eg** [comment]
@geoffthemedio Looks like godot-cpp builds with arm64, while freeorion with amd64, maybe just disable godot-cpp for a while.

**Comment by geoffthemedio** [comment]
> @geoffthemedio Looks like godot-cpp builds with arm64, while freeorion with amd64, maybe just disable godot-cpp for a while.

can you push a commit to do that?

**Comment by o01eg** [comment]
Nice, there was better solution to fix CMake configuration.

**Pull request merged**
