### PR TITLE
Increase pop when Population Policy is applied

### PR DESCRIPTION
**Pull request by rrobgill**
* Increase rate of change to population by 50%,
  if population on planet is lower than target population.

* No change to rate if population is decreasing

Signed-off-by: Rob Gill <rrobgill@protonmail.com>

### CODE REVIEW

**Comment by Oberlus** [comment]
Population growth is controlled in https://github.com/freeorion/freeorion/blob/ed213fba84d31196934ccf43c1a54d2246e73668/default/scripting/species/common/population.macros#L29
It already considers the case on negative growth and does not apply the policy effect in that case.
This PR should not be merged.

**Comment by geoffthemedio** [comment]
> This PR should not be merged.

Unless @rrobgill has some other insight I've missed, I agree...

**Comment by rrobgill** [comment]
can't believe i missed that. Sorry.

**Comment by geoffthemedio** [comment]
Scripts can be in unexpected places for various reasons.

**Pull request closed without merging**
