### PR TITLE
[AI] Cleanup.

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Reduce line length.
Rename local variables.
Fix possible issue in call of `get_fleets_for_mission`   Change `tried_fleets=verbose` to `verbose=verbose`.  I prefer pass arguments to function exactly as they were defined (positional as positional keywords as keywords, it helps to avoid such issues)

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@Dilvish-fo ?

**Comment by Dilvish-fo** [comment]
Looks ok from visual inspection, but as I've mentioned in other matters before CJ, in your comments here please characterize how much testing you've done on it and how confident you are it's ready to merge.  I'm pretty busy and this seems like it would be ok to rely on my visual inspection plus your actual testing, but I feel I need to know something about your actual testing in order to do that.

**Comment by Cjkjvfnby** [comment]
Run couple of times.  
Check that AI get more systems over time.
Check that error in logs same as in master.

**Comment by Cjkjvfnby** [comment]
@Dilvish-fo ?

**Comment by geoffthemedio** [comment]
Given lack of further comments, will merge...

**Pull request merged**
