### PR TITLE
Changes to Growth techs:

### PR DESCRIPTION
**Pull request by Deepsloth**
- Planetary Ecology will now unlock Adequate planets. Reduced the bonus of Xenological Genetics to Adequate planets in return.
- Hostile will now start with population  of -5 (was -4) evened out by Xenological Genetics.

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
Hmm.   Aren't these changes to Hostile beyond what was agreed?  You could accomplish  the agreed change with far fewer edits by leaving the the initial Hostile at -4, and then then in GRO_XENO_GENETICS instead of moving "Poor" and changing the values, simply move "Adequate" and don't change the values at all.

**Comment by Deepsloth** [comment]
As i've posted (here: http://www.freeorion.org/forum/viewtopic.php?f=15&t=9632&start=24), i did this simply for the tech description of GRO_XENO_GENETICS. Lumping Adequate and Hostile together and then list Poor could confuse players, who aren't so familiar with Good, Adeuate, Poor, Hostile, uninhabitable yet.

**Comment by MatGB** [comment]
I hadn't realised what you meant in that, yeah, the problem with doing this is it makes phototrophes weaker as they need more techs in the early game in order to grab bright/very bright worlds, and I really don't want to fiddle too much with any other balance issues for what should be a relatively minor tweak at this stage.

What I had in mind was to give Plan_Ecol an effectsgroup that gives a simple +1 population (just that, +1, not modified by size) to good and average planets that only activates if you haven't got a later tech, I suggested Symbiotic Biology but I'm happy for it to be Xeno Genetics.  Changing too many other stats, especially changing a base stat that's applied in multiple places, isn't necessary.

**Comment by Dilvish-fo** [comment]
> Lumping Adequate and Hostile together and then list Poor could confuse players, who aren't so familiar with Good, Adeuate, Poor, Hostile, uninhabitable yet.

You don't have to lump them together in the description: 

```
This tech provides a modest benefit for Adequate planets, its strongest benefit for Poor planets, and again a modest benefit for Hostile planets.
```

I think it makes just as much sense as the other groupings.

> What I had in mind was to give Plan_Ecol an effectsgroup that gives a simple +1 population (just that, +1, not modified by size) to good and average planets that only activates if you haven't got a later tech,

You know, that had been my understanding from the discussions as well, but then when I saw the PR I realized I had at least been misreading Sloths charts and so I dind't make a big deal of it.   But I agree, I would prefer it to be a mere +1, not +1*SizeAsDouble.

**Pull request closed without merging**
