### PR TITLE
Convert buildings/ABANDON_OUTPOST.focs

### PR DESCRIPTION
**Pull request by o01eg**
Changes in dump: 

```diff
@@ -33,7 +33,7 @@
             scope =
                 Source
             activation =
-                Turn low = 3 + Source.CreationTurn high = Source.System.LastTurnBattleHere
+                Turn low = Source.CreationTurn + 3 high = Source.System.LastTurnBattleHere
             stackinggroup = "ABANDON_OUTPOST_STACK"
             priority = 100
             effects =
@@ -51,11 +51,11 @@
                     Planet
                 ]
             activation =
-                Turn low = max(1 + Source.System.LastTurnBattleHere, 3 + Source.CreationTurn)
+                Turn low = max(Source.System.LastTurnBattleHere + 1, Source.CreationTurn + 3)
             stackinggroup = "ABANDON_OUTPOST_STACK"
             priority = 50
             effects = [
-                SetOwner empire = -(1)
+                SetOwner empire = -1
                 GenerateSitRepMessage
                     message = "SITREP_OUTPOST_ABANDONED" icon = icons/tech/environmental_encapsulation.png
                     parameters = tag = planet data = (Target.ID) // StringCast{i}
@@ -73,15 +73,15 @@
                         Building name = "BLD_ABANDON_OUTPOST"
                 ]
             activation =
-                Turn low = max(1 + Source.System.LastTurnBattleHere, 3 + Source.CreationTurn)
+                Turn low = max(Source.System.LastTurnBattleHere + 1, Source.CreationTurn + 3)
             priority = 50
             effects =
-                SetOwner empire = -(1)
+                SetOwner empire = -1
         EffectsGroup // from BLD_ABANDON_OUTPOST
             scope =
                 Source
             activation =
-                Turn low = max(1 + Source.System.LastTurnBattleHere, 3 + Source.CreationTurn)
+                Turn low = max(Source.System.LastTurnBattleHere + 1, Source.CreationTurn + 3)
             priority = 100
             effects =
                 Destroy
```

`int + FOCS stuff` doesn't work correctly so I had to revert it.

@Cjkjvfnby Could you also populate typed modules?

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
Pushed update changes.  There is some suppression, I'll work on them later.  If you encounter similar cases, feel free to use ignore statements. 

To unblock yourself from typing errors, feel free to put suppress to the whole file.
https://mypy.readthedocs.io/en/stable/common_issues.html#ignoring-a-whole-file

**Comment by o01eg** [comment]
It's quite strange it fails when trying to import typing while for techs and species there no such issues.

**Comment by o01eg** [comment]
@Cjkjvfnby You can use recent weekly test build to test it.

**Comment by Cjkjvfnby** [comment]
> It's quite strange it fails when trying to import typing while for techs and species there no such issues.


[Typing](https://docs.python.org/3/library/typing.html) is a module of the standard library but it's not included in the freeorion parser (adding it should be nice). 

That means that we could import this module only in pyi files.   Pyi files are not executed in runtime and are used only for linter.

It was my mistake to import it.  This focs._typing could serve an excellent job for annotating macros functions, but now it's complicated: https://github.com/freeorion/freeorion/blob/master/default/scripting/species/common/industry.py#L24

**Comment by Cjkjvfnby** [comment]
Does it mean that I can convert other buildings?  Do you have something in progress now?

**Comment by o01eg** [comment]
Currently I don't have anything in progress so you can convert other buildings.

**Pull request merged**
