### PR TITLE
[AI] Print utils

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Tools to pretty print tables.
We already have couple of realization in code, I replace only small part of them in this PR.  

Before - after example:

```
Empire priority_id 2 has current Capital Glorious Margrave I:
Buildings present at empire Capital (priority_id, Name, Type, Tags, Specials, Owned by Empire):
     471 |       Basic Shipyard | type:       SHIPYARD_BASE | tags:             ORBITAL | specials:                      | owner:2 
     472 |      Orbital Drydock | type:     ORBITAL_DRYDOCK | tags:             ORBITAL | specials:                      | owner:2 
     473 |    Cultural Archives | type:    CULTURE_ARCHIVES | tags:          ANTIQUATED | specials:                      | owner:2 
     474 |      Imperial Palace | type:     IMPERIAL_PALACE | tags:                     | specials:                      | owner:2 
```

```
Empire priority_id 2 has current Capital Supreme Margrave I:
Buildings present at empire Capital
=================================================================================
| Id* | Name              | Type             | Tags       | Specials | Owner Id |
=================================================================================
| 471 |    Basic Shipyard |    SHIPYARD_BASE |    ORBITAL |          |        2 |
| 472 |   Orbital Drydock |  ORBITAL_DRYDOCK |    ORBITAL |          |        2 |
| 473 | Cultural Archives | CULTURE_ARCHIVES | ANTIQUATED |          |        2 |
| 474 |   Imperial Palace |  IMPERIAL_PALACE |            |          |        2 |
---------------------------------------------------------------------------------
*Id  Building id
```

### CODE REVIEW

**Comment by LGM-Doyle** [comment]
Definitely an improvement.

When I refactored ResearchAI.py I had problems with the UTF-8 characters in some of the colony names.  The alphas and betas in the names are one codepoint but more than one 8 bit character.  So I couldn't get uniform column widths.  I eventually, gave up on fixing the problems, since it was only debug messages.  Did you have the same problems?

**Comment by Cjkjvfnby** [comment]
Table handles unicode chars correctly.

**Comment by Vezzra** [comment]
Looks very good, like @LGM-Doyle said, definitely an improvement. I'd like to see that module as a shared one that can also be used by the universe generation and turn event scripts (once we manage to adjust our Python interface accordingly...).

**Comment by Cjkjvfnby** [comment]
@Vezzra how about merge it?

**Comment by Vezzra** [comment]
Yup, done.

**Pull request merged**
