### PR TITLE
Balance Hyperspatial Dam

### PR DESCRIPTION
**Pull request by MatGB**
~ Population malus is set to equal planet size
~ Bonus is set to equal Black Hole Generator
~ Stacking Group added so does nothing if empire has BHG
~ Negative effects don't trigger if BHG in supply

### CODE REVIEW

**Comment by MatGB** [comment]
OK, fairly simple, works as intended, addresses #593 as a quick fix.

@freeorion/ai-team to my knowledge the AI doesn't use the Dam (as, frankly, it was terrible), this is basically ready to go in but I created a PR so you can decide if you want to make any amendments to the AI either now or in future, if you're happy that it doesn't hurt them please do merge in ASAP.

At a basic level, virtually all players would benefit now from using the dam _if_ they haven't got a black hole system, a black hole generator is better—in the next Cycle we hope to rework both and a few other things to make them more interesting as being discussed in the [Poison advance](http://www.freeorion.org/forum/viewtopic.php?f=2&t=10176) thread.

**Comment by Morlic-fo** [comment]
Fine with me. AI doesn't/won't build it but that seems not critical for release.

**Comment by Vezzra** [comment]
#593 shall remain open however, right? Because the real fix is still coming...

**Comment by MatGB** [comment]
Correct, but it's a lower priority, this just makes it a usable thing within current scripting style.

**Pull request merged**
