### PR TITLE
Reskin Acirema to Energy Frigates/Add Energy Compressor

### PR DESCRIPTION
**Pull request by MichaelCourtney**
https://www.freeorion.org/forum/viewtopic.php?f=15&t=12499

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
For post-release

**Comment by MichaelCourtney** [comment]
Will need to update to factor in:

https://github.com/freeorion/freeorion/pull/4421

**Comment by o01eg** [comment]
Yes, I should implement `CreateBuilding` effect for this PR.

**Comment by MichaelCourtney** [comment]
> Yes, I should implement `CreateBuilding` effect for this PR.

Thanks I got it working

**Pull request merged**
