### PR TITLE
Create Energy Frigate and amend tech tree

### PR DESCRIPTION
**Pull request by MatGB**
Needs an AI update, but is basically ready for use
@Dilvish-fo , @Morlic-fo or @Cjkjvfnby , the AI uses the energy line techs/hulls, note that this reduces the prerequisite for Compressed Energy from LRN_GRAVITONICS to LRN_FORCE_FIELD and makes LRN_GRAVITONICS a prereq for Quantum and Fractal hulls instead, this makes the line slightly easier to research but doesn't really need that many changes to the priorities, it could probably go in as is without that many changes but if they can learn to make use of it earlier at some point moving forward that'd be cool.

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
I agree that you wouldn't necessarily need to hold this up for corresponding AI changes (doesn't seem it would directly or relatively cripple the AI).

Any suggestions on whereabouts to move the tech forward to now?

Also, right now the AI only builds compressed energy shipyards at blue stars and black holes, if it has a top pilot species there (and then it always builds them).  Any suggestions on broader criteria for building the shipyards now?

**Comment by MatGB** [comment]
One at a white star if you've got a high vision species (Laenfa especially-compressed energy hulls make fast cheap scouts) and/or a good pilots species there, the energy frigate isn't brilliant enough on its own to justify it but it is cool, and fits a solid gap in the energy line so it's better for a player concentrating on energy rather than the AI which does a bit of everything, but if they can use it they're a mobile threat that look cool.

I'm still playing around with best choice for where the tech goes in my strategy, if you've got a white star/high vision species then earlier than currently otherwise about the same as now wouldn't hurt, I tried to make it cool not necessary but phototrophes should benefit from it.

**Comment by Dilvish-fo** [comment]
OK, sounds pretty reasonable, though currently we don't explicitly track good scouting species & this won't make my priority list for a fair while.  I've bookmarked this to come back to sometime if CJ or Morlic or perhaps Luiges90 doesn't tackle it sometime.

**Comment by MatGB** [comment]
So OK to merge this in? Observations of gameplay indicates they aren't suffering from it.

**Comment by Vezzra** [comment]
> Observations of gameplay indicates they aren't suffering from it.

If that's the case, sure, go ahead.

**Pull request merged**
