### PR TITLE
Increase refuel rate of ramscoop

### PR DESCRIPTION
**Pull request by MichaelCourtney**
https://freeorion.org/forum/viewtopic.php?t=12532

There are probably earlier threads saying the same

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
I got an error when running the game with latest binaries:

@MichaelCourtney , @geoffthemedio 


```
j:/projects/freeorion/default\scripting/ship_parts\Fuel\FU_RAMSCOOP.focs.txt:39:12: Parse error.  Expected (?-i:effects) here:
        OwnedBy empire = Source.Owner
    ]
    effectsgroups =
        EffectsGroup
            scope = Source
            Turn low = LocalCandidate.ArrivedOnTurn + 1
            ^
            activation = Stationary
            stackinggroup = "RAMSCOOP_STACK"
            // Update ship_hulls.macros if this number changes
            effects = SetFuel value = Value + (NamedRealLookup name = "FU_RAMSCOOP_REFUEL")
    icon = "icons/ship_parts/antimatter_tank.png"
```

**Comment by geoffthemedio** [comment]
Yep that's broken and I didn't notice or run a local test game.

@o01eg can or shouldn't a test build and run have tripped on that?

@MichaelCourtney did you test these changes before making a pull request?

**Comment by MichaelCourtney** [comment]
> Yep that's broken and I didn't notice or run a local test game.
> 
> @o01eg can or shouldn't a test build and run have tripped on that?
> 
> @MichaelCourtney did you test these changes before making a pull request?

Yes I tested, but I changed something right at the end and must have failed to retest.

**Comment by o01eg** [comment]
> @o01eg can or shouldn't a test build and run have tripped on that?

Parsers don't fail entire game on parser errors just don't add broken entry. Tests are written only for migrated or migrating things to Python .

**Comment by Cjkjvfnby** [comment]
Also, script changes do not trigger the build job.   I think this error does not happen too often, so we could postpone the automation.  

But if we could compile only the parser and run it as a command line, we might create a separate job to validate the script.

**Comment by geoffthemedio** [comment]
would probably work to have a command line flag for the server binary to validate scripts

**Comment by o01eg** [comment]
> But if we could compile only the parser and run it as a command line, we might create a separate job to validate the script.

Actually the parser is the slowest to build thing we even have.

**Comment by Cjkjvfnby** [comment]
> Actually the parser is the slowest to build thing we even have.

Do you think we could migrate FOCS to Python DSL?  Can I help with it?

**Comment by geoffthemedio** [comment]
> > Actually the parser is the slowest to build thing we even have.
> 
> Do you think we could migrate FOCS to Python DSL? Can I help with it?

C++ parsers are slow to build, but faster to run than Python currently. Any progress getting the Python to run in parallel?

**Comment by o01eg** [comment]
> Do you think we could migrate FOCS to Python DSL? Can I help with it?

Currently porting species are postponed until parser changes related to #4492 will be merged.

> C++ parsers are slow to build, but faster to run than Python currently. Any progress getting the Python to run in parallel?

Yes, I've managed to use sub-interpretes which are essential for isolated multi-threading.

**Pull request merged**
