### PR TITLE
PlanetTypeDistance valueref for terraform

### PR DESCRIPTION
**Pull request by agrrr3**
access to planet type difference in FOCS

### CODE REVIEW

**Comment by agrrr3** [comment]
note that i did not change content nor checksum calculation, so the CI fail seems bogus

**Comment by geoffthemedio** [comment]
> note that i did not change content nor checksum calculation, so the CI fail seems bogus

If it's SmokeTestHostless failing, then it can be ignored presently. It just seems to randomly fail 75% of the time or so.

I've restarted the Ubuntu tests, which sometimes gets it to work.

**Comment by geoffthemedio** [comment]
I combined your stuff into one commit, then reworked a bit as https://github.com/freeorion/freeorion/tree/planet_type_difference_parsing

I'd rather use ints than strings internally, since it's just an enum and the conversion is easier, and it should matching and storing the FOCS strings like Ocean rather than the enum string representations like PT_OCEAN anyway.

I also got rid of the shared_ptr by rearraning include order a bit.

**Comment by geoffthemedio** [comment]
@agrrr3 does that also work for you?

**Comment by geoffthemedio** [comment]
pushed my version to master https://github.com/freeorion/freeorion/commit/4a7eeb01d5eb6f76ffd4c399ff70943d26596924

**Comment by agrrr3** [comment]
Yes, I want mostly something what works. So, works for me

Geoff ***@***.***> schrieb am So., 30. Jän. 2022, 22:23:

**Pull request closed without merging**
