### PR TITLE
FOCS: Move defense effects from species

### PR DESCRIPTION
**Pull request by dbenage-cx**
Moves planetary defense, troops, and shield effects from species.

Tag as work towards #715

### CODE REVIEW

**Comment by MatGB** [comment]
Something's wrong with this, I'm getting zero shields on a lot of AI worlds, and only getting Barrier Shield 1 on my homeworld, should be getting Force Field Dynamics and the basic +1 from Self Defence (which ought actually to be removed for players that've got FFD but that's not been discussed as planned).

I suspect I'm ahead on research than my two Egassem neighbours which means Shield1 is working but the earlier two aren't.

**Comment by dbenage-cx** [comment]
@MatGB Should have caught that, took forever to figure out what was wrong.

Not sure how far you are on stringtable updates, would you want a PR for updates on these entries? (DEF_ROOT_DEFENSE mentions troops and not shield).

**Comment by MatGB** [comment]
We are, as a team, perpetually forgetting to update stringtables, anytime you catch something a quick fix is always welcome—I'm especialyl bad at remembering the unlocked-at-start stuff as I never look at it while playing.

I haven't yet started on the full review of the stringtable, I'm behind on the balancing work I wanted in already, I normally do a stringtable review after we've closed off for new work which is delayed a bit now.

**Comment by geoffthemedio** [comment]
Are there any remaining issues with these scripting changes?

**Comment by dbenage-cx** [comment]
Just verification from someone other than me ;)

**Comment by Vezzra** [comment]
Well, @MatGB has taken responsibility for this PR, so we're more or less waiting for him I guess...

**Comment by MatGB** [comment]
I had missed the fixes had been done before going away, I'll be able to test it over the weekend but if anyone else is able to today or tomorrow that'd be fine, it looks fine but the last bug was a weird one

**Comment by MatGB** [comment]
K, tested on a few savegames and a quick playthrough to a reasonable level, appears to work fine so merging.

Hard to be sure, but fairly certain there's a significant lag reduction in the mid to late game from it, as predicted, which is nice.

**Comment by dbenage-cx** [comment]
Ty MatGB, I'll get the last of it rebased and tested.

**Pull request merged**
