### PR TITLE
Test python scripts compiling.

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Probably https://github.com/freeorion/freeorion/blob/master/default/python/interface_mock/result/freeOrionAIInterface.py#L3373 should be fixed if this is going to be put into the automatic builds...

**Comment by o01eg** [comment]
Rebased over fix commits.

**Comment by geoffthemedio** [comment]
I don't know much about this, so hopefully @adrianbroher has time to comment.

**Comment by geoffthemedio** [comment]
Lacking any input from @adrianbroher, since this appears to not break anything, if you do know what you're doing, OK by me to merge, then...

**Pull request merged**
