### PR TITLE
Added some extra render state setting calls to hopefully prevent disappearing cursor.

### PR DESCRIPTION
**Pull request by geoffthemedio**
Speculative that this might help with https://github.com/freeorion/freeorion/issues/676

### CODE REVIEW

**Comment by dbenage-cx** [comment]
Since this is `cherry-pick for release`:
Can not speak to related issue, but not finding any cursor issues otherwise.

**Comment by geoffthemedio** [comment]
I'd only cherry pick if someone reports that it actually helps with cursor issues.

**Comment by Vezzra** [comment]
Duly noted.

**Comment by MatGB** [comment]
But for the most part the people with the problem will be unable to compile themselves (by definition it's lower spec machines), so unless they get a compiled version with this in to test they can't report it one way or the other.

**Comment by geoffthemedio** [comment]
I suppose I'll merge this then, not intended for cherry picking even if there's an RC3, so that the next test builds will have it and it can get some testing.

**Comment by Vezzra** [comment]
Ok, removed the "cherry pick for release" tag and assigned the PR to the "post v0.4.7" milestone.

**Pull request merged**
