### PR TITLE
move ARTISAN_APPRECIATION to happiness.macros

### PR DESCRIPTION
**Pull request by MichaelCourtney**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg comment?

**Comment by o01eg** [comment]
Looks fine.

**Comment by geoffthemedio** [comment]
@MichaelCourtney you tested it?

**Comment by MichaelCourtney** [comment]
> @MichaelCourtney you tested it?

It's not throwing a parser error, or an error in the log. I'll go quickly check that the bonus still happens.

**Comment by geoffthemedio** [comment]
Please always test and report that you did so and if/that it works for you in the pull request message.

**Comment by MichaelCourtney** [comment]
> Please always test and report that you did so and if/that it works for you in the pull request message.

Got it.
Tested with human and silexian (both artistic). working

**Pull request merged**
