### PR TITLE
[FOCS] Fix warnings in scripts

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
- Fix missed import for priorities
    - Remove unused macro from advanced focus

```
[error] ai : Parse.cpp:108 : macro_deep_referenced_in_text couldn't find referenced macro: POPULATION_DEFAULT_PRIORITY
[error] ai : Parse.cpp:166 : j:/projects/freeorion/default/scripting/buildings/COLONY_BASE.focs.txt: Unresolved macro reference: POPULATION_DEFAULT_PRIORITY
[error] ai : Parse.cpp:166 : j:/projects/freeorion/default/scripting/buildings/COLONY_BASE.focs.txt: Unresolved macro reference: POPULATION_DEFAULT_PRIORITY
```

### CODE REVIEW

**Comment by geoffthemedio** [comment]
probably OK

**Comment by geoffthemedio** [comment]
Superceeded by / included in #4792 ?

**Comment by Cjkjvfnby** [comment]
> Superceeded by / included in https://github.com/freeorion/freeorion/pull/4792 ?

Let me double-check.  I prefer to rename other common folders in FOCS.  species/common, buildings/common

**Comment by Cjkjvfnby** [comment]
> Superceeded by / included in https://github.com/freeorion/freeorion/pull/4792 ?

Yes.  Could be closed without merging.

**Pull request closed without merging**
