### PR TITLE
Fix boost assertion

### LINKED ISSUE #4851: FreeOrion fails to start with Debug build
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2024-01-22.373998f
* **Operating System**: Linux
* **Graphic card used**: Intel
* **Fetched as** 
  * Compiled from source

Description
-----------

Boost asserting works when Debug enabled and cause the game to fail:

```
freeorion: /usr/include/boost/xpressive/regex_primitives.hpp:560: boost::xpressive::mark_tag::mark_tag(int): Assertion `mark_nbr > 0' failed.

Thread 1 "freeorion" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: Нет такого файла или каталога.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff3ca815f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff3c5a472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff3c444b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff3c443d5 in __assert_fail_base (fmt=0x7ffff3db8dc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff54cb7ea "mark_nbr > 0", 
    file=file@entry=0x7ffff54cb7b8 "/usr/include/boost/xpressive/regex_primitives.hpp", line=line@entry=560, 
    function=function@entry=0x7ffff54cb788 "boost::xpressive::mark_tag::mark_tag(int)") at ./assert/assert.c:92
#5  0x00007ffff3c533a2 in __assert_fail (assertion=0x7ffff54cb7ea "mark_nbr > 0", file=0x7ffff54cb7b8 "/usr/include/boost/xpressive/regex_primitives.hpp", line=560, 
    function=0x7ffff54cb788 "boost::xpressive::mark_tag::mark_tag(int)") at ./assert/assert.c:101
#6  0x00007ffff53211f7 in boost::xpressive::mark_tag::mark_tag (
    this=0x7ffff577adb8 <GG::Font::ExpensiveParseFromTextToTextElements(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GG::Flags<GG::TextFormat>) const::full_regex>, mark_nbr=0) at /usr/include/boost/xpressive/regex_primitives.hpp:560
#7  0x00007ffff530fe8f in GG::Font::ExpensiveParseFromTextToTextElements (this=0x555557180e80, text="Messages", format=...) at /home/oleg/devel/freeorion/GG/src/Font.cpp:1247
#8  0x00007ffff542acb8 in GG::TextControl::SetText (this=0x5555571ce190, str="") at /home/oleg/devel/freeorion/GG/src/TextControl.cpp:195
#9  0x00007ffff5429d24 in GG::TextControl::TextControl (this=0x5555571ce190, x=(unknown: 0x5), y=(unknown: 0x2), w=(unknown: 0x1), h=(unknown: 0x19), str="", 
    font=std::shared_ptr<GG::Font> (empty) = {...}, color=..., format=..., flags=...) at /home/oleg/devel/freeorion/GG/src/TextControl.cpp:52
#10 0x0000555555a68357 in CUILabel::CUILabel (this=0x5555571ce190, str="", format=..., flags=..., x=(unknown: 0x5), y=(unknown: 0x2), w=(unknown: 0x1), h=(unknown: 0x19))
    at /home/oleg/devel/freeorion/UI/CUIControls.cpp:65
#11 0x0000555555acfea4 in GG::Wnd::Create<CUILabel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GG::TextFormat const&, GG::WndFlag const&, GG::X const&, GG::Y const&, GG::X, GG::Y> () at /home/oleg/devel/freeorion/GG/GG/Wnd.h:326
#12 0x0000555555ac51b0 in CUIWnd::Init (this=0x555556fc7fe0) at /home/oleg/devel/freeorion/UI/CUIWnd.cpp:174
#13 0x0000555555ac4ff0 in CUIWnd::CompleteConstruction (this=0x555556fc7fe0) at /home/oleg/devel/freeorion/UI/CUIWnd.cpp:159
#14 0x00005555559fdff0 in MessageWnd::CompleteConstruction (this=0x555556fc7fe0) at /home/oleg/devel/freeorion/UI/ChatWnd.cpp:302
#15 0x0000555555a43325 in GG::Wnd::Create<MessageWnd, GG::Flags<GG::WndFlag>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> ()
    at /home/oleg/devel/freeorion/GG/GG/Wnd.h:327
#16 0x0000555555a364aa in ClientUI::GetMessageWnd (this=0x555556b14ae0) at /home/oleg/devel/freeorion/UI/ClientUI.cpp:648
#17 0x0000555555a39ec4 in ClientUI::InitializeWindows (this=0x555556b14ae0) at /home/oleg/devel/freeorion/UI/ClientUI.cpp:1000
#18 0x0000555555a35ae7 in ClientUI::ClientUI (this=0x555556b14ae0) at /home/oleg/devel/freeorion/UI/ClientUI.cpp:598
#19 0x00005555557ffda5 in std::make_unique<ClientUI> () at /usr/include/c++/13/bits/unique_ptr.h:1070
#20 0x00005555557dba59 in GGHumanClientApp::GGHumanClientApp (this=0x7fffffffcec0, width=1920, height=1025, calculate_fps=true, name="", x=0, y=55, fullscreen=false, fake_mode_change=true)
    at /home/oleg/devel/freeorion/client/human/GGHumanClientApp.cpp:308
#21 0x00005555557b4e19 in mainSetupAndRun () at /home/oleg/devel/freeorion/client/human/chmain.cpp:277
#22 0x00005555557b0ccd in main (argc=1, argv=0x7fffffffdfc8) at /home/oleg/devel/freeorion/client/human/chmain.cpp:102
(gdb) f 6
#6  0x00007ffff53211f7 in boost::xpressive::mark_tag::mark_tag (
    this=0x7ffff577adb8 <GG::Font::ExpensiveParseFromTextToTextElements(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GG::Flags<GG::TextFormat>) const::full_regex>, mark_nbr=0) at /usr/include/boost/xpressive/regex_primitives.hpp:560
560	        BOOST_ASSERT(mark_nbr > 0);
(gdb) l
555	    /// \pre <tt>mark_nbr \> 0</tt>
556	    mark_tag(int mark_nbr)
557	      : base_type(mark_tag::make_tag(mark_nbr))
558	    {
559	        // Marks numbers must be integers greater than 0.
560	        BOOST_ASSERT(mark_nbr > 0);
561	    }
562	
563	    /// INTERNAL ONLY
564	    operator detail::basic_mark_tag const &() const
```

`mark_nbr` incorrectly set to 0

Boost version is 1.83.

Expected Result
---------------

Steps to reproduce
------------------

* Set `CMAKE_BUILD_TYPE` to `Debug`.
* Build freeorion.
* Launch.

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
It breaks text markup parsing. Try opening the pedia.

Probably need to update other places that use the same numbers to specify regex types or lookup results. [Font.cpp does](https://github.com/freeorion/freeorion/blob/master/GG/src/Font.cpp#L439). Probably [other places](https://github.com/freeorion/freeorion/blob/master/GG/src/Font.cpp#L1247) [also](https://github.com/freeorion/freeorion/blob/master/GG/src/Font.cpp#L1102).

**Comment by o01eg** [comment]
> It breaks text markup parsing. Try opening the pedia.

Yes, it was broken. Looks like those values should be in sync with other `mark_tag`s definitions.

**Comment by geoffthemedio** [comment]
I vaguely recall there being some other location where the index of those matches is used to look up in results of a regex parse, but I can't find where it is.

**Comment by o01eg** [comment]
Yes, after login to the game I get many errors: `GG::Font : Encountered malformed <rgba> formatting tag:` and then it fails with 
```
terminate called after throwing an instance of 'utf8::invalid_utf8'
  what():  Invalid UTF-8
```

**Comment by geoffthemedio** [comment]
That's probably realted to some `string_view` binding to some text that goes invalid before it should. I'd need a stack trace or particular commit where the issue starts to debug...

**Comment by o01eg** [comment]
Stacktarce is:
```
terminate called after throwing an instance of 'utf8::invalid_utf8'
  what():  Invalid UTF-8

Thread 1 "freeorion" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: Нет такого файла или каталога.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff54a815f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff545a472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff54444b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff56a09eb in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff56affca in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff56b0035 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff56b0288 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6886550 in unsigned int utf8::next<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) [clone .part.0] () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#9  0x00007ffff693a6f6 in unsigned int utf8::next<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#10 0x00007ffff692c08a in GG::Font::PreRenderText(GG::Pt, GG::Pt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GG::Flags<GG::TextFormat>, std::vector<GG::Font::LineData, std::allocator<GG::Font::LineData> > const&, GG::Font::RenderState&, unsigned long, GG::CPSize, unsigned long, GG::CPSize, GG::Font::RenderCache&) const ()
   from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#11 0x00007ffff692c3f4 in GG::Font::PreRenderText(GG::Pt, GG::Pt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GG::Flags<GG::TextFormat>, GG::Font::RenderCache&, std::vector<GG::Font::LineData, std::allocator<GG::Font::LineData> > const&, GG::Font::RenderState&) const ()
   from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#12 0x00007ffff69bb4a7 in GG::TextControl::RefreshCache() () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#13 0x00007ffff69bb547 in GG::TextControl::Render() () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#14 0x00007ffff6958033 in GG::GUI::RenderWindow(GG::Wnd*) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#15 0x00007ffff6958118 in GG::GUI::RenderWindow(GG::Wnd*) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#16 0x00007ffff6958080 in GG::GUI::RenderWindow(GG::Wnd*) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#17 0x00007ffff6958118 in GG::GUI::RenderWindow(GG::Wnd*) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#18 0x00007ffff6958118 in GG::GUI::RenderWindow(GG::Wnd*) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#19 0x00007ffff6958705 in GG::GUI::RenderWindow(GG::Wnd*) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#20 0x00007ffff69589ee in GG::GUI::Render() () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#21 0x00007ffff695b307 in GG::GUI::RunModal(bool const&) () from /home/oleg/devel/freeorion-lt-client/lib/freeorion/libGiGi.so
#22 0x0000555555b7908c in SDLGUI::Run() ()
#23 0x00005555556be2c6 in mainSetupAndRun() ()
#24 0x00005555556b795c in main ()
```

**Comment by geoffthemedio** [comment]
this is with the pull request as it is now, or after additional modifications? if as now, then the inconsistent tag numbering is probably related to the issue...

actually, try just replacing `static const mark_tag full_regex(0)` with `static constexpr std::size_t full_regex(0)`.

The documentation for `match_results::operator[](Sub const &sub)` says that `If sub == 0 then returns a reference to a sub_match object representing the sequence that matched the whole regular expression.` but the `mark_tag` constructor nevertheless has an assert that the number is > 0...

like: https://github.com/freeorion/freeorion/commit/34498aaa1d53a37859cfff6e42ec6e58544749aa

**Comment by o01eg** [comment]
@geoffthemedio Yes, it works that way.

**Comment by geoffthemedio** [comment]
OK, commit/merge that then and I'll redo it like https://github.com/freeorion/freeorion/commit/34498aaa1d53a37859cfff6e42ec6e58544749aa later...

**Pull request merged**
