### PR TITLE
Sly & Gaia special - prevent type cycling, reweight colonization

### PR DESCRIPTION
**Pull request by rrobgill**
1.  alter the Gaia special to prevent it from cycling through
    planet types when occupied by Sly (similar to Exobots)

2.  alter the Colonization AI to devalue the Gaia special as Sly derive
   no benefit from it (similar to Exobots)

Related Issue #3001 

Signed-off-by: Rob Gill <rrobgill@protonmail.com>

### CODE REVIEW

**Comment by agrrr3** [comment]
I would prefer if you could refactor that in FOCS to a more general solution:

Not sure if it works, but you should be able to check in the activation condition if Source.NextBetterPlanetType is the current planet type and only fire the effect if it is not.
Then remove the special cases for Sly and exobots

**Comment by rrobgill** [comment]
@agrrr3 it seems that NextBetterPlanetType (as visible within FOCS) will never stabilize for Sly, but will always be the current type +1 (clockwise). There is no way at this level to distinguish between this case (continual cycling with no goal) and ordinary clockwise progression towards a goal for another species.

(In /universe/Planet.cpp and universe/ValueRefs.cpp it seems there is no logic in NextBetterPlanetType() to handle a species that doesn't have a favoured planet falling amongst the terrestrial planets.)

The other thought that occured was adding a _preferredenvironment_ class for each species (could be done en-masse for most species in env.macros, would only need additions to ancient guardians, exobots and sly (or add macros for their environmental tolerances to env.macros as well) but this would also involve backend changes (SpeciesParser.cpp at the least).

**Comment by geoffthemedio** [comment]
> In /universe/Planet.cpp and universe/ValueRefs.cpp it seems there is no logic in NextBetterPlanetType() to handle a species that doesn't have a favoured planet falling amongst the terrestrial planets.

That should not be difficult to fix...

**Comment by rrobgill** [comment]
The BetterPlanet detection logic has been reworked to only consider terrestrial planets.

Using @agrrr3's suggested method allowed removing the species specific tests for the Gaia special.

**Comment by geoffthemedio** [comment]
@agrrr3 is this satisfactory, or would you prefer something else...?

**Comment by geoffthemedio** [comment]
@agrrr3 ?

**Comment by agrrr3** [comment]
I think for the moment this suffices well

**Comment by geoffthemedio** [comment]
not sure about whether it should go into v0.4.10...

**Comment by Vezzra** [comment]
It's a bugfix, so I'd say it should.

**Pull request merged**
