### PR TITLE
Add named values for Organic Growth/Update Pedia

### PR DESCRIPTION
**Pull request by MichaelCourtney**
Haven't tested, pushed to check format was ok.

Also:
https://www.freeorion.org/forum/viewtopic.php?f=2&t=12638&sid=06cefc896bf10a79ce532cb6623841bb

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg This would benefit from having a test build that runs the binaries and attempts to parse the scripts, as it adds some currently-invalid scripting, but there are no tests run that will fail in this case...

````
SH_SYMBIOTIC.focs.txt:9:4: Parse error.  Expected Common Parameters here:
    speed = 100
    fuel = 2
    NoDefaultFuelEffect
    stealth = 15
    structure = 10
    NamedReal name = "SH_SYMBIOTIC_ORGANIC_GROWTH_MAX" value = (10 * (GameRule name = "RULE_SHIP_STRUCTURE_FACTOR"))
    ^
    NamedReal name = "SH_SYMBIOTIC_ORGANIC_GROWTH_PERTURN" value = (0.2 * (GameRule name = "RULE_SHIP_STRUCTURE_FACTOR"))
    slots = [
        Slot type = External position = (0.30, 0.30)
        Slot type = External position = (0.45, 0.30)
        Slot type = Internal position = (0.40, 0.55)
````

**Comment by o01eg** [comment]
I create parser tests when starting to change boost parser to python parser. I could add count tests for other parsers later.

**Comment by geoffthemedio** [comment]
If by count tests, you mean checking that the number of eg. hulls parsed was as expected, then those aren't ideal since they will frequently break when adding or removing content.

Rather I mean having at least one full build and smoke test run for content-script-only changes would help detect if those changes broken anything. Those test are already run if there are code changes, but not all platform targets would be needed for script-only changes.

**Comment by o01eg** [comment]
To test for broken files maybe make parsers to somehow return if parser errors was happened. Currently tests and programs only warn about it in logs and continue execution.

**Comment by Vezzra** [comment]
@MichaelCourtney, closed as abandoned, superseded, invalid...?

**Comment by MichaelCourtney** [comment]
closed as buged implementation

**Comment by Vezzra** [comment]
Ok, invalid then... thanks for the quick reply!

**Pull request closed without merging**
