### PR TITLE
Edit Tests and Safety Stuff

### PR DESCRIPTION
**Pull request by geoffthemedio**
Might help with some reported crashes.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg the master bulid after this has a [failure for docker / void-musl](https://github.com/freeorion/freeorion/actions/runs/12397678729/job/34627082511):
`make[2]: *** No rule to make target '/usr/lib/libboost_python313.so.1.83.0', needed by 'freeoriond'.  Stop.`

That doesn't appear to be an issue with FreeOrion code, but rather the setup for that environment... can you look at it?

**Comment by o01eg** [comment]
Looks like Void issue, they miss version number for only boost.python library, while other boost libraries have file with version and without.

**Comment by Vezzra** [comment]
@geoffthemedio, can you do the cherry picking or provide a PR for the release branch? I'm getting conflicts when I try to cherry pick this.

**Comment by geoffthemedio** [comment]
it's already in release

**Comment by Vezzra** [comment]
Ah ok, thanks!

**Pull request merged**
