### PR TITLE
Add building godot-cpp as dependency to Godot client build scripts

### PR DESCRIPTION
**Pull request by Vezzra**
Extends the cmake build scripts so that when you build the GDNative library for the Godot client, the `godot-cpp` dependency automatically gets built too, and the resulting libraries all get copied to the right places.

The cmake feature used to implement this is `ExternalProject`.

This currently only has been tested successfully on Linux. Haven't done any tests on Windows yet, on macOS apparently further tweaking is necessary to get things to work.

### CODE REVIEW

**Comment by o01eg** [comment]
It fails if `freeorion/godot/client/bin/` doesn't exists.

**Comment by o01eg** [comment]
I think what about to split bin depending on architecture and OS? Currently i686 and x86_64 for Linux will replace each other.

For Windows we have to restore CMake project I suppose.

**Comment by Vezzra** [comment]
@o01eg,

> It fails if freeorion/godot/client/bin/ doesn't exists.

Thanks, fixed.

> I think what about to split bin depending on architecture and OS? Currently i686 and x86_64 for Linux will replace each other.

As long as you only develop for one platform/architecture on your system, this shouldn't be an issue, so I assumed the current setup sufficient for our prototyping purposes.

However, if you already need that, sure, feel free to adjust the cmake scripts accordingly (after we've merged this into the `build-godot` branch) - you're probably better at that than me (I'm don't know cmake that well actually, I go mostly by copy & paste, Google, trial & error... 😉).

> For Windows we have to restore CMake project I suppose.

Yeah, you're right, I forgot that on Windows we do not build with cmake, so doing any dev work for the Godot client on Windows doesn't work, at least not with the solution provided here.

It won't be _restoring_ the cmake project on Windows though, as we never got building with cmake on Windows working.

**Comment by Vezzra** [comment]
@geoffthemedio, this PR is not against master, but the `build-godot` branch, so no need to set this PR to draft. Actually, this PR is meant to be ready for review and merge.

**Comment by Vezzra** [comment]
@o01eg, ok to merge, or do you have any more comments?

**Comment by o01eg** [comment]
It tries to launch freeoriond from the godot's `bin/` folder.

**Comment by geoffthemedio** [comment]
> > For Windows we have to restore CMake project I suppose.
> 
> Yeah, you're right, I forgot that on Windows we do not build with cmake, so doing any dev work for the Godot client on Windows doesn't work, at least not with the solution provided here.

I added a Godot DLL project to the MSVC 2017 project files. It built. Not tested otherwise. https://github.com/freeorion/freeorion/commit/101d7184a522dcf504d6dc84fdc5c9c76e69821f

**Review by o01eg — APPROVED** [review]
Looks fine. I'll tune cmake later.

**Comment by geoffthemedio** [comment]
I tried [adding a Godot client project](https://github.com/freeorion/freeorion/commit/a13644aec8ec7ea1143f1b10152706b47f31fa78), but I get build errors in util\Logger.h even though it builds fine when included in the current client build. Not sure where to post about it, so:
````
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2059: syntax error: ';' (compiling source file ..\..\godot\OptionsDB.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C3536: 'channel': cannot be used before it is initialized (compiling source file ..\..\godot\OptionsDB.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2664: 'void ConfigureLogger(NamedThreadedLogger &,const std::string &)': cannot convert argument 2 from 'int' to 'const std::string &' (compiling source file ..\..\godot\OptionsDB.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: Reason: cannot convert from 'int' to 'const std::string' (compiling source file ..\..\godot\OptionsDB.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\..\godot\OptionsDB.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2059: syntax error: ';' (compiling source file ..\..\godot\GodotNetworking.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C3536: 'channel': cannot be used before it is initialized (compiling source file ..\..\godot\GodotNetworking.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2664: 'void ConfigureLogger(NamedThreadedLogger &,const std::string &)': cannot convert argument 2 from 'int' to 'const std::string &' (compiling source file ..\..\godot\GodotNetworking.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: Reason: cannot convert from 'int' to 'const std::string' (compiling source file ..\..\godot\GodotNetworking.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\..\godot\GodotNetworking.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\godot\godotsystem.cpp(48): warning C4244: 'argument': conversion from 'double' to 'real_t', possible loss of data
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2059: syntax error: ';' (compiling source file ..\..\godot\gdfreeorion.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C3536: 'channel': cannot be used before it is initialized (compiling source file ..\..\godot\gdfreeorion.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2664: 'void ConfigureLogger(NamedThreadedLogger &,const std::string &)': cannot convert argument 2 from 'int' to 'const std::string &' (compiling source file ..\..\godot\gdfreeorion.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: Reason: cannot convert from 'int' to 'const std::string' (compiling source file ..\..\godot\gdfreeorion.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\..\godot\gdfreeorion.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2059: syntax error: ';' (compiling source file ..\..\godot\GodotClientApp.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C3536: 'channel': cannot be used before it is initialized (compiling source file ..\..\godot\GodotClientApp.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): error C2664: 'void ConfigureLogger(NamedThreadedLogger &,const std::string &)': cannot convert argument 2 from 'int' to 'const std::string &' (compiling source file ..\..\godot\GodotClientApp.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: Reason: cannot convert from 'int' to 'const std::string' (compiling source file ..\..\godot\GodotClientApp.cpp)
1>  c:\users\g_top\desktop\fosdk11\freeorionalt2\util\logger.h(237): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\..\godot\GodotClientApp.cpp)
1>Done building target "ClCompile" in project "GodotClient.vcxproj" -- FAILED.
````

**Comment by o01eg** [comment]
I suppose some macros options differs so it some lead to syntax error in header.

**Comment by geoffthemedio** [comment]
Added some preprocessor defs which seems to have cleaned those up, but am now getting a bunch of boost log ABI link errors like
`Common.lib(OptionsDB.obj) : error LNK2038: mismatch detected for 'boost_log_abi': value 'v2_mt_nt6' doesn't match value 'v2s_mt_nt6' in gdfreeorion.obj`

**Comment by o01eg** [comment]
It is also options issue, it should be `_WIN32_WINNT=0x0600` missing

**Comment by geoffthemedio** [comment]
That's set in win32.dependency.props but apparently not used by the new projects...?

Found how to add them in the property manager. On to other linker errors...

**Comment by geoffthemedio** [comment]
Is there supposed to be a separate Godot library from the Godot FreeOrion client? I can't find a file that exports all the Godot symbols without also pulling in a bunch of FreeOrion-specific dependencies...

**Comment by o01eg** [comment]
@geoffthemedio On linux it builds static `godot-cpp` library.

**Comment by geoffthemedio** [comment]
I assumed it should be a dynamic library.

If static, why not just build directly into the client?

edit: now I'm just missing a `main` function for the Godot client link...

**Comment by o01eg** [comment]
> edit: now I'm just missing a main function for the Godot client link...

@geoffthemedio Godot client is a dynamic library.

**Comment by geoffthemedio** [comment]
ok then everything builds as of https://github.com/freeorion/freeorion/commits/Godot_MSVC_Project

**Pull request merged**
