### PR TITLE
Production summary rework

### PR DESCRIPTION
**Pull request by geoffthemedio**
Reworks production info panel (on production and research screens) to use a standard window base, and to provide some location-specific information depending on what production location is selected.

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
Yes, looks like a helpful change to me.

**Comment by Dilvish-fo** [comment]
Hmm, looking at this a bit more, from the code it appears to me that it is going to be using that same header for the Research Queue as well, is that right?  Although the current second half of the ProductionQueuePanel header is of rather low value, it at least seems theoretically of interest, whereas the second half of this new Panel seems totally senseless for the Research Queue.  I would suggest subclassing, with a different lower half for Production and Research.

**Comment by geoffthemedio** [comment]
The local info is (already) not displayed for the research queue, as there is no local info to set.

**Comment by Vezzra** [comment]
Did a brief test on OSX, works fine.

Anything preventing this from getting merged?

**Comment by geoffthemedio** [comment]
Ideally there would be config names passed in when creating the Wnds so the their position can be cased, but it presently doesn't make any sense to move the info panel anyway since the queue below it is still fixed in position... So I suppose not?

**Comment by Dilvish-fo** [comment]
I was just reordering some items on the queue and this happend:
prodiction_header

There are no blockades.  It just strikes me now though that it could be the epsilon handling in the ProductionQueue might leave some little smidgen unallocated.  If there's not already a min epsilon check here there probably should be.

**Comment by geoffthemedio** [comment]
Try chaging
`if (wasted_points > 0.0f)`
to
`if (wasted_points > 0.01f)`
in ProductionInfoPanel::SetTotalPointsCost and ProductionInfoPanel::SetLocalPointsCost in CUIControls.cpp.

**Pull request merged**
