### PR TITLE
Read resource files on Android from APK

### PR DESCRIPTION
**Pull request by o01eg**
Extracted from #3367 part of reading files

### CODE REVIEW

**Review by Vezzra — COMMENTED** [review]
Can't comment on the code changes, but does not cause any obvious issues on macOS.

**Comment by geoffthemedio** [comment]
needs rebase

**Comment by o01eg** [comment]
@geoffthemedio Rebased

**Comment by geoffthemedio** [comment]
builds and seems to run OK on Windows.

**Comment by o01eg** [comment]
Good. I'll merge it then.

**Pull request merged**
