### PR TITLE
[python] Use print function in common modules

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Add compatibility with python3 for common modules.  These modules can be imported before logging is configured so I used `print_function`

### CODE REVIEW

**Comment by Vezzra** [comment]
Is that really AI specific? To me it looks like these changes affect the common/general parts of the python scripting...?

**Comment by Cjkjvfnby** [comment]
> Is that really AI specific? To me it looks like these changes affect the common/general parts of the python scripting...?

@Vezzra Should I replace label or use both?

`The Issue/PR deals with the Python AI decision making code or affects it.`
`The Issue/PR deals with the FOCS language, turn events, the universe generator and probably game mechanics.`

**Review by Dilvish-fo — COMMENTED** [review]
Although you note in your intro that "These modules can be imported before logging is configured so I used print_function", it looks to me like at least one of these files does import logging first, but overall this looks fine to me and seems like a good general step.

**Review by Dilvish-fo — APPROVED** [review]

**Comment by Vezzra** [comment]
> Should I replace label or use both?

I'd only use "component:content scripting", as those changes contain nothing that looks AI specific. The AI modules might use these (utility etc.) functions, but they are not specific for the AI.

I'll go ahead and adjust the labels.

**Pull request merged**
