### PR TITLE
Tweak policy effect priorities

### PR DESCRIPTION
**Pull request by MichaelCourtney**
https://www.freeorion.org/forum/viewtopic.php?f=15&t=12631&sid=f9daf7545562f4efeda8cca4e888ca6c

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
That probably makes sense, but it's quite a drastic balancing change.

Should this go into the release?

Not to forget: I'll have to adapt the AI again when this is done, though that shouldn't be too complicated. Or you could include it into your PR: AI/colonization/calculate_{influence|production|research}.py

-Grummel7

**Comment by MichaelCourtney** [comment]
still need to do calcualte_influence, not very sure what I'm doing in python

**Comment by MichaelCourtney** [comment]
Doesn't seem to require a change in calculate_production. Should be all good now.

**Comment by geoffthemedio** [comment]
@Cjkjvfnby or @Grummel7 any comment?

**Comment by Grummel7** [comment]
> @Cjkjvfnby or @Grummel7 any comment?

Regarding the AI code, it looks okay. There will be a merge conflict, though, since I already fixed a small bug that Michael detected while adapting the AI. There is however no need to merge it, this PR could simply overwrite my change.

But the point I made in the forum is still valid: Do we want such a balancing change now? Since we did not discuss it during the last dev meeting, I assumed, it wouldn't be added for 0.5.

**Comment by Vezzra** [comment]
> Do we want such a balancing change now? Since we did not discuss it during the last dev meeting, I assumed, it wouldn't be added for 0.5.

If the change is so significant that you're not sure if it's a good thing to include it into the release, I'd lean toward not including at this point, so close to creating the release branch.

**Comment by MichaelCourtney** [comment]
I can fix the merge conflict easily enough, I'll just work on the basis that its going in after release.

**Comment by geoffthemedio** [comment]
still draft / work in progress?

**Comment by MichaelCourtney** [comment]
I'll try rebasing it on current master. It was done, but I believe Grummel7 updated 1 of the relevant files

**Comment by MichaelCourtney** [comment]
I'm not getting a  merge conflict, nor am I seeing @Grummel7 's change in the commit history.

**Comment by Grummel7** [comment]
> I'm not getting a merge conflict, nor am I seeing @Grummel7 's change in the commit history.

It was this commit (and the following fix): bbf2b7383828349377c3d9a5a8e2b7bdf2ff409c
If you do not get a conflict, you should check it manually, otherwise diversity may added with old and new rules.

**Comment by MichaelCourtney** [comment]
Should be right now

**Comment by MichaelCourtney** [comment]
Superseeded by:
https://github.com/freeorion/freeorion/pull/4886
and
https://github.com/freeorion/freeorion/pull/4887

**Pull request closed without merging**
