### PR TITLE
Package MacOS build

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by Vezzra** [comment]
Looks good! But how/where can the DMG build artifact be downloaded? In the logs I can only see that it got generated...

**Comment by o01eg** [comment]
I only add check if it could be generated. I didn't its publication. I've seen Mac OS issues was fixed so I didn't go further with it.

**Comment by geoffthemedio** [comment]
why not fully automate builds?

**Comment by o01eg** [comment]
Copied from windows action. Should work https://github.com/freeorion/freeorion/pull/4182

**Pull request merged**
