### PR TITLE
cmake: Fix config for CMP0093

### PR DESCRIPTION
**Pull request by xnox**
See https://cmake.org/cmake/help/v3.15/policy/CMP0093.html

### CODE REVIEW

**Comment by xnox** [comment]
Without this v0.4.9 will fail to build from source on Debian Ubuntu and all other up to date linux distributions.

**Comment by geoffthemedio** [comment]
@adrianbroher or @agrrr3 any comment?

**Comment by adrianbroher** [comment]
Icky.  Won't merge as there is no explicit policy selection for OLD or NEW behaviour in the patch.

**Comment by adrianbroher** [comment]
Also the change in CMake is too recent for me, so setting the policy to OLD would my preferred solution.

**Comment by xnox** [comment]
> Also the change in CMake is too recent for me, so setting the policy to OLD would my preferred solution.

But implementation of OLD may and will be removed at any time.

I guess i can add a `get()` call to check what the policy is set to, if it is available to cover all cases.

**Comment by xnox** [comment]
Also not that this will safe freeorion from removal in debian/ubuntu as both are dropping python2, and freeorion fails to work under boost-python38 / python3 only.

**Comment by adrianbroher** [comment]
> Also not that this will safe freeorion from removal in debian/ubuntu as both are dropping python2, and freeorion fails to work under boost-python38 / python3 only.

We are aware of that.  However this fact will not change the current schedule.

**Comment by adrianbroher** [comment]
> But implementation of OLD may and will be removed at any time.

Yes, and what is your point?  The CMake setup is already convoluted as it is.  I don't want to see any more crude fixes in there.

**Comment by xnox** [comment]
See my updated merge proposal that works with old/new cmakes, irrespective of cmake preset policy and is forward-proof.

**Comment by geoffthemedio** [comment]
@adrianbroher any better now?

**Comment by adrianbroher** [comment]
No. The same can be achieved with the _MAJOR, _MINOR variables in a single line and without caring for CMP0093.

**Comment by Vezzra** [comment]
@xnox,

> Without this v0.4.9 will fail to build from source on Debian Ubuntu and all other up to date linux distributions.

As @adrianbroher said, we are aware of this. The problem is, getting FO to work with Python3 requires a lot of adjustments, as all the AI, universe generation and event turn scripts are Python. Migrating the interface code as well as all the scripts is a non-trivial task we decided not to do for 0.4.9, and accept the fact that this will get FO removed from all Linux distros that do not support Python2 anymore (for the time being).

Getting the Python3 migration into 0.4.9 would cause another huge delay for that release, which is already massively delayed (we wanted to get that release out almost a year ago originally!).

We decided to dedicate the entire next release cycle to the Python3 migration, which we will try to get done asap, so FO can again be included in all Linux distros.

Until then, players on Linux are recommended to use our FO snap package. The release announcement will include a respective note.

**Comment by Vezzra** [comment]
Superseded by #2751.

**Pull request closed without merging**
