### PR TITLE
[stringtables] Update to en.txt changes

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
- remove old save options after  @LGM-Doyle  changes
- add ru translation to save options
- remove old ship designs after @MatGB changes
- fix renamed meter in tag after @dbenage-cx changes

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@Ouaz comments?

Needs rebase, seemingly.

**Comment by Cjkjvfnby** [comment]
Rebased.

**Comment by Ouaz** [comment]
> @Ouaz comments?

Good catch for the FR file, it seems I forgot to modify these two keys:

SD_FLAK to SD_CARRIER_2
SD_FLAK_DESC to SD_CARRIER_2_DESC

En.txt [6bf2fe3] / fr.txt [5ca35e0] (line 321 & 324)

That's why they got removed from the FR file with Cj's script. I will fix this by re-adding them along with the correct keys, with my  FR file weekly update next monday.

@geoffthemedio 
NB: That's weird, because it should have been a log error about these two nonexistent keys when launching the game in french, no?

**Comment by Cjkjvfnby** [comment]
> Good catch for the FR file, it seems I forgot to modify these two keys:
> SD_FLAK to SD_CARRIER_2
> SD_FLAK to SD_CARRIER_2_DESC

Does that meant that I can just revert removing  `SD_FLAK` and rename key to `SD_CARRIER_2` without changing value?   (https://github.com/freeorion/freeorion/pull/1717/files#diff-2efe38dcd6a76a030815ade89fecb49eL295)

**Comment by Ouaz** [comment]
> Does that meant that I can just revert removing  `SD_FLAK` and rename key to `SD_CARRIER_2` without changing value? 

Nope, the values have changed too (commited Jan 10, 2017)
(https://github.com/freeorion/freeorion/commit/6bf2fe3ff5bd56e128f5caecc77b63f2c5d2b50a#diff-fe03456032a6cd14b854949b5d9b2589L321)

In the FR file, I updated the values but forgot to change the keys (commited Jan 16, 2016)
(https://github.com/freeorion/freeorion/commit/5ca35e0df4eaa62392f6fb71c61a24ffc9561f59#diff-0e9b08414052f162035f9523bb6a6ef3L321). I will re-add these two strings with my weekly update tomorrow.

Your removal script is good in case of the de.txt file, as the values are still the former ones (not updated by the german translator).

**Pull request merged**
