### PR TITLE
Change Macos SDK Python reference from 3.5 to 3.6

### PR DESCRIPTION
**Pull request by o01eg**
Paired PR to #3321

For use with freeorion/freeorion-sdk#79

### CODE REVIEW

**Review by Vezzra — APPROVED** [review]
Yep, that works.

Of course, that must only be merged with the release of a new SDK version (if I understand correctly).

**Comment by geoffthemedio** [comment]
Is the new SDK considered released for purposes of this?

**Comment by o01eg** [comment]
@geoffthemedio Yes

**Comment by geoffthemedio** [comment]
already included in https://github.com/freeorion/freeorion/pull/3321 I think?

**Comment by geoffthemedio** [comment]
Edit: I published the v12 release, so now the file is available...

https://github.com/freeorion/freeorion-sdk/releases/download/v12/FreeOrionSDK_12_MSVC-v141-Win32.zip doesn't exist, though... so I can't point https://github.com/freeorion/freeorion/blob/master/.appveyor.yml#L25 to it

**Pull request closed without merging**
