### PR TITLE
Update Project File and CMake Python references from 3.5 to 3.6 and SDK references to 12

### PR DESCRIPTION
**Pull request by geoffthemedio**
For use with https://github.com/freeorion/freeorion-sdk/pull/79

### CODE REVIEW

**Review by o01eg — APPROVED** [review]
I'm fine with it but currently it breaks CI

**Comment by geoffthemedio** [comment]
> I'm fine with it but currently it breaks CI

It is expected to break the MSVC build in general, until a new SDK is released to use with it.

**Comment by geoffthemedio** [comment]
@o01eg How can the "Build FreeOrion on Windows" action be told to use the v12 SDK?

**Comment by o01eg** [comment]
@geoffthemedio Change url in

https://github.com/freeorion/freeorion/blob/846611c19c5ca7d6373363b05479f33b393b0a0d/.github/workflows/build-windows.yml#L32-L32

**Comment by geoffthemedio** [comment]
@o01eg good to go?

**Comment by o01eg** [comment]
Yes, on Linux I already use recent boost and python.

**Pull request merged**
