### PR TITLE
Read content files from Android Godot APK

### PR DESCRIPTION
**Pull request by o01eg**
Follows up #3339. Requires #3365 to export all required files.

New logs from Android:

```
00:27:39.633520 {0xc9909970} [info] log : Logger.cpp:204 : Added logger named "log"
00:27:39.634001 {0xc9909970} [info] log : Logger.cpp:204 : Added logger named "IDallocator"
00:27:39.634082 {0xc9909970} [info] log : Logger.cpp:396 : Logger initialized at Mon Mar 29 00:27:39 2021
00:27:39.634320 {0xc9909970} [info] log : Logger.cpp:343 : Setting "log" logger threshold to "debug".
00:27:39.634392 {0xc9909970} [debug] log : LoggerWithOptionsDB.cpp:105 : Configure log source "log" from optionsDB using threshold debug
00:27:39.634598 {0xc9909970} [info] log : Logger.cpp:343 : Setting "godot" logger threshold to "debug".
00:27:39.634731 {0xc9909970} [info] log : Logger.cpp:343 : Setting "log" logger threshold to "debug".
00:27:39.634784 {0xc9909970} [debug] log : LoggerWithOptionsDB.cpp:105 : Configure log source "log" from optionsDB using threshold debug
00:27:39.635045 {0xc9909970} [info] log : Logger.cpp:343 : Setting "IDallocator" logger threshold to "debug".
00:27:39.635101 {0xc9909970} [debug] log : LoggerWithOptionsDB.cpp:105 : Configure log source "IDallocator" from optionsDB using threshold debug
00:27:39.635155 {0xc9909970} [info] log : LoggerWithOptionsDB.cpp:91 : Initialized OptionsDB logging configuration.
00:27:39.635238 {0xc9909970} [info] godot : GodotClientApp.cpp:77 : v0.4.10+ build-godot-android-export-default [build 2021-03-28.16836bb] CMake
00:27:39.635302 {0xc9909970} [info] godot : DependencyVersions.cpp:90 : Dependency versions from headers:
00:27:39.635356 {0xc9909970} [info] godot : DependencyVersions.cpp:93 : Boost: 1_74
00:27:39.635406 {0xc9909970} [info] godot : DependencyVersions.cpp:93 : zlib: 1.2.7
00:27:39.635499 {0xc9909970} [info] godot : i18n.cpp:177 : Global locale: C
00:27:39.637853 {0xc9909970} [warn] godot : i18n.cpp:40 : Lanuage not detected from locale: "c"; falling back to default en
00:27:39.637972 {0xc9909970} [debug] godot : Directories.cpp:774 : IsExistingFile: check file default/stringtables/en.txt
00:27:39.638090 {0xc9909970} [debug] godot : Directories.cpp:781 : IsExistingFile: asset length 616873
00:27:39.638177 {0xc9909970} [debug] godot : Directories.cpp:774 : IsExistingFile: check file default/stringtables/en.txt
00:27:39.638252 {0xc9909970} [debug] godot : Directories.cpp:781 : IsExistingFile: asset length 616873
00:27:39.638316 {0xc9909970} [debug] godot : i18n.cpp:58 : GetDefaultStringTableFileName returning: default/stringtables/en.txt
00:27:39.638375 {0xc9909970} [debug] godot : i18n.cpp:82 : Stringtable option path: 
00:27:39.638425 {0xc9909970} [debug] godot : i18n.cpp:85 : Stringtable option path not specified yet, using default: default/stringtables/en.txt
00:27:39.647310 {0xc9909970} [error] godot : Parse.cpp:210 : File parsing include substitution given search path that is not a directory: default/stringtables
00:27:39.837410 {0xc9909970} [error] godot : AppInterface.cpp:60 : Background parse given non-existant resources directory!
```

### CODE REVIEW

**Comment by o01eg** [comment]
Files mostly reads but Parse.cpp incorrectly searches includes.
```
09:30:53.919212 {0xc220f970} [error] godot : Parse.cpp:218 : Exception caught regex parsing script file: boost::filesystem::canonical: No such file or directory: "/default/scripting/common/base_prod.macros"
```

The first it should be path `default/scripting/common/base_prod.macros`, and next it should use `ReadFile` and shouldn't use `boost::filesystem::canonical` in `process_include_substitutions`.


[freeorion-godot.log](https://github.com/freeorion/freeorion/files/6219729/freeorion-godot.log)

**Comment by o01eg** [comment]
Now all contents files could be read without errors:

[freeorion-godot.log.zip](https://github.com/freeorion/freeorion/files/6220525/freeorion-godot.log.zip)

**Review by Vezzra — COMMENTED** [review]
Can't comment on the code changes, but does not cause any obvious issues on macOS.

**Comment by o01eg** [comment]
It's a PR mostly for Godot testing.

**Comment by geoffthemedio** [comment]
can't test it. no comments on the code.

**Comment by o01eg** [comment]
Merged to https://github.com/freeorion/freeorion/pull/3235

**Pull request closed without merging**
