### PR TITLE
Ignore freshly established colonies for evacuation building effects

### PR DESCRIPTION
**Pull request by agrrr3**
Ignoring freshly established colonies on BLD_EVACUATION (i.e. do destroy the building and do not decrease population if the building is on such a colony).

Solves #950

### CODE REVIEW

**Comment by geoffthemedio** [comment]
You've tested this, including establishing a colony (in supply to main empire) and immediately producing an evacuation on it, and all works as expected?

**Comment by agrrr3** [comment]
> You've tested this, including establishing a colony (in supply to main empire) and immediately producing an evacuation on it, and all works as expected?

nice catch, there was an issue:
* colonizing and 1-turn building evacuation building does increase **but not decrease pop**

after shifting the turn numbers, this is fixed and following is tested:
* evacuation - usually population goes down by two, pop on another planet goes up by two
* completely evacuated planet still has building, turning destroys it. colonizing on the turn the building still exists does not make it decrease/increase population.
* colonizing and 1-turn building evacuation building does decrease/increase pop and thus immediately evacuates the colony

**Comment by geoffthemedio** [comment]
> * colonizing and 1-turn building evacuation building does decrease/increase pop and thus immediately evacuates the colony

what about with a cryo colony pod (3 pop to start, I think) ?

**Comment by agrrr3** [comment]
> > * colonizing and 1-turn building evacuation building does decrease/increase pop and thus immediately evacuates the colony
> 
> what about with a cryo colony pod (3 pop to start, I think) ?

as expected -2 pop decrease (and +2 pop increase) and building still there. scrapping or turning works as expected

**Comment by agrrr3** [comment]
is it possible to have automated tests for such effects?

**Comment by geoffthemedio** [comment]
> is it possible to have automated tests for such effects?

Probably, but constructing the test scenario and conditions for pass/fail for something like this is complicated...

**Pull request merged**
