### PR TITLE
Use Newer Boost IP Resolver and Avoid Deprecated Functions

### PR DESCRIPTION
**Pull request by geoffthemedio**
hopefully partly addresses #5044

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg Can you test this?

I was able to connect to the slow turn MP server, but didn't get a password email to actually log in.

May actually only be relevant on a LAN, and I'm not sure if I have suitable set of computers and networks to test that.

Checking with multiple servers listening on the local network might also be good?

**Comment by o01eg** [comment]
> @o01eg Can you test this?

Yes, it works for me too.

> I was able to connect to the slow turn MP server, but didn't get a password email to actually log in.

Maybe email got to spam, it least you successfully established connection.

**Comment by o01eg** [comment]
> May actually only be relevant on a LAN, and I'm not sure if I have suitable set of computers and networks to test that.

Yes, UDP multicast is actual only for LAN, I'm neither have one.

**Comment by geoffthemedio** [comment]
> Maybe email got to spam, it least you successfully established connection.

I checked, didn't see it.

**Comment by geoffthemedio** [comment]
> > May actually only be relevant on a LAN, and I'm not sure if I have suitable set of computers and networks to test that.
> 
> Yes, UDP multicast is actual only for LAN, I'm neither have one.

Worked over wifi LAN, so seemingly this will be good, if it actually fixes the build with the latest Boost.

**Pull request merged**
