### PR TITLE
Add SP_FULVER, precognitive unsatisfied ants

### PR DESCRIPTION
**Pull request by agrrr3**
Adding the Fulver for exploring if a GOOD_STOCKPILE GOOD_WEAPONS species adds strategic options. And I actually like 'em.

http://www.freeorion.org/forum/viewtopic.php?f=7&t=10940

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Link to forum thread?

**Comment by Dilvish-fo** [comment]
@Voker57 @l29ah even though it might be quite a while before you guys would consider adding new species into your multiplayer game, could one or both of you give some multiplayer-perspective-feedback on the forum thread?  thanks

**Comment by l29ah** [comment]
They look a little too good for warmongering, but overall LGTM for teamsmac inclusion.

**Comment by geoffthemedio** [comment]
OK to have in master, I suppose.

**Pull request merged**
