### PR TITLE
Fix #785

### LINKED ISSUE #785: Tech Tree Dependency Line Layout
The tech tree layout currently produces very unoptimal placement of dependency lines, where long pathes around techs are used for no apparent reason.

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR is a work in progress and so far only contains slight refactoring.

Fixes #785

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I tried fixing the build errors this produces, but still got crashes when trying to run it.

**Comment by Vezzra** [comment]
@geoffthemedio, "status:abandoned" is intended for closed issues/PRs - so, can we close this? Apparently you don't expect it to be picked up again...

**Comment by geoffthemedio** [comment]
Seems unlikely at the moment.

**Comment by geoffthemedio** [comment]
@adrianbroher do you expect to resume work on this, or should I delete the branch?

**Comment by adrianbroher** [comment]
I would like to continue working on this but not right now.

**Comment by adrianbroher** [comment]
superseded-by: #2930 

The associated branch `fix-785` can be deleted.

**Pull request closed without merging**
