### PR TITLE
[AI]  add log to possible error

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
- log possible error when location is not checked before issue order
- ignore first argument of `getBestShipInfo`, it was bad named

I did not test it yet.

Looks like errors in log after turn 100  may be caused by this issue.  It happens not every game.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@Morlic-fo, I am on vacations till January 13, please take care of this PR.

**Comment by Vezzra** [comment]
Um, I don't entirely understand... is the change to ignoring the first return value of `getBestShipInfo` supposed to be a cosmetic change (because it was "bad named", as indicated in the comment), or is that an attempt to fix a bug (as the actual code change seems to indicate)?

**Comment by Vezzra** [comment]
Bump?

**Comment by Cjkjvfnby** [comment]
It is not fix. Cosmetic changes and some logging for possible error. 

PS. I will be back to coding after 13january

**Pull request merged**
