### PR TITLE
Convert make_send_diplomatic_action lambda to function.

### PR DESCRIPTION
**Pull request by LGM-Doyle**
Issue #1557 reports that gcc 5.4 crashes when calling
make_send_diplomatic_action which is a lambda returning another lambda
to be used as the propose peace/war/alliance action.

This commit converts that lambda into a function returning a
std::function<void()> to work around the bug in gcc 5.4.

### CODE REVIEW

**Comment by Vezzra** [comment]
Same crash still happens with this PR. Backtrace:
```
#0 0x0000000003454e90 in ?? ()
No symbol table info available.
#1 0x0000000000722d29 in PlayerListWnd::PlayerRightClicked(std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&) ()
No symbol table info available.
#2 0x0000000000723053 in boost::detail::function::void_function_obj_invoker3<boost::_bi::bind_t<void, boost::_mfi::mf3<void, PlayerListWnd, std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&>, boost::_bi::list4<boost::_bi::value<PlayerListWnd*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >, void, std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&>::invoke(boost::detail::function::function_buffer&, std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&) ()
No symbol table info available.
#3 0x00007ffff5328774 in boost::signals2::detail::signal_impl<void (std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&)>, boost::function<void (boost::signals2::connection const&, std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&)>, boost::signals2::mutex>::operator()(std::_List_iterator<GG::ListBox::Row*>, GG::Pt const&, GG::Flags<GG::ModKey> const&) () from /home/user/SoftwareProjects/FO/build/libGiGi.so
No symbol table info available.
#4 0x00007ffff531c0cf in GG::ListBox::EventFilter(GG::Wnd*, GG::WndEvent const&) () from /home/user/SoftwareProjects/FO/build/libGiGi.so
No symbol table info available.
#5 0x00007ffff536b416 in GG::Wnd::HandleEvent(GG::WndEvent const&) () from /home/user/SoftwareProjects/FO/build/libGiGi.so
No symbol table info available.
#6 0x00007ffff52ede6b in GG::GUIImpl::HandleMouseButtonRelease(unsigned int, GG::Pt const&, int) () from /home/user/SoftwareProjects/FO/build/libGiGi.so
No symbol table info available.
#7 0x00007ffff6d5a175 in GG::SDLGUI::HandleSystemEvents() () from /home/user/SoftwareProjects/FO/build/libGiGiSDL.so
No symbol table info available.
#8 0x0000000000480973 in HumanClientApp::HandleSystemEvents() ()
No symbol table info available.
#9 0x00007ffff52bdae9 in GG::ModalEventPump::operator()() () from /home/user/SoftwareProjects/FO/build/libGiGi.so
No symbol table info available.
#10 0x00007ffff6d56ce8 in GG::SDLGUI::Run() () from /home/user/SoftwareProjects/FO/build/libGiGiSDL.so
No symbol table info available.
#11 0x0000000000466872 in mainSetupAndRun() ()
No symbol table info available.
#12 0x0000000000460f26 in main ()
No symbol table info available.
```

**Comment by Voker57** [comment]
Yes, same for me. Save for reproducing: http://dump.bitcheese.net/files/cesybag/FreeOrion_Voker57_Voker57_0096_20170515_172400.mps

(Voker57 -- you, 5 AIs for the rest, start, declare war on L29Ah)

gcc version 6.3.0 20170510 (Debian 6.3.0-17)

**Comment by LGM-Doyle** [comment]
Thanks both for the testing.  Here is a second attempt.

If this PR also crashes could you then go to the `FleetWnd` and right click and scrap any ship and tell me if that also crashes?  If scrapping a ship also crashes then a backtrace would also be helpful.

**Comment by Voker57** [comment]
This one appears to work. Scrapping ships does not crash either.

**Comment by Vezzra** [comment]
Same here. No more crashes when proposing peace, and scrapping ships also works fine.

**Comment by Vezzra** [comment]
FYI: I think you can ignore the failed Travis CI test. That has just been the Xcode build stalling for unknown reasons. I can build and run the PR on OSX perfectly fine, just checked to be sure.

**Comment by LGM-Doyle** [comment]
@Vezzra, very timely save. Thanks.

**Pull request merged**
