### PR TITLE
Keep tech names when zooming out tech screen

### PR DESCRIPTION
**Pull request by TheSilentOne1**
but remove the text shadow when the text size becomes smaller then 10.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Seems OK, though not great looking, for about three or four zoom steps into the non-shadowed area, then it's illegible anyway...

**Comment by TheSilentOne1** [comment]
Maybe a minimum font size would make sense, I'll try that out.

**Comment by geoffthemedio** [comment]
It's a bit more complicated than that... currently it uses the same font size for all zooms, and just using GL scaling to do the actual zooming. This makes the zooms faster, as it doesn't need to recreate all the UI widgets when the zoom level changes and thus the font changes...

**Comment by TheSilentOne1** [comment]
Or we could just hide the whole techname panel altogether when zoomed out and just show the icons. When I have some time I'll look into that.

**Comment by TheSilentOne1** [comment]
Would look like this:
techtree zoomed out

**Comment by geoffthemedio** [comment]
Should connect the dependency lines to the right side of the icons.

**Comment by TheSilentOne1** [comment]
If you (/ the other main developers) are positive about the general idea I'll fine-tune it some more ofc.

**Comment by geoffthemedio** [comment]
Better to post on the forums for design issues, I think...

**Comment by TheSilentOne1** [comment]
Okay will do.

**Comment by MatGB** [comment]
Geoff's right, it's fairly easy to fix it with a half decent Git client, have a new master branch, cherry pick the needed commits in rebase and push, there's already been at least once where we lost work due to a bad merge and we decided to never have merge commits, the Rebase workflow is easier to manage anyway.

I'm about to log off but if this is ready to commit and no one else has fixed it I can sort the cherry picking and commit it tomorrow, I think we need a Git basics/howto thread for the way we're using it as there are so many different things that can go wrong but at it's essence it's incredibly powerful and fairly simple.

**Comment by TheSilentOne1** [comment]
@ Geoff: oh, ok. Thanks for pointing that out.
@MatGB: I wouldn't mind if you did ;) , but if you don't want to bother with it I will (try to) take care of it when I have some time, probably on the next weekend.

**Comment by MatGB** [comment]
What I was going to do was fetch your branch, then cherry pick just the commits we want into a rebased clean master branch then push that directly, it should be easy to do with a decent GUI (it's doable with command line but a PITA) and it's the workflow I've found best overall as it stops me making mistakes.

**Comment by MatGB** [comment]
You can also merge commits, which can be incredibly useful when you realise you've made a typo in a fairly big one, etc.

**Comment by Dilvish-fo** [comment]
> You can also merge commits,

just to be clear on nomenclature, I think you mean probably "squash" commits?

**Comment by MatGB** [comment]
PRobably, yes, I know I've done it, and I think I googled how to merge them but, well, yeah, there are so many things you can do with Git making sure to use the right term is important.

**Pull request closed without merging**
