### PR TITLE
Convert test-scripting/species/SP_ABADDONI.focs

### PR DESCRIPTION
**Pull request by o01eg**
Follows up #4250

Difference between dumps:
```diff
--- /tmp/1.log	2022-10-15 21:40:46.056539362 +0300
+++ /tmp/2.log	2022-10-15 21:41:11.452492628 +0300
@@ -178,7 +178,7 @@
             accountinglabel = "FOCUS_INDUSTRY_LABEL"
             priority = 98
             effects =
-                SetTargetIndustry value = Value + Target.Population * NamedReal name = "INDUSTRY_FOCUS_TARGET_INDUSTRY_PERPOP" value = 1.000000 * 0.200000
+                SetTargetIndustry value = Value + Target.Population * NamedReal name = "INDUSTRY_FOCUS_TARGET_INDUSTRY_PERPOP" value = 0.200000
         EffectsGroup // from SP_ABADDONI
             scope =
                 Source
@@ -389,7 +389,7 @@
             accountinglabel = "GREAT_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.500000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.500000 * abs(Value)
         EffectsGroup // from SP_ABADDONI
             scope =
                 Source
@@ -463,7 +463,7 @@
             accountinglabel = "UNINHABTIABLE_ENVIRONMENT_LABEL"
             priority = 30
             effects =
-                SetTargetPopulation value = -(999.000000)
+                SetTargetPopulation value = -999.000000
         EffectsGroup // from SP_ABADDONI
             scope =
                 Source
@@ -646,7 +646,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_INDUSTRY"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
@@ -659,7 +659,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_RESEARCH"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
@@ -672,7 +672,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_INFLUENCE"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
@@ -685,7 +685,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_STOCKPILE"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
@@ -976,7 +976,7 @@
                 ]
             priority = 500
             effects =
-                SetConstruction value = Value + min(max(Value(Target.TargetConstruction) - Value, -(1.000000)), 1.000000)
+                SetConstruction value = Value + min(max(Value(Target.TargetConstruction) - Value, -1.000000), 1.000000)
         EffectsGroup // from SP_ABADDONI
             scope =
                 Source
@@ -995,9 +995,9 @@
                 ]
             priority = 500
             effects = [
-                SetResearch value = Value + min(1.000000, max(0.000000, Value(Target.Happiness)) / 5.000000, max(min(-(1.000000), (Value(Target.TargetResearch) - Value) / 5.000000), Value(Target.TargetResearch) - Value))
-                SetIndustry value = Value + min(1.000000, max(0.000000, Value(Target.Happiness)) / 5.000000, max(min(-(1.000000), (Value(Target.TargetIndustry) - Value) / 5.000000), Value(Target.TargetIndustry) - Value))
-                SetInfluence value = Value + min(1.000000, max(min(-(1.000000), (Value(Target.TargetInfluence) - Value) / 5.000000), Value(Target.TargetInfluence) - Value))
+                SetResearch value = Value + min(1.000000, max(0.000000, Value(Target.Happiness)) / 5.000000, max(min(-1.000000, (Value(Target.TargetResearch) - Value) / 5.000000), Value(Target.TargetResearch) - Value))
+                SetIndustry value = Value + min(1.000000, max(0.000000, Value(Target.Happiness)) / 5.000000, max(min(-1.000000, (Value(Target.TargetIndustry) - Value) / 5.000000), Value(Target.TargetIndustry) - Value))
+                SetInfluence value = Value + min(1.000000, max(min(-1.000000, (Value(Target.TargetInfluence) - Value) / 5.000000), Value(Target.TargetInfluence) - Value))
             ]
         EffectsGroup // from SP_ABADDONI
             scope =
@@ -1006,9 +1006,9 @@
                 Ship
             priority = 500
             effects = [
-                SetResearch value = Value + min(max(Value(Target.TargetResearch) - Value, -(1.000000)), 1.000000)
-                SetIndustry value = Value + min(max(Value(Target.TargetIndustry) - Value, -(1.000000)), 1.000000)
-                SetInfluence value = Value + min(max(Value(Target.TargetInfluence) - Value, -(1.000000)), 1.000000)
+                SetResearch value = Value + min(max(Value(Target.TargetResearch) - Value, -1.000000), 1.000000)
+                SetIndustry value = Value + min(max(Value(Target.TargetIndustry) - Value, -1.000000), 1.000000)
+                SetInfluence value = Value + min(max(Value(Target.TargetInfluence) - Value, -1.000000), 1.000000)
             ]
         EffectsGroup // from SP_ABADDONI
             scope =
@@ -1336,7 +1336,7 @@
             accountinglabel = "CAPITAL_POOR_CONNECTION_LABEL"
             priority = 100
             effects =
-                SetTargetHappiness value = Value + max(-(5.000000), 5.000000 - Statistic Min value = (JumpsBetween) // StaticCast{i,d}
+                SetTargetHappiness value = Value + max(-5.000000, 5.000000 - Statistic Min value = (JumpsBetween) // StaticCast{i,d}
      condition = And [
     Or [
         Capital
@@ -1452,7 +1452,7 @@
             stackinggroup = "POPULATION_TROOPS_STACK"
             priority = 98
             effects =
-                SetMaxTroops value = Value + Target.Population * NamedReal name = "BASIC_DEFENSE_TROOPS_MAX_TROOPS_PERPOP" value = 1.000000 * 0.200000
+                SetMaxTroops value = Value + Target.Population * NamedReal name = "BASIC_DEFENSE_TROOPS_MAX_TROOPS_PERPOP" value = 0.200000
         EffectsGroup // from SP_ABADDONI
             scope =
                 Source
```

Not sure why Python changes arguments of equality operation but when I switch them still got value reference and int. If I add operator==(int, value_ref_wrapper<int>) it started to be preferred in value reference equal int case otherwise.

### CODE REVIEW

**Comment by o01eg** [comment]
It's ready but I'm not sure if it should go to 0.5.0 release

**Comment by geoffthemedio** [comment]
I thought you added something to wrap values before negation? Is it being removed / undone?
````
-                SetResearch value = Value + min(max(Value(Target.TargetResearch) - Value, -(1.000000)), 1.000000)
+                SetResearch value = Value + min(max(Value(Target.TargetResearch) - Value, -1.000000), 1.000000)
````

**Comment by o01eg** [comment]
@geoffthemedio No, I've added it to dump to see old FOCS parser wrap negative values and new Python FOCS parser doesn't. https://github.com/freeorion/freeorion/pull/4075

**Review by Vezzra — APPROVED** [review]
Since #4251 contains this and builds and runs ok on macOS, this PR should be ok on macOS too.

**Comment by o01eg** [comment]
Merged in https://github.com/freeorion/freeorion/pull/4251

**Pull request closed without merging**
