### PR TITLE
New graphics for asteroid hull line

### PR DESCRIPTION
**Pull request by Vezzra**
- New graphics for small, standard and heavy asteroid hulls
- Adjusted slot positions on design screen accordingly

### CODE REVIEW

**Comment by Vezzra** [comment]
Decided to put this PR up as a suggestion, so others can have a look at it. I'm wondering especially about the graphic I used for the heavy asteroid hull - IMO it should be a bit bigger. The difference in size to the standard asteroid hull doesn't seem to be quite sufficient... what do you guys think?

**Comment by Ouaz** [comment]
IMO, it's the standard asteroid hull that is too big. Its diameter should be between the small and the heavy asteroid hull. ^^

**Comment by Vezzra** [comment]
Unnamed provided a slightly scaled up version of the heavy asteroid hull graphics. The difference isn't that great, but it's still an improvement. If no one objects within the next hours, I'm going to merge this and cherry pick it to the release branch.

**Comment by MatGB** [comment]
No objection from me, I don't think there is a huge amount you can do to differentiate one large rock from another without getting silly, we can always fiddle at a later date if it's confusing.

**Comment by Vezzra** [comment]
That pretty much sums it up :smile: 

And it's definitely an improvement over the old graphics, so we can't do much wrong here :wink:

**Comment by Vezzra** [comment]
Ok, I'm going to merge this. As I will squash the commits and rebase the branch prior to merging, I'm closing this PR.

**Pull request closed without merging**
