### PR TITLE
Add snapcraft.yaml to enable snap build.

### PR DESCRIPTION
**Pull request by dargad**
Hi

This PR adds support for building a snap package of Freeorion. Snaps are cross distro Linux software packages. One snap can be installed on Ubuntu all supported LTS and non LTS releases from 14.04 onward. Additionally they can installed on Debian, Manjaro, Fedora, OpenSUSE and others. Making a snap of Freeorion enables you to provide automatic updates on your schedule to your users via the snap store.

If accepted, you can use snapcraft locally, a CI system such as travis or circle-ci, or our free build system (build.snapcraft.io) to create snaps and upload to the store (snapcraft.io/store).

To test this PR locally, I used an Ubuntu 16.04 VM, with the following steps.

    snap install snapcraft --classic
    git clone -b snapcraft https://github.com/dargad/freeorion
    cd freeorion
    snapcraft

Please note that snapcraft.yaml has been implemented in such a way it automatically picks up Freeorion version from a tag (when run on the `release-<vernum>` branch) and marks the snap as *stable*. It can be installed with:

    snap install --dangerous freeorion_amd64.snap

(the --dangerous is necessary because we’re installing an app which hasn’t gone through the snap store review process)

Once installed the command can be executed: `freeorion`

screenshot from 2018-12-07 10-01-25

If landed, you will need to:
* Register an account in the snap store https://snapcraft.io/account
* Register the 'freeorion' name in the store
```
snapcraft login
snapcraft register freeorion
```

* Upload a built snap to the store
```snapcraft push freeorion_amd64.snap --release edge```
* Test installing on a clean Ubuntu 16.04 machine:
```snap install freeorion --edge```

The store supports multiple risk levels as “channels” with the edge channel typically used to host the latest build from git master. Stable is where stable releases are pushed. Optionally beta and candidate channels can also be used if needed.

Once you are happy, you can push a stable release to the stable channel, update the store page, and promote the application online (we can help there).

### CODE REVIEW

**Comment by agrrr3** [comment]
@dargad i just built a feature branch using your yaml and a ubuntu/snapcraft container on an ubuntu host, copied the file over to my fedora box and installed there. Runs beautifully :) 

Checked the basics graphics, sounds, savegames, turn advancement, 154MB snap filesize, looks good.

@dargad  Checking the snapcraft docs i could not quite figure out - Is it possible to have/is there a  best practice for publishing such special feature preview builds?

It would be great if we could offer the player community an easy entry to get a glimpse of the future.

**Comment by dargad** [comment]
> @dargad i just built a feature branch using your yaml and a ubuntu/snapcraft container on an ubuntu host, copied the file over to my fedora box and installed there. Runs beautifully :)

Thanks for trying that out @agrrr3. I'm glad it worked fine for you.

> @dargad Checking the snapcraft docs i could not quite figure out - Is it possible to have/is there a best practice for publishing such special feature preview builds?

The snaps address this issue by the concept of channels. Channels are composited of three parts: `<track>/<risk>/<branch>`. You can use a combination of those to mark the release appropriately (and prevent users of the stable version of unintentionally updating to a feature-testing release).

Normally you want your stable releases to be available under the `stable` channel, while some highly experimental features may be released under `experimental/edge/particular-feature` (you can request extra tracks for your project [here](https://forum.snapcraft.io/c/store)). To install from a non-stable channel a user would have to explicitly request for it, e.g.

    snap install freeorion --channel experimental/edge/particular-feature

More information about channels: https://docs.snapcraft.io/channels/551.

**Comment by agrrr3** [comment]
hey guys, if nobody objects i would analyse this further and register/push to freeorion on snapcraft.io

i plan to push stable 4.8 and useful experimental branches from freeorion/freeorion (e.g. government). If thats smooth maybe a rolling freeorion/freeorion master and a development branch which merges multiple feature branches.
The stable and the rolling master could come from travis, but maybe in the next step?

i will also have a look if and how it is possible to layer another contents/FOCS dir ("default/") on top.

when testing works out we/i would announce on the forums the availability

**Comment by geoffthemedio** [comment]
Please do...

**Comment by Vezzra** [comment]
@dargad, sorry for responding only now, but currently RL issues leave me almost no time for FO.

As release manager responding to and handling this proposal and PR is technically my responsibility, but, as I said, I currently don't have the capacity to do this. However, I certainly have no objections if someone else decides to take over that task. Being able to provide FO builds on a release channel like snap would be a big improvement regarding the availability of FO releases on Linux (as it works across many distros).

So, @agrrr3, if you want to take over for now, please, by all means, go ahead. The major challenge I foresee is to continually maintain the snapcraft.yaml file and the FO snap builds/releases. If you want to shoulder that responsibility (at least for now), that would certainly be much appreciated.

Just keep me posted about your progress/findings and what needs to be decided. If you register a FO account with snapcraft, please provide me with the login credentials (preferably via PM on the forum). We have special "admin areas" where we store and maintain the login data for the various FO accounts (like on YouTube etc.).

**Comment by agrrr3** [comment]
I tried to reserve the 'freeorion' name in snapcraft.io but it sais it is reserved and i am not sure i could file my request correctly. For the moment i requested for testing 'freeorion-agrrr3'.
Will see next week if i need to escalate.

**Comment by agrrr3** [comment]
Just to let you people now, i could register 'freeorion' and publish 0.4.7 and the latest test build.

@Vezzra is it possible to tag the weekly release revisions with something like ' 2019-01-20.fffde88' ? I would need something like that to (semi-)automate test builds. ATM i have to adjust version and stability in the snapcraft.yaml manually.

**Comment by Cjkjvfnby** [comment]
Please add snap/README.MD with PR description (maybe exclude screenshots).  Instructions how to run the script should be in the same place as the script.

**Comment by Vezzra** [comment]
> is it possible to tag the weekly release revisions with something like ' 2019-01-20.fffde88' ?

Possible, yes, practical, not so much. If I tag the commit of every weekly test build (and I have thought of that because it would have some nice benefits), that would lead to a massive spam of tags.

It would wreak havoc especially with the repo's releases page, as each and every tag gets dispayed on the timeline there. Meaning, the releases page would become practically unusable.

**Comment by agrrr3** [comment]
> > is it possible to tag the weekly release revisions with something like ' 2019-01-20.fffde88' ?
>
> It would wreak havoc especially with the repo's releases page, as each and every tag gets dispayed on the timeline there. Meaning, the releases page would become practically unusable.

@Vezzra As far as i understand github, you can tag revisions (using the basic git functionality) without creating github releases

@Cjkjvfnby Hi, this PR is not the one which will be merged (as it is not mine), at the moment it is just a place to talk about the plans. Hmm. Maybe I should put up an implementation PR and crosslink.

**Comment by Vezzra** [comment]
@agrrr3,

> As far as i understand github, you can tag revisions (using the basic git functionality) without creating github releases 

That's correct, but if you go to the releases page, you'll notice that on the timeline not only releases are shown, but also other tags (see the "with-FreeOrionSDK-v*" entries). Now imagine what happens if we add a tag per week...

But even if there were no issues with the releases page, tagging each test release would soon result in a large amount of tags. That doesn't sound like a good idea to me...

**Comment by agrrr3** [comment]
@Vezzra i am not very concerned about the many tags issues, but i think a single 'weekly' tag could work as well. E.g. you would change it every week and i could pull and automatically build and publish on tuesdays. I would use the commit date of the revision for the 2019-01-29 portion and the revision for the revision portion when building/releasing. Or you could  annotate the tag with meta-information, but i dont think that is a good idea.

**Comment by Vezzra** [comment]
@agrrr3,

> i am not very concerned about the many tags issues

Well, I am...

> i think a single 'weekly' tag could work as well. E.g. you would change it every week...

Unfortunately that's not how it works. AFAIK I can't even rename a tag, much less move it to another commit or somesuch. All I can do is delete the old tag and make a new one every week. However, the problem is, as soon as I push a tag to upstream, everyone else can (and many will) pull that tag into their local copies.

When I delete the tag later, I can only push that deletion to upstream. But tag deletion does not get _pulled_, and if someone who has pulled the tag later pushes changes to upstream, depending on their settings, they push the tags in their local copy too, and the tags I deleted reappear.

I'm not talking theory here, but an actual issue. There are two ancient tags from years ago, when I tagged some intermediate builds of a release branch, which I later tried to delete. They continue to reappear, defying all my attempts of getting rid of them.

Which means, if I start tagging the weekly test builds, those tags *are* going to accumulate, and that's something I want to avoid...

**Comment by agrrr3** [comment]
@Vezzra how about a "weekly" branch instead of a tag then. you can force that to a new revision and branches are anyway intended to track changing revisions (as tags are rather for stable revisions).

**Comment by Vezzra** [comment]
So, basically an empty branch which I rebase on master each time I make the test builds... that could work. If that helps you with automating the creation of the snap build I guess that's something I can do...

**Comment by agrrr3** [comment]
:+1: Yes, i could detect changes of the branch revision and automate on that.

**Comment by Vezzra** [comment]
@agrrr3, I've created a branch "weekly-test-builds", which I will rebase onto the commit (usually master HEAD) which the latest test builds are based upon each time I make those test builds.

**Comment by agrrr3** [comment]
@Vezzra could you please update the weekly-test-builds branch to the current revision?

**Comment by Vezzra** [comment]
Oops, sorry, done.

Obviously I need to get used to do that... I'm getting old, forgetful and muddle-headed... :wink:

**Comment by agrrr3** [comment]
Ok, I have a snapcraft yaml for the weekly builds which works. I am not sure what the next steps for automation are as i do not have a public build server.

Also I would like to add collaborators to the freeorion snapcraft store. I am not sure what one needs to get access (I used an ubuntu one account), but I can add email addresses there. @geoffthemedio @Vezzra would you send me an email-address i should add for you (maybe as PM?). Who else should get access?

**Comment by Vezzra** [comment]
@agrrr3, I've tried to register an Ubuntu One account, but haven't been able to confirm my email address so far (the confirmation email hasn't made it into my inbox yet, dunno what takes so long). If I understand correctly, that confirmation is required before my email address can be used in the snapcraft store, so I guess we have to wait a bit...

The email address I used is the same one I use for the repo commits, so you can pick it from the commit log.

> Who else should get access?

@Dilvish-fo. He, Geoff and me are the project lead team, so to speak, so he should get access too.

**Comment by geoffthemedio** [comment]
Confirmation worked for me for the project gmail account.

**Comment by Vezzra** [comment]
Yep, have been able to confirm my Ubuntu One account now, and accepted the share snap invitation.

**Comment by Vezzra** [comment]
Can/should we merge this PR now...?

**Comment by geoffthemedio** [comment]
> Can/should we merge this PR now...?

I'd defer to @agrrr3 about that...

**Comment by agrrr3** [comment]
This PR does not reflect the current state of the yaml.

Anywat this can be merged in order to appreciate the initial work. I will
do a PR for the necessary changes.

**Comment by Vezzra** [comment]
> Anywat this can be merged in order to appreciate the initial work. I will do a PR for the necessary changes.

Ok.

**Pull request merged**
