### PR TITLE
String table editor

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR adds the capability to edit string tables via a web browser to the `check/st-tool.py` script.

This is a follow up to #2752

st-editor

### CODE REVIEW

**Comment by adrianbroher** [comment]
@geoffthemedio 
> For colourblind users, something other than just red and green colours to distinguish OK from malformed or bad entries could be helpful.

I've added status indicators to each entry, see screenshot.

**Comment by Oberlus** [comment]
So this is finished and can be merged? :dancing_men:

**Comment by adrianbroher** [comment]
> So this is finished and can be merged?

No, there is no way to save yet and I would like to pull the string tables right from github.  But feel free to test it out.

**Comment by adrianbroher** [comment]
@Oberlus the script can now provide the string table as a download.  Feel free to use and give some feedback on the usability.

**Comment by adrianbroher** [comment]
Added fixes to bugs and improvements given by @Oberlus within https://www.freeorion.org/forum/viewtopic.php?p=100492#p100492

**Comment by Oberlus** [comment]
> @Oberlus the script can now provide the string table as a download. Feel free to use and give some feedback on the usability.

I fetched this branch to my local. I have tried the script (st-tool.py). I'm pleased with the improved verbosity of help. I will continue with Spanish translation sometime this week and give more feedback.

I can't figure out how to use it for the editor capabilities commented in the OP ("edit stringtables via a web browser).

**Comment by adrianbroher** [comment]
@Oberlus 
> I can't figure out how to use it for the editor capabilities commented in the OP ("edit stringtables via a web browser).

Run `check/st-tool.py edit default/stringtables/en.txt default/stringtables/es.txt`, it will start a webserver and open a browser with the editor.

**Comment by Oberlus** [comment]
> Run `check/st-tool.py edit default/stringtables/en.txt default/stringtables/es.txt`, it will start a webserver and open a browser with the editor.

Gah! So I finally learnt how to fetch a PR for local testing (`git pull upstream pull/2844/head`). The st-tool I had didn't show the edit verb, now it does.
Testing.

**Comment by Oberlus** [comment]
Feedback:
My system browser is Firefox 75.0 (64 bits), in Ubuntu 18.04.

- Visualization of keys and values is great. It is much better than Meld in every sense.
- Meld fails sometimes to correctly match reference and source keys, this editor does it perfectly.
- It lacks the meld functionality of copying reference value into source. Once you get used to it, you first read both values, select and copy (the part of) the reference value, and then click on the source value and copy it in there. That's fine.
- Response time is slow: when clicking on a value to edit, it takes aprox. 1 second to open the edit box, another second for it to close after clicking Save. Not big deal, but it increases edition time (unimportant when editing long texts, cumbersome when editing short names).
- If you want to copy chunks of text from several places (say from another source value and from the reference value), each time you click on another value (reference or source) or change focus of the browser window, the source value you were editing will close without saving, so you must click save after each modification before going anywhere else. Coupled with the slow response times it can be cumbersome.

Exiting the editor is done via Ctrl+C in the shell (as documented in the help). Out of curiosity, I tried closing the web browser (all its tabs), but it didn't stop the shell job. All this is fine, but a way to exit it without dumping a traceback would be more visually clean.

Here is the output dumped into shell window:

```
freeorion$ ./check/st-tool.py edit default/stringtables/en.txt default/stringtables/es.txt 
127.0.0.1 - - [14/Apr/2020 09:57:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2020 09:57:14] "GET /jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2020 09:57:14] "GET /jeditable.jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2020 09:57:16] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2020 09:59:12] "POST /update HTTP/1.1" 200 -
[...]
127.0.0.1 - - [14/Apr/2020 10:29:18] "POST /update HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2020 10:29:38] "POST /save HTTP/1.1" 200 -

^CTraceback (most recent call last):
  File "./check/st-tool.py", line 991, in <module>
    sys.exit(args.action(args))
  File "./check/st-tool.py", line 797, in edit_action
    server.serve_forever()
  File "/usr/lib/python3.6/socketserver.py", line 236, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

**Comment by Oberlus** [comment]
A minor bug: when you edit a value that has special formatting (such as <u>Turn</u>), the formatting tags are removed.
To be more specific: when you write the tags and click save, they are saved, but will be lost next time you edit the value.

**Comment by Oberlus** [comment]
What's the status on this?
Can it be merged even if the issues commented in [here](https://github.com/freeorion/freeorion/pull/2844#issuecomment-613312995) have not been addressed?

**Comment by Oberlus** [comment]
@adrianbroher , I found another bug, and I consider this one a serious issue:

When I make a translation that includes references (or whatever it is the name), the editor replaces the references by their current value upon saving. Example for better understanding:

If I write this translation:

> BLD_NEUTRONIUM_EXTRACTOR_DESC
> '''Construida en una estrella [[STAR_NEUTRON]], provee al imperio de neutronio. El neutronio extraido en esta instalación es transportado a cuaquier [[buildingtype BLD_NEUTRONIUM_FORGE]] del imperio para la construcción de naves equipadas con piezas de neutronio, como el [[shippart AR_NEUTRONIUM_PLATE]].
> [[BUILDING_AVAILABLE_ON_OUTPOSTS]].'''

it gets saved as

> BLD_NEUTRONIUM_EXTRACTOR_DESC
> '''Construida en una estrella de neutrones, provee al imperio de neutronio. El neutronio extraido en esta instalación es transportado a cuaquier Forja de neutronio del imperio para la construcción de naves equipadas con piezas de neutronio, como el Blindaje de neutronio.
> Este edificio puede ser construido en un puesto de avanzada.'''

This is an obvious problem because when the translator updates the values of the references the changes are not reflected in other values that were intended to reference them.

**Comment by adrianbroher** [comment]
I cannot confirm this behaviour.

When I save the string table only the string I've appended was, well appended.   The refs were not substituted.

Before:

> SD_SCOUT_DESC
> Barata y pequeña nave desarmada para reconocimiento y exploración. Further research aimed at improving [[metertype METER_DETECTION]] would allow for better designs.

After appending ` test` to the `SD_SCOUT_DESC` entry:

> SD_SCOUT_DESC
> Barata y pequeña nave desarmada para reconocimiento y exploración. Further research aimed at improving [[metertype METER_DETECTION]] would allow for better designs. test

**Comment by Oberlus** [comment]
@adrianbroher What web browser are you using for this (just in case it is relevant).

> I cannot confirm this behaviour.

I don't know what I was doing, but I can not replicate it anymore. I mean, it works fine now (and I have not changed anything in the branch I'm using for the translations).

Another bug: HTML tags are treated as they should be interpreted by the browser, and are removed upon edition. Examples:
- When translating ENVIRONMENT_TEXT, `</img>` becomes a broken image link upon save (i.e. I see in the editor the browser's default icon for image not found). Editing it again will remove that line.
- When translating SAVE_TIME_TITLE, `<u>Tiempo</u>` is shown as `Tiempo` (underlined) upon save. Editing it again will remove the tags and will show `Tiempo` (not underlined).
- When translating PASSED and FAILED, `<rgba 0 255 0 255>(cumplido)</rgba>` becomes `(cumplido)` (no special effect) upon save. Editing it will remove the tags.

**Comment by adrianbroher** [comment]
> Another bug: HTML tags are treated as they should be interpreted by the browser, and are removed upon edition. Examples:

I see, I probably forgot to escape the characters for HTML consumption, I will take a look at it.

**Comment by adrianbroher** [comment]
@Oberlus fixed in the latest commit.

**Comment by geoffthemedio** [comment]
Any other issues or should this be merged after a rebase?

**Comment by Oberlus** [comment]
> Any other issues or should this be merged after a rebase?

There are some nuissances commented here: https://github.com/freeorion/freeorion/pull/2844#issuecomment-613312995
But they could be polished (if even possible) in a follow up PR. Meanwhile having this merged would come handy. The tool is undoubtly a great addition.

**Comment by adrianbroher** [comment]
I will look into the suggestions, but I cannot promise that those can be tackled without introducing dependencies (which I will not do).

**Comment by adrianbroher** [comment]
Updated the javascript. The response time feel like it has improved significantly (in trade for backwards compatibility with older browsers), but I didn't do any before/after profiling.

I didn't have the time to tackle the other suggestions.

**Comment by Oberlus** [comment]
> Updated the javascript. The response time feel like it has improved significantly (in trade for backwards compatibility with older browsers), but I didn't do any before/after profiling.

I'll find to try this tomorrow.
If it works with Firefox, for me it will more than enough to merge it.

**Comment by geoffthemedio** [comment]
> ...it will more than enough to merge it.

please post your conclusion when it's available...

**Comment by Oberlus** [comment]
I pulled this PR into a new branch created from current master.
I tested all the st-tool verbs again, in the process of resync and reformat the ES stringtable.
The improvement on edit speed is modest. I would say that opening a key to edit or saving it took ~1 second before and maybe ~0.8 seconds now.
Even if there was no acceleration, the problem could be with my editor, and in any case the tool is helpful as is, and certainly handy to have in the master branch instead of as PR that once has to pull. I'd like it merged as is. Users could open issues if they find it too slow or any other problem.

Also, it would be great to clearly announce the addition of the tool, because it can certainly encourage casual players to contribute with small (or big) translations.

**Pull request merged**
