### PR TITLE
Fix division by zero when AI has researched everything

### PR DESCRIPTION
**Pull request by Grummel7**

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
Could you rebase it on master? 

Changes looks good.

**Comment by Vezzra** [comment]
@Grummel7, are you still there...?

**Comment by geoffthemedio** [comment]
> Could you rebase it on master?

This pull request is tagged for v0.5.0.1 and is requesting to pull into the v0.5 release branch.

@Cjkjvfnby Do you want a separate pull request for master?

**Comment by Vezzra** [comment]
Ok, this fix is important and should go in - after all, the AI should not break after it has researched everything.

However, looking at the diff I see changes to workflow files and cmake scripts which do not seem relevant to the issue. Only the changes to `ResourcesAI.py` seem to be. At least to me, but maybe I'm missing something?

Otherwise I wonder if those other changes accidentally slipped in. In which case this PR needs to get cleaned up before we can merge it (and finally proceed with the bugfix release).

If @Grummel7 isn't available, can anyone else take over and look into this PR?

**Comment by Vezzra** [comment]
@Grummel7, is/was the issue also present in master, and if yes, has the fix also been applied there?

**Pull request merged**
