### PR TITLE
Track winning/losing

### PR DESCRIPTION
**Pull request by wheals**
This PR finally adds a congratulatory SitRep for defeating all of your opponents! It also adds a sitrep when an empire loses, and adds icons on the empire window that show if an empire has lost or won.

The first commit removes a lot of old code. Perhaps it should have been kept around, but as it was never called (referenced only in commented-out code) and it looked pretty buggy to me anyway, I think it would be better to reimplement it if we want to e.g. have a separate popup for when you win, or send information to dead AIs that they don't have to do any calculations, if that helps performance.

A note for scripters: the Victory effect now issues its own sitrep, so you don't have to use the GenerateSitRepMessage effect as well.

### CODE REVIEW

**Comment by Vezzra** [comment]
How do you determine if a specific empire has been completely defeated? IIRC Geoff wants to retain the possibility to bring back an already wiped out empire (e.g. by being able to still gift ships/planets to it)...

Otherwise, looks good!

**Comment by wheals** [comment]
Right now it checks at the beginning of each turn whether the empire has no ships and no planets, and if so sets a bool on the empire that marks it as eliminated (and makes a sitrep message). To implement bringing back the empire, you'd have to check whether it had already been eliminated when you give it the object, and if so flip the bool back to false, but besides that there'd be no special code necessary.

**Comment by MatGB** [comment]
I love this idea, not just because scripting a sitrep without backend changes was beyond my abilities but also because it's long annoyed me that the AI clients take up system resources way past they're dead (and sometimes generate error messages, etc). Having them turned off but easily turned on again is a good solution.

40 files changed is a lot to go through, does this change the existing Experimentor & Transcendance sitreps? It'd be good to be standardised if possible.

**Comment by wheals** [comment]
Yes it does, see the changes to default/{buildings,techs}.txt. Also, I should note that this doesn't actually suspend AIs once they lose, but it should be relatively easy to implement now.

**Comment by MatGB** [comment]
Yeah, I found it by going through the individual commits, looks easier to use and I always like things that makes scripting easier.

I have noticed a potential problem with Experimentors that was caused by me, I'm going to test it though ;-)

**Comment by geoffthemedio** [comment]
Can you rebase?

**Comment by wheals** [comment]
Done.

**Pull request merged**
