### PR TITLE
Add some hotkeys

### PR DESCRIPTION
**Pull request by vincele**
Add CTRL-q  shortcut to exit to desktop
Add F4 shortcut to quit current game to IntroScreen
Add F5 shortcut to toggle fullscreen

Signed-off-by: Vincent Legoll vincent.legoll@gmail.com

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Without any confirmation dialog, I don't think there should be an instant quit command, to desktop or the intro screen. Particularly not if it's a single keypress with no modkey.

Fullscreen toggle should, I think, default to Alt + Enter.

**Comment by vincele** [comment]
I think CTRL-q is OK as-is, at least for linux users that already use this one for other applications...

I'm fine with the windows ALT-ENTER for toggle fullscreen, but what do you want for quit to introscreen ?

**Comment by geoffthemedio** [comment]
As above, "I don't think there should be an instant quit command"

**Comment by vincele** [comment]
Do you speak of the 2 instant quits or only the one with no modifier key ?
Does that mean you'll be OK with a hotkey with no default key binding, or do you want me to remove it from the PR ?
Do you mean there ought to be a "are you sure" confirmation window for those instant quits commands ?

Please be specific, just tell exactly what is it you want.
It looks like I'm being dense today...

**Comment by geoffthemedio** [comment]
There should not be a default-set hotkey to instant quit without a confirmation dialog. Doesn't matter if it has a modkey.

You can leave the quit commands in, as long as they are without default key bindings.

Later, if confirmation dialogs are added, a default key binding can also be set.

**Comment by vincele** [comment]
Thanks a lot for the clarification.

I'll do that as a first step: let the commands in but unbound, then see if I can manage to add the confirmation dialog.

**Comment by Dilvish-fo** [comment]
yes, vincele, for now please just get it in with no bindings, and then have a totally different PR (which we could put off until after 0.4.5) for the confirmation dialog.

**Comment by vincele** [comment]
And for fullscreen toggle: GG::GGK_RETURN, GG::GGK_LALT is OK for you ?

I don't know if there's a way to allow both LALT & RALT to work at the same time, and even then, french keyboards have ALT-GR (GGK_MODE) instead of RALT, so maybe LALT-only is OK...

**Comment by geoffthemedio** [comment]
MOD_KEY_ALT works for both alt keys. GGK enums are not ModKey enums.

**Comment by vincele** [comment]
Merged in another PR

**Pull request closed without merging**
