### PR TITLE
Add missing parenthese to upkeep.macros

### PR DESCRIPTION
**Pull request by alleryn**
There is this big libpython.py file here.... I think i did something wrong :/

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Yes; please remove the extra file from the commit.

**Comment by agrrr3** [comment]
Corresponding issue: #2558

**Comment by alleryn** [comment]
Two questions:
1. Is it ok to just close this PR and open a new one?
2. Is it ok to edit libpython.py into git.ignore or what is the best way to remove the file from the commit?  (Alternative question: did i do something wrong when building the FreeOrion SDK that this file appeared in the first place?)

**Comment by TheSilentOne1** [comment]
1: Make another commit that removes libpython.py, then squash the commits (git rebase -i HEAD~2) and force-push the new commit here. That should be the proper way to do it.

**Comment by alleryn** [comment]
Edit: Ok got it, i think.  Needed to use rm instead of remove. /Edit

> Make another commit that removes libpython.py

I don't know how to do this.

I tried `git remove libpython.py` but it said git remove is not a command

**Comment by alleryn** [comment]
Well i tried some stuff.... Not sure if i did it right.

**Comment by geoffthemedio** [comment]
The extra file is still there and now you have merge commits in the pull request, which also prevent it being accepted.

It's a small change, so maybe just reset and start over?

**Comment by alleryn** [comment]
Okay, yes i'll reset and start over.  Sorry about that.

**Comment by geoffthemedio** [comment]
Superceded by #2561

**Pull request closed without merging**
