### PR TITLE
make encyclopedia detail panel of production screen closable

### PR DESCRIPTION
**Pull request by TheSilentOne1**
- toggle visibility of pedia by clicking pedia icon on the toolbar

### CODE REVIEW

**Comment by Vezzra** [comment]
Builds and runs fine on OSX. However, I get these errors at the beginning of freeorion.log (didn't get those before, still not sure if they are related to your PR though):

```
2016-01-23 18:57:08.901113 [debug] Client : Logger initialized
2016-01-23 18:57:08.901320 [debug] Client : v0.4.5+ pr-454 [build 2016-01-23.616add0] Xcode 0640
2016-01-23 18:57:08.901360 [debug] Client : GL Version String: 2.1 ATI-1.32.25
2016-01-23 18:57:08.901918 [debug] Client : Dependency versions from headers:
2016-01-23 18:57:08.901940 [debug] Client : Boost: 1_56
2016-01-23 18:57:08.901953 [debug] Client : FreeType: 2.3.11
2016-01-23 18:57:08.901964 [debug] Client : PNG: 1.5.12
2016-01-23 18:57:08.901975 [debug] Client : Python: 2.7.6
2016-01-23 18:57:08.901987 [debug] Client : SDL: 2.0.3
2016-01-23 18:57:08.901998 [debug] Client : zlib: 1.2.7
2016-01-23 18:57:08.950334 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.messages" has not been initialized.
2016-01-23 18:57:09.004825 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.player-list" has not been initialized.
2016-01-23 18:57:09.006105 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.messages" has not been initialized.
2016-01-23 18:57:09.006313 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.player-list" has not been initialized.
2016-01-23 18:57:09.074611 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.sidepanel" has not been initialized.
2016-01-23 18:57:09.275252 [debug] Client : OpenAL initialized. Version 1.1Renderer SoftwareVendor Apple Computer Inc.
Extensions: AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE AL_EXT_float32 AL_EXT_STATIC_BUFFER AL_EXT_SOURCE_NOTIFICATIONS AL_EXT_SOURCE_SPATIALIZATION

2016-01-23 18:57:09.275767 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.sidepanel" has not been initialized.
2016-01-23 18:57:09.275803 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.sidepanel" has not been initialized.
2016-01-23 18:57:09.276109 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.sitrep" has not been initialized.
2016-01-23 18:57:09.276772 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.sitrep" has not been initialized.
2016-01-23 18:57:09.276799 [debug] Client : SitRepPanel::Update()
2016-01-23 18:57:09.277182 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.pedia" has not been initialized.
2016-01-23 18:57:09.451628 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.object-list" has not been initialized.
2016-01-23 18:57:09.452447 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.object-list" has not been initialized.
2016-01-23 18:57:09.452885 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.moderator" has not been initialized.
2016-01-23 18:57:09.522794 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.combat-report" has not been initialized.
2016-01-23 18:57:09.523879 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.sidepanel" has not been initialized.
2016-01-23 18:57:09.523918 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.sitrep" has not been initialized.
2016-01-23 18:57:09.523939 [debug] Client : SitRepPanel::Update()
2016-01-23 18:57:09.524057 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.pedia" has not been initialized.
2016-01-23 18:57:09.532756 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.object-list" has not been initialized.
2016-01-23 18:57:09.532906 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.moderator" has not been initialized.
2016-01-23 18:57:09.532950 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "map.combat-report" has not been initialized.
2016-01-23 18:57:09.631190 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "research.pedia" has not been initialized.
2016-01-23 18:57:09.632552 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "research.tech-controls" has not been initialized.
2016-01-23 18:57:09.634077 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "research.tech-controls" has not been initialized.
2016-01-23 18:57:09.634108 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "research.tech-controls" has not been initialized.
2016-01-23 18:57:09.634150 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "research.pedia" has not been initialized.
2016-01-23 18:57:09.634461 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "research.tech-controls" has not been initialized.
2016-01-23 18:57:09.634505 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "research.tech-controls" has not been initialized.
2016-01-23 18:57:09.657729 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.pedia" has not been initialized.
2016-01-23 18:57:09.660137 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.sidepanel" has not been initialized.
2016-01-23 18:57:09.661069 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.sidepanel" has not been initialized.
2016-01-23 18:57:09.661122 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.sidepanel" has not been initialized.
2016-01-23 18:57:09.661472 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.selector" has not been initialized.
2016-01-23 18:57:09.662632 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.pedia" has not been initialized.
2016-01-23 18:57:09.663148 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.sidepanel" has not been initialized.
2016-01-23 18:57:09.663201 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "production.selector" has not been initialized.
2016-01-23 18:57:09.679724 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.pedia" has not been initialized.
2016-01-23 18:57:09.681385 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.main-panel" has not been initialized.
2016-01-23 18:57:09.682622 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.part-palette" has not been initialized.
2016-01-23 18:57:10.273887 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.base-selector" has not been initialized.
2016-01-23 18:57:10.275134 [debug] Client : BasesListBox::Populate
2016-01-23 18:57:10.275159 [debug] Client : BasesListBox::PopulateWithSavedDesigns
2016-01-23 18:57:10.275481 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.pedia" has not been initialized.
2016-01-23 18:57:10.275752 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.main-panel" has not been initialized.
2016-01-23 18:57:10.275805 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.part-palette" has not been initialized.
2016-01-23 18:57:10.351511 [error] Client : CUIWnd.cpp:636 : CUIWnd::SaveOptions() : "design.base-selector" has not been initialized.
2016-01-23 18:57:10.351854 [debug] Client : DesignWnd::MainPanel::ReregisterDesigns
2016-01-23 18:57:10.489231 [debug] Client : Limited FPS to 60
2016-01-23 18:57:10.490280 [debug] Client : OpenGL Version Number: 2.1
2016-01-23 18:57:10.491756 [debug] Client : (HumanClientFSM) IntroMenu
...
```

**Comment by Vezzra** [comment]
Builds and runs fine on Linux (Ubuntu 15.10) too, but getting the same error messages in freeorion.log as on OSX.

**Comment by TheSilentOne1** [comment]
My bad. These "error messages" come from my previous commit, when I was looking for the reason why the production info panel and the production selector positions were not being saved. They can be safely ignored. Will fix this tomorrow.

**Comment by Vezzra** [comment]
Anymore testing required? Anything preventing this from getting merged?

**Comment by TheSilentOne1** [comment]
Not from my side -
@geoffthemedio okay for you?

**Comment by Vezzra** [comment]
Well, @geoffthemedio seems to have no more objections... I guess it's time to merge this, before it gets too far behind current master and you've to resolve arising conflicts.

**Comment by Vezzra** [comment]
Oh, and can you fix those error messages in the log? They still pop up, and not only with this PR...

**Pull request merged**
