### PR TITLE
Change various enum parser singletons into passed parameters.

### PR DESCRIPTION
**Pull request by LGM-Doyle**

### CODE REVIEW

**Comment by LGM-Doyle** [comment]
Part of #1808

**Comment by Vezzra** [comment]
Hm, @LGM-Doyle, how do you suggest to tag this? As "superseded" by #1808, as "merged" (as part of #1808 once that's merged)?

**Comment by geoffthemedio** [comment]
Superseded seems appropriate

**Comment by Vezzra** [comment]
Ok, tagged this, #1801, #1802 and #1803 as "superseded".

**Comment by LGM-Doyle** [comment]
I would have used merged since the PR is now part of master.  Superseded is fine, since visitors will see that #1808 contains this PR and was merged.

**Pull request closed without merging**
