### PR TITLE
Xenophobic Selfsustaining Population Malus depend on distance to alien planet

### PR DESCRIPTION
**Pull request by agrrr3**
2parts

1)
exclude LOW_BRAINPOWER species (exobot and ancient guardians) from causing xenophobic headaches

2)
For trith, the solution accumulates malus for each planet with sentient population based on the distance
• 4 jumps: -0.2 * xenophobic planet habitable size
• 3 jumps: -0.4 * xenophobic planet habitable size
• 2 jumps: -0.6 * xenophobic planet habitable size
• 1 jumps: -0.8 * xenophobic planet habitable size
• In same system: -1.0 *  per xenophobic planet habitable size
Note the malus worst case gets cut to reducing the self-sustaining pop boost to zero. So Trith are never worse than a normal species without growth specials in this regard.

Original discussion here:
https://www.freeorion.org/forum/viewtopic.php?p=115032&sid=d355dbb01d082df7767c280468f08fb3#p115032

@freeorion/ai-team anything necessary to change in AI?

### CODE REVIEW

**Comment by Oberlus** [comment]
While you are at it, could you make Ancient Guardians not to count for the malus?

**Comment by agrrr3** [comment]
> While you are at it, could you make Ancient Guardians not to count for the malus?

already implemented, was disrupted before commit/check in... coming right up...

**Comment by o01eg** [comment]
Is it for 0.5 release or master?

**Comment by agrrr3** [comment]
meh, i see some implementation issues...

**Comment by agrrr3** [comment]
this needs to be tested, i try to prioritize

@o01eg @Vezzra after feedback from the forums: this is for 0.5 as well

**Comment by agrrr3** [comment]
ok, i playtested for distances 1 and 2 and 3;with/without other Trith in range;with/without ancient guardians in range. 
ok to merge from my side.

**Comment by Vezzra** [comment]
> after feedback from the forums: this is for 0.5 as well

Ok

**Pull request merged**
