### PR TITLE
[AI] Refactor interactive shell to easy add new local variables

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This PR should be merged via squash and rebase.

interactive_shell_example

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Any Python people care to have a look / comment / merge?

**Comment by Cjkjvfnby** [comment]
> Any Python people care to have a look / comment / merge?

All of them busy or absent :(

**Comment by Morlic-fo** [comment]
Will test this weekend

**Comment by geoffthemedio** [comment]
Test plans changed or delayed?

**Pull request merged**
