### PR TITLE
[AI] Change shipDesign.name to property

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Change `shipDesign.name` to property:
- add hack in python to override c++ behavior
- update all usages
- replace translated name in logs to inner name

This code works and can be merged. 

Next step (I need help with it):
- change c++ wrapper: `shipDesign.name` and `shipDesign.description`(not used) should be changed to properties
- revert changes  for `extend_free_orion_AI_interface.py`

### CODE REVIEW

**Comment by Vezzra** [comment]
Ok, I have changed the Python bindings for ShipDesign::Name and ShipDesign::Description: 8d6d78dc712b43fa0823bd6875c4cf01706bf622. I've branched off this PR and pushed the commit to [my fork](https://github.com/Vezzra/freeorion/tree/python-bindings-shipdesign).

I've noticed that you granted me push access to your fork, so I could push my commit to your branch. Do you want me to do that? Otherwise you can just pull it in from my fork.

I haven't touched `extend_free_orion_AI_interface.py`.

Do you need any further assistance from me?

**Comment by Cjkjvfnby** [comment]
You can remove `get_name` from c++ api and all changes from `extend_free_orion_AI_interface.py` and merge it to master.

**Comment by Vezzra** [comment]
Just to be sure: you mean, apply those changes to your PR branch (that is, push them to the branch in your fork) and then merge the PR, right?

I'd rather not remove the `get_name` binding, keeping the ability to get the translated name seems important to me. For one, all those wrappers are going to be part of the common Python interface, that means, also be used for the server (where there might be use cases in the future).

And then the AI is going to need functions like that once exchange of diplomatic messages get implemented. I'd want the AI to use the translated name if it offers 10 "Hammerhead" class warships in a trade, instead of using a internal key name like "SD_HAMMERHEAD"...

**Comment by geoffthemedio** [comment]
Ideally, chat messages, AI or otherwise, would support display-side stringtable lookup with some pedia-like markup. Something like

```
<userstring>SD_HAMMERHEAD</userstring>
```

or

```
[[SD_HAMMERHEAD]]
```

inserted into a chat message would trigger replacement by the corresponding stringtable entry.

**Comment by Vezzra** [comment]
Yep, you're right of course. Hm, thinking more about it, @Cjkjvfnby is probably right - the AI scripts will very rarely, if ever, have any use for the translated name/description strings, so it's better to reduce unnecessary clutter in the interface and remove the `get_name` and `get_description` bindings. And for the rare case that the translation should be needed, the `userString` function should be sufficient.

@Cjkjvfnby, I'm going to incorporate the changes you proposed, squash commits, rebase, push to the branch in your fork and then merge.

**Comment by Cjkjvfnby** [comment]
@Vezzra, Thank you. 

PS. Github allow to delete branch after merge if user have permission. I think It will be good practice to do it.

**Comment by Vezzra** [comment]
Yes, I know, although I usually do that using my GUI git client.

Anyway, in this case I left it to you because it's your fork/branch, and I wasn't completely sure if you wanted me to delete the branch myself.

**Comment by Cjkjvfnby** [comment]
For person who merge it is one additional click, for owner a little more.  In 99% cases deleting is what owner expected.

**Comment by Vezzra** [comment]
Ack.

**Comment by geoffthemedio** [comment]
[[SD_HAMMERHEAD]] style substitutions in chat messages now happen

https://github.com/freeorion/freeorion/commit/eadcd6113160a203ee1404d7730ceb8923ace457

**Comment by Vezzra** [comment]
Excellent :smiley:

**Pull request merged**
