### PR TITLE
Other Tweaks

### PR DESCRIPTION
**Pull request by geoffthemedio**
...

### CODE REVIEW

**Comment by o01eg** [comment]
Catch assertion in gdb: 

```
freeorion: /home/oleg/devel/freeorion/UI/TechTreeLayout.cpp:266: TechTreeLayout::Node::Node(std::string, GG::X, GG::Y): Assertion `width > GG::X0 && height > GG::Y0 && GetTech(tech)' failed.

Thread 1 "freeorion" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: Нет такого файла или каталога.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff30a815f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff305a472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff30444b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff30443d5 in __assert_fail_base (fmt=0x7ffff31b8dc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x5555565220c8 "width > GG::X0 && height > GG::Y0 && GetTech(tech)", file=file@entry=0x555556521ee0 "/home/oleg/devel/freeorion/UI/TechTreeLayout.cpp", 
    line=line@entry=266, function=function@entry=0x555556522178 "TechTreeLayout::Node::Node(std::string, GG::X, GG::Y)") at ./assert/assert.c:92
#5  0x00007ffff30533a2 in __assert_fail (assertion=0x5555565220c8 "width > GG::X0 && height > GG::Y0 && GetTech(tech)", 
    file=0x555556521ee0 "/home/oleg/devel/freeorion/UI/TechTreeLayout.cpp", line=266, function=0x555556522178 "TechTreeLayout::Node::Node(std::string, GG::X, GG::Y)")
    at ./assert/assert.c:101
#6  0x00005555561a7963 in TechTreeLayout::Node::Node (this=0x555557a539f0, tech="", width=(unknown: 0x260), height=(unknown: 0x60)) at /home/oleg/devel/freeorion/UI/TechTreeLayout.cpp:266
#7  0x00005555561a7234 in TechTreeLayout::AddNode (this=0x5555570aa3c8, tech="CON_ASYMP_MATS", width=(unknown: 0x260), height=(unknown: 0x60))
    at /home/oleg/devel/freeorion/UI/TechTreeLayout.cpp:218
#8  0x00005555561bea3d in TechTreeWnd::LayoutPanel::Layout (this=0x5555570aa180, keep_position=false) at /home/oleg/devel/freeorion/UI/TechTreeWnd.cpp:1366
#9  0x00005555561bd7e3 in TechTreeWnd::LayoutPanel::Reset (this=0x5555570aa180) at /home/oleg/devel/freeorion/UI/TechTreeWnd.cpp:1229
#10 0x00005555561c606d in TechTreeWnd::Reset (this=0x7fffbccd01b0) at /home/oleg/devel/freeorion/UI/TechTreeWnd.cpp:2098
#11 0x00005555560c1ba5 in ResearchWnd::Reset (this=0x5555579c2610, context=...) at /home/oleg/devel/freeorion/UI/ResearchWnd.cpp:500
#12 0x0000555555d7f296 in MapWnd::InitTurn (this=0x555557928e50, context=...) at /home/oleg/devel/freeorion/UI/MapWnd.cpp:2981
#13 0x000055555586d483 in PlayingTurn::PlayingTurn (this=0x555557f88470, ctx=...) at /home/oleg/devel/freeorion/client/human/HumanClientFSM.cpp:1167
(gdb) l
261	TechTreeLayout::Node::Node(std::string tech, GG::X width, GG::Y height) :
262	    weight(NODE_CELL_HEIGHT),
263	    tech_name(std::move(tech)),
264	    m_width(Value(width)),
265	    m_height(Value(height))
266	{ assert(width > GG::X0 && height > GG::Y0 && GetTech(tech)); }
```

I suppose assertion should check `tech_name` here.

**Comment by o01eg** [comment]
Still broken even in Release build:

Снимок экрана_2024-01-31_08-47-22

**Comment by agrrr3** [comment]
some playtesting feedback
I took super-testers (so super-stealthed ships) and blockaded some systems; this would not be triggering combat by wandering medium krill swarm and also not by aggressive enemy fleet with mass drivers. Switching to aggressive stance triggered combat.
Actually there is a system where i blockade and there is a medium krill swarm and an empire ship and still no combat is triggered (the empire could not see the krill swarm, but the krill swarm should see the empire ship). When a kraken arrived, finally combat ensued.

**Comment by geoffthemedio** [comment]
> some playtesting feedback

Not clear if you're saying it's working correctly or incorrectly...

**Comment by agrrr3** [comment]
Not working for the purpose of triggering combat. I did not change the default setting (2) for Stealthy Blockader Visibility - not sure if that is full visibility. 
I did not do multiplayer so I could not see directly if the enemy empire could see me. Also I am not sure if stealthy blockader visibility works for monsters.

**Comment by geoffthemedio** [comment]
I just ran a test in a multiplayer game, where one empire's stealthy fleet was obstructive blockading and another empire's aggressive fleet tried to move through the system. The result was combat...
Premovement:
blockade combat pre
After combat:
blockade combat post

That is one of the two specific scenarios that needed to be addressed, I thought.

The other is when the moving fleet is not aggressive, in which case previous tests showed that it's working now, with the fleet being stopped by the stealthy blockader, and the blockader is revealed to the moving/blockaded fleet's empire.

[hidden blockade test mp save.zip](https://github.com/freeorion/freeorion/files/14123512/hidden.blockade.test.mp.save.zip)

**Comment by geoffthemedio** [comment]
> Still broken even in Release build:

It looks like the image block factory map is missing... Can you run with
````
 GG/src/RichText/RichText.cpp | 14 +++++++++++++-
 1 file changed, 13 insertions(+), 1 deletion(-)

diff --git a/GG/src/RichText/RichText.cpp b/GG/src/RichText/RichText.cpp
index 10676b67a..8875b679b 100644
--- a/GG/src/RichText/RichText.cpp
+++ b/GG/src/RichText/RichText.cpp
@@ -158,7 +158,19 @@ public:
 
     // Set the mapping from tags to factories that should be used to generate blocks from them.
     void SetBlockFactoryMap(RichText::BlockFactoryMap block_factory_map) noexcept
-    { m_block_factory_map = std::move(block_factory_map); }
+    {
+        m_block_factory_map = std::move(block_factory_map);
+        std::cout << "Set RichText BlockFactoryMap with tags "
+                  << [this]() {
+                        std::string retval = std::string{"("}
+                            .append(std::to_string(m_block_factory_map.size()))
+                            .append("): ");
+                        for (auto& [tag, fac] : m_block_factory_map)
+                            retval.append(tag).append(" ");
+                        return retval;
+                     }()
+                  << std::endl;
+    }
 
 private:
     // Parses content into tags.
````

And report what it shows on the console when trying to view a planet species suitability report? Should be a bunch of `Set RichText BlockFactoryMap with tags (2): img GG_RICH_PLAIN`

**Comment by o01eg** [comment]
I catch my issues in 2024-01-30.0dd6806 weekly test build so I suppose this PR has nothing to do with it.

**Comment by geoffthemedio** [comment]
> the default setting (2) for Stealthy Blockader Visibility - not sure if that is full visibility.

0 = no visibility -> when being blockaded, nothing extra gets revealed, not even that the blockader is present
1 = basic visibility -> just the presence of the ship/fleet is revealed
2 = partial visibility -> standard visibility when detecting stuff by having stronger detection than its stealth
3 = full visibility -> all info about an object, as if you owned it

**Comment by agrrr3** [comment]
> I just ran a test in a multiplayer game, where one empire's stealthy fleet was obstructive blockading and another empire's aggressive fleet tried to move through the system. The result was combat... 

can confirm with your multiplayer game and my fedora build. The stats are shown as zeroes, but it is working as intended. Will upload my single player where it did not work.

> 
> That is one of the two specific scenarios that needed to be addressed, I thought.

yes, that is good and exactly the scenario i meant

> 
> The other is when the moving fleet is not aggressive, in which case previous tests showed that it's working now, with the fleet being stopped by the stealthy blockader, and the blockader is revealed to the moving/blockaded fleet's empire.

did not check yet. 

but there is another issue: the stealhted ships are not stealthed in combat anymore - those are visible starting in first bout.

**Comment by geoffthemedio** [comment]
> but there is another issue: the stealhted ships are not stealthed in combat anymore - those are visible starting in first bout.

Do you mean the ships in the blockading fleet? They are revealed due to being part of a blockade, and so are visible.

I suppose it would be reasonable to do an extra check to only reveal ships involved in a blockade if there are not any armed visible ships in the fleet. The first implementation specifically didn't do any logic to decide which ships to reveal, but at least it would probably be reasaonable to only reveal ships if necessary to reveal something to enforce the blockade...

It could also just reveal the fleet, but not any of the ships, but I'm not sure how useful that would be for the blockaded player or how it would work in the UI...

**Comment by agrrr3** [comment]
>
> Do you mean the ships in the blockading fleet? They are revealed due to
> being part of a blockade.
>
Yes, but hidden ships should still have the advantage of not being
targetable in the first bout.
Maybe only reveal if no combat happens? Or reveal after combat processing?

Having a visibility state for that may also make sense.

**Comment by geoffthemedio** [comment]
> Having a visibility state for that may also make sense.

I'd probably rather try to pass the list of blockading fleets to `CombatConditionsInSystem`. Having another special case visibility level that has to be handled / checked for everywhere by only has a very specific use case / meaning is awkward.

**Comment by agrrr3** [comment]
test game not working with AI/monsters on 877ec6c4464eb6b9ae7daffd5f3436aa9efcbfa3
[save-20240131_115239.zip](https://github.com/freeorion/freeorion/files/14233916/save-20240131_115239.zip)

there should be combat on Ioran (yellow, upper left)

**Comment by agrrr3** [comment]
> > Having a visibility state for that may also make sense.
> 
> I'd probably rather try to pass the list of blockading fleets to `CombatConditionsInSystem`. 

you mean instead of adding the fleets to the visibility map? Seems valid for triggering combat :)

> Having another special case visibility level that has to be handled / checked for everywhere by only has a very specific use case / meaning is awkward.

i thought the visibility levels would be monotone, so all the tests are lesser-equal-than. in that case UI and probably triggering combat would use this level.
also the not so specific meaning could be: there is at least one ship, but no details.

**Comment by o01eg** [comment]
I forgot why I wanted this PR to be merged, but will it be ready for weekly test build at April 23th?

**Comment by geoffthemedio** [comment]
> I forgot why I wanted this PR to be merged, but will it be ready for weekly test build at April 23th?

I think it's OK now. Probably some bugs I haven't noticed, though.

**Pull request merged**
