### PR TITLE
Fix DebugLogger usage in Python Init not to get wide string

### LINKED ISSUE #4978: Unable to launch game in either windowed or fullscreen mode
Bug Report
==========

Unable to launch game in either windowed or fullscreen mode

Environment
-----------

* **FreeOrion Version**: 2024-07-12.0739705
* **Operating System**: Windows 11 Pro
* **Graphic card used**: Nvidia Mobile RTX 3060
* **Fetched as**
  * Binary release
  * Weekly development build

Description
-----------

config.xml:
```
<?xml version="1.0"?>
<XMLDoc>
  <video>
    <fullscreen>
      <reset>0</reset>
      <width>1463</width>
      <height>823</height>
    </fullscreen>
    <fullscreen/>
  </video>
  <version>
    <string>v0.5+ [build 2024-07-12.0739705] MSVC 2022 Win32</string>
  </version>
  <video/>
</XMLDoc>
```

[freeorion.log](https://github.com/user-attachments/files/16257615/freeorion.log)

Expected Result
---------------
Game to run

Steps to reproduce
------------------

* Click on either windowed or fullscreen version of test build

### PR DESCRIPTION
**Pull request by Blue-Award**
Also, avoid trying to roundtrip wide path for SetPythonHome/SetProgramName on Windows - it already gets wide path

Fixes https://github.com/freeorion/freeorion/issues/4978 by doing utf16to8 conversion on file paths before logging them. Because that's what caused the original issue - DebugLogger getting wide character screen. 

Another thing I fixed here is avoiding [Py_DecodeLocale()](https://docs.python.org/3.9/c-api/sys.html#c.Py_DecodeLocale)  in Windows case before calling [Py_SetPythonHome ](https://docs.python.org/3.9/c-api/init.html?highlight=py_setpythonhome#c.Py_SetPythonHome)

The doc says:

> Use [Py_DecodeLocale()](https://docs.python.org/3.9/c-api/sys.html#c.Py_DecodeLocale) to decode a bytes string to get a wchar_* string.

But in Windows' case, the path is already wide, so instead I'm doing simple copy.

I also moved [Py_GetProgramFullPath](https://docs.python.org/3.9/c-api/init.html?highlight=py_getprogramfullpath#c.Py_GetProgramFullPath) pre-emptively to post-init, as going from version 3.10 it returns NULL otherwise: [Py_GetProgramFullPath](https://docs.python.org/3.10/c-api/init.html?highlight=py_getprogramfullpath#c.Py_GetProgramFullPath). Instead, I'm logging [Py_GetPath](https://docs.python.org/3.9/c-api/init.html?highlight=py_getpath#c.Py_GetPath)

However, I am not sure that piece is doing anything really, even the original comment says 
>Not sure if they are really required

Seems to work out better with my changes, anyway, because instead of getting ?????? I get proper unicode path when not going through Py_DecodeLocale. It just seems this doesn't really affects anything in my case, Python works either way. Like I also don't get why setting program name to "Python" when it ends up being FreeOrion.exe anyway, looking at Py_GetProgramFullPath after these calls.

BUT I think there is another issue I am not addressing here and probably warrants look at (separately I think). The doc says to use [Py_PreInitialize](https://docs.python.org/3.9/c-api/init_config.html?highlight=preinit#c.Py_PreInitialize) and doesn't seem we're doing it?

### CODE REVIEW

**Comment by geoffthemedio** [comment]
PythonCommon stuff seems to work:
````
07:52:21.069021 {0x0000c628} [debug] client : PythonCommon.cpp:49 : Initializing FreeOrion Python interface
07:52:21.069021 {0x0000c628} [debug] client : PythonCommon.cpp:61 : Python home set to C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ
07:52:21.069021 {0x0000c628} [debug] client : PythonCommon.cpp:65 : Python program name set to C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ\Python
07:52:21.165043 {0x0000c628} [debug] client : PythonCommon.cpp:77 : Python initialized
07:52:21.165043 {0x0000c628} [debug] client : PythonCommon.cpp:78 : Python program: C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ\FreeOrion.exe
07:52:21.165043 {0x0000c628} [debug] client : PythonCommon.cpp:79 : Python version: 3.9.10 (main, Apr 26 2023, 09:42:47) [MSC v.1935 64 bit (AMD64)]
07:52:21.165043 {0x0000c628} [debug] client : PythonCommon.cpp:80 : Python prefix: C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ
07:52:21.165043 {0x0000c628} [debug] client : PythonCommon.cpp:81 : Python module search path: C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ\python39.zip;;C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ\Lib\python39;C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ\Lib\python39\lib-dynload;C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ\Lib\python39\lib-dynload\RelWithDebInfo;C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ\Lib\python39\plat-win32;C:\Users\g_top\Desktop\FOSDK14\FreeOrionШ
````

But I still get:
````
07:52:24.210204 {0x0000c628} [debug] client : PythonParser.cpp:435 : Executing module file C:/Users/g_top/Desktop/FOSDK14/FreeOrion?/default\scripting\techs\ship_parts\fuel\fuel.py
````

**Comment by o01eg** [comment]
Parser uses ` << module_path.string();` to output path to log.

**Comment by Blue-Award** [comment]
indeed, and path.string() or path.generic_string() produce ????? in Windows, unless it's set to default to utf8

(this is also why things like loading fonts or music don't work for me cause optionsDB gets the paths as path.string() - I'll prolly fix that too for completeness sake)

**Comment by o01eg** [comment]
Should we try to introduce `boost::filesystem::path` type to OptionsDB to store path values?

**Comment by Blue-Award** [comment]
I would think it's fine to assume utf8 encoded narrow string storage in optionsDB, like it is happening in other places in code that convert between paths and strings with utf16to8 or vice versa. It's just one of places that fell through the cracks cause I guess people rarely put FO into "unicode rich" path. Anyway, trying to go another way would need to be mindful about interoperability of config (and save?) files

I wonder if there is other way to fix logging of wide strings, cause then it should be non issue to log path.native() without preemptive narrow conversion (thru path.string(), path.generic_string(), or utf16to8 on path.native() ).

I'm not sure why the default narrow conversion in something like the logger (or gil::read_image for that matter) fails. Maybe need to actually set locale to something? doesn't seem the app is setting the locale explicitly, so whatever is there by default maybe doesn't handle those things well (on Windows)

I saw something about imbuing streams with utf8 locale, maybe that could help with logger at least

**Comment by geoffthemedio** [comment]
> I would think it's fine to assume utf8 encoded narrow string storage in optionsDB

yes, or rather require utf8 in OptionsDB

**Comment by Blue-Award** [comment]
I've used GiGi's utf16to8 originally in the fix here but when having a look at moving to std::filesystem I've run into https://github.com/freeorion/freeorion/blob/95f0731133558cbe0187fb6b5b4c67123188f474/util/Directories.cpp#L767 

That method looks like something that could be used for the places that take generic_string for example for logging purposes. Although on windows it bases on generic_wstring and does WideCharToMultiByte on it. Meanwhile linux etc it is path.string() rathr than path.generic_string(). 

Looks nicer to use than GiGI's utf16to8

In this PR here, I'm actually converting wchar_t*, but still, instead of GiGI's utf16to8 looks like I could use winapi's WideCharToMultiByte like the above method does. I think I'd like to change this PR to do that. 

And maybe use the `PathToString` method in my other fix about loading textures, too, rather than utf16to8.

And seems using that method would be quick fix for optionsdb stuff regarding music and fonts as well

**Comment by Blue-Award** [comment]
I pushed a change to use winapi's WideCharToMultiByte instead of GiGi's utf16to8, inspired by util/Directories.h PathToString except it's wchar_t* to std:string

**Comment by o01eg** [comment]
As it works with file names anyway maybe it's better to use `util/Directory` functions.

**Comment by Blue-Award** [comment]
I think going through filesystem::path would be unnecessary, and more importantly, not sure if even working, because Python operates on wchar_t* similarly to Windows, meanwhile on unix the basis for boost::filesystem::path is std::string

That being said a helper function to do wide to narrow multibyte utf8 conversion and back, could be useful (and itself usable by PathToString etc) in some more basic place, I suppose I didn't want to go that far but eventually may prove more useful. Could put in directories.h or maybe somewhere in logger

(also it can be implemented multiple ways, gigi does its own thing, currently std has similar conversion on its own, actually, while Freeorion's PathToString is directly calling winapi which I kinda like but not everybody likes such things)

**Comment by Blue-Award** [comment]
just rebased to current master, there was no merge conflict with other changes in PythonParser.cpp but dunno, figured it's maybe better that way?

**Comment by Blue-Award** [comment]
OK you know what since I include `<windows.h>` I figured i'll define `NOMINMAX`, it wasn't causing trouble here but better safe than sorry

**Comment by Blue-Award** [comment]
I've noticed I kept `-1` instead of `original_size` from testing in `WideCharToMultiByte` in `GetLoggableString` and that would include NULL with conversion, so no need for that (and rebased to master)

**Comment by Blue-Award** [comment]
I have digged around and have good understanding on why logging of wide char input may fail on Windows, and can propose a more broad solution.

Boost isn't making it easy though, and I'd rather have this localized solution to a particular problem merged before starting a discussion where I am not even sure if broader solution is needed/desired, or just gotta keep explicitly converting wide strings to utf8 before logging.

**Pull request merged**
