### PR TITLE
Fixes errors with boost::placeholders::_1 and _2 and _3

### LINKED ISSUE #3122: error: use of undeclared identifier '_1
Can't build 0.4.10 freeorion with clang and boost 1.73.0

```
/home/omv/freeorion/BUILD/freeorion-0.4.10/UI/FleetWnd.cpp:2416:68: error: use of undeclared identifier '_1'
        boost::bind(&FleetDetailPanel::ShipSelectionChanged, this, _1));
        |       |       |       |       |       |       |       |  ^
/home/omv/freeorion/BUILD/freeorion-0.4.10/UI/FleetWnd.cpp:2418:64: error: use of undeclared identifier '_1'
        boost::bind(&FleetDetailPanel::ShipRightClicked, this, _1, _2, _3));
        |       |       |       |       |       |       |      ^
/home/omv/freeorion/BUILD/freeorion-0.4.10/UI/FleetWnd.cpp:2418:68: error: use of undeclared identifier '_2'
        boost::bind(&FleetDetailPanel::ShipRightClicked, this, _1, _2, _3));
        |       |       |       |       |       |       |       |  ^
/home/omv/freeorion/BUILD/freeorion-0.4.10/UI/FleetWnd.cpp:2418:72: error: use of undeclared identifier '_3'
        boost::bind(&FleetDetailPanel::ShipRightClicked, this, _1, _2, _3));
        |       |       |       |       |       |       |       |      ^
/home/omv/freeorion/BUILD/freeorion-0.4.10/UI/FleetWnd.cpp:2420:69: error: use of undeclared identifier '_1'
        boost::bind(&FleetDetailPanel::UniverseObjectDeleted, this, _1));
        |       |       |       |       |       |       |       |   ^
/home/omv/freeorion/BUILD/freeorion-0.4.10/UI/FleetWnd.cpp:2819:63: error: use of undeclared identifier '_1'
        boost::bind(&FleetWnd::CreateNewFleetFromDrops, this, _1));
        |       |       |       |       |       |       |     ^
/home/omv/freeorion/BUILD/freeorion-0.4.10/UI/FleetWnd.cpp:2822:61: error: use of undeclared identifier '_1'
        boost::bind(&FleetWnd::UniverseObjectDeleted, this, _1));
```

### PR DESCRIPTION
**Pull request by geoffthemedio**
Attempts to resolve #3122

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Might need a .1 bugfix release apparently...

**Comment by Vezzra** [comment]
> Might need a .1 bugfix release apparently...

In which case the "cherry pick for release" label needs to stay. All PRs which are supposed to go into a bugfix release need to be tagged that way, so I can know what to cherry pick to the release branch for the bugfix release.

**Comment by geoffthemedio** [comment]
I removed the cherry pick tag because this pull request is already against the v0.4.10 branch

**Comment by Vezzra** [comment]
> I removed the cherry pick tag because this pull request is already against the v0.4.10 branch

Oh, sorry, completely missed that. Is that because it's only an issue with the release branch, or because you intend to provide a separate/better fix for master? Or why did you make this PR against the release branch?

**Comment by geoffthemedio** [comment]
It's already in master (and merged here). I initially made the pull request against v0.4.10 because that was the version the issue was reported for.

**Comment by Vezzra** [comment]
Ok, I see... still, if a bug/issue is present in both master and the release branch, and the same fix is going to applied to both, I'd prefer if the bugfix PR was made against master and tagged for cherry picking, regardless of what version the bug was reported for.

IMO more consistent, and less confusing for me. 😉

**Pull request merged**
