### PR TITLE
[AI] colonization planning adjustments re defense value of multiple p…

### PR DESCRIPTION
**Pull request by Dilvish-fo**
planets in system.  While not really being a bug fix, it addresses some AI behavior that players had noticed as being inefficient (overvaluing uninhabitable planets)

### CODE REVIEW

**Comment by Vezzra** [comment]
I assume this is your request to cherry pick e4601dc33b4ed58e54b0b90ae19394eb7e331a44 into the release branch? No need to make a PR for this, opening an issue is the way to go for that (I can't _merge_ anyway, I have to _cherry pick_ the commit).

But lets leave it as a PR this time. Anyone any objections? Speak up, or I'm going to cherry pick.

**Comment by Cjkjvfnby** [comment]
Just calculate new numbers:
`get_base_outpost_defense_value` changes from 1.0 to 258.33
`get_base_colony_defense_value` changes from 1.0 to 496.0

**Comment by MatGB** [comment]
I believe the thing about cherry picking is it doesn't add extra 'merge pull request X' commits into teh branch so it's not diverging horrifically from master, but I'm probably wrong, Git logic isn't always Earth logic but seems to make sense within itself once you've understood it.

**Comment by Dilvish-fo** [comment]
I didn't put this up because I expected to merge it, just as a way to have the code subject to inspection.  Next time, if I don't already have a separate PR for review before going into master, I will follow the route adrian did with the commit referenced in an issue.

**Comment by Dilvish-fo** [comment]
> Just calculate new numbers:
> get_base_outpost_defense_value changes from 1.0 to 258.33
> get_base_colony_defense_value changes from 1.0 to 496.0

And your point is...?  

The goal is to (well, this should be pretty obvious I suppose, but you haven't given me anything else to reply to) have the defense value be low when there is not much defense that they provide, and for it to go up as more defense is provided.   The ranges seem reasonable to me.

**Comment by Dilvish-fo** [comment]
did a further reduction in the final version, taking the scaling factor from 10 to 6

**Pull request closed without merging**
