### PR TITLE
Added the tech "Controlled Mega-Fauna Maturation" that increases the …

### PR DESCRIPTION
**Pull request by Deepsloth**
…chance of monster spawns at monster nests by 0.05 and unlocks the building "Mega-Fauna Maturation Pen" that provides a 0.05 chance of spawning Level 2 monsters (suggested by labgnome and Bluehand).

### CODE REVIEW

**Comment by Deepsloth** [comment]
This is an updated version of PR #270: https://github.com/freeorion/freeorion/pull/270

Next Release Milestone

Controlled Mega-Fauna Maturation is now a dead end tech that needs Mega-Fauna Endocrine Systems. So it doesn't need AI updates.

**Comment by MatGB** [comment]
OK, I've grabbed a copy I'll play through a game to confirm it's fine and/or nitpick.

**Comment by MatGB** [comment]
OK, minor quibble, it needs the enqueued building macro for consistency.

More major feedback, I love the idea of this but I'm not sure on the implementation. I see no reason to not build one on every monster nest, which is basically what I'm doing. But they're quite expensive for a random bonus, even if it is a fairly good bonus.

Given we're trying to move away from buildings that you feel you need to have everywhere, I'm wondering if upping the price but have it work on every nest in supply? It can be the megafauna research centre and represent the centralised planning for all the pens and breeders spread over the galaxy. Possibly one for each nest type would be the most balanced approach.

Alternatively, make the bonus a bit better (possibly do both) by increasing the rate that monsters mature if in the same system as the centre—if we go for the in supply bonus, I'd still say have this bonus only apply here, you breed monsters at their nests but send them to the training grounds to be big and scary (which would tie in well with having stargates and similar).

I definitely like the idea and like building them, but setting the game on high monsters I'm building my 5th or 6th currently and I haven't invaded an AI yet.

**Comment by Deepsloth** [comment]
> Given we're trying to move away from buildings that you feel you need to have everywhere, I'm wondering if upping the price but have it work on every nest in supply? It can be the megafauna research centre and represent the centralised planning for all the pens and breeders spread over the galaxy. Possibly one for each nest type would be the most balanced approach.

This sounds good. I'm on vacation at the moment and will be for the next two weeks. I would be glad to hand over the (Mega-Fauna-) reins to you Mat.

**Comment by geoffthemedio** [comment]
Requires some updates and a rebase...?

**Comment by MatGB** [comment]
Oh gods, I had completely forgotten about this, I was working on it before the RCs were ready then got distracted testing them, the concept is good the implementation not so, I'll have a look at it again.

**Comment by MatGB** [comment]
Have a copy on my machine, will work with Sloth to get it updated.

**Pull request closed without merging**
