### PR TITLE
Update AI default research order

### PR DESCRIPTION
**Pull request by Morlic-fo**
So, this is the first pass of the research order (mostly early/midgame stuff, lategame mostly untouched) dealing with issue #633. 
Testing and feedback is requested:
- Any new error messages popping up?
- Does the AI seemingly forget some important techs or research them too late? How is the Active Radar timing now?
- Does the AI resource output / expansion improve compared to previous version?
- General feeling of difficulty compared to previous version, e.g. military timeline of the AI, difficulty to conquer the AI's planets, timing windows etc.

As far as I am concerned, this may be merged to master for easier testing once @Cjkjvfnby reviewed the code eventhough the tech order is still WIP. Should be unproblematic to revert if "major" issues are revealed that can't be hotfixed "in time" for release.
### AI pursues economic techs slightly more greedy now:
- AI always starts the game with the "holy quadruple" of Planetary Ecology, Subterranean Habitation, Algorithmic Elegance and Nascent Artificial Intelligence
- Adaptive Automation and Exobots are researched much earlier
- AI should no longer research Orbital Generation, Microgravity Industry or Asteroid Hulls prematurely
- AI will research various growth techs slightly earlier
- Delayed Industrial Center slightly in favor of other PP boosts

The AI may be weaker against early attacks. Didn't use to make a challenge when rushed properly anyway. The changes are intended to let the AI to keep economically up with the human player for a longer time.
### Removed unused techs:
- AI will no longer research hull types it doesn't use due to its ShipDesign algorithm anyway.
- AI will no longer research stealth techs (which came too late to be of any use anyway and aren't used in current generation ship designs)
- AI will no longer "prematurely" research theory techs
### MISC research priority:
- Delay weapon upgrade techs slightly after the initial weapon is researched to allow building of ships before the tech upgrade (e.g. may squeeze some economic tech in between Laser 2 and 3)
- Active Radar is researched earlier now
## Rewrite tech groups as classes
- added functionality to avoid missing important techs are forgotten in specific (sub-)tech groups.
- add test function to check for invalid techs/research groups
- Delayed Force-Field-Harmonics slightly

### CODE REVIEW

**Comment by Morlic-fo** [comment]
Not sure about labels, the issue is tagged as refactoring so using that.

**Comment by Vezzra** [comment]
Refactoring should be fine. If I understand correctly it is supposed to have a broader meaning, so something like tweaking/extending an existing feature/mechanic/algorithm is also covered by it (at least I think this is how @adrianbroher intended it).

**Comment by Cjkjvfnby** [comment]
I made comments as PR.  This is only style changes.  Feel free to apply all or just part of them to you PR.

PS. You branch is not compatible with latest windows build and should be rebased.

**Comment by LGM-Doyle** [comment]
I tested this PR.

I played with 9 maniacal AIs in a 273 star galaxy. 

I did not notice any new errors.

All AIs had room to grow. There was noticeable improvement in the consistency of the starts of the AIs, so the level of difficulty is probably slightly increased.

**Comment by Vezzra** [comment]
Played a test game too with this PR, 10 AI on a 500 star map (wanted to see how the AI does when it has plenty of room to expand). Around turn 130 I was well ahead (as usual), but I had a good starting spot and have been able to develop quite quickly.

From what I've seen there aren't any obvious errors or broken stuff, the AI is at least as capable as before, probably even a bit better. It's hard to judge by just one quick test game, and I don't have time for much more.

I'd say merge it.

**Comment by Cjkjvfnby** [comment]
Style fixes and couple of typos can wait after release. So I don't mind to merge it as is.

**Comment by Morlic-fo** [comment]
I'm looking through your suggested changes right now, I will merge when I am done.

**Pull request merged**
