### PR TITLE
Rework Centralization

### PR DESCRIPTION
**Pull request by MichaelCourtney**
Only partially tested.
Also the pedia entry has issues as it ends up with a value with 3 decimal places.

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
https://freeorion.org/forum/viewtopic.php?t=12921&sid=903f6ebf8eaad802ac395cbc1d3ff5ad

**Comment by MichaelCourtney** [comment]
Played with the numbers till I found something that would display correctly in the pedia and still give good balance.

It gives approximately the same bonus to an average stability species as the old policy on turn 1 and will scale up if the player adopts policies the species likes, it can reasonably strong combined with bureaucracy, but that also consumes a 2nd policy slot.

Adjusted the IP cost of centralization and bureaucracy inline with changes, they were quite cheap anyway.

Minor tweaks to Egassem/Replicon to make sure they don't fall too far behind higher stability species in the early game.

I've tested it, it works and balance seems better, if possible I'd like to see it testing in the 27th MP, to see if other players feel the balance is right.

**Comment by Blue-Award** [comment]
I am wondering if this is not too big of a buff to add propaganda to likes especially for Replicon. Seems like everybody's is using the propaganda, even if not at first (if they want to run liberty first for more science, particularly in team game, but later you gonna pick propaganda anyway, right?). 

If the goal was to boost centralization, maybe that's what Replicons could be liking instead? Would it work with the fluff? I realize that specifically goes against the face of Egassem, but maybe boosting their stability is fine. It's just that Replicon's main malus thing seems to be the -5 stability and I find it not that hard to combat, and now gonna be even easier

**Comment by MichaelCourtney** [comment]
You could be right, not sure. As far as why I rejected centralisation as a like for Replicon it was because its already very busy in terms of species that like/dislike it

**Comment by MichaelCourtney** [comment]
I don't always run propaganda, there's also diversity and artisans in that mix

**Pull request merged**
