### PR TITLE
[CI] Weekly test builds

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
- Fix weekly-build
  - workflow name
  - passing secrets
- Move the mac os matrix out of the

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
This branch is based on the changes I have pushed to weekly-release. 

https://github.com/freeorion/freeorion/actions/runs/5137869458

**Comment by Cjkjvfnby** [comment]
I'll go ahead and merge this branch.  I want to test it in master and for weekly-build.

@o01eg could you still take a look at the changes?  

I'll reach you soon with some questions about some steps.

Also, I'll take a look into: https://github.com/freeorion/freeorion/actions/runs/5138225886/jobs/9247321899, these tasks start to fail everywhere. 

UPD.  This is an issue on the fedora side, I can reproduce it with the image.  We need just wait a bit.  https://github.com/fedora-cloud/docker-brew-fedora/issues/109

**Comment by o01eg** [comment]
Looks fine.

About Fedora Rawhide I suppose we could temporarily disable it until issue will be solved.

**Comment by Vezzra** [comment]
👍

**Pull request merged**
