### PR TITLE
add tech icons

### PR DESCRIPTION
**Pull request by TheSilentOne1**
for:
transorganic sentience
psychogenic domination
defense network regeneration
renamed heavy mining processors and used as neutronium extraction

### CODE REVIEW

**Comment by adrianbroher** [comment]
Renaming the "heavy_mining_processor.png" icon breaks the BLD_HEAVY_MINE_PROCESSOR icon reference.

**Comment by TheSilentOne1** [comment]
Thanks for poiting that out, I didn't know that building existed. Is it actually unlockable and does it do anything? Otherwise we might as well remove it.

**Comment by MatGB** [comment]
Remove it, it hasn't done anything for years

**Comment by adrianbroher** [comment]
> Remove it, it hasn't done anything for years

Done.

**Comment by Vezzra** [comment]
@adrianbroher, what "category:*" label would you suggest for this PR?

@TheSilentOne1: looks fine, as far as I'm concerned, go ahead and merge.

**Comment by geoffthemedio** [comment]
I feel like a "minor/tweak" category is needed...

**Pull request merged**
