### PR TITLE
Add no-rebel troops requirement to default species annexation condition

### PR DESCRIPTION
**Pull request by geoffthemedio**
should help with #4947

### CODE REVIEW

**Comment by agrrr3** [comment]
no annexation while there is a civil war seems sensible. (although that
this is one of the few annexation counters seems weird)

So this PR is mostly for UI right? so the button is not available and give
the reason in the mouse-over.

@geoffthemedio can you point me to the backend code which prevented
annexation here?
it probably should only live in the FOCS condition, shouldnt it?

**Comment by geoffthemedio** [comment]
It's a more general condition in HandleInvasion and HandleAnnexation that a planet with ground combat can't be annexed. This includes combat with rebels.

https://github.com/freeorion/freeorion/blob/master/server/ServerApp.cpp#L3216
https://github.com/freeorion/freeorion/blob/master/server/ServerApp.cpp#L3571

**Comment by geoffthemedio** [comment]
accidentally pushed directly to master as https://github.com/freeorion/freeorion/commit/6c553c92bbc90f8ece554a00209d1b4e2d894f32

**Comment by Vezzra** [comment]
Closed as merged means #4947 can be closed as resolved, correct?

**Comment by geoffthemedio** [comment]
> Closed as merged means #4947 can be closed as resolved, correct?

Debatable... the UI inconsistency was resolved. Whether the restriction about no ground combat for annexation should be left in place is not really decided and so the issue status is unclear...

**Comment by Vezzra** [comment]
Ok...

**Pull request closed without merging**
