### PR TITLE
Add `--log-file` option to redirect logs.

### PR DESCRIPTION
**Pull request by o01eg**
Add option `--log-file` to the server, client and AI to change default log file.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
When is this needed or useful?

**Comment by Dilvish-fo** [comment]
So, what's the use-case for this?  Is it part of your standalone server work?
I'm currently not really seeing the the benefit outweigh the clutter here.   Also, it looks like by itself this will only cause the human client log to be redirected, that to redirect the server and AI logs you would need to start those separately (and so for the AI would only work for multiplayer games).  So the help message should be more clear about that.

Also, if someone specifies the same file for them all I suppose the result might be OS dependent, but on mine (Ubuntu Linux, just setting the server log and human log the same) it tries to put them into the same file but does a poor job of it, overwriting each other in strange ways.  So you'd probably need to check if the specified logfile is already open for writing and if it is then instead just use the default logfile, with an error message written to the console, or something.

**Comment by o01eg** [comment]
It mostly done to separate logs from two or more client which I run on the same system to test multiplayer but I made it same way as `log-level` so it works for server and AI as well.
About setting same log file I suppose it user's error.
However I look up to `text_file_backend` documentation and it accept only `std::ios_base::openmode` open flag which doesn't support any locks.

**Comment by geoffthemedio** [comment]
Maybe it should automatically change the log file name if there is already a server or client/ui process running, to avoid mixing two process' logs into one file? I don't think there's presently any way to check for that, though.

**Comment by o01eg** [comment]
@geoffthemedio Then it need a way to get which log file is used by running processes. And it requires many platform-depended code.
I think it will be good to add process id as prefix to log file. The only trouble then is to clean up old logs.

**Comment by o01eg** [comment]
It sad but it looks like boost::process appeared at 1.64 version.

**Comment by o01eg** [comment]
Rebased.
So will it be responsibility of those who set `log-file` to prevent collisions?

**Pull request merged**
