### PR TITLE
Tweak Species Likes/Dislikes Data Wrangling

### PR DESCRIPTION
**Pull request by geoffthemedio**
May help / fix issues like https://freeorion.org/forum/viewtopic.php?p=117136#p117136

### CODE REVIEW

**Comment by o01eg** [comment]
When I open Exobot species encyclopedia I got error in log:

```
i18n.cpp:355 : Missing string: PLC_ALLIED_REPAIRPLC_BUREAUCRACYPLC_DESIGN_SIMPLICITYPLC_ENGINEERINGPLC_EXOBOT_PRODUCTIVITY
```

**Comment by geoffthemedio** [comment]
Only with and not without this?

**Comment by MichaelCourtney** [comment]
I see it with Vezzra's latest windows build

**Comment by MichaelCourtney** [comment]
Its this:

https://github.com/freeorion/freeorion/commit/88e0d5bd425773235cfac8a3d56793491dd48dd5

I'm not getting the error when I use the old exobot.focs.txt instead of exobot.focs.py

**Comment by MichaelCourtney** [comment]
Yeah ok exobot.py is missing a bunch of commas in the likes, dislikes

**Comment by o01eg** [comment]
> Yeah ok exobot.py is missing a bunch of commas in the likes, dislikes

Does adding commas here fix issue?

**Comment by MichaelCourtney** [comment]
> > Yeah ok exobot.py is missing a bunch of commas in the likes, dislikes
> 
> Does adding commas here fix issue?

yes

**Comment by o01eg** [comment]
@Cjkjvfnby Could you put missing commas in species likes and dislikes?

**Comment by MichaelCourtney** [comment]
> @Cjkjvfnby Could you put missing commas in species likes and dislikes?

https://github.com/freeorion/freeorion/pull/4684

**Pull request merged**
