### PR TITLE
Replace boost::bind with C++11 lambdas

### PR DESCRIPTION
**Pull request by adrianbroher**
As advertised in the title.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Starting with d19159b9 the server crashes when starting a game.
````
17:02:56.048463 {0x000035c8} [error] server : serverapp.cpp:487 : ServerApp::HandleNonPlayerMessage : Received an invalid message type "UNDEFINED" for a non-player Message.  Terminating connection.
17:02:56.048463 {0x000035c8} [error] FSM : serverfsm.cpp:284 : A Disconnection event was not handled by any of these states : [struct Idle].  It is being ignored.
17:02:56.048463 {0x000035c8} [error] network : servernetworking.cpp:449 : PlayerConnection::HandleMessageHeaderRead(): error #995 "The I/O operation has been aborted because of either a thread exit or an application request"
````

**Comment by geoffthemedio** [comment]
Now the client crashes when starting a game. Nothing relevant in the log.

**Comment by adrianbroher** [comment]
@geoffthemedio I have only rebased the PR. I didn't had time and motivation yet to debug the issue.

**Comment by adrianbroher** [comment]
Updated the PR, re-reviewed the whole code.

There were several places when replacing boost::bind with lambdas the reference captured variables became invalid as the referenced object left scope.

**Comment by geoffthemedio** [comment]
I can't practically go through this line by line, so I'll assume you caught the problematic cases. It seems to work OK in a local test game.

**Comment by geoffthemedio** [comment]
As of b11e685f7c4a22b3f6f9374c970729ed89414012 (or earlier, but not with ff51452d68818f207fe71cde8054da5fd7ddb1dd ), I get a crash if I quickstart a game, left click on my homeworld fleet icon, right click on the top fleet and merge system ships into it, then right click it again to split it.

Exception popup says `Unhandled exception at 0x7773F959 in FreeOrion.exe: 0xC0000005: Access violation executing location 0x00000000.`

Reported call stack contains:
````
>	[Inline Frame] FreeOrion.exe!boost::function0<void>::operator()() Line 763	C++
 	[Inline Frame] FreeOrion.exe!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke(boost::function<void __cdecl(void)> &) Line 117	C++
 	[Inline Frame] FreeOrion.exe!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()(boost::function<void __cdecl(void)> &) Line 90	C++
 	[Inline Frame] FreeOrion.exe!boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>::operator()(const boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > &) Line 133	C++
 	FreeOrion.exe!boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> >::dereference() Line 110	C++
 	[Inline Frame] FreeOrion.exe!boost::iterators::iterator_core_access::dereference(const boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > &) Line 550	C++
 	[Inline Frame] FreeOrion.exe!boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> >,boost::signals2::detail::void_type,boost::iterators::single_pass_traversal_tag,boost::signals2::detail::void_type const &,int,0,0>::operator*() Line 656	C++
 	FreeOrion.exe!boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > first, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > last) Line 61	C++
 	[Inline Frame] FreeOrion.exe!blocking_combiner<boost::signals2::optional_last_value<void> >::operator()(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(void),boost::function<void __cdecl(void)> >,boost::signals2::mutex> >) Line 29	C++
 	[Inline Frame] FreeOrion.exe!boost::signals2::detail::combiner_invoker<void>::operator()(blocking_combiner<boost::signals2::optional_last_value<void> > &) Line 64	C++
 	FreeOrion.exe!boost::signals2::detail::signal_impl<void __cdecl(void),blocking_combiner<boost::signals2::optional_last_value<void> >,int,std::less<int>,boost::function<void __cdecl(void)>,boost::function<void __cdecl(boost::signals2::connection const &)>,boost::signals2::mutex>::operator()() Line 242	C++
 	[Inline Frame] FreeOrion.exe!boost::signals2::signal<void __cdecl(void),blocking_combiner<boost::signals2::optional_last_value<void> >,int,std::less<int>,boost::function<void __cdecl(void)>,boost::function<void __cdecl(boost::signals2::connection const &)>,boost::signals2::mutex>::operator()() Line 722	C++
 	FreeOrion.exe!NewFleetOrder::ExecuteImpl() Line 243	C++
 	FreeOrion.exe!Order::Execute() Line 44	C++
 	FreeOrion.exe!OrderSet::IssueOrder(std::shared_ptr<Order> && order) Line 29	C++
 	FreeOrion.exe!`anonymous namespace'::CreateNewFleetFromShips(const std::vector<int,std::allocator<int> > & ship_ids, NewFleetAggression aggression) Line 231	C++
 	FreeOrion.exe!FleetWnd::FleetRightClicked::__l54::<lambda>() Line 3525	C++
 	[Inline Frame] GiGi.dll!std::_Func_class<void>::operator()() Line 311	C++
 	GiGi.dll!GG::PopupMenu::Run() Line 311	C++
 	FreeOrion.exe!FleetWnd::FleetRightClicked(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > > it, const GG::Pt & pt, const GG::Flags<GG::ModKey> & modkeys) Line 3667	C++
 	[Inline Frame] FreeOrion.exe!FleetWnd::CompleteConstruction::__l2::<lambda_b05f7c5722917601949a7ffe086cace7>::operator()(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > > modkeys, const GG::Pt &) Line 2797	C++
 	FreeOrion.exe!boost::detail::function::void_function_obj_invoker3<<lambda_b05f7c5722917601949a7ffe086cace7>,void,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>::invoke(boost::detail::function::function_buffer & function_obj_ptr, std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > > a0, const GG::Pt & a1, const GG::Flags<GG::ModKey> & a2) Line 159	C++
 	[Inline Frame] GiGi.dll!boost::function3<void,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>::operator()(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >) Line 763	C++
 	[Inline Frame] GiGi.dll!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke(boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> &) Line 105	C++
 	[Inline Frame] GiGi.dll!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()(boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> &) Line 90	C++
 	[Inline Frame] GiGi.dll!boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>::operator()(const boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > &) Line 133	C++
 	GiGi.dll!boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> >::dereference() Line 110	C++
 	[Inline Frame] GiGi.dll!boost::iterators::iterator_core_access::dereference(const boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > &) Line 550	C++
 	[Inline Frame] GiGi.dll!boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> >,boost::signals2::detail::void_type,boost::iterators::single_pass_traversal_tag,boost::signals2::detail::void_type const &,int,0,0>::operator*() Line 656	C++
 	GiGi.dll!boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > first, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)> >,boost::signals2::mutex> > last) Line 61	C++
 	[Inline Frame] GiGi.dll!boost::signals2::detail::combiner_invoker<void>::operator()(boost::signals2::optional_last_value<void> &) Line 64	C++
 	GiGi.dll!boost::signals2::detail::signal_impl<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)>,boost::function<void __cdecl(boost::signals2::connection const &,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)>,boost::signals2::mutex>::operator()(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > > <args_0>, const GG::Pt & <args_1>, const GG::Flags<GG::ModKey> & <args_2>) Line 242	C++
 	[Inline Frame] GiGi.dll!boost::signals2::signal<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)>,boost::function<void __cdecl(boost::signals2::connection const &,std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >,GG::Pt const &,GG::Flags<GG::ModKey> const &)>,boost::signals2::mutex>::operator()(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<GG::ListBox::Row> > > >) Line 722	C++
 	GiGi.dll!GG::ListBox::EventFilter(GG::Wnd * w, const GG::WndEvent & event) Line 1754	C++
 	[External Code]	
 	[Inline Frame] GiGi.dll!std::_Func_class<void,std::shared_ptr<GG::Wnd> &>::operator()(std::shared_ptr<GG::Wnd> &) Line 82	C++
 	GiGi.dll!GG::ProcessThenRemoveExpiredPtrs<std::vector<std::weak_ptr<GG::Wnd>,std::allocator<std::weak_ptr<GG::Wnd> > > >(std::vector<std::weak_ptr<GG::Wnd>,std::allocator<std::weak_ptr<GG::Wnd> > > & container, const std::function<void __cdecl(std::shared_ptr<GG::Wnd> &)> & process, std::weak_ptr<GG::Wnd> * __formal) Line 85	C++
 	GiGi.dll!GG::Wnd::HandleEvent(const GG::WndEvent & event) Line 1114	C++
 	GiGi.dll!GG::GUIImpl::HandleMouseButtonRelease(unsigned int mouse_button, const GG::Pt & pos, int curr_ticks) Line 526	C++
````

**Pull request merged**
