### PR TITLE
Import screenshots from website

### PR DESCRIPTION
**Pull request by Siosm**
This also converts screenshots to JPEG to reduce their size.

Split from a suggestion in: https://github.com/freeorion/freeorion/pull/3146#discussion_r475193626

### CODE REVIEW

**Comment by adrianbroher** [comment]
Hosting the screenshots on the freeorion domain is intentional as it does not bind us to github forever. See #2826 and #1657 .

**Comment by Siosm** [comment]
Just to be clear here, I do not advocate for any particular option. I did this one as suggested in another PR.

**Comment by Vezzra** [comment]
In these matters I'd defer the decision to @adrianbroher. If he says we should go with the screenshots hosted on the website, this overrules the suggestion made by @Cjkjvfnby.

So, unless @geoffthemedio (in his capacity as project lead) objects, I'd say close this PR and revert the relevant parts of #3146 to link to the screenshots on the website.

**Comment by geoffthemedio** [comment]
> close this PR and revert the relevant parts of #3146 to link to the screenshots on the website.

sounds reasonable...

**Comment by agrrr3** [comment]
+1 having the freeorion.org rather than the github link and @vezzra lets put the putting screenshots (with the right path) probably in the release checklist?

Else I do not know about the metainfo xml so much, my first reaction was to put screenshots into the build artifact so those would also be available offline.

**Comment by Siosm** [comment]
Closing this one. Thanks for the feedback!

**Comment by Cjkjvfnby** [comment]
@Siosm , sorry for confusing you.

**Comment by Siosm** [comment]
@Cjkjvfnby No worries!

**Comment by Vezzra** [comment]
> lets put the putting screenshots (with the right path) probably in the release checklist?

@agrrr3, yep, sounds reasonable.

**Pull request closed without merging**
