### PR TITLE
texture loading - use gil::read_image with ifstream to overcome unicode path issues

### LINKED ISSUE #4984: Failure to read textures with unicode path on Windows
One of issues I've seen trying to reproduce https://github.com/freeorion/freeorion/issues/4978

Texture loading fails with unicode path, at least if you don't set the "BETA" setting on recent Windows versions to default to UTF8 encoding.

Windows is internally based on wide char strings, so ideally you run wide char APIs to avoid encodings back and forth. Historically standard APIs would use chars not wide chars, leading to issues with interoperability with Windows. 

FreeOrion's attempt to go around that, converting from UTF16 to UTF8, fails bit short due to windows historically NOT supporting utf8 encoding in its char APIs. As alluded above, it's possible to force recent Windows versions to work with utf8 apps (assume utf8 encoding), but it's not a default setting, and still possibly leads to conversions back and forth

Luckily in case of texture loading, one can use gil::read_image that doesn't use string path (and possibly falls short to convert file path properly). Instead, you can use gil::read_image that uses pre-opened file stream. And you can open file stream using wide char file path either by using std::filesystem::path with std::ifstream (c++17), or use boost::filesystem::ifstream with boost::filesystem::path - that's my proposal to fix the issue

Of course other way would be to tell users to avoid paths with troublesome unicode characters, or force Windows to use the UTF8 encoding by default, but at least if there's a solution that leads to more direct usage of wide char windows APIs in an interoperable way, I'd go with that

### PR DESCRIPTION
**Pull request by Blue-Award**
…on Windows

FIxes https://github.com/freeorion/freeorion/issues/4984

I kept utf16to8 conversion for error reporting, otherwise to actually do gil::read_image, I'm using boost::filesystem::ifstream using given boost::filesystem::path without any conversions

Alternatively if allowed to use c++17, one could use std::filesystem and std::ifstream

I suppose I'd need someone on Linux to verify it still works there, I mean I don't see why it wouldn't, but can't exactly check myself. 

It works on windows without forcing it to understand UTF8 with "beta" setting on default locale (which is not a default option). It also still works with that setting turned on.

### CODE REVIEW

**Comment by Blue-Award** [comment]
note since the utf16to8 filename is not actively used if everything goes well in this fix, it's probably a good idea not to do the conversion before it's needed. Ideally I'd do something "lazy" but would need to look up how it's done in c++

or just have the conversion as helper method and call it in case of failure

or just ignore the issue and go with path.generic_string() without conversion, althoug if the codepage doesn't match then such string comes out with ????? question marks instead of legible code. With UTF8, at least you could read the log file (treated as utf8) with the path coming out properly

**Comment by geoffthemedio** [comment]
> I'm using boost::filesystem::ifstream using given boost::filesystem::path without any conversions
> 
> Alternatively if allowed to use c++17, one could use std::filesystem and std::ifstream

C++17 (or C++20 outside of GiGi code) is supported, but there were issues with switching to the std versions of libraries like filesystem, variant, and optional, so the boost versions are still used.

**Comment by geoffthemedio** [comment]
opening a filestream directly from a path instead of converting to a filename seems reasonable, but I'd like some test reports before merging this...

**Comment by Blue-Award** [comment]
I need to check cause it seems that instead of going through file stream, you could use path.native() directly in read_image (i.e. without doing utf conversion). Which should be less controversial change if it worked, no?

By test reports, do you mean somebody else confirming it works, particularly on Linux? Or MacOS? Cause yeah well I'd like to see it myself.

But first I'll chect the path.native() thing in read_image just... not right now

**Comment by geoffthemedio** [comment]
> I need to check cause it seems that instead of going through file stream, you could use path.native() directly in read_image (i.e. without doing utf conversion). Which should be less controversial change if it worked, no?

Not really... if you're passed in a path and it works to set up an fstream yourself with that path, then I don't see a problem doing that, and thereby avoiding any issues with how to format the path as a string and what the API you're calling expects...

**Comment by o01eg** [comment]
I've tested it on Linux with FreeOrion installed to incorrect utf-8 path and main screen and pedia works.

**Comment by geoffthemedio** [comment]
> I've tested it on Linux with FreeOrion installed to incorrect utf-8 path and main screen and pedia works.

What does "installed to incorrect utf-8 path" mean?

**Comment by Blue-Award** [comment]
> > I need to check cause it seems that instead of going through file stream, you could use path.native() directly in read_image (i.e. without doing utf conversion). Which should be less controversial change if it worked, no?
> 
> Not really... if you're passed in a path and it works to set up an fstream yourself with that path, then I don't see a problem doing that, and thereby avoiding any issues with how to format the path as a string and what the API you're calling expects...

OK, good. I've actually checked and.... gil::read_image with wide string still goes to narrow conversion that causes issue. So, file stream it is

I've made a lambda to utf16to8 of filename for error throwing/logging purposes, not to do that like, every time. Please bear with me until I update the PR. Tho I'm thinking if the logger gives woes with wide strings, then maybe it would be useful to have some helper function for that in general. Most places with path seem to go path.generic_string() but it causes ?????? marks in unicode paths, unless windows is set to UTF8 with this beta setting. I've seen some places that do utf16to8 seemingly specifically solely for logging, so those could use such helpers too

(and the fix to DebugLogger issue on Python init could use such helper too though there we're talking wchar_t* rather than path.native's wstring... so maybe such helper function could be in util/Logger.h)

**Comment by o01eg** [comment]
> What does "installed to incorrect utf-8 path" mean?

It means I put FreeOrion compiled files to directory that has bytes representing incorrect utf-8 name.

**Comment by Blue-Award** [comment]
When you say "incorrect utf-8 name" it suggests dealing with something that is somehow incorrect utf-8. I would expect there is nothing to fix there in such case? as in, that would be broken by design at very deep level, I'd expect OS not allowing something like that, even (but dunno)

I'd like if you checked the behavior with <i>correctly</i> encoded utf8 name, just with Unicode characters that are outside ASCII/your locale's ANSI. I mean even some random emoji as long as it is properly encoded should work

**Comment by o01eg** [comment]
> I'd expect OS not allowing something like that, even (but dunno)

Linux allows literally any byte sequence to be a path name, I just suppose it could fail some way like it fails on Windows.

> I'd like if you checked the behavior with correctly encoded utf8 name, just with Unicode characters that are outside ASCII/your locale's ANSI. I mean even some random emoji as long as it is properly encoded should work

In that case everything works on Linux

**Comment by Blue-Award** [comment]
OK I've tweaked the error logging to do actual job (utf conversion) only if relevant (error is being thrown), and verified it works both fine and when not fine

o01eg, could you specifically confirm that linux works good with this change, out of correct utf8 path?

Also if you remove some texture like the main splash screen, see if error is logged allright

**Comment by o01eg** [comment]
> o01eg, could you specifically confirm that linux works good with this change, out of correct utf8 path?

Yes, it works good with `master` and this PR regardless path.

> Also if you remove some texture like the main splash screen, see if error is logged allright

In both `master` and this PR I get missing image sign instead and line in console
```
Texture::Load passed non-existant path: /tmp/test/888фываолдж888/share/freeorion/default/data/art/splash.png
```

**Comment by geoffthemedio** [comment]
after adding Ш to the FreeOrion root path, and with the fix python init and this both applied, after renaming splash.png, I get on the console:
`Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrion?/default/data/art/splash.png`
and in the client log:
`23:07:00.858232 {0x00008e14} [error] client : ClientUI.cpp:1079 : Unable to load texture "C:/Users/g_top/Desktop/FOSDK14/FreeOrion?/default/data/art/splash.png"`

**Comment by Blue-Award** [comment]
Yes, so things are working as expected, right?

Perhaps you're worried about seeing question mark, however the places you report on use path.generic_string(). The ClientUI.cpp one I didn't touch (though it should have following line with reason: that shows the file name as coming from Texture.cpp throw BadFile), 

The other, output to console, I did not change in Texture.cpp as I am not convinced console on windows works well with utf8. Admittedly I didn't experiment much there. Maybe if cerr was redirected to file then utf8 output would make sense to then open the file as utf8. But I was expecting not much luck with showing things on actual live console

**Comment by Blue-Award** [comment]
crucially, with those two fixes, game launches and is playable. WIthout it, not so much. However it still has some issues I alluded to (unable to load music and fonts). Though if you have utf8 setting turned on windows, only the python bit is a gamebreaker, other things work without explicit utf8 conversion to fix them

**Comment by geoffthemedio** [comment]
> I did not change in Texture.cpp as I am not convinced console on windows works well with utf8.

after deleting splash.png,

`std::cerr << "Texture::Load passed non-existant path: " << loggable_path(path) << std::endl;`

surprisingly works on the developer console:

`Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrionШ/default\data\art\splash.png`

but not the standard console:

`Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrionð¿/default\data\art\splash.png`

whereas

`std::wcerr << "Texture::Load passed non-existant path: " << path.generic_wstring() << std::endl;`

truncates for both consoles:

`Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrion`

and

`std::cerr << "Texture::Load passed non-existant path: " << path.generic_string() << std::endl;`

replaces the wide char for both:

`Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrion?/default/data/art/splash.png`

**Comment by Blue-Award** [comment]
https://www.boost.org/doc/libs/master/libs/nowide/doc/html/index.html promises to deal with things like that, and freeorion sdk seems to have boost_nowide.dll at least for Windows.

Like you'd use [boost::nowide::cerr](https://www.boost.org/doc/libs/master/libs/nowide/doc/html/namespaceboost_1_1nowide.html#ae2fae63f1575764692d8ee82fb5a30ee) insead of std::cerr and it would be smart to call Console window winapi if attached to console window, or do different thing if output is redirected to a file

And apparently it could imbue itself into boost::filesystem to handle the stuff automagically (not into std::filesystem tho, but std::filesystem has some easier support of utf8 apparently tho not automagical)

that nowide doc even mentions the utf8 'beta' windows setting, and manifesting to switch to utf8 without the beta setting.

**Comment by geoffthemedio** [comment]
````
boost::nowide::cerr << "3 Texture::Load passed non-existant path: " << path.generic_string() << std::endl;
boost::nowide::cerr << "4 Texture::Load passed non-existant path: " << loggable_path(path) << std::endl;
````
on the standard windows console gives:
````
3 Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrion?/default/data/art/splash.png
4 Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrionШ/default\data\art\splash.png
````
and on the dev console gives:
````
3 Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrion?/default/data/art/splash.png
4 Texture::Load passed non-existant path: C:/Users/g_top/Desktop/FOSDK14/FreeOrionШ/default\data\art\splash.png
````

**Comment by geoffthemedio** [comment]
Can probably do something like:
````
 GG/src/Texture.cpp   | 11 +++++++++--
 util/Directories.cpp | 34 +++++++++++++++++++++-------------
 2 files changed, 30 insertions(+), 15 deletions(-)

diff --git a/GG/src/Texture.cpp b/GG/src/Texture.cpp
index 761c151e8..ee13e7eb1 100644
--- a/GG/src/Texture.cpp
+++ b/GG/src/Texture.cpp
@@ -24,6 +24,13 @@
 #include <GG/Texture.h>
 #include <GG/utf8/checked.h>
 
+#if __has_include(<boost/nowide/iostream.hpp>)
+#  include <boost/nowide/iostream.hpp>
+using boost::nowide::cerr;
+#else
+using std::cerr;
+#endif
+
 
 using namespace GG;
 
@@ -155,11 +162,11 @@ void Texture::Load(const boost::filesystem::path& path, bool mipmap)
     };
 
     if (!fs::exists(path)) {
-        std::cerr << "Texture::Load passed non-existant path: " << path.generic_string() << std::endl;
+        cerr << "Texture::Load passed non-existant path: " << loggable_path(path) << std::endl;
         throw BadFile("Texture file \"" + loggable_path(path) + "\" does not exist");
     }
     if (!fs::is_regular_file(path)) {
-        std::cerr << "Texture::Load passed non-file path: " << path.generic_string() << std::endl;
+        cerr << "Texture::Load passed non-file path: " << loggable_path(path) << std::endl;
         throw BadFile("Texture \"file\" \"" + loggable_path(path) + "\" is not a file");
     }
 
diff --git a/util/Directories.cpp b/util/Directories.cpp
index 1216a351b..d677f71f5 100644
--- a/util/Directories.cpp
+++ b/util/Directories.cpp
@@ -50,6 +50,15 @@
 #  include <windows.h>
 #endif
 
+#if __has_include(<boost/nowide/iostream.hpp>)
+#  include <boost/nowide/iostream.hpp>
+using boost::nowide::cerr;
+using boost::nowide::cout;
+#else
+using std::cerr;
+using std::cout;
+#endif
+
 namespace fs = ::boost::filesystem;
 
 namespace {
@@ -195,17 +204,17 @@ void CopyInitialResourceAndroid(const std::string& rel_path)
                      << "You can delete this file it is a one time message.\n\n";
 
         } catch(fs::filesystem_error const & e) {
-            std::cerr << "Error: Unable to migrate files from old config dir\n"
-                      << old_path << "\n"
-                      << " to new XDG specified config dir\n"
-                      << config_path << "\n"
-                      << " and data dir\n"
-                      << data_path << "\n"
-                      << " because " << e.what() << "\n";
+            cerr << "Error: Unable to migrate files from old config dir\n"
+                 << old_path << "\n"
+                 << " to new XDG specified config dir\n"
+                 << config_path << "\n"
+                 << " and data dir\n"
+                 << data_path << "\n"
+                 << " because " << e.what() << "\n";
             throw;
         }
 
-        std::cout << msg.str();
+        cout << msg.str();
     }
 #endif
 }
@@ -366,12 +375,12 @@ void InitDirs(std::string const& argv0, bool test)
         // executable is not the main binary in application bundle (i.e. Server or AI)
         uint32_t size = sizeof(bundle_dir);
         if (_NSGetExecutablePath(bundle_dir, &size) != 0) {
-            std::cerr << "_NSGetExecutablePath() failed: buffer too small; need size " << size << std::endl;
+            cerr << "_NSGetExecutablePath() failed: buffer too small; need size " << size << std::endl;
             exit(-1);
         }
     }
 
-    std::cout << "Bundle dir " << bundle_dir;
+    cout << "Bundle dir " << bundle_dir;
 
     bundle_path = fs::path(bundle_dir);
 
@@ -379,12 +388,11 @@ void InitDirs(std::string const& argv0, bool test)
         // search bundle_path for a directory named "FreeOrion.app", exiting if not found, else constructing a path to application bundle contents
         auto appiter = std::find(bundle_path.begin(), bundle_path.end(), "FreeOrion.app");
         if (appiter == bundle_path.end()) {
-            std::cerr << "Error: Application bundle must be named 'FreeOrion.app' and executables must not be called from outside of it." << std::endl;
+            cerr << "Error: Application bundle must be named 'FreeOrion.app' and executables must not be called from outside of it." << std::endl;
             exit(-1);
         } else {
-            for (auto piter = bundle_path.begin(); piter != appiter; ++piter) {
+            for (auto piter = bundle_path.begin(); piter != appiter; ++piter)
                 app_path /= *piter;
-            }
             app_path /= "FreeOrion.app/Contents";
         }
 ````

**Pull request merged**
