### PR TITLE
C++20 Prep

### PR DESCRIPTION
**Pull request by geoffthemedio**
-remove MSVS 2019 project files
-feature-macro gated defaulted operator<=> as operator== replacement
-move copysign workaround code into a header file
-comment out some not-working code
-bump CI build to Ubuntu 22.04
-bump CMake build to C++20

### CODE REVIEW

**Review by o01eg — APPROVED** [review]
Looks fine.

**Comment by o01eg** [comment]
Do Ubuntu 20.04 cause errors? It seems snap package based on it builds fine.

**Comment by o01eg** [comment]
Should we also drop MS VS 2019 from SDK release?

**Comment by geoffthemedio** [comment]
> Do Ubuntu 20.04 cause errors?

It reportedly has Boost 1.71 https://freeorion.org/forum/viewtopic.php?p=116076#p116076 https://github.com/freeorion/freeorion/actions/runs/4702585049/jobs/8340033020#step:11:19 https://github.com/boostorg/signals2/issues/50

**Comment by geoffthemedio** [comment]
> Should we also drop MS VS 2019 from SDK release?

Could, though not necessary yet, I think.

**Pull request merged**
