### PR TITLE
Draw starlanes and fleet in Godot client

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Review by Vezzra — COMMENTED** [review]
@o01eg,

this does build, but when I run the Godot client, I can't launch a "game".

If I use the Single Player Game Setup, I get an error as soon as I press OK, in `GameSetup.gd`, line 33:
```
    global.gs_seed = $ToplevelContainer/LeftContainer/Seed/LineEdit.text
```
`global.gs_seed` doesn't exist anymore, so trying to access this variable of course fails.

When I try to use "Quickstart", the program freezes for a few seconds, then becomes responsive again, but nothing else happens.

What is supposed to work and how?

The code looks ok, as far as I can tell at least. But I only glanced over it, and I don't really understand what a lot of the stuff actually does...

**Comment by o01eg** [comment]
@Vezzra  I forgot to test it from Single Player Game Setup but Quickstart works for me. You should place Godot binary to the same folder as `freeoriond`.

**Comment by Vezzra** [comment]
> You should place Godot binary to the same folder as `freeoriond`.

Tried that with Quickstart, nothing happens. Not even the short freeze I have when trying it from the IDE... 🤔

**Comment by o01eg** [comment]
What is in `freeorion-godot.log`?

**Comment by Vezzra** [comment]
Ok, finally got around to try again, with the latest version of the branch. Rebuilt everything, exported the Godot client app, put it into the build folder where all the other FO binaries are and ran it.

The Godot client launched successfully, but when I click "Quickstart" I get a CTD.

Log files (freeoriond.log and freeorion-godot.log) attached: [freeorion-logs.zip](https://github.com/freeorion/freeorion/files/5679332/freeorion-logs.zip)

**Comment by o01eg** [comment]
I didn't exported project but it looks like client crashed:

freeorion-godot.log:
```
...
14:15:10.149804 {0x00007fc623e6d7c0} [debug] godot : GodotClientApp.cpp:252 : Sending host SP setup message
```

freeoriond.log
```
14:15:10.243888 {0x00007feace15e740} [error] FSM : ServerFSM.cpp:286 : A Disconnection event was not handled by any of these states : [4Idle].  It is being ignored.
```

**Comment by Vezzra** [comment]
@o01eg,

> I didn't exported project

Then what do you mean when you said I should place the FO Godot client "binary" in the same folder as `freeoriond` and launch it from there? Without exporting the Godot project I don't get a binary...?

> but it looks like client crashed

Makes sense, but now what? If I understand correctly, on your (Linux) system the Godot client works, you get to the starmap screen without crashing.

If you don't export the project, but also don't run from within the Godot IDE, then what exactly are you doing? How do you run the Godot client? Maybe if I can reproduce exactly what you do, I can get it to run on my system as well...

**Comment by o01eg** [comment]
I move `godot` binary to the folder with `freeoriond` and open project or launch it from that `godot`.

**Comment by Vezzra** [comment]
Oh, ok. Well, just tried that too (copied the godot binary to the folder where the FO build artifacts have been placed, launched Godot, loaded the Godot client project and run the client). Same result. Clicking "Quickstart" crashes the app (in this case it crashes back into the IDE).

Content of log files also the same.

A second try to launch the client results in clicking "Quickstart" doing nothing, probably because the first crash leaves the `freeoriond` process running. If I kill `freeoriond` and try again, "Quickstart" crashes again.

I'm on Ubuntu 18.04 LTS. Any idea what's going on...?

**Comment by o01eg** [comment]
Hard to say, would be nice to get backtrace where crash happens.

**Comment by o01eg** [comment]
Next line I get in godot log is:
```
08:43:04.763582 {0x00007ff81eb94e80} [debug] godot : GodotClientApp.cpp:252 : Sending host SP setup message
08:43:04.763779 {0x00007ff81eb94e80} [debug] godot : GodotClientApp.cpp:254 : GodotClientApp::NewSinglePlayerGame done
```

**Comment by Vezzra** [comment]
I see.

I'm sorry, I don't really know how to proceed. I don't know how to get a backtrace for a crashing Godot app. And I currently don't have the time to track down the exact line where the crash happens the hard way. Maybe in a week or so, I have another vacation (hopefully an undisturbed one this time) around Christmas and New Year for two weeks.

**Comment by o01eg** [comment]
Looks like something in `ClientNetworking::SendMessage` is broken but its hard to detect. Would be nice to try with `network` logger set to trace.

**Comment by Vezzra** [comment]
> Looks like something in ClientNetworking::SendMessage is broken but its hard to detect. Would be nice to try with network logger set to trace.

Ok, I'll try to get around to that next week.

**Comment by o01eg** [comment]
Maybe add https://github.com/bitwes/Gut and write some unit tests so I could try to debug it on Ubuntu 18.04 LTS in Docker without GUI.

**Comment by Vezzra** [comment]
@o01eg, here are the logs with log level set for everything to "trace". Don't know how much that helped, though:

[logs.zip](https://github.com/freeorion/freeorion/files/5754681/logs.zip)

However, I had to hack the C++ code to set all loggers to "trace". For some reason, setting the respective entries in `config.xml` didn't do anything.

**Comment by o01eg** [comment]
Looks like it doesn't change anything.

**Comment by Vezzra** [comment]
> Maybe add https://github.com/bitwes/Gut and write some unit tests so I could try to debug it on Ubuntu 18.04 LTS in Docker without GUI.

I'm sorry, but I don't know how to do that - I've never done anything with unit tests, on any platform with any language. I know that concepts exists, and the most basic idea what it's supposed to do, but that's it. I don't even know where to begin to set up unit tests in Godot (using that tool), so that that would yield any useful information... :disappointed: 

There has to be a way so you can reproduce the issue on your system.

Sorry for not being able to be more helpful, but I'm hitting the limits of my rather mediocre programming skills here...

The only thing I can do is to try and test how the Godot client works on my Mac and Windows systems.

**Comment by Vezzra** [comment]
> Looks like it doesn't change anything.

I was afraid of that. This is quite frustrating... :disappointed:

**Comment by o01eg** [comment]
Added unit test. To call it launch next command

```bash
<freeorion sources>/godot/client $ <freeoriond binaries folder>/godot.x11.opt.tools.64 --verbose -d -s --path $PWD addons/gut/gut_cmdln.gd -gtest=res://test/integration/quickstart.gd -gexit

**Comment by o01eg** [comment]
Managed to reproduce it on dockered Ubuntu 18.04

**Comment by o01eg** [comment]
Ok, something happened within Godot:

```cpp
Thread 1 "Godot_v3.2.3-st" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f78ca6dc921 in __GI_abort () at abort.c:79
#2  0x00007f78ba778b15 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00007f78baa202ba in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00000000028fc7ab in _Unwind_RaiseException_Phase2 ()
#5  0x0000000000000000 in ?? ()
(gdb) thread apply all bt

Thread 19 (Thread 0x7f789dffb700 (LWP 11014)):
#0  0x00007f78ca7bda47 in epoll_wait (epfd=9, events=0x7f789dffa670, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007f78c939a49d in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) () from /freeorion/godot/client/bin/linux.64/libfreeoriongodot.so
#2  0x00007f78c939e5d8 in boost::asio::detail::task_io_service::run(boost::system::error_code&) () from /freeorion/godot/client/bin/linux.64/libfreeoriongodot.so
#3  0x00007f78c9391db4 in ClientNetworking::Impl::NetworkingThread(std::shared_ptr<ClientNetworking const>) () from /freeorion/godot/client/bin/linux.64/libfreeoriongodot.so
#4  0x00007f78c939f77a in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, ClientNetworking::Impl, std::shared_ptr<ClientNetworking const> >, boost::_bi::list2<boost::_bi::value<ClientNetworking::Impl*>, boost::_bi::value<std::shared_ptr<ClientNetworking const> > > > >::run() () from /freeorion/godot/client/bin/linux.64/libfreeoriongodot.so
#5  0x00007f78bb37d416 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.62.0
#6  0x00007f78ca4846db in start_thread (arg=0x7f789dffb700) at pthread_create.c:463
#7  0x00007f78ca7bd71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 18 (Thread 0x7f78c8123700 (LWP 11012)):
#0  0x00007f78ca7807a0 in __GI___nanosleep (requested_time=0x7f78c8122ba0, remaining=0x7f78c8122ba0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000000887f1b in OS_Unix::delay_usec(unsigned int) const [clone .constprop.13855] ()
#2  0x00007f78c93ce28e in godot::___godot_icall_void_int (inst=<optimized out>, arg0=<optimized out>, mb=<optimized out>) at /freeorion/godot/godot-cpp/include/gen/__icalls.hpp:1657
#3  godot::OS::delay_msec (this=<optimized out>, msec=<optimized out>) at /freeorion/godot/godot-cpp/src/gen/OS.cpp:189
#4  0x00007f78c93a640c in godot::GDFreeOrion::network_thread() () from /freeorion/godot/client/bin/linux.64/libfreeoriongodot.so
#5  0x00007f78c93a7e17 in godot_variant godot::__wrapped_method<godot::GDFreeOrion, void>(void*, void*, void*, int, godot_variant**) () from /freeorion/godot/client/bin/linux.64/libfreeoriongodot.so
#6  0x00000000024672b2 in NativeScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) ()
#7  0x0000000000000030 in ?? ()
#8  0x00007f78c8122e08 in ?? ()
#9  0x0000000100000050 in ?? ()
#10 0x0000000005afbd38 in ?? ()
#11 0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7f78cab25700 (LWP 10998)):
#0  0x00007f78ca7807a0 in __GI___nanosleep (requested_time=0x7f78cab24dd0, remaining=0x7f78cab24dd0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000000887f1b in OS_Unix::delay_usec(unsigned int) const [clone .constprop.13855] ()
#2  0x0000000000fcb09b in AudioDriverDummy::thread_func(void*) ()
#3  0x0000000000000020 in ?? ()
#4  0x0000000000002d59 in ?? ()
#5  0x00000000050ee0b0 in ?? ()
#6  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7f78cab66700 (LWP 10997)):
#0  0x00007f78ca48d7c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x50a7498) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x50a7498, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f78ca48d8b8 in __new_sem_wait_slow (sem=0x50a7498, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000218374d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x00000000050a7520 in ?? ()
#5  0x0000000000fe774c in VisualServerScene::_gi_probe_bake_threads(void*) ()
#6  0x00000000050a7520 in ?? ()
#7  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7f78caca8700 (LWP 10996)):
#0  0x00007f78ca48d7c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x501b2a8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x501b2a8, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f78ca48d8b8 in __new_sem_wait_slow (sem=0x501b2a8, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000218374d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x000000000501b2e0 in ?? ()
#5  0x0000000000af19a6 in _IP_ResolverPrivate::_thread_function(void*) ()
#6  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f78caca9b80 (LWP 10992)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f78ca6dc921 in __GI_abort () at abort.c:79
#2  0x00007f78ba778b15 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00007f78baa202ba in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00000000028fc7ab in _Unwind_RaiseException_Phase2 ()
#5  0x0000000000000000 in ?? ()
```

**Comment by o01eg** [comment]
```
(gdb) l
131	}
132	
133	Message HostSPGameMessage(const SinglePlayerSetupData& setup_data) {
134	    std::ostringstream os;
135	    {
136	        std::string client_version_string = FreeOrionVersionString();
137	        freeorion_xml_oarchive oa(os);
138	        oa << BOOST_SERIALIZATION_NVP(setup_data)
139	           << BOOST_SERIALIZATION_NVP(client_version_string);
140	    }
(gdb) n
137	        freeorion_xml_oarchive oa(os);
(gdb) p version_string
No symbol "version_string" in current context.
(gdb) p client_version_string
$2 = "v0.4.10+ godot-fleet-starlanes-draw [build 2020-12-08.68841e0] CMake"
(gdb) n

Thread 1 "Godot_v3.2.3-st" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
```

**Comment by Vezzra** [comment]
@o01eg,

> Managed to reproduce it on dockered Ubuntu 18.04

Having succeeded in reproducing the crash, do you still need me to run this command:
```
<freeorion sources>/godot/client $ <freeoriond binaries folder>/godot.x11.opt.tools.64 --verbose -d -s --path $PWD addons/gut/gut_cmdln.gd -gtest=res://test/integration/quickstart.gd -gexit
```
Or is there anything else I shall try on my system?

**Comment by o01eg** [comment]
I've build Godot 3.2.3 from sources and couldn't reproduce it. Only downloaded version failed.

**Comment by o01eg** [comment]
The deepest source of crash I got:
```
(gdb) l
116	// preserve correct static polymorphism.
117	class BOOST_SYMBOL_VISIBLE xml_oarchive :
118	    public xml_oarchive_impl<xml_oarchive>
119	{
120	public:
121	    xml_oarchive(std::ostream & os, unsigned int flags = 0) :
122	        xml_oarchive_impl<xml_oarchive>(os, flags)
123	    {
124	        if(0 == (flags & no_header))
125	            init();
(gdb) p no_header
$5 = boost::archive::no_header
(gdb) n
125	            init();
(gdb) s

Thread 1 "Godot_v3.2.3-st" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Нет такого файла или каталога.
```

**Comment by o01eg** [comment]
I've opened issue on Godot https://github.com/godotengine/godot/issues/44987 about crash.

@Vezzra Could you try to build Godot 3.2.3 from sources to continue development?

**Comment by Vezzra** [comment]
> Could you try to build Godot 3.2.3 from sources to continue development?

Ugh. I'm not exactly thrilled by that prospect, but if it's necessary, I can give it a try. Might take a while until I get around to that though, so I have to ask for a bit patience...

**Comment by Vezzra** [comment]
@o01eg,

sorry it took so long, but I took me several tries to get things working (first I had troubles with building Godot, then I managed to confuse myself with all the different project folders I've accumulated, etc.).

But I finally managed to "start" a game from within the Godot FO client. As you said, the scale is off, you need to zoom out quite a bit to see anything. And, at least when I tried it, there have been only 4 systems and one fleet, not exactly what I expected from a default quickstart game.

Anyway, so far, so good! 👍

**Comment by o01eg** [comment]
Could we merge it?

> And, at least when I tried it, there have been only 4 systems and one fleet, not exactly what I expected from a default quickstart game.

Doesn't player see only home system and ones linked to it?

**Comment by Vezzra** [comment]
@o01eg,

> Could we merge it?

Yes, go ahead. I'll leave doing the merge to you, as it's a quite massive change, and I don't know if you want to do some cleanup first. So, whenever you feel the branch is ready, merge it.

> Doesn't player see only home system and ones linked to it?

Ah, yes, of course. Didn't think that the Godot client would take that in account already, and expected to see the whole map.

**Comment by o01eg** [comment]
> Ah, yes, of course. Didn't think that the Godot client would take that in account already, and expected to see the whole map.

I draw all systems server sends to client. Visibility for objects is checked on the server.

**Pull request merged**
