### PR TITLE
Fix MSVC link error

### PR DESCRIPTION
**Pull request by wheals**
Before this, I consistently ran into the following error:
```
4>UniverseWrapper.obj : error LNK2005: "class Universe const volatile * __cdecl boost::get_pointer<class Universe const volatile >(class Universe const volatile *)" (??$get_pointer@$$CDVUniverse@@@boost@@YAPDVUniverse@@PDV1@@Z) already defined in AIWrapper.obj
4>../../FreeOrionCA.exe : fatal error LNK1169: one or more multiply defined symbols found
```
MSVC version: Microsoft Visual Studio Community 2015 14.0.24720.00 Update 1

Someone else who uses MSVC should probably test this. For what it's worth, [this comment](https://github.com/freeorion/freeorion/issues/1246#issuecomment-275485658) suggests the functions are no longer necessary with the removal of TemporaryPtr.

I also added an update to my preferred crediting since this is my first PR in a while, didn't want to cause the bother of a separate PR.

### CODE REVIEW

**Comment by wheals** [comment]
Judging by the AppVeyor failure, seems at least some versions of MSVC need the definitions after all... :( No idea how to detect whether they're necessary, though.

**Comment by geoffthemedio** [comment]
With this patch applied, I get a bunch of link errors, similar to the AppVeyor results.

**Comment by wheals** [comment]
Seems that the function definitions are necessary [specifically for MSVC2015 Update 3](http://stackoverflow.com/questions/38261530/unresolved-external-symbols-since-visual-studio-2015-update-3-boost-python-link). I'll update and make sure that that fixes the link error without needing to change the code, then close the PR.

**Comment by wheals** [comment]
OK, I upgraded to Update 3 (14.0.25431.01), and that fixed *most* of the errors, but one of them still remained. I'll try pushing the fix for it now, and see if it also works on other machines.

If not, maybe changing the `#if` to use [_MSC_FULL_VER](https://msdn.microsoft.com/en-us/library/b0084kay.aspx) will help.

**Comment by adrianbroher** [comment]
> OK, I upgraded to Update 3 (14.0.25431.01), and that fixed most of the errors, but one of them still remained.

Have you tried ~~turning it off and on again~~ to do a clean build?  It's maybe possible that the template code already is instantiated somewhere in an object file causing the multiple symbol definition.

**Comment by wheals** [comment]
I did do a clean build after upgrading, but I can try cleaning the FreeOrionCA and FreeOrionD projects again and trying yet another time (hesitant to clean out everything since my computer tends to choke while compiling the parser -- it actually crashed when I did the clean build earlier, and that might have messed it up).

**Comment by geoffthemedio** [comment]
You can reduce the number of parallel builds in the options somewhere. Might help get the parser to build.

**Comment by wheals** [comment]
Seems a clean and a rebuild fixed it. Sorry for the trouble.

**Pull request closed without merging**
