### PR TITLE
packaging: Update releases in appdata metainfo

### PR DESCRIPTION
**Pull request by travier**
packaging: Update releases in appdata metainfo

---

github/ISSUE_TEMPLATE/release: Clarify metadata release update

Clarify that new releases have to be added to the metadata independently
of screenshots updates.

### CODE REVIEW

**Comment by travier** [comment]
I'm updating the Flatpak build on Flathub.

**Comment by o01eg** [comment]
@Vezzra Should `v0.5` milestone be closed in case of bug-fix release?

**Comment by Vezzra** [comment]
> @Vezzra Should `v0.5` milestone be closed in case of bug-fix release?

We have always done it this way. Bugfix releases usually contain fixes backported from master, so the fixes themselves are considered part of the next major release (0.5.1 in this case).

**Comment by travier** [comment]
> @Vezzra Should `v0.5` milestone be closed in case of bug-fix release?

Is this related to this PR? Should I change something?

**Comment by o01eg** [comment]
> > @Vezzra Should `v0.5` milestone be closed in case of bug-fix release?
> 
> Is this related to this PR? Should I change something?

No, it's fine. I suppose just it should go to bug-fix release and release template.

**Comment by travier** [comment]
I've updated the release issue template.

**Comment by Vezzra** [comment]
Merged & cherry-picked to the 0.5 release branch

**Pull request merged**
