### PR TITLE
Improve server polling timeout consistency

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This PR are some tweaks to the network polling, that I meant to push earlier.

The PR switches some clocks from posix clock to boost::chrono, so that all clocks in freeorion are of one type.

The PR makes the network polling more reasonable, so that the polling interval is 10ms, about one refresh interval.

It might address bug #1371, but I have not tested it.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
seems to work fine for me

**Comment by Vezzra** [comment]
On OSX I can't start a game with this PR, connecting to the server times out.

Log files: [logfiles.zip](https://github.com/freeorion/freeorion/files/817044/logfiles.zip)

**Comment by LGM-Doyle** [comment]
@Vezzra, thanks for the log files.  I'm working on a fix.

**Comment by LGM-Doyle** [comment]
This PR should be reviewed before #1373 and #1375.

I have remove the polling code, which should not have been there since the `boost::asio` code already polls internally.  That was a misunderstanding in the current `HumanClientApp`.

I've also converted the asio interface to `std::chrono`, since the `boost::asio` code now defaults to `std::chrono` and this avoid some long redefinitions of timers.

@Vezzra I hope it now works on OSX again.

**Comment by adrianbroher** [comment]
> since the boost::asio code now defaults to std::chrono

With what definition of `now`?

**Comment by LGM-Doyle** [comment]
> With what definition of now?

Boost 1.49 if I did not misread their revision history.

**Comment by Vezzra** [comment]
@LGM-Doyle, nope, unfortunately I'm still unable to start a game on OSX with that PR (commit 47c20e25c55842574359c1b14538d55650a7f9bb). Still getting the same timeout error when the client tries to connect to the server.

Logfiles: [logfiles.zip](https://github.com/freeorion/freeorion/files/827207/logfiles.zip)

**Comment by LGM-Doyle** [comment]
@Vezzra I still don't know what the issue is.  

I've added more debugging message to this PR.  Could you try it and provide logs again, including any AI logs, if they exist?

The problem is not be directly related to this PR, since issue #1371 pre-dates this PR.

I think something changed with OSX in the relevant time period.

I've added a progressively backed off delay to the connection retry attempts in case the original round trip time through the SDL timer was effectively creating a delay in the new game connections, but a shorter delay in the load game connections.  If this works then we can keep it.

Otherwise, could you also check your system logs and firewall logs for any messages coinciding with starting up freeorion with this PR.

Thanks.

**Comment by Vezzra** [comment]
>  Could you try it and provide logs again, including any AI logs, if they exist?

As expected no AI logs, but I think `freeorion.log` might contain some interesting info. Apparently all connection attempts except the very first fail because of an "invalid argument" error. The first one apparently simply fails because the server isn't ready yet.

Log files: [logfiles.zip](https://github.com/freeorion/freeorion/files/828548/logfiles.zip)

> The problem is not be directly related to this PR, since issue #1371 pre-dates this PR.
>
> I think something changed with OSX in the relevant time period.

Well, all I can say that I can at least start games with builds of master. So something you did in this PR changed things in a way that you can't even start a game on OSX now.

Obviously something doesn't work on OSX the same way it does on Windows and Linux...

> Otherwise, could you also check your system logs and firewall logs for any messages coinciding with starting up freeorion with this PR.

Can you check the FO logs I provided first, if anything in there gives you a relevant clue? Before I have to start hacking and digging through the jungle... 😨  😉 

For what it's worth, the issue turns up even when I switch off the OS firewall, so I guess the firewall isn't the culprit here.

**Comment by LGM-Doyle** [comment]
@Vezzra thanks for the logs.  I'd like to try again.

I've refactored the connect attempts so that they close the socket before every attempt to connect.

If this works I'll remove the noisy debugging and rebase #1375 onto it.

Based on the comments in #1371, there is a difference between the quick and normal start game and the load game in terms of connecting on OSX.  I think that once we figure out what that difference is then both this PR  and that issue will be fixed.

**Comment by Vezzra** [comment]
@LGM-Doyle, success. I'm now able to start new and load saved games with this PR. 👍

**Comment by LGM-Doyle** [comment]
Thanks for testing.

**Comment by Vezzra** [comment]
Anything preventing this from being merged?

**Comment by geoffthemedio** [comment]
if it runs, it's probly OK

**Comment by LGM-Doyle** [comment]
#1375 contains all of the changes in #1374.  If #1375 is about to be merged, it will save one rebase to just wait a day or two.

**Comment by Vezzra** [comment]
Ok, that's fine. 👍

**Comment by Vezzra** [comment]
@LGM-Doyle, #1375 has been merged, which means we can close this one, right? I suggest to tag it as "follow up" and provide a reference to #1375 as the superseding PR.

**Comment by LGM-Doyle** [comment]
Included in #1375, which was merged.

**Pull request closed without merging**
