### PR TITLE
BSD build update, Adding DragonFlyBSD and NetBSD.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg any comments on this?

**Comment by o01eg** [comment]
Looks fine but need to be rebased

**Comment by geoffthemedio** [comment]
Rebased as https://github.com/freeorion/freeorion/tree/BSD_Rebase

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/0efd594d04ec9b8d38dbab295bc417339e60bd02

**Pull request closed without merging**
