### PR TITLE
Remove tabs from text files

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
I replace tabs to 4 spaces in *.txt files inside default (except string tables).

### CODE REVIEW

**Comment by adrianbroher** [comment]
There are some wrong indentation in 97b266b.

**Comment by Cjkjvfnby** [comment]
In editor it looks for me same as I see it before. (github show tab wider then 4 spaces). I don't sure if it is my patch brakes indentation. Can you point exact place?

**Comment by adrianbroher** [comment]
> Can you point exact place?

See the notes in commit 97b266b

**Comment by Dilvish-fo** [comment]
Marcel, I see notes above that you had comments on the code, but whether following the links you posted or the commits tab above, I do not find any actual comments with the code (which I have had no trouble finding in other cases).  Did you perhaps over-zealously delete duplicate comments, or am I doing something wrong?  
Also, it seems this is another case where the second commit of this PR [should ideally get squashed into the first](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) while it is still pending, yes?

**Comment by adrianbroher** [comment]
> Did you perhaps over-zealously delete duplicate comments, or am I doing something wrong?

My bad, the link I posted does nothing. Follow the underlined link in the image.

follow-link

**Comment by Cjkjvfnby** [comment]
Finally find you comments. I check some of them and see that this issues not related to changing tabs to spaces. I add fixes.

@Dilvish-fo  I can squash commit but don't sure if I can push this history change. :)  It is not trouble to make new PR with single commit changes.

**Comment by Dilvish-fo** [comment]
I think there is one remaining indent issue -- line 100-101 of buildings.txt should not have been dedented, it looks like to me.

As for the squash commit issue, I think that since this PR is still pending it's not like a force push to this main repository, it would be just you making local changes to your own repo so that when the PR afterwards gets merged it brings the condensed history not your original longer one (at least, that's how I understand it)

**Comment by Dilvish-fo** [comment]
Cj, the indents look fine to me now.  Normally there should be no trouble quashing multiple commits of a pending PR into a single commit & for little cleanup commits that would be the best practice, and better then just submitting a new PR that would lose the commentary (and wouldn't you still have to rebase anyways?).  Marcel hasn't commented here but in [one of Morlic's PRs](https://github.com/freeorion/freeorion/pull/12) Marcel agreed about the squashing and Morlic had no trouble squashing his two commits into one.  It could be your merge from master complicates it?  I'll bring this issue up in the branch management thread on our forums so we can try to get a consensus on such things.

**Comment by Cjkjvfnby** [comment]
@Dilvish-fo  Lets try to do next:

You add my repository as remote (same as adding upstream)
You fetch this branch.
You checkout it as local branch.
After that I will squash commits and push.
You will pull this branch

**Comment by Dilvish-fo** [comment]
I'm not understanding why you think this would be a better process.   This issue seems to me to be related to the post I just made in the git Q&A thread on our forums, could you follow up there (or make a new thread just for this topic) with an explanation for this proposed handling so we can get a consensus on what process to use?

**Comment by Cjkjvfnby** [comment]
I just want to reproduce situation with history rewriting.

**Comment by Dilvish-fo** [comment]
Ah, I guess perhaps I had misunderstood what you meant by "You will pull this branch".  So by checking out your branch locally I just preserve the history as a bit of a potential backup in case something goes wrong with the squash?  And by "You will pull this branch" you were just referring to me merging this PR?  That sounds fine, if I'm understanding right.  I have done the first step

> git checkout --track cj/remove-tabs-from-text-files
> Branch remove-tabs-from-text-files set up to track remote branch remove-tabs-from-text-files from cj

**Comment by Cjkjvfnby** [comment]
All I want that you have my branch as local. (You already done it.)
After that I will change its history and push it. (I will do it this evening ~10h from now)
Then you update you local branch again.  And check commit history (`gitk`, `git log`).  I dont know what really happend.  May be it will be trivial since you dont have any changes.  Maybe not.     You can checkout my branch couple of times with different names. One just as is. For second merge master into it, for third add commit with changes in this code.  And pull them one by one.

Rewriting history can couse troubles. Before making this as rule we should get this troubles.

PS. I already have a backup for this code in special branch, rebased and squashed.

**Comment by Dilvish-fo** [comment]
Cj, if you want to experiment with the squashing rather than just doing it, you can do that all yourself with extra branches, I don't think you need me to help you with it.

**Comment by Cjkjvfnby** [comment]
@Dilvish-fo, you right squashing is very private operation and I cant take you with me into it. It all was about handle rewritten history.

**Comment by Cjkjvfnby** [comment]
I made other pr with this changes with pretty history.

**Pull request closed without merging**
