### PR TITLE
Add testing and RelWithDebugInfo for cmake for windows

### PR DESCRIPTION
**Pull request by o01eg**
Yet another try to fix Cmake for Windows MS VS made on top @dlshcbmuipmam's #2388
Adds RelWithDebugInfo configuration and fix test compilation

Tests with standard sources layout in FreeOrion SDK x64 v141
```
cmake -DBUILD_TESTING=On -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DPYTHON_EXECUTABLE=..\python.exe ..
cmake --build . --config RelWithDebInfo
```

### CODE REVIEW

**Comment by o01eg** [comment]
I've successfully launched freeorion.exe and played some game.
`Unittest`s could be enabled but compilation already took near one hour limit also it requires to have `boost_unit_test_framework.dll` in `PATH`.

**Comment by o01eg** [comment]
Also I catch segfault in a smoke test within parser library but I couldn't catch it without test:

```
fo_systemtest_game.exe!boost::spirit::traits::inhibit_clear_queue<class boost::spirit::lex::lexertl::functor<struct boost::spirit::lex::lexertl::position_token<class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > >,struct boost::mpl::vector<bool,int,double,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na,struct boost::mpl::na>,struct boost::mpl::bool_<1>,unsigned __int64>,class boost::spirit::lex::lexertl::detail::data,class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > >,struct boost::mpl::bool_<1>,struct boost::mpl::bool_<1> > >(class boost::spirit::lex::lexertl::iterator<class boost::spirit
fo_systemtest_game.exe!??@0b74d5a39e4dac0168082d1dc1c7ae93@()
fo_systemtest_game.exe!parse::detail::parse_file<struct `anonymous namespace'::grammar,class GameRules>(struct parse::lexer const &,class boost::filesystem::path const &,class GameRules &)
fo_systemtest_game.exe!parse::game_rules(class boost::filesystem::path const &)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Invoker_functor::_Call(GameRules(*)(const boost::filesystem::path &) &&)
[Внедренный фрейм] fo_systemtest_game.exe!std::invoke(GameRules(*)(const boost::filesystem::path &) &&)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Invoke_stored_explicit(std::tuple<GameRules (__cdecl*)(boost::filesystem::path const &),boost::filesystem::path> &&)Строка 622
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\mutex(622)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Invoke_stored(std::tuple<GameRules (__cdecl*)(boost::filesystem::path const &),boost::filesystem::path> &&)Строка 630
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\mutex(630)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Fake_no_copy_callable_adapter<GameRules (__cdecl&)(boost::filesystem::path const &),boost::filesystem::path const &>::operator()()Строка 1796
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\future(1796)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Invoker_functor::_Call(std::_Fake_no_copy_callable_adapter<GameRules (__cdecl&)(boost::filesystem::path const &),boost::filesystem::path const &> &)
[Внедренный фрейм] fo_systemtest_game.exe!std::invoke(std::_Fake_no_copy_callable_adapter<GameRules (__cdecl&)(boost::filesystem::path const &),boost::filesystem::path const &> &)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Invoker_ret<GameRules,0>::_Call(std::_Fake_no_copy_callable_adapter<GameRules (__cdecl&)(boost::filesystem::path const &),boost::filesystem::path const &> &)
fo_systemtest_game.exe!std::_Func_impl_no_alloc<std::_Fake_no_copy_callable_adapter<GameRules (__cdecl&)(boost::filesystem::path const &),boost::filesystem::path const &>,GameRules>::_Do_call()
[Внедренный фрейм] fo_systemtest_game.exe!std::_Func_class<GameRules>::operator()()Строка 556
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\future(556)
fo_systemtest_game.exe!std::_Packaged_state<GameRules __cdecl(void)>::_Call_immediate()Строка 556
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\future(556)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Func_class<void>::operator()()
[Внедренный фрейм] fo_systemtest_game.exe!Concurrency::details::_MakeVoidToUnitFunc::__l2::<lambda_052e919cc0e5399df76dff3972c0cac1>::operator()()Строка 2348
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\ppltasks.h(2348)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Invoker_functor::_Call(Concurrency::details::_MakeVoidToUnitFunc::__l2::<lambda_052e919cc0e5399df76dff3972c0cac1> &)
[Внедренный фрейм] fo_systemtest_game.exe!std::invoke(Concurrency::details::_MakeVoidToUnitFunc::__l2::<lambda_052e919cc0e5399df76dff3972c0cac1> &)
[Внедренный фрейм] fo_systemtest_game.exe!std::_Invoker_ret<unsigned char,0>::_Call(Concurrency::details::_MakeVoidToUnitFunc::__l2::<lambda_052e919cc0e5399df76dff3972c0cac1> &)
fo_systemtest_game.exe!std::_Func_impl_no_alloc<<lambda_052e919cc0e5399df76dff3972c0cac1>,unsigned char>::_Do_call()
[Внедренный фрейм] fo_systemtest_game.exe!std::_Func_class<unsigned char>::operator()()Строка 1465
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\ppltasks.h(1465)
[Внедренный фрейм] fo_systemtest_game.exe!Concurrency::task<unsigned char>::_InitialTaskHandle<void,<lambda_c7f79b24b8b68e2d375105fe248774b5>,Concurrency::details::_TypeSelectorNoAsync>::_LogWorkItemAndInvokeUserLambda(std::function<unsigned char __cdecl(void)>)Строка 3517
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\ppltasks.h(3517)
[Внедренный фрейм] fo_systemtest_game.exe!Concurrency::task<unsigned char>::_InitialTaskHandle<void,<lambda_c7f79b24b8b68e2d375105fe248774b5>,Concurrency::details::_TypeSelectorNoAsync>::_Init(Concurrency::details::_TypeSelectorNoAsync)Строка 3537
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\ppltasks.h(3537)
[Внедренный фрейм] fo_systemtest_game.exe!Concurrency::task<unsigned char>::_InitialTaskHandle<void,<lambda_c7f79b24b8b68e2d375105fe248774b5>,Concurrency::details::_TypeSelectorNoAsync>::_Perform()Строка 3522
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\ppltasks.h(3522)
fo_systemtest_game.exe!Concurrency::details::_PPLTaskHandle<unsigned char,Concurrency::task<unsigned char>::_InitialTaskHandle<void,<lambda_c7f79b24b8b68e2d375105fe248774b5>,Concurrency::details::_TypeSelectorNoAsync>,Concurrency::details::_TaskProcHandle>::invoke()Строка 1465
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\ppltasks.h(1465)
fo_systemtest_game.exe!Concurrency::details::_TaskProcHandle::_RunChoreBridge(void * _Parameter)Строка 160
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\pplwin.h(160)
fo_systemtest_game.exe!Concurrency::details::_DefaultPPLTaskScheduler::_PPLTaskChore::_Callback(void * _Args)Строка 51
	в c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\pplwin.h(51)
msvcp140.dll!000007fee98f9864()
ntdll.dll!0000000077b1ceb4()
ntdll.dll!0000000077c09c73()
kernel32.dll!0000000077a0570d()
ntdll.dll!0000000077b6385d()
```

Main thread:
```
[Внешний код]
fo_systemtest_game.exe!boost::asio::detail::win_iocp_io_context::do_one(unsigned long msec, boost::system::error_code & ec)Строка 381
	в d:\devel\freeorionsdk_10_msvc-v141\include\boost\asio\detail\impl\win_iocp_io_context.ipp(381)
[Внедренный фрейм] fo_systemtest_game.exe!boost::asio::detail::win_iocp_io_context::run(boost::system::error_code &)Строка 163
	в d:\devel\freeorionsdk_10_msvc-v141\include\boost\asio\detail\impl\win_iocp_io_context.ipp(163)
[Внедренный фрейм] fo_systemtest_game.exe!boost::asio::io_context::run()Строка 62
	в d:\devel\freeorionsdk_10_msvc-v141\include\boost\asio\impl\io_context.ipp(62)
fo_systemtest_game.exe!ClientNetworking::Impl::ConnectToServer(const ClientNetworking * const self, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & ip_address, const std::chrono::duration<__int64,std::ratio<1,1000> > & timeout, bool expect_timeout)Строка 369
	в d:\devel\freeorionsdk_10_msvc-v141\freeorion\network\clientnetworking.cpp(369)
fo_systemtest_game.exe!ClientNetworking::Impl::ConnectToLocalHostServer(const ClientNetworking * const self, const std::chrono::duration<__int64,std::ratio<1,1000> > & timeout, bool expect_timeout)Строка 438
	в d:\devel\freeorionsdk_10_msvc-v141\freeorion\network\clientnetworking.cpp(438)
fo_systemtest_game.exe!ClientAppFixture::PingLocalHostServer()Строка 38
	в d:\devel\freeorionsdk_10_msvc-v141\freeorion\test\system\clientappfixture.cpp(38)
fo_systemtest_game.exe!SmokeTestGame::host_server::test_method()Строка 44
	в d:\devel\freeorionsdk_10_msvc-v141\freeorion\test\system\smoketestgame.cpp(44)
fo_systemtest_game.exe!SmokeTestGame::host_server_invoker()Строка 42
	в d:\devel\freeorionsdk_10_msvc-v141\freeorion\test\system\smoketestgame.cpp(42)
[Внедренный фрейм] boost_unit_test_framework.dll!boost::function0<void>::operator()()Строка 759
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\function\function_template.hpp(759)
[Внедренный фрейм] boost_unit_test_framework.dll!boost::detail::forward::operator()()Строка 1300
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\execution_monitor.ipp(1300)
boost_unit_test_framework.dll!boost::detail::function::function_obj_invoker0<boost::detail::forward,int>::invoke(boost::detail::function::function_buffer & function_obj_ptr)Строка 138
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\function\function_template.hpp(138)
[Внедренный фрейм] boost_unit_test_framework.dll!boost::detail::do_invoke(const boost::shared_ptr<boost::detail::translator_holder_base> &)Строка 281
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\execution_monitor.ipp(281)
boost_unit_test_framework.dll!boost::execution_monitor::catch_signals(const boost::function<int __cdecl(void)> & F)Строка 1139
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\execution_monitor.ipp(1139)
boost_unit_test_framework.dll!boost::execution_monitor::execute(const boost::function<int __cdecl(void)> & F)Строка 1203
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\execution_monitor.ipp(1203)
boost_unit_test_framework.dll!boost::execution_monitor::vexecute(const boost::function<void __cdecl(void)> & F)Строка 1309
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\execution_monitor.ipp(1309)
boost_unit_test_framework.dll!boost::unit_test::unit_test_monitor_t::execute_and_translate(const boost::function<void __cdecl(void)> & func, unsigned int timeout)Строка 46
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\unit_test_monitor.ipp(46)
boost_unit_test_framework.dll!boost::unit_test::framework::state::execute_test_tree(unsigned long tu_id, unsigned int timeout, const boost::unit_test::framework::state::random_generator_helper * const p_random_generator)Строка 771
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\framework.ipp(771)
boost_unit_test_framework.dll!boost::unit_test::framework::state::execute_test_tree(unsigned long tu_id, unsigned int timeout, const boost::unit_test::framework::state::random_generator_helper * const p_random_generator)Строка 717
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\framework.ipp(717)
boost_unit_test_framework.dll!boost::unit_test::framework::state::execute_test_tree(unsigned long tu_id, unsigned int timeout, const boost::unit_test::framework::state::random_generator_helper * const p_random_generator)Строка 717
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\framework.ipp(717)
boost_unit_test_framework.dll!boost::unit_test::framework::run(unsigned long id, bool continue_test)Строка 1577
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\framework.ipp(1577)
boost_unit_test_framework.dll!boost::unit_test::unit_test_main(bool(*)() init_func, int argc, char * * argv)Строка 233
	в d:\devel\freeorion-sdk\build\boost-prefix\src\boost\boost\test\impl\unit_test_main.ipp(233)
[Внешний код]
```

**Comment by o01eg** [comment]
Rebased. Add bcrypt dependency for Boost >= 1.67 on Windows. See https://github.com/boostorg/uuid/issues/68

**Comment by geoffthemedio** [comment]
So what is the status of this? Mostly works but has error on a test? Does it break anything that previously worked, or just doesn't fix everything you'd like? Should it be merged as is?

**Comment by o01eg** [comment]
@geoffthemedio I'm testing boost bump from https://github.com/freeorion/freeorion-sdk/pull/49 with it and didn't find other issues up to boost 1.69.

**Comment by geoffthemedio** [comment]
sooo... should it be merged as is?

**Comment by o01eg** [comment]
Yes

**Pull request merged**
