### PR TITLE
Convert default/scripting/species/SpeciesCensusOrdering.focs

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
> * error C2039: '_copysign': is not a member of 'std'

https://github.com/freeorion/freeorion/blob/master/msvc2022/Parsers/StdAfx.h#L24

**Comment by o01eg** [comment]
Yes, it should be fixed but somehow that changes trigger it again. Maybe it fixed in boost 1.80 so I opened PR for SDK https://github.com/freeorion/freeorion-sdk/pull/107

**Comment by o01eg** [comment]
Boost 1.80 doesn't fix it.

**Comment by o01eg** [comment]
@geoffthemedio Looks like precompiled headers fixed `_copysign` issue.

**Pull request merged**
