### PR TITLE
Kick out other players controls same empire

### PR DESCRIPTION
**Pull request by o01eg**
Additionally kills AI process if other player was AI.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I don't have an easy way to test this, so if you think it's fine, then fine...

**Comment by o01eg** [comment]
I made `auth.py` `get_player_delegation` returns `AI_1` to be delegated. Then started first client and host multiplayer game with two 2, then I started second client and in lobby chosen empire of `AI_1`.

**Comment by geoffthemedio** [comment]
So you tested it and it seemed to work?

**Comment by o01eg** [comment]
Yes

**Pull request merged**
