### PR TITLE
The Honeycomb special will now turn nearby planets into asteroids ins…

### PR DESCRIPTION
**Pull request by Deepsloth**
…tead of destroying them.

Suggestion by Mat here: http://www.freeorion.org/forum/viewtopic.php?f=6&t=10147

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Is it intended that the new asteroid belts will keep their planet-type names?

Would make sense for events happening mid-game, but probably not for stuff during galaxy generation / on turn 1 before any players can see it.

**Comment by MatGB** [comment]
It is intended, yes, as discussed on forum thread

**Comment by geoffthemedio** [comment]
ah, there it is. thought I remembered it, but didn't see it on the page.

**Comment by Vezzra** [comment]
Looks very simple and straightforward, anything preventing this from being merged?

**Pull request merged**
