### PR TITLE
add new graphic for ion storm

### PR DESCRIPTION
**Pull request by TheSilentOne1**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Seems too close in colour to the molecular cloud and galaxy gas... all are similar blue-green colours.

**Comment by TheSilentOne1** [comment]
Don't think so:

fields

**Comment by geoffthemedio** [comment]
I'm not saying they can't be told apart, but I'm not colourblind and I know there is a difference between them. For a new player or someone who can't distinguish colours as well, it might be more difficult.

**Comment by TheSilentOne1** [comment]
If you feel colors need to be altered to make the fields more distinctive, I'd rather change the molecular cloud. The ion storm lightning color seems right to me. I'll post some suggestions on the forums.

**Comment by geoffthemedio** [comment]
The apparent size of the ion storm is quite a bit smaller than its area of effect, partly because the graphic proposed doesn't fill the texture size...
ion size

**Comment by TheSilentOne1** [comment]
Here's the cropped version.

**Comment by geoffthemedio** [comment]
Slightly but not much better...
small ion appearance

**Comment by TheSilentOne1** [comment]
Not much I can do without giving the storm a solid border. I think it might be a good idea to add a marker to fleet buttons (similar to the blockade marker) and update the planet status indicator if a planet or fleet gets affected by a field. Would that be possible with a reasonable amount of work?

**Pull request merged**
