### PR TITLE
Draft amendments to Industry modifier prioritisation

### PR DESCRIPTION
**Pull request by MatGB**
Commit makes clear what the work does, it appears to have the desired effect, but certain species might need nerfing after further testing.

Amendments to Concentration Camp timings **not** tested, that's happening tomorrow but wanted to have it available for others to look/give feedback and, well, sleep beckons.

### CODE REVIEW

**Comment by MatGB** [comment]
Gah, forgot to remove the new art commit, never mind it's a draft PR that needs deleting anyway.

**Comment by geoffthemedio** [comment]
If nobody has objections / will bother to test the pull request, do you want to rebase and then have this merged...?

**Comment by MatGB** [comment]
I'm finishing off a few points, there are some overpower/underpower issues, I decided to go through and finish stuff oldest first hence this got put behind Energy Frigate in the queue, hopefully done tonight anyway.

**Comment by MatGB** [comment]
Closing as a more up to date version will be pushed directly when I've finished tweaking.

**Pull request closed without merging**
