### PR TITLE
Rework Replicon

### PR DESCRIPTION
**Pull request by MichaelCourtney**
https://www.freeorion.org/forum/viewtopic.php?f=6&t=12485

Tested that they work, haven't been tested for balance yet.

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
Preliminary play testing in single player suggests this works. I'd probably need to try them in multiplayer to see how they really compare.

**Comment by MichaelCourtney** [comment]
@o01eg - do you know what the python check fail is about? The scripting works fine in game

**Comment by o01eg** [comment]
@MichaelCourtney `black` formatter propose to format operations per line:

```diff
-        90 * TECH_COST_MULTIPLIER
+        90
+        * TECH_COST_MULTIPLIER
```

**Comment by geoffthemedio** [comment]
> @MichaelCourtney `black` formatter propose to format operations per line:
> 
> ```diff
> -        90 * TECH_COST_MULTIPLIER
> +        90
> +        * TECH_COST_MULTIPLIER
> ```

@o01eg Why is the spilt-line version better? Can / should the formatter be disabled for FOCS Python stuff?

**Comment by agrrr3** [comment]
> Why is the spilt-line version better?

guessing... either for consistency. or more fine-grained versioning

more probable/more specific: because a formatter is bad on judging on a per-case basis and having a single way of writing things removes edit-wars and unnecessary conflicts on merging

**Comment by o01eg** [comment]
@geoffthemedio I think it splits long lines on operation depending on their priority and * and / have same priority. As I see in PEP8 https://peps.python.org/pep-0008/#should-a-line-break-before-or-after-a-binary-operator lines split at each operator.

**Review by Oberlus — APPROVED** [review]

**Pull request merged**
