### PR TITLE
Update fr.txt

### PR DESCRIPTION
**Pull request by Ouaz**
- On par with en.txt in master (Aug 21, 2015 - 378c170)
- Contains EN stringtable commits 378c170 ; b15df70 ; f60246d ; 612cf7b ; 5c10317
- It seems none of them requires a cherry picking.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
Extra space after value

```
BLD_COL_HAPPY
Colonie Happybirthday 
```

**Comment by Vezzra** [comment]
5c1031798e109d0f081afc73bd9e18c4298487da and f60246d1cf147b32acaeff3ff1deb8d1112f1fa1 most likely are going to be cherry picked, so it's probably better to split off the translation of the respective keys to a separate PR (or you can make an extra PR with those keys for the release branch, whatever you prefer).

**Comment by Vezzra** [comment]
Update: 5c1031798e109d0f081afc73bd9e18c4298487da and f60246d1cf147b32acaeff3ff1deb8d1112f1fa1 _have_ been cherry picked. So an update to this PR is required (or a second PR for the release branch, containing only the keys relevant for the cherry picked commits, whatever you prefer).

**Comment by Ouaz** [comment]
@Vezzra:  Ok fine, I will submit a PR for the release branch this evening with all the recently cherry-picked commits (Aug 22-23) and a different PR for the master branch.

I close this master branch PR to open a new one with the latest additions.

@Cjkjvfnby : ok, fixed, thanks.

**Pull request closed without merging**
