### PR TITLE
Fix MacOS CI

### PR DESCRIPTION
**Pull request by o01eg**
Try to fix MacOS CI with using same version works on FreeOrion SDK CI.

### CODE REVIEW

**Comment by o01eg** [comment]
It fixed brew issues but it looks boost-python was somehow broken

**Comment by geoffthemedio** [comment]
> It fixed brew issues but it looks boost-python was somehow broken

Maybe something from my attempt would help? 

https://github.com/freeorion/freeorion/commits/BrewFixMaybe

**Comment by o01eg** [comment]
@geoffthemedio  I suppose boost, python, and boost-python should be from same source either our SDK or brew.

**Comment by o01eg** [comment]
Something happened with GLEW library too.

**Review by Vezzra — COMMENTED** [review]
Can't say much, I don't really know how that CI stuff works - so, as far as I am concerned, looks fine...

**Comment by o01eg** [comment]
It was built in my fork https://travis-ci.org/github/o01eg/freeorion/builds/740599681 so I think it's fine to merge, but it would be nice to fix unittests linker issues.

**Comment by geoffthemedio** [comment]
Even if the unit tests won't link, having the other OSX test builds run is a major improvement.

**Pull request merged**
