### PR TITLE
[FOCS] Convert FULVER

### PR DESCRIPTION
**Pull request by Cjkjvfnby**

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@o01eg this code gives me.  I have rebased and pushed new branch


```python
effects=SetVisibility(empire=Source.Owner, visibility=MaxOf("Visibility", Basic, ValueVisibility))
```

```
PythonCommon.cpp:101 : Traceback (most recent call last):
PythonCommon.cpp:101 :   File "<string>", line 112, in <module>
PythonCommon.cpp:101 : TypeError: '__UnlockableItemType' object is not callable
PythonParser.cpp:358 : Unable to parse data file j:/projects/freeorion/default\scripting/species\SP_FULVER.focs.py
```

**Comment by Cjkjvfnby** [comment]
@o01eg ping

**Comment by o01eg** [comment]
Use `GiveEmpirePolicy` for effect name.

**Comment by Cjkjvfnby** [comment]
> Use GiveEmpirePolicy for effect name.

Do you track somewhere these API changes?  

Having different names between focs.txt and focs.py will make conversation a pain.

**Comment by Cjkjvfnby** [comment]
Rebased, tests are passed.

**Review by o01eg — CHANGES_REQUESTED** [review]
Missing Exobot in Research and Influence focus.
Mistyped: 
```
stackinggroup = "SP_FULVER)_TOWARDS_TARGET_OPINION_OF_EMPIRE"
```
and 
```
accountinglabel = "@1@_FUEL_LABEL"
```

**Comment by Cjkjvfnby** [comment]
Updated the code and checked the diff. 

- Exabot changes are ok.  the problem is in macroses https://github.com/freeorion/freeorion/pull/4770 
- Order of comparison operation could not be changed, 0 == x and x == 0 produces the same result.  If it could be fixed it would be nice. 

Also, there are some diffs with `-1 != -(1)`, but I grepped them out.

```diff
--- SP_FULVER.txt.master
+++ SP_FULVER.txt.sa-extract-FULVER
@@ -21,6 +21,7 @@
                     Or [
                         Not
                             EmpireHasAdoptedPolicy empire = Source.Owner name = "PLC_RACIAL_PURITY"
+                        Species name = "SP_EXOBOT"
                         Species name = Statistic Mode value = LocalCandidate.Species condition = And [
     Capital
     OwnedBy empire = Source.Owner
@@ -39,6 +40,7 @@
                     Or [
                         Not
                             EmpireHasAdoptedPolicy empire = Source.Owner name = "PLC_RACIAL_PURITY"
+                        Species name = "SP_EXOBOT"
                         Species name = Statistic Mode value = LocalCandidate.Species condition = And [
     Capital
     OwnedBy empire = Source.Owner
@@ -650,7 +652,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_INDUSTRY"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
@@ -663,7 +665,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_RESEARCH"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
@@ -676,7 +678,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_INFLUENCE"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
@@ -689,7 +691,7 @@
                     Planet
                     Not
                         Focus name = "FOCUS_STOCKPILE"
-                    (0 = LocalCandidate.TurnsSinceFocusChange)
+                    (LocalCandidate.TurnsSinceFocusChange = 0)
                 ]
             priority = 600
             effects =
```

**Comment by o01eg** [comment]
> Order of comparison operation could not be changed, 0 == x and x == 0 produces the same result. If it could be fixed it would be nice.

Python itself somehow reorders it so those changes are fine.

**Comment by Cjkjvfnby** [comment]
So now all diffs are ok, and this Python script produces the same result as focs.

**Review by o01eg — APPROVED** [review]

**Comment by Cjkjvfnby** [comment]
<details><summary>Diff</summary>
<p>

```diff
--- SP_LEMBALALAM.txt.master
+++ SP_LEMBALALAM.txt.sa-convert-CELESTEPHYTE
@@ -361,7 +361,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + -0.333333 * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_LEMBALALAM
             scope =
                 Source
--- SP_MUURSH.txt.master
+++ SP_MUURSH.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_MUURSH
             scope =
                 Source
--- SP_THENIAN.txt.master
+++ SP_THENIAN.txt.sa-convert-CELESTEPHYTE
@@ -1758,8 +1758,8 @@
                 SetPopulation value = Value * 0.500000
                 GenerateSitRepMessage
                     message = "EFFECT_THENIAN_NATURAL_DIEOFF" icon = icons/sitrep/colony_starvation.png
-                    parameters = tag = planet data = (Target.ID) // StringCast{int}
-                        
+                    parameters = [  tag = tag data = "planet"  tag = data data = (Target.ID) // StringCast{int}
+                         ]
                     affiliation = TheEmpire
                     empire = Target.Owner
             ]
--- SP_MISIORLA.txt.master
+++ SP_MISIORLA.txt.sa-convert-CELESTEPHYTE
@@ -421,7 +421,7 @@
             accountinglabel = "BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (0.800000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + -0.200000 * abs(Value)
         EffectsGroup // from SP_MISIORLA
             description = "BAD_STOCKPILE_DESC"
             scope =
--- SP_OURBOOLS.txt.master
+++ SP_OURBOOLS.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (2.000000 / 3.000000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_OURBOOLS
             scope =
                 Source
--- SP_SCYLIOR.txt.master
+++ SP_SCYLIOR.txt.sa-convert-CELESTEPHYTE
@@ -408,7 +408,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_SCYLIOR
             scope =
                 Source
--- SP_HUMAN.txt.master
+++ SP_HUMAN.txt.sa-convert-CELESTEPHYTE
@@ -394,7 +394,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_HUMAN
             scope =
                 Source
--- SP_PHINNERT.txt.master
+++ SP_PHINNERT.txt.sa-convert-CELESTEPHYTE
@@ -357,7 +357,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_PHINNERT
             scope =
                 Source
--- SP_SLY.txt.master
+++ SP_SLY.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_SLY
             description = "GREAT_STOCKPILE_DESC"
             scope =
--- SP_SILEXIAN.txt.master
+++ SP_SILEXIAN.txt.sa-convert-CELESTEPHYTE
@@ -382,7 +382,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (2.000000 / 3.000000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_SILEXIAN
             scope =
                 Source
--- SP_UGMORS.txt.master
+++ SP_UGMORS.txt.sa-convert-CELESTEPHYTE
@@ -422,7 +422,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_UGMORS
             scope =
                 Source
--- SP_TAEGHIRUS.txt.master
+++ SP_TAEGHIRUS.txt.sa-convert-CELESTEPHYTE
@@ -394,7 +394,7 @@
             accountinglabel = "GREAT_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.500000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.500000 * abs(Value)
         EffectsGroup // from SP_TAEGHIRUS
             scope =
                 Source
--- SP_KILANDOW.txt.master
+++ SP_KILANDOW.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + -0.333333 * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_KILANDOW
             scope =
                 Source
--- SP_TRITH.txt.master
+++ SP_TRITH.txt.sa-convert-CELESTEPHYTE
@@ -394,7 +394,7 @@
             accountinglabel = "GREAT_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.500000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.500000 * abs(Value)
         EffectsGroup // from SP_TRITH
             scope =
                 Source
--- SP_NYMNMN.txt.master
+++ SP_NYMNMN.txt.sa-convert-CELESTEPHYTE
@@ -347,7 +347,7 @@
             accountinglabel = "BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (0.800000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + (-1.200000) * abs(Value)
         EffectsGroup // from SP_NYMNMN
             scope =
                 Source
--- SP_SUPER_TEST.txt.master
+++ SP_SUPER_TEST.txt.sa-convert-CELESTEPHYTE
@@ -422,7 +422,7 @@
             accountinglabel = "GREAT_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.500000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.500000 * abs(Value)
         EffectsGroup // from SP_SUPER_TEST
             description = "GREAT_STOCKPILE_DESC"
             scope =
--- SP_VOLP.txt.master
+++ SP_VOLP.txt.sa-convert-CELESTEPHYTE
@@ -392,7 +392,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_VOLP
             scope =
                 Source
```

</p>
</details>

**Pull request merged**
