### PR TITLE
disable music when app loses focus

### PR DESCRIPTION
**Pull request by TheSilentOne1**
as requested here:
https://github.com/freeorion/freeorion/issues/1361

### CODE REVIEW

**Comment by adrianbroher** [comment]
This isn't suspending the sound system.

**Comment by TheSilentOne1** [comment]
Does it have to be? That shouldn't be complicated either, but all we want to disable the music, don't we?

**Comment by geoffthemedio** [comment]
In at least some cases, I think people still want to have the turn update sound be audible, so that they know when turn processing finished with the game minimized.

**Comment by adrianbroher** [comment]
>  That shouldn't be complicated either, but all we want to disable the music, don't we?

No, I don't think stopping and restarting is the right thing to do.  The music should continue playing at the point where it was paused.

**Comment by TheSilentOne1** [comment]
@adrianbroher: I think you're right, I changed it.
Beware: I have no plan about (how) OpenAL (works). Testing suggests this works as intended, but no guarantees.

**Comment by adrianbroher** [comment]
@TheSilentOne1 Looks good in my opinion.  And according to the API of OpenAL this should be right way to do this.  I will test the PR as soon as I have some time.  Thanks so far.

**Comment by Vezzra** [comment]
The corresponding issue #1361 is assigned to the "post 0.4.7" milestone, however, with a solution already implemented that looks promising so far, this has a good chance to be ready for 0.4.7, in which case there is no reason to hold it back.

So this now looks more like "optional for 0.4.7", and both issue and PR could be set to this milestone. @adrianbroher, just wanted to check back with you, as you initially assigned the issue to "post 0.4.7" - are you ok with switching to "optional for 0.4.7"?

**Comment by adrianbroher** [comment]
@Vezzra Sure, go ahead.  I didn't expect that someone would pick this up the mentioned issue this fast and any solution wouldn't be missed for v0.4.7.

**Comment by geoffthemedio** [comment]
works for me

**Comment by TheSilentOne1** [comment]
@adrianbroher: Did you want to have a look at this or shall I squash & merge?

**Comment by adrianbroher** [comment]
@TheSilentOne1 go ahead.

**Pull request merged**
