### PR TITLE
Allow unhandled exceptions to leave a complete stack trace in camain …

### PR DESCRIPTION
**Pull request by LGM-Doyle**
…and cdmain.

Remove exception handlers from camain and dmain that were not handling
the exception and only printing a message to the log.
These non-handlers just unroll the stack.

Allow unhandled exceptions to crash freeorion and produce a complete
stack trace.

This applies to linux only.

These are the same changes for the same reasons as PR #604.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Can someone else on Linux confirm this works as intended?

**Comment by dbenage-cx** [comment]
Based on the description, this seems to have to opposite effect? (or my testing is flawed)

UI/ResearchWnd.cpp:445 `throw "a";` 
launch game->quickstart->add research to queue

PR:

```
$ gdb build/freeorion
(gdb) r
...
main() caught unknown exception.
[Thread 0x7fffe17cf700 (LWP 13861) exited]
[Thread 0x7fffe5fd1700 (LWP 13860) exited]
[Inferior 1 (process 13854) exited normally]
(gdb) bt
No stack.
```

**Comment by Vezzra** [comment]
> (or my testing is flawed)

This, I guess. You're testing the _human_ client, this PR removes the top level exception handlers from the _AI_ client and the _server_.

**Comment by Vezzra** [comment]
I can build and run this PR on my Linux box, works fine. But I don't know how to make the AI client and the server throw unhandled exceptions, and even if I managed that, I don't know how to get the stack...

**Comment by LGM-Doyle** [comment]
Here is how I tested. 

You need to 
1. cause the freeorionca or the freeoriond executables to crash. 
2. at the same time you need to capture the stack trace.
1. To cause the crashes on the first turn update I added either 

`case Message::TURN_UPDATE: {
         throw "a";`

to AIClientApp.cpp:249, or

`ProcessingTurn::ProcessingTurn(my_context c) :
    my_base(c)`

`{ if (TRACE_EXECUTION) DebugLogger() << "(ServerFSM) ProcessingTurn"; 
throw "a";}`

to ServerFSM.cpp:1442 

Only add one or the other change not both.

2 . To grab the backtrace I used gdb as follows:
Start a freeorion game with a single AI.
Start gdb with the pid of either freeoriond or freeorionca.
Continue the now observed process running.
Hit next turn.
Look at backtrace.

`freeorion --quickstart&`  assuming your config files starts a game with single AI.
`ps -elf | grep freeorionca`
`gdb ./freeorionca --pid <pid from ps>`
`(gdb) continue`
Hit next turn.
`(gdb) backtrace`

**Comment by dbenage-cx** [comment]
Thank you LGM-Doyle, both of the provided have backtrace.
Will assume the first (invalid) test differs from master due to commits since this PR formed.

**Comment by Vezzra** [comment]
Yep, thanks @LGM-Doyle, with those instructions I've been able to test this too and can confirm PR works as expected. Going to merge.

**Pull request merged**
