### PR TITLE
Made producing troop pods require a production location with troops.

### PR DESCRIPTION
**Pull request by geoffthemedio**
Seems like a reasonable restriction... Might require AI adjustment, though.

### CODE REVIEW

**Comment by Vezzra** [comment]
Yep, sounds good. @freeorion/ai-team: any estimates how complicated it will be to adjust the AI to this change?

**Comment by MatGB** [comment]
Will this actually do anything much? Delay of maybe a turn or two in the _very_ early game until you've got a moderate level in the troops tech so you're normally past the benchmarks immediately on conquest? (I think troops regenerate too quickly at the higher end which is linked to this)

**Comment by geoffthemedio** [comment]
I'm planning to do some additional reworking of troop levels and regeneration. I think it's generally far too easy to quickly produce a lot of troop ships now, especially right from the start of the game. The AI being able to handle needing a minimum troop level on planets to produce troops there is probably a requirement for this...

**Comment by Morlic-fo** [comment]
The AI in the current state has (should have) no problems with checking location requirements for ship parts/hulls. 

However, it will generally not plan to reach these requirements (unless more or less hardcoded). So for this PR, there should not be a problem as I expect the troop count to be trivially reached.

If the mechanics become more complicated so the AI has to do something before building the troop ships (compared to only checking where it can currently build them), then adaptions will be necessary.

**Comment by Vezzra** [comment]
Good enough. As the changes are very simple, I don't think much testing is required. So, as far as I'm concerned, ok to merge.

**Comment by geoffthemedio** [comment]
Future plans include making producing colony and troop ships consume population or troops from planets, and probably making troop ships require some tech research before being producible, which will require some AI adjustments.

**Comment by Vezzra** [comment]
Sounds promising :smiley:

**Comment by Cjkjvfnby** [comment]
FYI: There are all places of call `issueEnqueueShipProductionOrder` with `troop` in design name.
Game for 8 players, last 79 turns.

```
AI_1.log
  design                         code location                  number of count

  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1352           6
  SD_TROOP_SHIP                  ProductionAI.py:1352           3

AI_2.log
  design                         code location                  number of count

  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1170           2

AI_3.log
  design                         code location                  number of count

  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1352           7
  SD_TROOP_SHIP                  ProductionAI.py:1352           2

AI_4.log
  design                         code location                  number of count

  SD_TROOP_SHIP                  ProductionAI.py:1170           2
  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1170           2
  SY Heavy Troopers Mk. 1        ProductionAI.py:1170           1
  SD_TROOP_SHIP                  ProductionAI.py:1352           2

AI_5.log
  design                         code location                  number of count

  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1352           2
  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1170           2
  SD_TROOP_SHIP                  ProductionAI.py:1352           1

AI_6.log
  design                         code location                  number of count

  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1352           18
  TY Heavy Troopers Mk. 1        ProductionAI.py:1352           1
  SD_TROOP_SHIP                  ProductionAI.py:1352           3
  SD_ORG_TROOP_SHIP              ProductionAI.py:1352           5

AI_7.log
  design                         code location                  number of count

  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1352           3
  SD_TROOP_DROP                  InvasionAI.py:155              1
  SD_TROOP_SHIP                  ProductionAI.py:1352           1

AI_8.log
  design                         code location                  number of count

  SD_ROBO_FLUX_TROOPS            ProductionAI.py:1170           3
  PY Heavy Troopers Mk. 1        ProductionAI.py:1170           2
  SD_TROOP_SHIP                  ProductionAI.py:1352           1


Code locations summary
  - InvasionAI.py:155
  - ProductionAI.py:1170
  - ProductionAI.py:1352
```

**Pull request merged**
