### PR TITLE
Enable test build on MacOS CI

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by o01eg** [comment]
I suppose link issue related to https://github.com/freeorion/freeorion/issues/3181

**Review by Vezzra — COMMENTED** [review]
I don't think that I can give any kind useful input here.

The changes you made seem reasonable to me, but I don't really know how that CI stuff works. And I can't really offer any help - sorry.

**Comment by Vezzra** [comment]
> I suppose link issue related to #3181

If the CI build fails with the same or a similar build error, most likely.

**Comment by o01eg** [comment]
@agrrr3 Could you try to look up this PR

**Comment by agrrr3** [comment]
@o01eg I do not see how i can contribute here. What is the problem/error? 

edit1: Oh i see the CI build fail. AFAIU the last thing it tries before failure is to compile CUILinkTextBlock. and what seems to fail is `Ld build/Release/fo_unittest_parse normal x86_64`. But i really do not have a clue what goes on there

**Comment by o01eg** [comment]
@agrrr3 There link error with your code:

```
Undefined symbols for architecture x86_64:

  "void RegisterValueRef<PlanetType>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::unique_ptr<ValueRef::ValueRef<PlanetType>, std::__1::default_delete<ValueRef::ValueRef<PlanetType> > >&&)", referenced from:

      void parse::insert_named_ref<PlanetType>(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::unique_ptr<ValueRef::ValueRefBase, std::__1::default_delete<ValueRef::ValueRefBase> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::unique_ptr<ValueRef::ValueRefBase, std::__1::default_delete<ValueRef::ValueRefBase> > > > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, parse::detail::MovableEnvelope<ValueRef::ValueRef<PlanetType> > const&, bool&) in NamedValueRefParser.o

  "void RegisterValueRef<PlanetEnvironment>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::unique_ptr<ValueRef::ValueRef<PlanetEnvironment>, std::__1::default_delete<ValueRef::ValueRef<PlanetEnvironment> > >&&)", referenced from:
```

**Comment by o01eg** [comment]
Looks like it is fixed now.

**Review by Vezzra — COMMENTED** [review]
@o01eg, as the changes look very simple to me, and I don't really know much about that CI stuff anyway, I don't really know what kind of input I can give - to me it looks ok....

**Pull request merged**
