### PR TITLE
Use default logging

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This works on win7 because name is ignored for my case , can you test it on other platforms?

@Dilvish-fo , @Vezzra 

If this work we can get rid of the `convenience_function_references_for_logger` and make code more elegant.

- [x] win7
- [ ] win8
- [x] win10
- [x] linux
- [x] macosx

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
On Win10 this seems to work fine without a difference in the resulting log files that I could detect by looking back and forth between old and new.

It would probably be at least a few days or more before I would be able to test this on my Linux machine.

**Comment by Vezzra** [comment]
@Cjkjvfnby, sorry for not getting around to this yet. I've been down with the flu. Don't know when I will get to this, but will try to do so ASAP.

**Comment by Vezzra** [comment]
Ok, ran a quick test on Linux (default quickstart game), so far the log files look ok. However, I do get some errors in the logs, but I don't think they ar related to this PR. The first one is a line that practically appears in all logs:
```
13:21:06.192966 [error] ai : StringTable.cpp:118 : Duplicate string ID found: 'GASEOUS_DESC' in file: '/home/user/SoftwareProjects/FO/build/default/stringtables/en.txt'.  Ignoring duplicate.
```
The second one is an error that occurs with AI 4:
```
13:22:21.016732 [error] python : FreeOrionAI.py:338 - Exception local variable 'per_gg' referenced before assignment while trying to calculate_priorities
13:22:21.016755 [error] python : FreeOrionAI.py:338 - Traceback (most recent call last):
13:22:21.016769 [error] python : FreeOrionAI.py:338 -   File "/home/user/SoftwareProjects/FO/src/default/python/AI/FreeOrionAI.py", line 335, in generateOrders
13:22:21.016783 [error] python : FreeOrionAI.py:338 -     action()
13:22:21.016796 [error] python : FreeOrionAI.py:338 -   File "/home/user/SoftwareProjects/FO/src/default/python/AI/PriorityAI.py", line 41, in calculate_priorities
13:22:21.016809 [error] python : FreeOrionAI.py:338 -     ColonisationAI.get_colony_fleets()  # sets foAI.foAIstate.colonisablePlanetIDs and many other values used by other modules
13:22:21.016821 [error] python : FreeOrionAI.py:338 -   File "/home/user/SoftwareProjects/FO/src/default/python/AI/ColonisationAI.py", line 414, in get_colony_fleets
13:22:21.016834 [error] python : FreeOrionAI.py:338 -     this_score = evaluate_planet(pid, MissionType.OUTPOST, None, [])
13:22:21.016846 [error] python : FreeOrionAI.py:338 -   File "/home/user/SoftwareProjects/FO/src/default/python/AI/ColonisationAI.py", line 931, in evaluate_planet
13:22:21.016859 [error] python : FreeOrionAI.py:338 -     orb_gen_val += per_gg * discount_multiplier
13:22:21.016871 [error] python : FreeOrionAI.py:338 - UnboundLocalError: local variable 'per_gg' referenced before assignment
```
As the PR branch is based on a commit from Feb 16th, those issues might have been fixed in master in the meantime.

Test on OSX to follow.

**Comment by Vezzra** [comment]
A brief test on OSX (also default quickstart game) produced the same results as on Linux.

So, unless the errors I reported above have anything to do with this PR, these changes seem to be ok as far as I can tell.

**Comment by Dilvish-fo** [comment]
> As the PR branch is based on a commit from Feb 16th, those issues might have been fixed in master in the meantime.

Yes, both those issues are unrelated to this PR and have already been fixed in master

**Comment by Dilvish-fo** [comment]
@Cjkjvfnby I'm not sure if/when we'd be able to get the Win8 test you were hoping for, and I see little reason to wait for it.  I suggest you proceed with the simplification/cleanup you contemplated.

**Comment by Cjkjvfnby** [comment]
Thanks, everybody, for testing. Looks like it work on all main platforms.

I have dropped `convenience_function_references_for_logger` and rebased PR.

**Pull request merged**
