### PR TITLE
Build freeorioncommon as shared library on Windows with CMake

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR enables building `freeorioncommon` as a shared library on windows within the CMake build system.  This is a work in progress and unfortunately breaks both the current MSVC builds.

If someone wants to test this out please keep the following things in mind:

* You need to pass the toolset (at least v140_xp or a later one) with the cmake `-T` parameter to support WindowsXP.  When not passing the -T parameter the build will still work but the resulting executable won't be executable on WindowsXP obviously.
* Use a different build directory than the source directory.  The build will probably work if this advice is ignored but I didn't test this variant because it is considered bad style.
* The build copies the used library DLLs into the build dir and links the default directory automatically to allow an arbitrary build layout with different build configurations.  However the build expects the libraries and the python.exe to be located inside a `bin` which is at the same level as the SDK `include` and `lib` directories.  If you don't want to copy around files you can establish the same layout by downloading the most recent SDK and **not** executing the included `bootstrap.bat`.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Does this effectively just merge parse and common and then make the combination a DLL instead of static library?

**Comment by adrianbroher** [comment]
> Does this effectively just merge parse and common and then make the combination a DLL instead of static library?

Somewhat.  `common` and `parse` stay different targets (or projects in VS) with different build configurations, but the build artifact is a single dll.

**Comment by adrianbroher** [comment]
@LGM-Doyle the `Pending::Pending` implementation defines a move constructor and a move assign operator.  Is there a particular reason why you did not implement the corresponding copy operations?  This causes the build to fail for me with the MSVC compiler.

**Comment by LGM-Doyle** [comment]
std::future is not copyable.

I could work on a copyable version next week, if it is preventing this from landing.

**Comment by o01eg** [comment]
Hi, could you try to rebase it over current master? At least I took one commit to enable CI test.

**Comment by adrianbroher** [comment]
Stale branch, superceded by adrianbroher/win-cmake

**Comment by Vezzra** [comment]
Superseded by #2697.

**Comment by adrianbroher** [comment]
@Vezzra can you delete this branch?

**Comment by Vezzra** [comment]
Well, @geoffthemedio beat me to it...

**Pull request closed without merging**
