### PR TITLE
Fix Compile Errors

### LINKED ISSUE #2938: Build Errors with Boost 1.73
Reported by @l29ah in https://github.com/freeorion/freeorion/pull/2937

> Okay, what about this 400kB worth of an error message?
> [error.log](https://github.com/freeorion/freeorion/files/4605955/error.log)

Then after some tweaks https://github.com/freeorion/freeorion/pull/2937#issuecomment-626355163

> Not much different:
> [build.log](https://github.com/freeorion/freeorion/files/4606161/build.log)

### PR DESCRIPTION
**Pull request by geoffthemedio**
Attempting to some of fix: https://github.com/freeorion/freeorion/issues/2938

### CODE REVIEW

**Comment by l29ah** [comment]
Checked it out: 
[build.log](https://github.com/freeorion/freeorion/files/4606970/build.log)

**Comment by Oberlus** [comment]
`boost/phoenix/core/is_nullary.hpp:115:16: error: base type [...] fails to be a struct or class type`

```
#include <boost/phoenix/object/dynamic_cast.hpp>
#include <boost/phoenix/operator/self.hpp>
```

https://stackoverflow.com/questions/54952100/boostspirit-attribute-assignment-struct-is-nullary-base-type-fails-to-be-a-s

Maybe that will solve also the `boost/phoenix/core/actor.hpp:119:13: error: ‘value’ is not a member of` that accompany each instance of the previous error.


Then there are several `boost/phoenix/core/actor.hpp:224:81: error: invalid initialization of reference of type` for which I didn't find any specific mention on Internet.

**Comment by geoffthemedio** [comment]
@Oberlus @l29ah I added those includes to `EnumParser.cpp`. Could you try again and report back?

The other change I was going to try was:
````
 parse/Lexer.h | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/parse/Lexer.h b/parse/Lexer.h
index e5a0381cd..de8c70879 100644
--- a/parse/Lexer.h
+++ b/parse/Lexer.h
@@ -3,6 +3,10 @@
 
 #define BOOST_SPIRIT_NO_PREDEFINED_TERMINALS
 
+#include <boost/spirit/include/phoenix_limits.hpp>      // needs to be included before proto
+#include <boost/proto/proto.hpp>
+#include <boost/spirit/include/phoenix_core.hpp>
+#include <boost/spirit/include/phoenix_operator.hpp>
 #include <boost/spirit/include/lex_lexertl.hpp>
 #include <boost/spirit/include/lex_lexertl_position_token.hpp>
 ````

**Comment by l29ah** [comment]
The parser builds ok after your change to EnumParser.cpp.

**Comment by geoffthemedio** [comment]
> The parser builds ok after your change to EnumParser.cpp.

Are there any other errors then?

**Comment by l29ah** [comment]
Yay it compiled and seems working!

**Comment by l29ah** [comment]
Nah it crashes when i try to order a fleet to go to a system:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e7a4b76f73 in ShipsListBox::Refresh (this=0x61) at /home/l29ah/projects/freeorion/UI/FleetWnd.cpp:2230
2230	        auto fleet = Objects().get<Fleet>(m_fleet_id);
[Current thread is 1 (Thread 0x7effe430f780 (LWP 15366))]
>>> bt
#0  0x000055e7a4b76f73 in ShipsListBox::Refresh (this=0x61) at /home/l29ah/projects/freeorion/UI/FleetWnd.cpp:2230
#1  0x000055e7a4b4eb40 in FleetDetailPanel::SetFleet (this=0x55e7a907af30, fleet_id=-2) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:1020
#2  0x00007effe6183c1a in boost::function0<void>::operator() (this=<optimized out>) at /usr/include/boost/function/function_template.hpp:677
#3  boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void ()> >(boost::function<void ()>&, boost::signals2::detail::unsigned_meta_array<>, std::tuple<> const&, boost::enable_if<boost::is_void<boost::function<void ()>::result_type>, void>::type*) const (this=<optimized out>, func=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:117
#4  boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void ()>, , 0ul>(boost::function<void ()>&, std::tuple<> const&, mpl_::size_t<0ul>) const (this=<optimized out>, args=empty std::tuple, func=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#5  boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) const (this=0x7ffffee75d20, connectionBody=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#6  boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >::dereference() const (this=0x7ffffee75b30) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
#7  boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:550
#8  boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (this=0x7ffffee75b30) at /usr/include/boost/iterator/iterator_facade.hpp:656
#9  boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >) const (last=..., first=..., this=<optimized out>) at /usr/include/boost/signals2/optional_last_value.hpp:57
#10 blocking_combiner<boost::signals2::optional_last_value<void> >::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >) (last=..., first=..., this=<optimized out>) at /home/l29ah/projects/freeorion/universe/../util/blocking_combiner.h:29
#11 boost::signals2::detail::combiner_invoker<void>::operator()<blocking_combiner<boost::signals2::optional_last_value<void> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(blocking_combiner<boost::signals2::optional_last_value<void> >&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >) const (this=<optimized out>, last=..., first=..., combiner=...) at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:64
#12 boost::signals2::detail::signal_impl<void (), blocking_combiner<boost::signals2::optional_last_value<void> >, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() (this=0x55e7a86aca50) at /usr/include/boost/signals2/detail/signal_template.hpp:243
#13 0x00007effe6236d06 in boost::signals2::signal<void (), blocking_combiner<boost::signals2::optional_last_value<void> >, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() (this=0x55e7a80f60e8) at /usr/include/boost/signals2/detail/signal_template.hpp:720
#14 Fleet::SetRoute (this=0x55e7a80f60e0, route=std::__cxx11::list = {...}) at /home/l29ah/projects/freeorion/universe/Fleet.cpp:791
#15 0x00007effe639ac72 in FleetMoveOrder::ExecuteImpl (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:1020
#16 0x00007effe6392560 in Order::Execute (this=0x55e7a9c23a50) at /home/l29ah/projects/freeorion/util/Order.cpp:43
#17 0x00007effe63a58ec in OrderSet::IssueOrder (this=this@entry=0x7ffffee77bd8, order=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:1020
#18 0x000055e7a4bf1bb4 in MapWnd::PlotFleetMovement (this=0x55e7a8312560, system_id=4290, execute_move=true, append=false) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:756
#19 0x000055e7a4bf31e9 in MapWnd::SystemRightClicked (this=0x55e7a8312560, system_id=4290, mod_keys=...) at /home/l29ah/projects/freeorion/GG/GG/Flags.h:406
#20 0x000055e7a4d9f132 in boost::function2<void, int, GG::Flags<GG::ModKey> >::operator() (a1=..., a0=<optimized out>, this=<optimized out>) at /usr/include/boost/function/function_template.hpp:677
#21 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (int, GG::Flags<GG::ModKey>)>, 0u, 1u, int&, GG::Flags<GG::ModKey>&>(boost::function<void (int, GG::Flags<GG::ModKey>)>&, boost::signals2::detail::unsigned_meta_array<0u, 1u>, std::tuple<int&, GG::Flags<GG::ModKey>&> const&, boost::enable_if<boost::is_void<boost::function<void (int, GG::Flags<GG::ModKey>)>::result_type>, void>::type*) const (this=<optimized out>, args=std::tuple containing = {...}, func=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:105
#22 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (int, GG::Flags<GG::ModKey>)>, int&, GG::Flags<GG::ModKey>&, 2ul>(boost::function<void (int, GG::Flags<GG::ModKey>)>&, std::tuple<int&, GG::Flags<GG::ModKey>&> const&, mpl_::size_t<2ul>) const (this=<optimized out>, args=std::tuple containing = {...}, func=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#23 boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > const&) const (connectionBody=..., this=0x7ffffee76a70) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#24 boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> >::dereference() const (this=0x7ffffee76880) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
#25 boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > const&) (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:550
#26 boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (this=0x7ffffee76880) at /usr/include/boost/iterator/iterator_facade.hpp:656
#27 boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> >) const (last=..., first=..., this=<optimized out>) at /usr/include/boost/signals2/optional_last_value.hpp:57
#28 boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, int, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (int, GG::Flags<GG::ModKey>), boost::function<void (int, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> >) const (this=<optimized out>, last=..., first=..., combiner=...) at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:64
#29 boost::signals2::detail::signal_impl<void (int, GG::Flags<GG::ModKey>), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (int, GG::Flags<GG::ModKey>)>, boost::function<void (boost::signals2::connection const&, int, GG::Flags<GG::ModKey>)>, boost::signals2::mutex>::operator()(int, GG::Flags<GG::ModKey>) (this=0x55e7a928d390, args#0=<optimized out>, args#1=...) at /usr/include/boost/signals2/detail/signal_template.hpp:243
#30 0x00007effe508e7a3 in GG::Wnd::HandleEvent (this=this@entry=0x55e7a928ce70, event=...) at /home/l29ah/projects/freeorion/GG/src/Wnd.cpp:1163
#31 0x00007effe4ff4655 in GG::GUIImpl::HandleMouseButtonRelease (this=0x55e7a5defc50, mouse_button=2, pos=..., curr_ticks=69689) at /home/l29ah/projects/freeorion/GG/src/GUI.cpp:538
#32 0x000055e7a4d46bc4 in SDLGUI::HandleSystemEvents (this=this@entry=0x7ffffee77cb0) at /home/l29ah/projects/freeorion/UI/SDLGUI.cpp:472
#33 0x000055e7a495819d in HumanClientApp::HandleSystemEvents (this=0x7ffffee770b0) at /home/l29ah/projects/freeorion/client/human/HumanClientApp.cpp:974
#34 0x00007effe4ff80b9 in GG::GUI::RunModal (this=this@entry=0x7ffffee77cb0, wnd=std::shared_ptr<GG::Wnd> (empty) = {...}, done=@0x7ffffee77d60: false) at /home/l29ah/projects/freeorion/GG/src/GUI.cpp:1321
#35 0x000055e7a4d46075 in SDLGUI::Run (this=0x7ffffee77cb0) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:616
#36 0x000055e7a4933d6d in mainSetupAndRun () at /home/l29ah/projects/freeorion/client/human/chmain.cpp:300
#37 0x000055e7a492b61c in main (argc=<optimized out>, argv=<optimized out>) at /home/l29ah/projects/freeorion/client/human/chmain.cpp:104
```

**Comment by l29ah** [comment]
Also vertical scrolling in the tech tree is broken.

**Comment by l29ah** [comment]
The scrolling limits don't react to the changes of zoom level, that is.

**Comment by geoffthemedio** [comment]
I doubt the crashes and scrolling issues are related to the parser build issues...

**Comment by geoffthemedio** [comment]
@l29ah Could you make separate issues for the scrolling and crash?

**Pull request merged**
