### PR TITLE
FIX Issue #4946 (TextBox RGBA Tags, EASY merge)

### PR DESCRIPTION
**Pull request by Mr-Twave**
Does this fix the issue? (Also please don't mark my messages in #4946 as spam I was just trying to help :( )

### CODE REVIEW

**Comment by Mr-Twave** [comment]
Let me facilitate your understanding of this fix to equal mine:


1. We still apply the text_color to the player's name for player messages.
2. The message content (filtered_message) is no longer wrapped in a color tag. This preserves any internal color formatting that might be present in the message.
3. For server messages (when player_name is empty), we apply the text_color to the entire message, as these are likely meant to be uniformly colored.
4. The overall structure and functionality of the method remain the same, including the handling of timestamps, private messages, and the logic for showing/flashing the message window.

Yep.

If we wanted to go a lot further with the fixes, you can feel free to steal some code from my investigations (of which I will not be implementing in this fix alone, as this fix is particularly for the RGBA tags. I just wanted to see if I could help suggest someone else to squash a few more bugs.)

Here's a possible list of fixes beyond just the fix that I've provided;

1. TagParser.cpp:

```cpp
#include "TagParser.h"
#include <boost/regex.hpp>
#include <sstream>
#include <stdexcept>

namespace {
    bool IsValidColor(int r, int g, int b, int a) {
        return r >= 0 && r <= 255 &&
               g >= 0 && g <= 255 &&
               b >= 0 && b <= 255 &&
               a >= 0 && a <= 255;
    }

    std::string ValidateAndFormatRgbaTag(const std::string& params) {
        std::istringstream iss(params);
        int r, g, b, a;
        if (iss >> r >> g >> b >> a && IsValidColor(r, g, b, a)) {
            std::ostringstream oss;
            oss << r << " " << g << " " << b << " " << a;
            return oss.str();
        }
        return "255 255 255 255"; // Default to white if invalid
    }
}

namespace GG {

RichTextTag::RichTextTag(std::string tag_, std::string params_string_, std::string content_) :
    tag(std::move(tag_)),
    tag_params(std::move(params_string_)),
    content(std::move(content_))
{}

RichTextTag::RichTextTag(std::string_view tag_, std::string params_string_, std::string content_) :
    RichTextTag(std::string{tag_}, std::move(params_string_), std::move(content_))
{}

std::string RichTextTag::ToString() const {
    return "<" + tag + (tag_params.length() != 0 ? " " + tag_params : "") + ">" + content + "</" + tag + ">";
}

namespace ParseTagsImpl {
    std::string::const_iterator ParseTagsImpl(const std::string::const_iterator start,
                                              const std::string::const_iterator end,
                                              std::vector<RichTextTag>* tags)
    {
        std::string::const_iterator current = start;
        boost::match_results<std::string::const_iterator> match;
        boost::match_flag_type flags = boost::match_default;

        typedef boost::basic_regex<char, boost::regex_traits<char>> regex;
        const static regex tag("<(?<begin_tag>\\w+)( "
                                "(?<params>[^>]+))?>|</"
                                "(?<end_tag>\\w+)>");

        while (boost::regex_search(current, end, match, tag, flags)) {
            const boost::ssub_match& begin_match = match["begin_tag"];
            const boost::ssub_match& end_match = match["end_tag"];

            if (begin_match.matched) {
                std::string tag_name = begin_match.str();
                std::string params = match["params"].str();
                
                if (tag_name == "rgba") {
                    params = ValidateAndFormatRgbaTag(params);
                }

                if (tags && current != current + match.position()) {
                    tags->emplace_back(RichText::PLAINTEXT_TAG, "",
                                       std::string(current, current + match.position()));
                }

                current = FinishTag(tag_name, params,
                                    current + match.position() + match.length(), end, tags);

            } else if (end_match.matched) {
                return current + match.position();

            } else {
                throw std::runtime_error("Error parsing rich text tags: match not begin or end tag:" + match.str());
            }
        }

        if (tags && current != end)
            tags->emplace_back(RichText::PLAINTEXT_TAG, "", std::string(current, end));

        return end;
    }

    // ... (other helper functions remain the same)
}

std::vector<RichTextTag> TagParser::ParseTags(const std::string& text, std::set<std::string> known_tags)
{
    std::vector<RichTextTag> tags;

    try {
        ParseTagsImpl::ParseTagsImpl(text.begin(), text.end(), &tags);
    } catch (const std::exception& ex) {
        tags.clear();
        tags.emplace_back(ParseTagsImpl::CreateErrorTag(ex.what()));
        return tags;
    }

    std::vector<RichTextTag> relevant_tags;
    for (RichTextTag& tag : tags) {
        if (known_tags.count(tag.tag))
            ParseTagsImpl::AddWithPlaintextSquashing(relevant_tags, std::move(tag));
        else
            ParseTagsImpl::AddWithPlaintextSquashing(relevant_tags, ParseTagsImpl::WrapInPlaintext(tag));
    }
    return relevant_tags;
}

} // namespace GG
```

2. ChatWnd.cpp:

```cpp
#include "ChatWnd.h"
#include "ClientUI.h"
#include "CUIControls.h"
#include "TagParser.h"
// ... other necessary includes

class MessageWnd : public CUIWnd {
public:
    // ... other methods

    void HandlePlayerChatMessage(const std::string& text,
                                 const std::string& player_name,
                                 GG::Clr text_color,
                                 const boost::posix_time::ptime& timestamp,
                                 int recipient_player_id,
                                 bool pm)
    {
        std::string wrapped_text;
        const std::string&& formatted_timestamp = ClientUI::FormatTimestamp(timestamp);
        if (utf8::is_valid(formatted_timestamp.begin(), formatted_timestamp.end()))
            wrapped_text.append(formatted_timestamp);

        std::set<std::string> known_tags = {"rgba", "i", "b", "u", "s"}; // Add other known tags
        auto tags = GG::TagParser::ParseTags(text, known_tags);

        if (player_name.empty()) {
            // This is likely a server message
            wrapped_text.append(GG::RgbaTag(text_color));
            for (const auto& tag : tags) {
                wrapped_text.append(tag.ToString());
            }
            wrapped_text.append("</rgba>");
        } else {
            // This is a player message
            wrapped_text.append(GG::RgbaTag(text_color))
                        .append(player_name)
                        .append("</rgba>");
            if (pm)
                wrapped_text.append(UserString("MESSAGES_WHISPER"));
            wrapped_text.append(": ");
            for (const auto& tag : tags) {
                wrapped_text.append(tag.ToString());
            }
        }

        *m_display += wrapped_text.append("\n");
        m_display_show_time = GG::GUI::GetGUI()->Ticks();

        // if client empire is target of message, show message window
        const ClientApp* app = ClientApp::GetApp();
        if (!app) {
            ErrorLogger() << "MessageWnd::HandlePlayerChatMessage couldn't get client app!";
            return;
        }
        // only show and flash message window if other player sent message
        const auto& players = app->Players();
        const auto it = players.find(app->PlayerID());
        if (it == players.end() || it->second.name != player_name) {
            Flash();
            Show();
        }
    }

    // ... other methods
};
```

3. ClientUI.cpp:

```cpp
#include "ClientUI.h"
#include <sstream>

namespace ClientUI {

std::string RgbaTag(const GG::Clr& clr) {
    std::ostringstream ss;
    ss << "<rgba " << static_cast<int>(clr.r)
       << " " << static_cast<int>(clr.g)
       << " " << static_cast<int>(clr.b)
       << " " << static_cast<int>(clr.a) << ">";
    return ss.str();
}

// ... other ClientUI functions

} // namespace ClientUI
```

4. LinkText.cpp:

```cpp
#include "LinkText.h"
#include "ClientUI.h"

class LinkText : public GG::TextControl {
public:
    // ... other methods

    std::string LinkDefaultFormatTag(const Link& link, const std::string& content) const {
        return ClientUI::RgbaTag(ClientUI::DefaultLinkColor()) + content + "</rgba>";
    }

    std::string LinkRolloverFormatTag(const Link& link, const std::string& content) const {
        return ClientUI::RgbaTag(ClientUI::RolloverLinkColor()) + content + "</rgba>";
    }

    // ... other methods
};
```

6. MeterBrowseWnd.cpp:

```cpp
#include "MeterBrowseWnd.h"
#include "ClientUI.h"

namespace {
    std::string ColourWrappedtext(const std::string& text, const GG::Clr colour) {
        return ClientUI::RgbaTag(colour) + text + "</rgba>";
    }
}

// ... rest of the file
```

7. Font.cpp:

No changes needed here, as the RgbaTag function is already optimized.

8. CUIControls.cpp:

```cpp
#include "CUIControls.h"
#include "TagParser.h"

namespace {
    std::set<std::string> GetKnownTags() {
        return {"rgba", "i", "b", "u", "s"}; // Add other known tags
    }
}

class SomeTextControl : public TextControl {
public:
    void SetText(const std::string& str) override {
        auto tags = GG::TagParser::ParseTags(str, GetKnownTags());
        std::string processed_text;
        for (const auto& tag : tags) {
            processed_text += tag.ToString();
        }
        TextControl::SetText(processed_text);
    }

    // ... other methods
};

// ... other control classes
```

9. TestTagParser.cpp:

```cpp
#define BOOST_TEST_MODULE TagParserTests
#include <boost/test/unit_test.hpp>
#include "TagParser.h"

BOOST_AUTO_TEST_CASE(test_rgba_tag_validation) {
    // This test assumes ValidateAndFormatRgbaTag is made public or we're testing through ParseTags
    std::set<std::string> known_tags = {"rgba"};
    
    auto tags = GG::TagParser::ParseTags("<rgba 255 128 64 200>test</rgba>", known_tags);
    BOOST_CHECK_EQUAL(tags[0].tag_params, "255 128 64 200");

    tags = GG::TagParser::ParseTags("<rgba 300 128 64 200>test</rgba>", known_tags);
    BOOST_CHECK_EQUAL(tags[0].tag_params, "255 255 255 255");

    tags = GG::TagParser::ParseTags("<rgba 255 128 64>test</rgba>", known_tags);
    BOOST_CHECK_EQUAL(tags[0].tag_params, "255 255 255 255");

    tags = GG::TagParser::ParseTags("<rgba not a color>test</rgba>", known_tags);
    BOOST_CHECK_EQUAL(tags[0].tag_params, "255 255 255 255");
}

BOOST_AUTO_TEST_CASE(test_tag_parsing) {
    std::set<std::string> known_tags = {"rgba", "i", "b"};
    auto tags = GG::TagParser::ParseTags("<rgba 255 0 0 255>Red <b>bold</b> text</rgba>", known_tags);
    BOOST_CHECK_EQUAL(tags.size(), 3);
    BOOST_CHECK_EQUAL(tags[0].tag, "rgba");
    BOOST_CHECK_EQUAL(tags[1].tag, "b");
    BOOST_CHECK_EQUAL(tags[2].tag, "rgba");
}

// ... other test cases
```

These changes provide a comprehensive fix for the tag parsing and handling issues across the codebase. The modifications ensure consistent use of the TagParser, proper color validation, and correct handling of various tag types. The changes are inclusive of the entire relevant functions and their scopes, providing context for each fix.

Remember to update the corresponding header files for any public interface changes, and to adjust any other parts of the codebase that might be affected by these changes. Also, make sure that all necessary include statements are present in each file.

**Comment by geoffthemedio** [comment]
You appear to be copy-pasting output from ChatGPT or equivalent so I'm not going to pay it much attention.

**Comment by Mr-Twave** [comment]
> You appear to be copy-pasting output from ChatGPT or equivalent so I'm not going to pay it much attention.

I'm not using ChatGPT, Claude 3.5 Sonnet diagnosed the issue. Want to test it out w/ me?

**Comment by Blue-Award** [comment]
@Mr-Twave , please understand that piping stuff through a large language model and then expecting others to check if it makes sense, is not exactly helping. It pretty much means asking others to do all the actual work necessary to understand the issue etc.

Though seems you're trying to set up your own build to dig further into this - awesome!

Entertaining the proposed change, all I can see it does is moving `</rgba>` closing tag to right after player's name in case of player message, dropping the coloring of the message itself (not coloring the (Whisper) mention, either). Don't see how it fixes anything, and actually breaks the normal use case of coloring entire player's message.

Maybe it fixes something in case player put <rgba> tags themselves into the message, but doesn't even fix anything if the tags user put in were malformed. I would treat that as separate case, somehow sanitizing/dealing with tags in user input. Maybe my fault of reporting that on the https://github.com/freeorion/freeorion/issues/4946 - I was trying to note something peculiar but I don't claim it's the same as original issue.

I think it might be quite hard to fix the original issue without clear reproduction steps. And not like we have any at the moment (except that it was happening quite inevitably in our multiplayer games - but not like we know what triggers the issue there)

**Comment by Mr-Twave** [comment]
I feel like I've identified the file with the error with the change.
Piping it through a large language model was more to bring attention to the correct place. The correct place seems to be the file I've modified- I just need the correct understanding of what the output should look like. As you say, the whole player's message should be colored. Unfortunately, I think that could be more complicated than you want, especially in cases where there are nested rgba tags.

**Comment by Mr-Twave** [comment]
I'll try and pipe it through Claude 3.5 sonnet again with your suggestions. I don't think you'll be getting a solution for that soon. My workaround solution should prevent that error from occurring, though.

**Comment by Mr-Twave** [comment]
Closed in favor of the clever fix @Blue-Award came up with by using bisects to narrow down the scope of the issue in #4994 .

**Pull request closed without merging**
