### PR TITLE
Fix CI build for OSX

### PR DESCRIPTION
**Pull request by dbenage-cx**
Minor attempt to fix travis errors, will look into this more tonight

### CODE REVIEW

**Comment by geoffthemedio** [comment]
It's failing with a time limit now, rather than immediately, so that's an improvement.

**Comment by adrianbroher** [comment]
The `brew update` (line 35) statement should be obsolete too when raising the OSX image to version 8.3 (line 21), which would shave off another 2 to 3 minutes of build time.  The previous 8.1 version was retired some time ago by TravisCI anyway.

https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

**Comment by dbenage-cx** [comment]
@adrianbroher TY for link, I removed the request for a specific `osx_image` to lower a need to update the config each time the image is deprecated (but maybe you prefer we not implicitly follow the default?).

I did not find anything around the 28 December time-frame (roughly when builds stopped working), so assume this was when the deprecated 8.1 image was removed.

**Comment by adrianbroher** [comment]
@dbenage-cx Yes, I would prefer to keep an explicit version instead of praying for the current default to work.

**Pull request merged**
