### PR TITLE
Remove AIInterface::DoneTurn() calls from Python AI

### PR DESCRIPTION
**Pull request by Morlic-fo**
There is a single logical place to call AIInterface::DoneTurn(). Let's call it at that particular time and avoid worrying about it in python code...

### CODE REVIEW

**Review by Dilvish-fo — COMMENTED** [review]
I think this will likely have some minor conflicts with #2273 , which has more commits and has been pending longer so I've like to let CJ wrap that up first, then have you deal with any conflicts here before merging this.

Also, just to note, there have been discussions on the forums, focused on multiplayer games, about making the turn-end process still allow player to submit more orders until everyone is done.  If that gets implemented, it could be beneficial to try having the AI split order generation into high-priority/fast orders and lower-priority and/or super-carefully-checked orders, the latter of which could be interrupted in some way if they drag on past a couple minutes if the human player is already finished.  That might easily call for reverting some of this, but would also involve a lot of other related changes.  So I don't really see that prospect as a reason to not do this, but still felt it worth noting.

**Comment by Cjkjvfnby** [comment]
@Morlic, please resolve conflicts

**Comment by geoffthemedio** [comment]
@Morlic-fo see the previous comment with (probably) the wrong name linked.

**Comment by Cjkjvfnby** [comment]
@Morlic-fo do you plan to merge this?

**Comment by Morlic-fo** [comment]
Will come back to this, thanks for reminder.

**Comment by geoffthemedio** [comment]
needs rebase...

**Comment by geoffthemedio** [comment]
@Morlic-fo ?

**Pull request merged**
