### PR TITLE
rework of stacking system

### PR DESCRIPTION
**Pull request by Morlic-fo**
-add capacity to shields, detectors, stealth
-add macros to handle stacking: only the strongest part works

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
as I understand it, since this PR is still pending the better practice (for a cleaner commit history) will be for morlic to use "rebase -i" to squash this last fixit commit in with the first one (like described here http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html), yes?

**Comment by adrianbroher** [comment]
@Dilvish-fo Yes, lets try that.

**Comment by Morlic-fo** [comment]
ok... after endless problems (why would notepad++ not work with git?) I think I finally got it right?

Oh - seems like comments to the commits get removed as well.

**Comment by adrianbroher** [comment]
> I think I finally got it right?

Yeah, that looks good.

> Oh - seems like comments to the commits get removed as well.

It doesn't matter, the comment was fixed this way anyway.

This PR still needs a review from a FOCS guy.

**Comment by Dilvish-fo** [comment]
Ok this looks fine to me and appears to work as expected.  It's my understanding from the related forum thread that Geoff is ok with this going in, subject to the understanding that it may need revision if we change stacking and/or the significance/operation of part capacity, so I'll merge the pull request.

**Pull request merged**
