### PR TITLE
Add alternatives to Ancient Guardians

### PR DESCRIPTION
**Pull request by MichaelCourtney**

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
https://www.freeorion.org/forum/viewtopic.php?f=15&t=12470

There's a 2nd change I'm working on as with high specials and high minimum monster jumps you get too many ancient guardians. My opinion is Raagh's would be perfectly fine guards on terrans and stealthy natives would be fine on their relevant enviros. I just haven't worked out how to script a bunch of different native guards for different enviros in a clean fashion.

**Comment by MichaelCourtney** [comment]
Re Phinnert:

Homeworld:
Their planet has low gravity and a very thick atmosphere. Its composition is unique as it has a low proportion of heavier metals, but a much higher proportion of other heavy elements, particularly noble gases.

**Comment by MichaelCourtney** [comment]
Note there are a couple of bugs in it I can't work out at the moment. For some reason it seems to always add cloud cover to ancient guards on tundras and ancient guards/nymnmn on deserts. I also seem to always get ancient guards and not hhhoh or furthest on the tundras.

Also needs a check in there for no natives setting. Not sure what that is

**Comment by MichaelCourtney** [comment]
Ok I left SP_ off hhhoh and furthest, which explains some things

**Comment by MichaelCourtney** [comment]
Fixed weirdness with cloud cover. It's now working except for:

Phinnert don't get the cloud cover special when added via guards
No check yet for natives = none
Any tweaking suggested by others, e.g. should the weaker guards get a building (ancient shield generator?), or similar changes

**Comment by MichaelCourtney** [comment]
It's working now, but it needs something to make some of the guards tougher

**Comment by MichaelCourtney** [comment]
Done. Reason for change is mostly aesthetic. Sometimes I get a universe with too many ancient guardians. To my eye ancient guardians everywhere looks ugly, and they can be quite annoying.

**Comment by MichaelCourtney** [comment]
Side note it doesn't place furthest near a capital and it would be nice in general if furthest (normal native placement) weren't near empires (due to the name), but I don't know if Species will take a location entry.

**Comment by Vezzra** [comment]
@MichaelCourtney, closed as abandoned, superseded, invalid...?

**Comment by MichaelCourtney** [comment]
Closed due to being a "messy" implementation. Though I didn't delete the branch, if there is interest in this.

**Comment by Vezzra** [comment]
Has it been replaced with/superseded by a better implementation/PR?

**Comment by MichaelCourtney** [comment]
> Has it been replaced with/superseded by a better implementation/PR?

No. I was just trying to clear out some PRs I wasn't working on any more, on the grounds they may be distracting. Apologies if that was the wrong decision. Functionally the PR works if its something you'd like to include post-release.

**Comment by Vezzra** [comment]
No problem, just wanted to know what label for closing I need to use... :wink:

**Pull request closed without merging**
