### PR TITLE
Don't set any roles when return player to lobby.

### PR DESCRIPTION
**Pull request by o01eg**
Fix issue when returned back to lobby players acquired roles he shouldn't to have or lost his roles.

### CODE REVIEW

**Comment by o01eg** [comment]
@geoffthemedio  Found it while testing ingame lobby. If player don't get roles to become Moderator or Observer after current game is finished he is returned back to lobby and here get additional roles he mustn't obtain.

**Comment by geoffthemedio** [comment]
The player gets the extra roles only if they don't have them initially, or regardless of the roles they had before the game? What if the player has the extra roles before the game? Do they retain them when being returned to the lobby? What if a player doesn't have galaxy setup adjustment roles before a game, do they then get them after the game?

**Comment by o01eg** [comment]
> The player gets the extra roles only if they don't have them initially, or regardless of the roles they had before the game?

Regardless previous roles.

> What if the player has the extra roles before the game? Do they retain them when being returned to the lobby?

He will lose them as well.

> What if a player doesn't have galaxy setup adjustment roles before a game, do they then get them after the game?

In a hostless mode all players should capable to adjust galaxy setup. But, if someone was revoked this role, he obtain them here. Maybe I shouldn't change any roles when return to lobby. Thanks.

**Comment by geoffthemedio** [comment]
So now if a player is in a game then returns to the lobby, they lose all roles? It doesn't check what roles the player should have if defined in `auth.txt` and they then instead have no roles...?

**Comment by o01eg** [comment]
> So now if a player is in a game then returns to the lobby, they lose all roles?

No. After changes player have his roles untouched.

> It doesn't check what roles the player should have if defined in `auth.txt` and they then instead have no roles...?

Player connection obtains roles on establish and then never changes its roles.

**Comment by geoffthemedio** [comment]
Your various replies seem to contradict eachother, but presumably the latest is accurate.

**Pull request merged**
