### PR TITLE
Append appropriate file extension when saving

### PR DESCRIPTION
**Pull request by dbenage-cx**
Addresses the expected result portion of #660

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@geoffthemedio, can you take care about this PR?

**Comment by geoffthemedio** [comment]
This doesn't quite work as intended. If there is a file "test", then it will pop up a warning about overwriting, even though the file that will be written is "test.sav". If there is a "test.sav", and the user types just "test", it won't pop up a warning, but will overwrite the "test.sav" file.

**Comment by dbenage-cx** [comment]
Moved to CheckChoiceValidity(), appending the extension as the user types (saving only).

**Comment by geoffthemedio** [comment]
Now when I put the cursor at the end of a filename and press backspace, or otherwise type anything without .sav at the end, it appends it very awkwardly.
extension

**Comment by dbenage-cx** [comment]
Was commit 2b5d9ca accidental?  I can rebase either way but wanted to check before scrubbing a commit.

New commit behavior disables the OK button if the extension is not valid.  To assist quickly changing the name, only the non-extension part of the filename is initially selected.

If that is not preferred, should we just hide the extension from the user?

**Comment by geoffthemedio** [comment]
yes, accidental. switching between branches apparently didn't remove the old branch modifications before applying the new branch stuff, and then after an unrelated commit I pushed.

**Comment by geoffthemedio** [comment]
Disabling the OK button without any indication why is not useful.
It should just treat any save file name without ".sav" at the end as if it had ".sav" at the end when the user clicks OK. That includes popping up a warning that "test.sav" already exists if the user types just "test".

**Comment by dbenage-cx** [comment]
Rebased.  Of note, multiplayer does not confirm overwrite.  This is the same behavior as master so I did not want to muddy the waters further if this is a separate issue.

**Comment by Vezzra** [comment]
> Addresses the expected result portion of #660

Is #660 completely fixed by this (and can be closed), or are further fixes required to address #660?

**Comment by dbenage-cx** [comment]
@Vezzra I've commented on issue, remainder is expected behavior.

**Pull request merged**
