### PR TITLE
ScriptingContext State Passing

### PR DESCRIPTION
**Pull request by geoffthemedio**
This is an incremental step towards replacing accessing gamestate via global getters in Effect, ValueRef, Condition, and similar code, and instead getting it from the passed-in ScriptingContext:
-take and store SpeciesManager by mutable reference in ScriptingContext
-modify ScriptingContext state in Effects
-access and modify ScriptingContext state rather than member state in Universe effect functions

### CODE REVIEW

**Comment by o01eg** [comment]
I've started server under gdb and connect client to it. Then I started the game and catch segfault:

```
19:21:15.815080 {0x00007ffff41f6740} [debug] python : monsters.py:205 : Actual # monster fleets placed: 14; Total Placement Expectation: 179.1
19:21:15.815159 {0x00007ffff41f6740} [debug] python : universe_generator.py:180 : Distributing Starting Specials
19:21:15.815306 {0x00007ffff41f6740} [debug] python : specials.py:77 : Specials available for distribution at game start:
19:21:15.815333 {0x00007ffff41f6740} [debug] python : specials.py:79 : ... ABANDONED_COLONY_SPECIAL      : spawn rate 0.400 / spawn limit 9999
...
19:21:15.815746 {0x00007ffff41f6740} [debug] python : specials.py:79 : ... WORLDTREE_SPECIAL             : spawn rate 1.000 / spawn limit 1
19:21:15.815824 {0x00007ffff41f6740} [debug] python : specials.py:86 : Base chance for specials is 0.2. Placing specials on 73 of 393 (0.1858)objects
19:21:15.815941 {0x00007ffff41f6740} [debug] python : specials.py:109 :  Placing in 57 locations remaining.
19:21:15.816106 {0x00007ffff41f6740} [debug] python : specials.py:127 : Caching specials_locations() at 6 of 73 remaining locations.
```

```
Thread 1 "freeoriond" received signal SIGSEGV, Segmentation fault.
0x00007ffff78e659c in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_lower_bound (this=<optimized out>, __k=<synthetic pointer>: 1036, __y=0x5555559c9058, __x=0x7000500000005)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/stl_tree.h:1945
1945		if (!_M_impl._M_key_compare(_S_key(__x), __k))
(gdb) bt
#0  0x00007ffff78e659c in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_lower_bound (this=<optimized out>, __k=<synthetic pointer>: 1036, __y=0x5555559c9058, __x=0x7000500000005)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/stl_tree.h:1945
#1  std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::find (__k=<synthetic pointer>: 1036, this=0x5555559c9050) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/stl_tree.h:2570
#2  std::set<int, std::less<int>, std::allocator<int> >::count (__x=<synthetic pointer>: 1036, this=0x5555559c9050) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/stl_set.h:749
#3  Condition::(anonymous namespace)::HomeworldSimpleMatch::operator() (this=<synthetic pointer>, this=<synthetic pointer>, candidate=std::shared_ptr<const UniverseObject> (use count 9, weak count 1) = {...})
    at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:1638
#4  (anonymous namespace)::<lambda(const auto:57&)>::operator()<std::shared_ptr<const UniverseObject> > (o=std::shared_ptr<const UniverseObject> (use count 9, weak count 1) = {...}, this=<synthetic pointer>)
    at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:125
#5  std::copy_if<std::move_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<const UniverseObject>*, std::vector<std::shared_ptr<const UniverseObject> > > >, std::back_insert_iterator<std::vector<std::shared_ptr<const UniverseObject> > >, (anonymous namespace)::EvalImpl(Condition::ObjectSet&, Condition::ObjectSet&, Condition::SearchDomain, const Pred&) [with Pred = Condition::(anonymous namespace)::HomeworldSimpleMatch]::<lambda(const auto:57&)> > (__pred=..., 
    __result=..., __last=..., __first=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/stl_algo.h:749
#6  (anonymous namespace)::EvalImpl<Condition::(anonymous namespace)::HomeworldSimpleMatch> (pred=..., search_domain=<optimized out>, non_matches=..., matches=...) at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:122
#7  Condition::Homeworld::Eval (this=<optimized out>, parent_context=..., matches=..., non_matches=..., search_domain=<optimized out>) at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:1680
#8  0x00007ffff791e9c3 in Condition::Contains::Eval (this=0x7fffd42d7d50, parent_context=..., matches=std::vector of length 1, capacity 1 = {...}, non_matches=std::vector of length 0, capacity 0, 
    search_domain=Condition::SearchDomain::MATCHES) at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:2893
#9  0x00007ffff790b7bd in Condition::And::Eval (this=<optimized out>, parent_context=..., matches=std::vector of length 1, capacity 1 = {...}, non_matches=std::vector of length 0, capacity 0, 
    search_domain=Condition::SearchDomain::MATCHES) at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:9849
#10 0x00007ffff791dff2 in Condition::ContainedBy::Eval (this=0x7fffd42bab90, parent_context=..., matches=std::vector of length 5, capacity 8 = {...}, non_matches=std::vector of length 1, capacity 6 = {...}, 
    search_domain=Condition::SearchDomain::NON_MATCHES) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/unique_ptr.h:154
#11 0x00007ffff7905e73 in Condition::Not::Eval (this=<optimized out>, parent_context=..., matches=..., non_matches=..., search_domain=<optimized out>) at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:10167
#12 0x00007ffff790c041 in Condition::And::Eval (this=0x7fffd42ce140, parent_context=..., matches=std::vector of length 0, capacity 0, non_matches=std::vector of length 5, capacity 8 = {...}, search_domain=<optimized out>)
    at /mnt/another/srcs/GIT/freeorion/universe/Conditions.cpp:9831
#13 0x000055555588807e in (anonymous namespace)::FilterIDsWithCondition (cond=0x7fffd42ce140, obj_ids=...) at /mnt/another/srcs/GIT/freeorion/server/ServerWrapper.cpp:210
#14 0x000055555588a870 in (anonymous namespace)::SpecialLocations (special_name="ABANDONED_COLONY_SPECIAL", object_ids=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/unique_ptr.h:154
#15 0x000055555589b6a3 in boost::python::detail::invoke<boost::python::to_python_value<boost::python::list const&>, boost::python::list (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::python::list const&), boost::python::arg_from_python<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::python::arg_from_python<boost::python::list const&> > (ac1=..., ac0=..., f=<optimized out>, rc=...)
    at /usr/include/boost/python/detail/invoke.hpp:73
#16 boost::python::detail::caller_arity<2u>::impl<boost::python::list (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<boost::python::list, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::python::list const&> >::operator() (args_=<optimized out>, this=<optimized out>)
    at /usr/include/boost/python/detail/caller.hpp:233
#17 boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::python::list (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<boost::python::list, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::python::list const&> > >::operator() (this=<optimized out>, args=<optimized out>, 
    kw=<optimized out>) at /usr/include/boost/python/object/py_function.hpp:38
#18 0x00007ffff707f72d in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib64/libboost_python38.so.1.74.0
#19 0x00007ffff707f928 in ?? () from /usr/lib64/libboost_python38.so.1.74.0
#20 0x00007ffff7084833 in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib64/libboost_python38.so.1.74.0
#21 0x00007ffff707d0f2 in ?? () from /usr/lib64/libboost_python38.so.1.74.0
#22 0x00007ffff6db69e6 in _PyObject_MakeTpCall () from /usr/lib64/libpython3.8.so.1.0
#23 0x00007ffff6d8fc23 in ?? () from /usr/lib64/libpython3.8.so.1.0
#24 0x00007ffff6d96f26 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.8.so.1.0
#25 0x00007ffff6e6d464 in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.8.so.1.0
#26 0x00007ffff6db6790 in _PyFunction_Vectorcall () from /usr/lib64/libpython3.8.so.1.0
#27 0x00007ffff6d8fb9d in ?? () from /usr/lib64/libpython3.8.so.1.0
#28 0x00007ffff6d936f2 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.8.so.1.0
#29 0x00007ffff6d8e8a9 in ?? () from /usr/lib64/libpython3.8.so.1.0
#30 0x00007ffff6db84df in PyVectorcall_Call () from /usr/lib64/libpython3.8.so.1.0
#31 0x00007ffff6d9337f in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.8.so.1.0
#32 0x00007ffff6e6d464 in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.8.so.1.0
#33 0x00007ffff6db6790 in _PyFunction_Vectorcall () from /usr/lib64/libpython3.8.so.1.0
#34 0x00007ffff6db72ce in ?? () from /usr/lib64/libpython3.8.so.1.0
#35 0x00007ffff6db758e in PyEval_CallFunction () from /usr/lib64/libpython3.8.so.1.0
#36 0x00005555557fa51c in boost::python::call<boost::python::api::object, boost::python::dict> (a0=..., callable=<optimized out>) at /usr/include/boost/python/object_core.hpp:440
#37 boost::python::api::object_operators<boost::python::api::object>::operator()<boost::python::dict> (a0=..., this=0x7fffffffbb40) at /usr/include/boost/python/object_call.hpp:19
#38 PythonServer::CreateUniverse (this=this@entry=0x7fffffffd270, player_setup_data=std::map with 3 elements = {...}) at /mnt/another/srcs/GIT/freeorion/server/ServerFramework.cpp:302
#39 0x00005555557bd9ef in ServerApp::GenerateUniverse (this=0x7fffffffc7a0, player_setup_data=std::map with 3 elements = {...}) at /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:1512
#40 0x00005555557bebd1 in ServerApp::NewGameInitConcurrentWithJoiners (this=0x7fffffffc7a0, galaxy_setup_data=..., player_setup_data=...) at /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:717
#41 0x00005555557bf5fb in ServerApp::NewMPGameInit (this=this@entry=0x7fffffffc7a0, multiplayer_lobby_data=...) at /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:640
#42 0x000055555583374e in WaitingForMPGameJoiners::react (this=0x555555f542c0, u=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:1020
#43 0x0000555555855a55 in boost::statechart::custom_reaction<CheckStartConditions>::react<WaitingForMPGameJoiners, boost::statechart::event_base, void const*> (
    eventType=<synthetic pointer>: 0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>, evt=..., stt=...) at /usr/include/boost/statechart/custom_reaction.hpp:41
#44 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list4<boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> >, boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0> > (
    eventType=0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>, evt=..., stt=...) at /usr/include/boost/statechart/simple_state.hpp:814
#45 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react<boost::mpl::list4<boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> > > (eventType=0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>, evt=..., this=0x555555f542c0)
    at /usr/include/boost/statechart/simple_state.hpp:850
#46 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list5<boost::statechart::custom_reaction<AuthResponse>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> >, boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0> > (eventType=<optimized out>, evt=..., stt=...) at /usr/include/boost/statechart/simple_state.hpp:820
#47 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react<boost::mpl::list5<boost::statechart::custom_reaction<AuthResponse>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> > > (eventType=<optimized out>, evt=..., this=<optimized out>)
    at /usr/include/boost/statechart/simple_state.hpp:850
#48 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list6<boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<AuthResponse>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> >, boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0> > (eventType=0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>, evt=..., stt=...) at /usr/include/boost/statechart/simple_state.hpp:820
#49 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react<boost::mpl::list6<boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<AuthResponse>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> > > (
    eventType=0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>, evt=..., this=0x555555f542c0) at /usr/include/boost/statechart/simple_state.hpp:850
#50 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list<boost::statechart::in_state_reaction<Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection>, boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<AuthResponse>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0> > (eventType=0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>, evt=..., stt=...) at /usr/include/boost/statechart/simple_state.hpp:820
#51 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react<boost::mpl::list<boost::statechart::in_state_reaction<Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection>, boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<AuthResponse>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> > (
    eventType=0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>, evt=..., this=0x555555f542c0) at /usr/include/boost/statechart/simple_state.hpp:850
#52 boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl (this=0x555555f542c0, evt=..., eventType=0x5555559c8140 <boost::statechart::detail::id_holder<CheckStartConditions>::idProvider_>)
    at /usr/include/boost/statechart/simple_state.hpp:488
#53 0x00005555557ee196 in boost::statechart::detail::send_function<boost::statechart::detail::state_base<std::allocator<boost::statechart::none>, boost::statechart::detail::rtti_policy>, boost::statechart::event_base, void const*>::operator() (this=<synthetic pointer>) at /usr/include/boost/statechart/state_machine.hpp:84
#54 boost::statechart::null_exception_translator::operator()<boost::statechart::detail::send_function<boost::statechart::detail::state_base<std::allocator<boost::statechart::none>, boost::statechart::detail::rtti_policy>, boost::statechart::event_base, void const*>, boost::statechart::state_machine<ServerFSM, Idle, std::allocator<boost::statechart::none>, boost::statechart::null_exception_translator>::exception_event_handler> (this=0x555555a15840, action=...)
    at /usr/include/boost/statechart/null_exception_translator.hpp:33
#55 boost::statechart::state_machine<ServerFSM, Idle, std::allocator<boost::statechart::none>, boost::statechart::null_exception_translator>::send_event (evt=..., this=0x555555a157d0)
    at /usr/include/boost/statechart/state_machine.hpp:885
#56 boost::statechart::state_machine<ServerFSM, Idle, std::allocator<boost::statechart::none>, boost::statechart::null_exception_translator>::process_queued_events (this=<optimized out>)
    at /usr/include/boost/statechart/state_machine.hpp:910
#57 boost::statechart::state_machine<ServerFSM, Idle, std::allocator<boost::statechart::none>, boost::statechart::null_exception_translator>::process_event (this=this@entry=0x555555a157d0, evt=...)
    at /usr/include/boost/statechart/state_machine.hpp:280
#58 0x00005555557b8c2f in ServerApp::HandleNonPlayerMessage (this=<optimized out>, msg=..., player_connection=std::shared_ptr<PlayerConnection> (use count 9, weak count 1) = {...})
    at /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:482
#59 0x00005555557de1a4 in boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >::operator() (a2=..., a1=..., p=<optimized out>, this=<optimized out>) at /usr/include/boost/bind/mem_fn_template.hpp:280
#60 boost::_bi::list3<boost::_bi::value<ServerApp*>, boost::arg<1>, boost::arg<2> >::operator()<boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >, boost::_bi::rrlist2<Message, std::shared_ptr<PlayerConnection> > > (a=<synthetic pointer>..., f=..., this=<optimized out>) at /usr/include/boost/bind/bind.hpp:398
#61 boost::_bi::bind_t<void, boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >, boost::_bi::list3<boost::_bi::value<ServerApp*>, boost::arg<1>, boost::arg<2> > >::operator()<Message, std::shared_ptr<PlayerConnection> > (a2=..., a1=..., this=<optimized out>) at /usr/include/boost/bind/bind.hpp:1318
#62 std::_Function_handler<void (Message, std::shared_ptr<PlayerConnection>), boost::_bi::bind_t<void, boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >, boost::_bi::list3<boost::_bi::value<ServerApp*>, boost::arg<1>, boost::arg<2> > > >::_M_invoke(std::_Any_data const&, Message&&, std::shared_ptr<PlayerConnection>&&) (__functor=..., __args#0=..., __args#1=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/std_function.h:300
#63 0x00005555558651a0 in std::function<void (Message, std::shared_ptr<PlayerConnection>)>::operator()(Message, std::shared_ptr<PlayerConnection>) const (__args#1=std::shared_ptr<PlayerConnection> (empty) = {...}, __args#0=..., 
    this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/std_function.h:688
#64 boost::_bi::list2<boost::_bi::value<Message>, boost::_bi::value<std::shared_ptr<PlayerConnection> > >::operator()<std::function<void (Message, std::shared_ptr<PlayerConnection>)>, boost::_bi::list0>(boost::_bi::type<void>, std::function<void (Message, std::shared_ptr<PlayerConnection>)>&, boost::_bi::list0&, int) (a=<synthetic pointer>..., f=..., this=<optimized out>) at /usr/include/boost/bind/bind.hpp:319
#65 boost::_bi::bind_t<boost::_bi::unspecified, std::function<void (Message, std::shared_ptr<PlayerConnection>)>, boost::_bi::list2<boost::_bi::value<Message>, boost::_bi::value<std::shared_ptr<PlayerConnection> > > >::operator()() (
    this=<optimized out>) at /usr/include/boost/bind/bind.hpp:1294
#66 std::_Function_handler<void (), boost::_bi::bind_t<boost::_bi::unspecified, std::function<void (Message, std::shared_ptr<PlayerConnection>)>, boost::_bi::list2<boost::_bi::value<Message>, boost::_bi::value<std::shared_ptr<PlayerConnection> > > > >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/std_function.h:300
#67 0x00005555558576ae in std::function<void ()>::operator()() const (this=0x7fffffffc510) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/std_function.h:688
#68 ServerNetworking::HandleNextEvent (this=this@entry=0x7fffffffd110) at /mnt/another/srcs/GIT/freeorion/server/ServerNetworking.cpp:748
#69 0x00005555557a05a0 in ServerApp::Run (this=<optimized out>) at /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:337
#70 0x0000555555605e28 in main (argc=<optimized out>, argv=<optimized out>) at /mnt/another/srcs/GIT/freeorion/server/dmain.cpp:96
```

`IApp::s_app` is initialized here.

**Comment by geoffthemedio** [comment]
probably need to pass a named and longer-lifetime ScriptingContext rather than a temporary to those MatchHelper structs that store the input parameter by reference...

**Comment by geoffthemedio** [comment]
@o01eg Could you post another crash stacktrace with the latest version of this branch?

**Review by o01eg — APPROVED** [review]
Looks it builds and works now.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/cd5ceebcd926c1402f0bdac92ca5e1303fb8a9d5

**Pull request closed without merging**
