### PR TITLE
Allowed wider and taller windows to span multiple monitors

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This is a simple patch to allow freeorion to startup spanning dual monitors.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
10240 pixels seems a bit excessive...

**Comment by LGM-Doyle** [comment]
Yes it is excessive.

It is a lot more than my two monitors.

However, it is less than three 4K monitors side by side, 3*3840 = 111520, so it is arguably too small.
Ideally, someone uses SDL to determine the whole desktop size and caps it at that size, but I thought that would be OS dependent and painful.

I figure you can wait until someone tries at a size wider than 10240 and bumps it again.

**Comment by geoffthemedio** [comment]
Regardless of the combined size of big monitors, does the UI even make sense to have that big?

**Comment by LGM-Doyle** [comment]
Overall it works very well.

The startup defaults do not work.  Many of the sub windows default to 1/2 overall window size, which means in my case an entire monitor.  However, once you have started a game and adjusted the windows once it works wonderfully.  

I have 2/3 of one monitor with pedia, queues, turn report and fleets and pretty much the galaxy on the second screen.  It is galactoramic.

I do not think that it is possible to imagine all the sizes people might want to play at.  There are three changes that will improve the experience.

First add more windows final state to the saved UI state so they do not need to be adjusted each time you restart.  For example the research filter always pops up spanning the entire screen on each restart.

Second, choose some maximum default sizes and aspect ratios so that you don't get pedias that span two or three monitors.

Third, in the future start sizing things in a pixel independent manner.  I have not read enough of the code, nor am I familiar enough with SDL to know if this isn't already being done.

**Comment by geoffthemedio** [comment]
ok...

**Pull request merged**
