### PR TITLE
[Universe Generation] Use Tables in statistic

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
- use tables instead of prints
- print empty values

before

```
############################################################
##             Universe generation statistics             ##
############################################################
Planet Count Distribution: planets_in_system | num_systems | % of systems
             0  |    55 | 36.7%
             1  |    46 | 30.7%
             2  |    31 | 20.7%
             3  |    11 |  7.3%
             4  |     6 |  4.0%
             5  |     1 |  0.7%

Planet Size Distribution: size | count | % of planets
        tiny         |     5 |  2.9%
        small        |    32 | 18.8%
        medium       |    64 | 37.6%
        large        |     9 |  5.3%
        huge         |     3 |  1.8%
        asteroids    |    29 | 17.1%
        gasGiant     |    28 | 16.5%
############################################################
Planet Type Summary for a total of 170 placed planets
swamp        11.2%
toxic         6.5%
inferno       7.1%
radiated      8.2%
barren        7.1%
tundra        5.3%
desert        4.7%
terran        8.8%
ocean         7.6%
asteroids    17.1%
gasGiant     16.5%
############################################################
Empire Starting Species Summary for 7 Empires and 10 playable species
Approximately 0 to 1 empires expected per species
species          :   # --     %
SP_TRITH         :   1 --  14.3%
SP_ETTY          :   2 --  28.6%
SP_GYSACHE       :   2 --  28.6%
SP_HUMAN         :   2 --  28.6%

Natives Placement Summary (native frequency: 14.3%)
Settled natives         SP_SETINON on   2 planets --   2.3% of total and  13.3% vs   2.9% (actual vs expected) of ['swamp'] planets
Settled natives        SP_SILEXIAN on   1 planets --   1.1% of total and  10.0% vs   7.1% (actual vs expected) of ['terran'] planets
Settled natives    SP_GISGUFGTHRIM on   2 planets --   2.3% of total and  20.0% vs   7.1% (actual vs expected) of ['toxic'] planets
Settled natives       SP_TRENCHERS on   1 planets --   1.1% of total and  11.1% vs   4.8% (actual vs expected) of ['barren'] planets
Settled natives      SP_FIFTYSEVEN on   1 planets --   1.1% of total and   6.7% vs   2.9% (actual vs expected) of ['swamp'] planets
Settled natives        SP_BEIGEGOO on   1 planets --   1.1% of total and   7.1% vs   7.1% (actual vs expected) of ['radiated'] planets
Settled natives          SP_RAAAGH on   1 planets --   1.1% of total and  10.0% vs   7.1% (actual vs expected) of ['terran'] planets
Settled natives        SP_ABADDONI on   1 planets --   1.1% of total and  11.1% vs   7.1% (actual vs expected) of ['inferno'] planets
Settled natives         SP_SCYLIOR on   1 planets --   1.1% of total and  12.5% vs   4.8% (actual vs expected) of ['ocean'] planets
Settled natives         SP_ACIREMA on   1 planets --   1.1% of total and   7.1% vs   7.1% (actual vs expected) of ['radiated'] planets

Planet Type Summary for Native Planets (native frequency: 14.3%)
Potential (% of tot) : Settled (% of potential)
Totals           87 :    12
swamp         17.2% :  20.0%
toxic         11.5% :  20.0%
inferno       10.3% :  11.1%
radiated      16.1% :  14.3%
barren        10.3% :  11.1%
tundra         9.2% :   0.0%
desert         4.6% :   0.0%
terran        11.5% :  20.0%
ocean          9.2% :  12.5%
asteroids      0.0% :   0.0%
gasGiant       0.0% :   0.0%
############################################################
Space Monsters Placement Summary
Placed space monster SM_CLOUD 1 times
Placed space monster SM_KRILL_1 2 times
Placed space monster SM_TREE 2 times
Placed space monster SM_FLOATER 2 times
Placed space monster SM_SNAIL 1 times

Tracked Monster and Nest Summary (base monster freq: 12.5%)
Monster            |   chance |  # tried | # placed | # valid sys locs | # valid nest planet locs
SM_KRAKEN_1        |   0.10   |      4   |      0   |         10       |   10
SM_SNOWFLAKE_1     |   0.15   |      3   |      0   |         18       |   20
SM_JUGGERNAUT_1    |   0.15   |      0   |      0   |          5       |    7
############################################################
Special Placement Summary
Placed special SPICE_SPECIAL 1 times
Placed special GAIA_SPECIAL 2 times
Placed special MINERALS_SPECIAL 2 times
Placed special ELERIUM_SPECIAL 1 times
Placed special DERELICT_SPECIAL3 14 times
Placed special DERELICT_SPECIAL2 12 times
Placed special SUPERCONDUCTOR_SPECIAL 4 times
Placed special ABANDONED_COLONY_SPECIAL 1 times
Placed special ACCRETION_DISC_SPECIAL 1 times
Placed special MODERATE_TECH_NATIVES_SPECIAL 1 times
Placed special HONEYCOMB_SPECIAL 1 times
Placed special PANOPTICON_SPECIAL 1 times
Placed special TIDAL_LOCK_SPECIAL 2 times
Placed special CRYSTALS_SPECIAL 8 times
Placed special ECCENTRIC_ORBIT_SPECIAL 1 times
Placed special RESONANT_MOON_SPECIAL 3 times
Placed special PROBIOTIC_SPECIAL 2 times
Placed special FRUIT_SPECIAL 2 times

Specials Count(Repeat) Distribution:
     count  | tally | % of objects
          0 |   368 | 86.2%
          1 |    59 | 13.8%
          2 |     0 |  0.0%
          3 |     0 |  0.0%
          4 |     0 |  0.0%
```

after

```
###########################################################
##             Universe generation statistics             ##
############################################################
Planet Count Distribution
=====================================================
| planets in system | num of systems | % of systems |
=====================================================
| 0                 |             67 |         44.7 |
| 1                 |             34 |         22.7 |
| 2                 |             27 |         18.0 |
| 3                 |             19 |         12.7 |
| 4                 |              2 |          1.3 |
| 5                 |              1 |          0.7 |
-----------------------------------------------------
Planet Size Distribution
====================================
| size      | count | % of planets |
====================================
| tiny      |    10 |          6.3 |
| small     |    26 |         16.5 |
| medium    |    54 |         34.2 |
| large     |    14 |          8.9 |
| huge      |     2 |          1.3 |
| asteroids |    26 |         16.5 |
| gasGiant  |    26 |         16.5 |
------------------------------------

############################################################
Planet Type Summary for a total of 158 placed planets
==============================
| planet type | % of planets |
==============================
| swamp       |          8.2 |
| toxic       |          7.6 |
| inferno     |          7.0 |
| radiated    |          7.0 |
| barren      |         10.8 |
| tundra      |          5.1 |
| desert      |          8.9 |
| terran      |          5.1 |
| ocean       |          7.6 |
| asteroids   |         16.5 |
| gasGiant    |         16.5 |
------------------------------

############################################################
Empire Starting Species Summary
Approximately 0 to 1 empires expected per species
7 Empires and 10 playable species
==============================
| species    | count | %     |
==============================
| SP_CHATO   |     0 |   0.0 |
| SP_CRAY    |     0 |   0.0 |
| SP_EAXAW   |     0 |   0.0 |
| SP_EGASSEM |     0 |   0.0 |
| SP_ETTY    |     2 |  28.6 |
| SP_GEORGE  |     0 |   0.0 |
| SP_GYSACHE |     2 |  28.6 |
| SP_HUMAN   |     2 |  28.6 |
| SP_LAENFA  |     0 |   0.0 |
| SP_TRITH   |     1 |  14.3 |
------------------------------

Natives Placement Summary (native frequency: 14.3%)
===========================================================================
| settled natives | on planets | total | actual | expected | planet types |
===========================================================================
| SP_ABADDONI     |          2 |   2.3 |   18.2 |      7.1 |      inferno |
| SP_ACIREMA      |          1 |   1.2 |   11.1 |      7.1 |     radiated |
| SP_KOBUNTURA    |          1 |   1.2 |    7.1 |      4.8 |       barren |
| SP_PHINNERT     |          1 |   1.2 |   10.0 |      2.9 |        swamp |
| SP_SCYLIOR      |          1 |   1.2 |   10.0 |      4.8 |        ocean |
| SP_SETINON      |          2 |   2.3 |   20.0 |      2.9 |        swamp |
| SP_SILEXIAN     |          2 |   2.3 |   33.3 |      7.1 |       terran |
| SP_TRENCHERS    |          1 |   1.2 |    7.1 |      4.8 |       barren |
| SP_UGMORS       |          1 |   1.2 |    9.1 |      7.1 |      inferno |
---------------------------------------------------------------------------

Planet Type Summary for Native Planets (native frequency: 14.3%)
Totals: native_potential_planet_total: 86; native_settled_planet_total 12
=================================================================
| planet type | potential (% of tot) | settled (% of potential) |
=================================================================
| swamp       |        11.6279069767 |            29.9999999997 |
| toxic       |        11.6279069767 |                      0.0 |
| inferno     |        12.7906976744 |            27.2727272725 |
| radiated    |        10.4651162791 |             11.111111111 |
| barren      |        16.2790697674 |            14.2857142856 |
| tundra      |        9.30232558138 |                      0.0 |
| desert      |        9.30232558138 |                      0.0 |
| terran      |        6.97674418604 |            33.3333333328 |
| ocean       |        11.6279069767 |             9.9999999999 |
| asteroids   |                  0.0 |                      0.0 |
| gasGiant    |                  0.0 |                      0.0 |
-----------------------------------------------------------------

############################################################
Monster placement
==============================
| monster            | count |
==============================
| SM_CLOUD           |     2 |
| SM_DAMPENING_CLOUD |     0 |
| SM_DRAGON          |     0 |
| SM_DRONE           |     1 |
| SM_DRONE_FACTORY   |     2 |
| SM_EXP_OUTPOST     |     0 |
| SM_FLOATER         |     3 |
| SM_JUGGERNAUT_1    |     0 |
| SM_KRAKEN_1        |     0 |
| SM_KRILL_1         |     1 |
| SM_SNAIL           |     0 |
| SM_SNOWFLAKE_1     |     0 |
| SM_TREE            |     1 |
------------------------------

Space Monsters Placement Summary
Tracked Monster and Nest Summary (base monster freq: 12.5%)
===============================================================================================================
| monster         | chance | attempts | number placed | number valid sys locs | number valid nest planet locs |
===============================================================================================================
| SM_JUGGERNAUT_1 |   0.15 |        0 |             0 |                     4 |                             4 |
| SM_KRAKEN_1     |   0.10 |        0 |             0 |                    11 |                            13 |
| SM_SNOWFLAKE_1  |   0.15 |        5 |             0 |                    13 |                            17 |
---------------------------------------------------------------------------------------------------------------

############################################################
Special Placement Summary
=================================================
| special                        | times placed |
=================================================
| ABANDONED_COLONY_SPECIAL       |            1 |
| ACCRETION_DISC_SPECIAL         |            0 |
| ANCIENT_RUINS_DEPLETED_SPECIAL |            0 |
| ANCIENT_RUINS_SPECIAL          |            0 |
| BLD_SCRYING_SPHERE             |            1 |
| CLOUD_COVER_MASTER_SPECIAL     |            0 |
| CLOUD_COVER_SLAVE_SPECIAL      |            0 |
| COMPUTRONIUM_SPECIAL           |            0 |
| CONC_CAMP_MASTER_SPECIAL       |            0 |
| CONC_CAMP_SLAVE_SPECIAL        |            0 |
| CRYSTALS_SPECIAL               |            8 |
| DERELICT_SPECIAL2              |            9 |
| DERELICT_SPECIAL3              |            8 |
| DIM_RIFT_MASTER_SPECIAL        |            0 |
| DIM_RIFT_SLAVE_SPECIAL         |            0 |
| ECCENTRIC_ORBIT_SPECIAL        |            5 |
| ELERIUM_SPECIAL                |            2 |
| EXTINCT_BANFORO_SPECIAL        |            0 |
| EXTINCT_KILANDOW_SPECIAL       |            0 |
| EXTINCT_MISIORLA_SPECIAL       |            0 |
| FORTRESS_SPECIAL               |            0 |
| FRUIT_SPECIAL                  |            3 |
| GAIA_SPECIAL                   |            0 |
| HEAD_ON_A_SPIKE_SPECIAL        |            0 |
| HIGH_TECH_NATIVES_SPECIAL      |            1 |
| HONEYCOMB_SPECIAL              |            0 |
| JUGGERNAUT_NEST_SPECIAL        |            0 |
| KRAKEN_NEST_SPECIAL            |            0 |
| MINERALS_SPECIAL               |            4 |
| MODERATE_TECH_NATIVES_SPECIAL  |            0 |
| MONOPOLE_SPECIAL               |            2 |
| NOVA_BOMB_ACTIVATOR_SPECIAL    |            0 |
| PANOPTICON_SPECIAL             |            1 |
| PHILOSOPHER_SPECIAL            |            1 |
| POSITRONIUM_SPECIAL            |            2 |
| PROBIOTIC_SPECIAL              |            2 |
| RESONANT_MOON_SPECIAL          |            0 |
| SNOWFLAKE_NEST_SPECIAL         |            0 |
| SPICE_SPECIAL                  |            2 |
| SUPERCONDUCTOR_SPECIAL         |            3 |
| SUPERNOVA_SPECIAL              |            0 |
| SUPERNOVA_SPECIAL2             |            0 |
| SUPERNOVA_SPECIAL3             |            0 |
| SUPERNOVA_SPECIAL4             |            0 |
| TEMPORAL_ANOMALY_SPECIAL       |            0 |
| TIDAL_LOCK_SPECIAL             |            5 |
| VOID_MASTER_SPECIAL            |            0 |
| VOID_SLAVE_SPECIAL             |            0 |
| VOLCANIC_ACTIVITY_SPECIAL      |            0 |
| VOLCANIC_ASH_MASTER_SPECIAL    |            0 |
| VOLCANIC_ASH_SLAVE_SPECIAL     |            0 |
| WORLDTREE_SPECIAL              |            1 |
-------------------------------------------------
Specials Count(Repeat) Distribution
================================
| count | tally | % of objects |
================================
|     0 |   358 |         85.4 |
|     1 |    61 |         14.6 |
|     2 |     0 |          0.0 |
|     3 |     0 |          0.0 |
|     4 |     0 |          0.0 |
--------------------------------
```

### CODE REVIEW

**Comment by Vezzra** [comment]
Well, looks much better, definitely!

**Comment by Cjkjvfnby** [comment]
Add new table with systems

```
 ############################################################
 System summary
 ========================================================================================
 | id  | name       | planets                 | connections                 | star      |
 ========================================================================================
 |   0 |   Trophy α |              1, 2, 3, 4 |                     72, 279 |     white |
 |   5 |     Rome β |                       6 |                         177 |    yellow |
 |   7 |    Nyota α |                    8, 9 |                     28, 254 |    yellow |
 |  10 |     Rarity |                      11 |                         282 |    orange |
 |  12 |  Panon Poe |                         |                    107, 195 |    noStar |
 |  13 |  Urchachka |                  14, 15 |                    122, 256 |     white |
 |  16 |   Bradbury |              17, 18, 19 |                    276, 285 |      blue |
 |  20 |   Al Borak |                         |                    190, 250 |    noStar |
 |  21 |   Albans α |                      22 |                     69, 235 |    orange |
 |  23 |     Goth α |              24, 25, 26 |                     86, 267 |    yellow |
 |  27 |   Kewkba δ |                         |                         298 |    orange |
 |  28 |   Tanith α |                      29 |                 7, 142, 231 |    orange |
 |  30 |     Staila |                         |                43, 241, 254 |    noStar |
 |  31 |   Thorne γ |                         |                     99, 280 |    noStar |
 |  32 |   Draconis |                         |                     41, 295 |    noStar |
 |  33 |      Babel |                      34 |                     58, 254 |     white |
 |  35 |   Albion β |                  36, 37 |                    151, 267 |    orange |
 |  38 |   Salpeter |                  39, 40 |               140, 176, 295 |    yellow |
 |  41 |    Himring |                         |                32, 140, 209 |    noStar |
 |  42 |    Gundung |                         |                    164, 216 |    noStar |
 |  43 |    Nyota γ |                      44 |                     30, 227 |    orange |
 |  45 |     Goth γ |                         |                    177, 266 |    noStar |
 |  46 |  Fairchild |                         |                    165, 210 |    noStar |
 |  47 |   Adhafera |              48, 49, 50 |                         241 |    yellow |
 |  51 |     Vulcan |                         |                    108, 295 |    noStar |
 |  52 |     Wolf α |              53, 54, 55 |                    144, 301 |    yellow |
 |  56 |      Mobas |                      57 |                         301 |    yellow |
 |  58 | Baal-Samem |                  59, 60 |           33, 175, 241, 256 |       red |
 |  61 |   Kewkba γ |                         |                    276, 298 |     white |
 |  62 |    Gamow β |                  63, 64 |                    194, 294 |    yellow |
 |  65 |     Cheleb |                         |                    216, 256 |    noStar |
 |  66 |    Grian β |                  67, 68 |                    145, 250 |    orange |
 |  69 |   Albans γ |                         |                          21 |    noStar |
 |  70 |      Seren |                      71 |               134, 204, 290 |    yellow |
 |  72 |   Trophy β |                  73, 74 |                           0 |      blue |
 |  75 |     Cyteen |                      76 |                    113, 241 |     white |
 |  77 |     Gefjon |                  78, 79 |                         250 |    orange |
 |  80 |       Ster |              81, 82, 83 |                    175, 303 |    yellow |
 |  84 |   Kewkba β |                      85 |                         285 |     white |
 |  86 |   Estela α |                      87 |           23, 177, 241, 243 |    yellow |
 |  88 |   Thorne β |              89, 90, 91 |                    268, 289 |    yellow |
 |  92 |     Zakuri |                         |                    295, 300 |    noStar |
 |  93 |    D'nebag |                     306 |                    268, 297 |      blue |
 |  94 |    Waldorf |                         |                    194, 274 |    noStar |
 |  95 | Hadhodrond |                         |               285, 294, 298 |    noStar |
 |  96 |      Ryoun |                      97 |                    175, 212 |    yellow |
 |  98 |    Bragi δ |                         |                         300 |    noStar |
 |  99 |     Mithra |                     305 |                     31, 299 |     white |
 | 100 |       Crow |           101, 102, 103 |                         299 |    yellow |
 | 104 |    Gehenna |                         |                    290, 294 |    noStar |
 | 105 |      Irk β |                     106 |                    126, 280 |    yellow |
 | 107 |     Rome γ |                         |           12, 135, 177, 279 |    noStar |
 | 108 |    Plato α |           109, 110, 111 |           51, 209, 219, 244 |    yellow |
 | 112 |     Wolf β |                         |                         263 |     white |
 | 113 |      Suraj |                     114 |                     75, 256 |    yellow |
 | 115 |     Becrux | 116, 117, 118, 119, 120 |               204, 249, 299 |    yellow |
 | 121 |      Irk γ |                         |                         222 | blackHole |
 | 122 |   Huishtín |           123, 124, 125 |                13, 175, 190 |    yellow |
 | 126 |      Irk η |                         |                    105, 222 |    noStar |
 | 127 |   Elased β |                128, 129 |                         235 |    yellow |
 | 130 |    Siqieiq |                         |                    150, 217 |    noStar |
 | 131 |      Segin |                         |                         242 |    noStar |
 | 132 |    Gamow α |                     133 |                    227, 294 |      blue |
 | 134 |   Orocarni |                         |                     70, 211 |    noStar |
 | 135 |   Elased γ |                     136 |                    107, 235 |    orange |
 | 137 |      Holly |                138, 139 |                         259 |    yellow |
 | 140 | Terebellum |                     141 |                 38, 41, 216 |    orange |
 | 142 |       Hale |                         |                28, 211, 227 |    noStar |
 | 143 |     Hetu’u |                         |                    205, 250 |    orange |
 | 144 |     Wolf γ |                         |                          52 |    noStar |
 | 145 |    Grian γ |                         |                     66, 190 |    noStar |
 | 146 |   Elased α |                     147 |                    215, 235 |    orange |
 | 148 |     Waglen |                         |                         259 |    noStar |
 | 149 |    Herbert |                         |                         274 | blackHole |
 | 150 |      Medea |                         |                    130, 209 |    noStar |
 | 151 |     Menkab |                     152 |                35, 169, 282 |    yellow |
 | 153 |  Narsilion |                         |                         303 |    noStar |
 | 154 |   Hewish α |                155, 156 |                         285 |    yellow |
 | 157 |    Bragi γ |                     158 |                    165, 293 |    yellow |
 | 159 |   Kirkwood |                         |                    194, 285 |    orange |
 | 160 |      Alven |           161, 162, 163 |                    249, 303 |    orange |
 | 164 |     Illuin |                         |                     42, 267 |    noStar |
 | 165 |    Bragi α |           166, 167, 168 |                46, 157, 232 |    yellow |
 | 169 |      Burke |                170, 171 |                    151, 217 |      blue |
 | 172 |     Balder |                         |                    195, 274 |    noStar |
 | 173 |   Thorne α |                     174 |                    253, 289 |    yellow |
 | 175 |      Ithil |                         |             58, 80, 96, 122 |    noStar |
 | 176 |   Morthrai |                         |                     38, 300 |    noStar |
 | 177 |     Rome α |      178, 179, 180, 181 |              5, 45, 86, 107 |       red |
 | 182 |   Alkurhah |           183, 184, 185 |                    226, 246 |    yellow |
 | 186 |   Estela β |           187, 188, 189 |               195, 227, 241 |    orange |
 | 190 |    Fiorina |           191, 192, 193 |           20, 122, 145, 216 |    orange |
 | 194 |  T'ae-yang |                         |                 62, 94, 159 |    noStar |
 | 195 |   Laganini |                196, 197 |                12, 172, 186 |    orange |
 | 198 |    Klazart |                199, 200 |                    244, 295 |    orange |
 | 201 |     Situla |                202, 203 |                         298 |    yellow |
 | 204 |      Mongo |                         |                70, 115, 231 |    noStar |
 | 205 |    Uftivan |           206, 207, 208 |                    143, 222 |    orange |
 | 209 |    Reverie |                         |           41, 108, 150, 267 |    noStar |
 | 210 |       Lhûn |                     307 |                     46, 301 |    yellow |
 | 211 |     Zoctan |                         |               134, 142, 294 |    noStar |
 | 212 |   Matahari |                213, 214 |                96, 222, 303 |    orange |
 | 215 |  Mothallah |                         |                    146, 274 |    noStar |
 | 216 |    Jhonaai |                         |            42, 65, 140, 190 |    noStar |
 | 217 |    Hagalaz |                     218 |               130, 169, 246 |   neutron |
 | 219 |    Plato β |                220, 221 |                         108 |    yellow |
 | 222 |      Irk α |           223, 224, 225 |     121, 126, 205, 212, 249 |    orange |
 | 226 |     Xiddig |                         |               182, 282, 302 |    noStar |
 | 227 |    Nyota β |           228, 229, 230 |           43, 132, 142, 186 |    orange |
 | 231 |   Tanith β |                         |                28, 204, 303 |    orange |
 | 232 |    Bragi β |                233, 234 |                         165 |    orange |
 | 235 |   Albans β |                     236 |           21, 127, 135, 146 |    yellow |
 | 237 |        Ran |                     238 |                    256, 267 |    yellow |
 | 239 |     Laan β |                     240 |                    290, 298 |     white |
 | 241 |   Estela γ |                         |     30, 47, 58, 75, 86, 186 |    noStar |
 | 242 |         Ra |                         |                    131, 300 |    noStar |
 | 243 |       Uruz |                         |                     86, 256 |    noStar |
 | 244 |      Diell |                         |                    108, 198 |    noStar |
 | 245 |     Botein |                         |                    293, 300 |    noStar |
 | 246 |     Lambda |                247, 248 |                    182, 217 |    yellow |
 | 249 |      Irk ζ |                         |          115, 160, 222, 280 |    noStar |
 | 250 |    Grian α |                251, 252 |             20, 66, 77, 143 |    orange |
 | 253 |        Rin |                         |                    173, 268 |    noStar |
 | 254 |       Gray |                     255 |              7, 30, 33, 303 |    yellow |
 | 256 | Telemachus |                257, 258 |   13, 58, 65, 113, 237, 243 |     white |
 | 259 |   Hewish β |           260, 261, 262 |               137, 148, 285 |    orange |
 | 263 |      Irk δ |                     264 |                    112, 280 |    orange |
 | 265 |     Goth δ |                         |                    266, 282 |    noStar |
 | 266 |     Goth β |                         |                45, 265, 267 |    orange |
 | 267 |   Albion α |                         |  23, 35, 164, 209, 237, 266 |    yellow |
 | 268 |   Kitalpha |                269, 270 |                 88, 93, 253 |    orange |
 | 271 |        Nit |                272, 273 |                         297 |     white |
 | 274 |   Marinara |                     275 |           94, 149, 172, 215 |    yellow |
 | 276 |   Kewkba α |                277, 278 |                 16, 61, 297 |    orange |
 | 279 |   Thalassa |                         |                 0, 107, 282 |    noStar |
 | 280 |      Irk ε |                     281 |           31, 105, 249, 263 |    yellow |
 | 282 |    Whipple |                283, 284 |      10, 151, 226, 265, 279 |    orange |
 | 285 |      Zeist |           286, 287, 288 |   16, 84, 95, 154, 159, 259 |    orange |
 | 289 |   Thorne δ |                         |                     88, 173 |    noStar |
 | 290 |     Laan α |                291, 292 |           70, 104, 239, 299 |    orange |
 | 293 |   Engolong |                         |                    157, 245 |    noStar |
 | 294 |    Scorpii |                         |       62, 95, 104, 132, 211 |    noStar |
 | 295 |      Atlas |                     296 |         32, 38, 51, 92, 198 |    orange |
 | 297 |    Taonoui |                         |                93, 271, 276 |    noStar |
 | 298 |    Savitru |                         |        27, 61, 95, 201, 239 |    noStar |
 | 299 |    Talitha |                         |           99, 100, 115, 290 |    noStar |
 | 300 |     Steren |                         |       92, 98, 176, 242, 245 | blackHole |
 | 301 |    Kithrup |                         |                 52, 56, 210 |    noStar |
 | 302 |   Trophy γ |                         |                         226 |    noStar |
 | 303 |     Oyarsa |                     304 | 80, 153, 160, 212, 231, 254 |    yellow |
----------------------------------------------------------------------------------------
```

**Comment by Vezzra** [comment]
Is there a reason why the column contents are all right aligned? For the id column that might make sense, but all the other columns I'd expect to be left aligned.

**Comment by Cjkjvfnby** [comment]
No reason. It default behavior of Table. I think I can change it.

**Comment by Cjkjvfnby** [comment]
I plan to do column alignment changes in separate pr, so I will merge this.

**Comment by Vezzra** [comment]
> I plan to do column alignment changes in separate pr, so I will merge this.

That's fine.

**Pull request merged**
