### PR TITLE
Boost compatibility

### PR DESCRIPTION
**Pull request by geoffthemedio**
Attempting to back-port https://github.com/freeorion/freeorion/pull/2410 to release 0.4.8 as requested.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg the build errors appear to be timeouts; can you test manually?

**Comment by o01eg** [comment]
@geoffthemedio I didn't get errors on my PC.

I've send backport patch to Gentoo team https://bugs.gentoo.org/685718 to see if they get errors with different boost and cmake versions.

**Comment by o01eg** [comment]
After upgrading my linux I found other issue. Could #2462 be picked here?

**Comment by geoffthemedio** [comment]
I don't have a computer available for a day or two but I could probably accept a pull request into this branch if you make one...

**Comment by Vezzra** [comment]
@geoffthemedio, @o01eg, with 0.4.9 on the horizon, is this still needed, or can we close it? There won't be a maintenance release for 0.4.8 after all...

**Comment by o01eg** [comment]
@Vezzra Yep, I think it could be closed.

**Comment by geoffthemedio** [comment]
@Vezzra Although there are no plans for a maintenance release, would it make sense to push compatibility and bugfix commits to previous release branches anyway, in case someone wants to build it with the fixes? Similar situation with https://github.com/freeorion/freeorion/pull/2539

**Comment by Vezzra** [comment]
@geoffthemedio, yes, sure, maybe the latest commit on the 0.4.8 branch should then also be tagged, so it can be accessed easier?

**Comment by geoffthemedio** [comment]
Then you'd need to keep re-tagging if anything else is committed, though, I assume?

**Comment by Vezzra** [comment]
Correct, but that shouldn't be too much of an issue - I don't expect this to happen that often before we get the next release out. Or at least, I hope so. 0.4.9 has been delayed far too long already... 😞

**Pull request closed without merging**
