### PR TITLE
tweak build-macos.yml

### PR DESCRIPTION
**Pull request by geoffthemedio**
add macos-10.15

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
Could you add a comment on why we need it and how long or until which condition we plan to keep it? 

There is a warning regarding it in:
https://github.com/freeorion/freeorion/actions/runs/4702515016

> The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583

**Comment by geoffthemedio** [comment]
@Cjkjvfnby @o01eg just _increased_ the lowest supported MacOS version [to 10.15](https://github.com/freeorion/freeorion/commit/2f55e60cf3db5e44a536efaae874fde7718fea79) so it seemed reasonable to have a test build of that version. I'd keep it as long as it doesn't break or until the version is increased again.

**Comment by Vezzra** [comment]
> ...it seemed reasonable to have a test build of that version. I'd keep it as long as it doesn't break or until the version is increased again.

Sounds reasonable. As long as the ckeck works, I'd say we should include it. If it breaks at some point, we can remove it.

**Comment by o01eg** [comment]
Maybe also use `macos-10.15` to upload weekly test binaries too? Although I don't remember someone complain about compatibility issues.

**Comment by Vezzra** [comment]
@o01eg, no, I'd leave it as it is. As you said, we didn't have any complaints about compatibility issues, so I'd stick with "don't fix what isn't broken"... :wink:

**Comment by geoffthemedio** [comment]
@Vezzra @o01eg it looks like GitHub has [removed MacOS 10.15](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) as an option for hosting runners, and added MacOS 13 [beta]. Consequently, the recently submitted action jobs for building on 10.15 have stalled. Without an option to have test builds on 10.15, it's difficult for me to develop much while ensuring it will still build. Does requiring MacOS 11 to build affect the minimum supported version to run FreeOrion? If yes, then I think we need to move to requiring at least MacOS 11 to run. Either way, we probably need to move to requiring at laest 11 to build, so that tests can be run.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/pull/4509

**Comment by Vezzra** [comment]
> Does requiring MacOS 11 to build affect the minimum supported version to run FreeOrion?

It *should* not. Minimum macOS version required to *build* something and the minimum *target* macOS version are two different things.

Of course, can't be 100% sure without actually testing that. Unfortunately I have no access to a Mac system on 10.15, so we probably have to do it blindly.

My suggestion is: Live with the fact that we only have macOS 11 or later available on Github CI, consequently only *officially* support *building* on macOS 11 or later (even if it maybe still works on 10.15).

But leave the cmake build scripts as they are (don't change any minimum versions for whatever there) and hope the resulting apps still work on macOS 10.15 (as they should in theory).

If we get complaints at some point from people trying to run FO on 10.15, we can still raise the officially supportet macOS version for running FO to macOS 11.

But as long as possible, let's stick with claiming FO will run on macOS 10.15.

**Comment by o01eg** [comment]
@Vezzra What about XCode version? Should we maintain some minimum version?

**Comment by geoffthemedio** [comment]
Is particular, any reason to use the latest available on GitHub runners on MasOS 11?

**Comment by Vezzra** [comment]
> @Vezzra What about XCode version? Should we maintain some minimum version?

We've done so in the past, I think it's good to have an officially minimum supported version. Xcode 13.2 should be ok I guess.

**Comment by Vezzra** [comment]
> Is particular, any reason to use the latest available on GitHub runners on MasOS 11?

It's probably not necessary to have runners for each supported macOS version. But having one runner for the minimum supported version, and one for the most recent macOS version might make sense. If these pass, it's very likely that all versions in between should work too.

**Pull request merged**
