### PR TITLE
Remove CMake boost::signals dependencies

### PR DESCRIPTION
**Pull request by geoffthemedio**
Testing what happens in CMake build when removing signals dependencies, given https://github.com/freeorion/freeorion/issues/2308

### CODE REVIEW

**Comment by o01eg** [comment]
https://stackoverflow.com/questions/27252213/cmake-can-not-find-boostsignals2

Looks like `signals2` doesn't require component as it is header-only now.

**Comment by geoffthemedio** [comment]
> Looks like signals2 doesn't require component as it is header-only now.

Tried again by just removing all references to signals in CMakeLists.txt files.

**Comment by jbeich** [comment]
[Builds fine](https://ptpb.pw/CDkM) with Boost 1.69.

**Comment by geoffthemedio** [comment]
Would make sense to include in a v0.4.8 bugfix point release...

**Comment by o01eg** [comment]
Is it planned? I suppose some more fixes should be picked to the bugfix point release.

**Comment by geoffthemedio** [comment]
Not yet, but not being able to build against the next boost version might warrant one if various distros start including it by default.

**Comment by Vezzra** [comment]
@geoffthemedio,

> Do you know if these changes are enough for OSX as well?

The latest test builds already contained that change, and built and ran ok on OSX, so I guess we're good...

**Comment by Vezzra** [comment]
> Would make sense to include in a v0.4.8 bugfix point release...

Yep. And you've already tagged it for cherry picking too, excellent...

**Pull request merged**
