### PR TITLE
Add possibility to join during the playing game as a observer.

### PR DESCRIPTION
**Pull request by o01eg**
1. Fix bug with desync between the message and the player connection in the queued events.
2. Add server's options to allow clients connect as a observer.
3. Add react to JoinGame during PlayingGame state.
4. Some refactoring.

### CODE REVIEW

**Comment by vincele** [comment]
I have not tested, I only looked at it briefly, but this looks clean enough at first glance.

I'd fold the forgotten fix into the right patch, though...

**Comment by Dilvish-fo** [comment]
So, under what circumstances would you intend for this late-joinder-as-observer to be used?  It seems that such joinder would be easy to overlook and would be ripe for abuse in a multiplayer game.

**Comment by o01eg** [comment]
It is mostly for AI-only game. Second it is to test if possible to join a already started game.

**Comment by Dilvish-fo** [comment]
> It is mostly for AI-only game. Second it is to test if possible to join a already started game.

An AI-only game already has to be started up a human either as observer or as moderator, doesn't it?  Simply 'testing if this is possible' doesn't seem like much of a reason to add this to main, particularly in light of my concern about abuse potential.

In your intro comments I see a reference to 

> Fix bug with desync between the message and the player connection in the queued events.

but I'm not noticing that actually in the code anywhere.  I'm thinking I'd like you ask you to submit a separate PR with two commmits, one being the desync fix and the other commit being the GetPlayerInfoMap() refactoring.

**Comment by o01eg** [comment]
> An AI-only game already has to be started up a human either as observer or as moderator, doesn't it?

No, I ran the server even without gui: https://github.com/o01eg/freeorion/tree/ai-runner

> Simply 'testing if this is possible' doesn't seem like much of a reason to add this to main, particularly in light of my concern about abuse potential.

I saw same functionality in freeciv and it doesn't cause such concerns.
But I agree it possible to host server with this option enabled and other players don't know about it. In freeciv it solved by notifications about each join and leave in the chat and each player can see the server's options.

> but I'm not noticing that actually in the code anywhere.

I noticed it because in `WaitingForTurnEnd::react(const TurnOrders& msg)` I got wrong client type due multiple different players.

**Comment by Dilvish-fo** [comment]
> No, I ran the server even without gui: https://github.com/o01eg/freeorion/tree/ai-runner

Your understanding of No seems quite strange to me-- it looks to me like you had to add a specialized AI client to get around needing to have a human start the game either as player, observer, or moderator.  So your answer is really "Yes, but I made other changes to avoid that..."

> I noticed it because 

I wasn't asking how you noticed it, I was saying I didn't notice anything in the PR that seemed like a fix for the described problem.  Even now, looking at WaitingForTurnEnd::react I don't see what you are talking about.  The assert can't actually fix anything (and we are generally moving away from those and instead providing smoother error handling; I see no good reason for an assert here).  I also can't see how adding a  const designator to that connection pointer could actually fix the described problem.  So let me say more clearly: _Are you sure the fix is actually in this code?  If it is, please identify it more clearly._

**Comment by Dilvish-fo** [comment]
Well, to reiterate from a few posts up, I hope that you would be willing to submit a separate PR with two things from here:  one commit with the fix for whatever message desync problem you found, and another commit with the GetPlayerInfoMap() refactoring.

While I can see that the other portions of this, related to adding an observer after game start, tie in with your ai-runner interest, I think that at the very least they are premature to add into our main code, for the reasons explained above.

**Pull request closed without merging**
