### PR TITLE
Extract cmake build to action

### PR DESCRIPTION
**Pull request by Cjkjvfnby**

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
Got stuck with the build.

Not sure why I get this error.
https://github.com/freeorion/freeorion/actions/runs/3176577286/jobs/5176038734

I have added `shell: bash` because in the workflow it could be empty but for the actions, it is required. 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

@o01eg have you seen such kind of things before?

**Comment by o01eg** [comment]
No, it looks like something wrong with /MP flag

**Comment by Cjkjvfnby** [comment]
I have managed it to work. 

This is a bit dirty part, this part has a different shape and need to be done with `if`. 

@o01eg Do you think that it's possible to replace `vs-prerelease` to `vs-version: ` at this point?

```
- name: Add msbuild to PATH
      if:   inputs.mvc == '2019'
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,16.30)'
    - name: Add msbuild to PATH
      if: inputs.mvc == '2022'
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-prerelease: true
```

**Comment by o01eg** [comment]
@Cjkjvfnby I think its fine if it builds successfully.

**Review by o01eg — APPROVED** [review]

**Pull request merged**
