### PR TITLE
Remove boost::gil fork from GG code

### PR DESCRIPTION
**Pull request by adrianbroher**
No need to maintain a fork if the FreeOrion specific changes can be used with the upstream boost::gil library without great effort.

I would appreciate it if this change could be tested on Windows and Mac because both build and texture loading may be broken by this change on those platforms.

### CODE REVIEW

**Comment by adrianbroher** [comment]
With the CI now finally working properly there is at least one bug on MacOSX that needs to be fixed before I need to bother other people with review requests.

**Comment by geoffthemedio** [comment]
Builds and seems to run OK on Windows.

**Review by Vezzra — APPROVED** [review]
Builds and runs fine on OSX. LGTM. 👍

**Comment by adrianbroher** [comment]
Thanks for the review.

**Pull request closed without merging**
