### PR TITLE
Expanding the Playable species mix

### PR DESCRIPTION
**Pull request by MatGB**
Very much a work in progress without stringtable updates.

Plan is to expand and rebalance the playable species mix with an objective in mind, also tweak a few native species for balance and similar.

Thus far done:
~ Moved Trith back to Radiated
~ Made Sslith ocean dwellers (they're aquatic)
~ Made Scylior playable but deliberately didn't give them Large Planet
~ Made Abaddoni playable, gave them Large Planet and Broad Tolerance and gave them SubHab as an initial unlock for both flavour and balance
~ Added Radons (placeholder name), a playable Radiated world robotic species with fairly simple stats

I want to add more species and make a few other balance tweaks based on feedback.

### CODE REVIEW

**Comment by MatGB** [comment]
Two forum threads:
[Balancing the Playable species](http://www.freeorion.org/forum/viewtopic.php?f=15&t=10397)
[Expanding the Playable species mix](http://www.freeorion.org/forum/viewtopic.php?f=15&t=10398)

**Comment by geoffthemedio** [comment]
rebasing appears to have failed spectacularly, or has master commits merged in

**Comment by MatGB** [comment]
Yeah, I had to switch PCs last night and saved my work: your stats changes made my colony buildings break, and after I'd pushed the rebase I got this, I have no clue what went wrong but can fix when back on my box.

**Comment by MatGB** [comment]
Fixed.

If someone from the @freeorion/ai-team has time can you take a quick look at what I've done with the Abaddoni and confirm it doesn't bother the AI and/or need you to do any work?

**Comment by Morlic-fo** [comment]
It's only adding a starting tech on first turn, right?

That should be fine.

**Comment by MatGB** [comment]
OK, finally made time to tidy up this and do the stringtable update. I'm relatively happy with things as they are and will do follow up work when I've time.

@Vezzra I'm happy for this to merge in as is now, I'll be offline for awhile tomorrow so if no one objects could you merge it in before doing the test release?

**Comment by Vezzra** [comment]
Will do.

**Comment by Vezzra** [comment]
@MatGB, "follow-up" is intended for PRs that got closed because they have been superceded by other PR(s), so I'm not sure why you tagged this as "follow-up". I guess you mean that there need to be further work done in this area (expanding playable species mix)?

We don't really have a label for that, to manage a larger project encompassing a series of PRs you can use the project feature. Or open an issue that only gets closed once all the work on the matter has been done.

Unless you think we really need a separate label for that purpose, we can of course consider that too...

I've gone ahead and already removed the "follow-up" label, to prevent forgetting it later.

**Comment by geoffthemedio** [comment]
When I see "follow up", I assume it means that the tagged pull request is following up on a previous change.

If something is superseded by something else, I'd label it "redundant" or perhaps even "superseded".

**Comment by Vezzra** [comment]
It's probably a good idea to rename that label to "superseded" to avoid this ambiguity/confusion. @adrianbroher, any objections?

**Comment by Vezzra** [comment]
> It's probably a good idea to rename that label to "superseded" to avoid this ambiguity/confusion.

Done.

**Pull request merged**
