### PR TITLE
Fix Fedora Rawhide package manager name on CI

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by o01eg** [comment]
@Cjkjvfnby It quite strange not to test dockerized CI if `Dockefile` got changed.

**Comment by Cjkjvfnby** [comment]
@o01eg, this is configured here:
https://github.com/freeorion/freeorion/blob/master/.github/workflows/pr_run_config.toml

I guess we need to move some items from the `group.ignored` to other sections.   Probably create another [group.docker_builds] and register it for the build_ubuntu. 

It would be nice if you could do it, just to get some experience.  But if you are busy I can do it myself.

**Comment by o01eg** [comment]
Why it should be registered for `build_ubuntu`?

**Comment by Cjkjvfnby** [comment]
> Why it should be registered for build_ubuntu?

Sorry, I thought that dockers were part of the Ubuntu build.  I forgot that we don't run dockers on PR.  With this new config, we should do it, since it would be run only when needed.

**Pull request merged**
