### PR TITLE
Enable Godot for snap package

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
What help is wanted?

**Comment by o01eg** [comment]
@geoffthemedio I need help from @agrrr3 about snap.

**Comment by agrrr3** [comment]
@o01eg sorry, what help do you need exactly?

**Comment by o01eg** [comment]
@agrrr3 I need you to test it with your snap distribution and fix if needed.

**Comment by agrrr3** [comment]
Not sure what you need - I could build and run the godot client (latest/edge:      2021-09-29.38c23df98     2021-10-29 (244)). That is branch version from your repo (not PR merged) I could start the main screen and change settings etc. 

I will (try to) rebase on master and trigger a rebuild to see if I can use the chat abilities.

Here the output:

$ freeorion_edge.freeorion-godot 
/snap/freeorion/244/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0: /snap/freeorion/244/gnome-platform/usr/lib/x86_64-linux-gnu/libffi.so.7: no version information available (required by /snap/freeorion/244/usr/lib/x86_64-linux-gnu/libwayland-client.so.0)
Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
 
ERROR: open_dynamic_library: Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
   At: drivers/unix/os_unix.cpp:424.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: init_library: No nativescript_init in "/usr/lib/x86_64-linux-gnu/freeorion/libfreeoriongodot.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506.
ERROR: connect: Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER
   At: core/object.cpp:1452.
ERROR: connect: Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER
   At: core/object.cpp:1452.
ERROR: _start_func: Method failed.
   At: core/bind/core_bind.cpp:2694.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: terminate: No valid library handle, can't terminate GDNative object
   At: modules/gdnative/gdnative.cpp:388.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:476.
ERROR: cleanup: Condition "allocs_used > 0" is true.
   At: core/pool_vector.cpp:69.

**Comment by agrrr3** [comment]
If I rebase on with latest master,the result is worse (2021-10-29.8d9f28b1a (245), based on 8be76a865b9bb379ef613c56bcddd60276ef7650) :

$ freeorion_edge.freeorion-godot 
/snap/freeorion/245/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0: /snap/freeorion/245/gnome-platform/usr/lib/x86_64-linux-gnu/libffi.so.7: no version information available (required by /snap/freeorion/245/usr/lib/x86_64-linux-gnu/libwayland-client.so.0)
Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
 
ERROR: open_dynamic_library: Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
   At: drivers/unix/os_unix.cpp:424.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: init_library: No nativescript_init in "/usr/lib/x86_64-linux-gnu/freeorion/libfreeoriongodot.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506.
ERROR: start: Condition "!valid_type" is true. Continuing.
   At: main/main.cpp:1693.
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by agrrr3** [comment]
Also that stuff was already working in #3339 wasnt it?

**Comment by agrrr3** [comment]
(the first) problem is it does not find the libfreeoriongodot.so at the godot3-server export step. i dunno how exactly all that works together - i need the export to work and i think it uses the same path when looking stuff up when running the client(?)

> HOME=/build/freeorion/parts/freeorion/build/home godot3-server --path ../src/godot --export-pack Linux/X11 /build/freeorion/parts/freeorion/install/usr/share/freeorion/freeorion.pck


find / -iname libfreeoriongodot.so
/build/freeorion/parts/freeorion/src/godot/bin/linux.64/libfreeoriongodot.so
/build/freeorion/parts/freeorion/build/libfreeoriongodot.so
/build/freeorion/parts/freeorion/install/usr/lib/x86_64-linux-gnu/freeorion/libfreeoriongodot.so

**Comment by agrrr3** [comment]
If I use the SNAPCRAFT_PART_INSTALL path for libfreeoriongodot.so in the gdnlib file, it complains when exporting:
 open_dynamic_library: Can't open dynamic library: /build/freeorion/parts/freeorion/install/usr/lib/x86_64-linux-gnu/freeorion/libfreeoriongodot.so. Error: libfreeorioncommon.so: cannot open shared object file: No such file or directory

**Comment by agrrr3** [comment]
@o01eg is the export actually necessary/helpful for the snapcraft client? I guess it is necessary for android - but the snap is basically running a ubuntu in a container

**Comment by agrrr3** [comment]
#3601 contains my fixes

**Comment by o01eg** [comment]
@agrrr3 Thank you!

**Pull request closed without merging**
