### PR TITLE
Bar ancient guardians from vassalization

### PR DESCRIPTION
**Pull request by MichaelCourtney**
https://www.freeorion.org/forum/viewtopic.php?t=12710

### CODE REVIEW

**Comment by geoffthemedio** [comment]
the commit does more than its message claims... please separate and give more thorough messages.

**Comment by agrrr3** [comment]
design/description and implementation differ. the PR also bars exobot (LOW_BRAINPOWER) from vassalization.

would be okay fluffwise for me (maybe low brainpower people are too unorganised to work as vassals). but the description would need to change.

**Comment by MichaelCourtney** [comment]
> design/description and implementation differ. the PR also bars exobot (LOW_BRAINPOWER) from vassalization.
> 
> would be okay fluffwise for me (maybe low brainpower people are too unorganised to work as vassals). but the description would need to change.

Right, I'd also be ok with either version. Not sure which way to go here.

**Comment by MichaelCourtney** [comment]
I just left exobots out. Seemed simpler. Possibly they can be excluded too later on if players find exobot vassals odd

**Pull request merged**
