### PR TITLE
Fix techs button issue

### PR DESCRIPTION
**Pull request by o01eg**
Fixes race condition when techs categories was accessed by UI thread before parsing thread set future to wait.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I would still keep the UI code changes so that if the default dir changes and the techs are reparsed, the UI can update.

**Comment by o01eg** [comment]
@geoffthemedio That UI changes have some issues with button state https://github.com/freeorion/freeorion/pull/3403#issuecomment-822004138

**Comment by o01eg** [comment]
@geoffthemedio Rebased and removed revert and throwing errors.

**Comment by geoffthemedio** [comment]
> @geoffthemedio That UI changes have some issues with button state [#3403 (comment)](https://github.com/freeorion/freeorion/pull/3403#issuecomment-822004138)

I know, I didn't fix all the quirks, but just made it usable.

**Comment by geoffthemedio** [comment]
seems fine...

**Comment by o01eg** [comment]
Rebased

**Comment by geoffthemedio** [comment]
> 
> 
> seems fine...

**Pull request merged**
