### PR TITLE
Windows binaries archive in CI

### PR DESCRIPTION
**Pull request by o01eg**
It was asked in recent voice chat for an archive with binaries for AI team.

It's a partial approach of #3421 to provide artifact with game binaries for Win32. Maybe could be improved further to provide game installer later.

### CODE REVIEW

**Comment by o01eg** [comment]
That how artifacts looks like https://github.com/o01eg/freeorion/actions/runs/2423028484

**Comment by o01eg** [comment]
How binaries looks https://github.com/o01eg/freeorion/actions/runs/2422118304

**Review by Vezzra — APPROVED** [review]
Can't really provide much useful input on the changes in the script files, but they seem to work. The resulting archive contains all the binaries my little Python script stores in the "Binaries Only" archive, and much more (all the Boost DLLs etc.).

**Comment by Cjkjvfnby** [comment]
I am thinking about extracting this to a separate workflow with the manual run.

So you build binaries when you need them. 

I'll experiment in my repo since this workflow must be in master to run it manaully.
https://github.com/Cjkjvfnby/freeorion/blob/master/.github/workflows/windows-artefacts.yml

UPD. never mind, it took additional 10 seconds and generate 24 MB of files.  We could leave it here.

**Comment by o01eg** [comment]
@Cjkjvfnby I suppose we can add `workflow_dispatch` to `on` block and check it in `if` parameter of appropriate step.

**Comment by geoffthemedio** [comment]
> manual run.

why not for all master branch CI runs?

**Comment by Cjkjvfnby** [comment]
It looks 10 seconds to build them, so building on master branches sounds reasonable.

**Comment by Cjkjvfnby** [comment]
@o01eg , maybe we could merge this branch now?

**Pull request merged**
