### PR TITLE
Use FindPython3 CMake module instead of deprecated FindPythonLibs and FindPythonInterp

### PR DESCRIPTION
**Pull request by o01eg**
It was removed in recent CMake release https://cmake.org/cmake/help/v3.27/release/3.27.html#deprecated-and-removed-features

Not sure about milestone, I suppose 0.5.0.1 should be built on recent CMake too.

### CODE REVIEW

**Review by Vezzra — DISMISSED** [review]
I can build and run this PR on Mac, and start a game. However, universe generation reports errors, and apparently no useable universe gets created, so while you get into the game, there is nothing there (no systems, no empire, nothing).

However, I don't know if these issues have been introduced by this PR or by some other commit since the last test builds and before the commit this PR is based on.

Log files attached:
[logfiles.zip](https://github.com/freeorion/freeorion/files/12160410/logfiles.zip)

**Comment by o01eg** [comment]
@Vezzra Could you try `master` branch?

**Comment by Vezzra** [comment]
Ok, just tried to build and run 4f3c4ba8de5fa8e5616bf7f8a554d5d661a31617, same issues, universe generation fails.

So it's not a problem of this PR. However, due to this, I can't test this PR until those issues are resolved.

**Comment by Vezzra** [comment]
> @Vezzra Could you try `master` branch?

Yeah, just did, see my post above.

**Comment by o01eg** [comment]
So was it broken somewhere between previous weekly test build 3e4785df6b68bc886c26a600dc9ddb47e2f8eacb and 4f3c4ba8de5fa8e5616bf7f8a554d5d661a31617 ?

**Comment by Vezzra** [comment]
No, I just checked recent test builds. The last one that worked was build 2023-06-19.aa45874, test build 2023-06-27.1b21f9b already has the described issues.

Will open an issue for this.

**Comment by Vezzra** [comment]
Done, opened issue: #4644

**Review by Vezzra — APPROVED** [review]
Builds and runs ok on Mac

**Comment by o01eg** [comment]
@Vezzra @geoffthemedio Should it be backported to 0.5.0.1 release?

**Comment by Vezzra** [comment]
Probably makes sense - @geoffthemedio?

**Pull request merged**
