### PR TITLE
Increase Default Window Size

### PR DESCRIPTION
**Pull request by geoffthemedio**
hopefully addresses #4428

### CODE REVIEW

**Comment by o01eg** [comment]
I suppose 800 not enough. There screenshot of 850 pixel width:
title

**Review by o01eg — CHANGES_REQUESTED** [review]
Looks fine. With width of 1046 menu button half-appears. 
title

**Review by o01eg — APPROVED** [review]

**Comment by agrrr3** [comment]
snap build works well out of the box
`v0.5.0   amd64   beta/default-window-size  v0.5-rc2-2-g3e6920517     348         -           2023-04-12T00:00:00Z     `

**Comment by Vezzra** [comment]
This should definitely go into the release. I'll delay RC3 until this has been merged.

**Comment by o01eg** [comment]
Do we wait @Cjkjvfnby  to confirm?

**Comment by Vezzra** [comment]
> Do we wait @Cjkjvfnby to confirm?

Sure, but not indefinitely. If he doesn't confirm by the end of the week, I'd say go ahead and merge. I want to get RC3 out on Sunday at the latest, preferably sooner.

**Comment by Vezzra** [comment]
As I want to get out RC3 today evening, can we merge this? Doesn't look like there will be anymore input from anyone, it has been tested and approved, so as far as I am concerned, no need to wait any longer...

**Comment by Vezzra** [comment]
What prevents this from getting merged? I'll postpone RC3 until Tuesday evening, hopefully this will be merged until then...

**Comment by Vezzra** [comment]
Ok, if this hasn't been merged until tomorrow (Tuesday) evening, and nobody objects to merging this, I'll do the merge myself before I build RC3. The change is straightforward and simple enough, and has already been approved. No point in delaying RC3 any longer for this...

**Comment by Vezzra** [comment]
@geoffthemedio, I just realized that this PR was against the release branch. So I guess this is just a quick fix for the release, and you intend to provide a better fix for master? And #4428 should stay open...?

**Comment by geoffthemedio** [comment]
I have no related plans...

**Comment by Vezzra** [comment]
> I have no related plans...

In that case, I assume this should be cherry picked to master?

**Comment by geoffthemedio** [comment]
I thought I had already...

**Comment by Vezzra** [comment]
> I thought I had already...

@geoffthemedio, are you sure? Which commit in master is it? I can't find it...

**Comment by geoffthemedio** [comment]
If I had been able to find it, I would have linked to it. Hence "I thought I had already" not "I already did".

**Comment by Vezzra** [comment]
Ok, I cherry picked the commit to master: da57e12342d94212c22580f735c8cd185fa64c18

**Pull request merged**
