### PR TITLE
Rebalance exobots to be bad at everything but live anywhere

### PR DESCRIPTION
**Pull request by Oberlus**
[Forum thread](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11648).

This PR makes Exobots adequate at all planet environments (asteroids remain poor and gas giants uninhabitable), and reduce the research investment required by unlocking them with Nascent AI and Nanotech Production. It also decouples Adaptive Automation from Nascent AI by removing the latter from the tech requirements of the former.

This PR has three objectives. In order of importance:

1. Help empires with few good/adequate planets nearby their HW (unlucky start) to be able to resort to Exobots as a poor man's option, so that these empires do not drag behind empires with many good/adequate planets nearby their HW (lucky start).
Making Exobots researchable after Nascent AI and Nanotech Production allows for such unlucky empires to start colonizing around 10 to 20 turns sooner, instead of having to wait for Adaptive Automation to unlock Exobots and/or to research several growth techs up to Xenologic Genetics to access poor planets with their starting species. Being forced to follow one (or both) of these research paths before being able to colonize any sensible number of planets (because of an unlucky start) is a sure recipe to lose the game if your enemies were not as unlucky as you and know the basics of FreeOrion, because this empire will be considerably weak in research, industry and/or military with respect other empires, or in a serious PP&RP output disadvantage if didn't prioritize those research paths and got stuck with few colonies.

2. Make Exobots equally useful to all playable species, instead of the current configuration that makes them useless to species that prefer Radiated planets (or marginally useful for such species when bad at industry), and very useful to species that prefer Terran, Ocean or Swamp.

3. Increase research strategy options at start by not forcing every empire that pursues Adaptive Automation to also get first Nascent AI.
Making Adaptive Automation researchable after Algorithmic Elegance instead of Nascent AI allows empires interested only on the industry flat bonus to skip the research flat bonus.

[Related thread](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11124).

### CODE REVIEW

**Comment by Voker57** [comment]
I give you green light!

**Comment by agrrr3** [comment]
Could you add some discussion about the base proposal? I would also like to know what kind of tech one needs to populate planets and asteroids after the proposed change.

**Comment by Oberlus** [comment]
> Could you add some discussion about the base proposal? I would also like to know what kind of tech one needs to populate planets and asteroids after the proposed change.

I updated PR initial comment. There is also some more discussion in the linked thread.

As per the other question (which I forgot to answer): this PR does not change any habitability tech, so to populate planets with non-Exobot species the techs required are the same as without this PR, and to populate planets with Exobot species the techs required are Planetary Ecology (to unlock adequate environments with 1 pop) and the techs required for Exobots:
- Nascent AI, unlocked by Algorithmic Elegance, and
- Nanotech Production, unlocked by Robotic Production.

To populate asteroid belts with Exobot it is also required Xenological Genetics, unlocked by Symbiotic Biology and Genetic Medicine, the latter unlocked by Genetic Engineering (this is as without the PR).

**Comment by agrrr3** [comment]
The thread is only far related to your pr, should we reuse that for design discussion? I think there is reasoning about effects missing and we would loose that if it is not in the forums.

AFAICS Planetary Ecology and one late 1HS (e.g. a growth special) would be enough for asteroids. On a side note most part of pop-based industry on asteroids gets reduced by about 63%. 

For part 2) I would rather remove other radiation-preferring species. Empty planets per se are not a problem.

3) sounds interesting

**Comment by TheSilentOne1** [comment]
@Oberlus: any plans to add some refinements for the exobots?

**Comment by Oberlus** [comment]
> The thread is only far related to your pr, should we reuse that for design discussion?

Yes, better to continue debate in a [dedicated thread](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11648).

> Any plans to add some refinements for the exobots?

@TheSilentOne1 Yes! I like your TAR idea for Exobots very much. Let's brainstorm it in the forums.

**Comment by Oberlus** [comment]
Update:

Testing this with two MP 1v1 and several SP vs 5 AI in varied conditions (10/20/30 systems per empire, low/high density, lucky and unlucky starts):

- Exobots are still the only species that can colonize asteroid belts, and so they are always interesting to have, sooner or later. This PR doesn't change that.
- In games with natives to grab, early Exobots might not be interesting at all, depending on your species, the native species and the types of planets available. This is OK.
- Few systems per player implies empires clashes soon, before Exobots can be researched, so it's often better to try and grab an enemy's species. OK.
- High density galaxies,or with many systems per player (30+), imply more planet types available an so Exobots can be delayed. OK.
- Bad research species doesn't have a so bad time to get to Exobots thanks to not having to research AA. OK.
- In very bad starting positions (no good/adeq. planets to colonize, no CanColonize natives to grab), Exobots allows for expansion sooner (as explained in the PR), and hence it makes unlucky games less agonistic. OK.
- A lucky start without Exobots (e.g. Chato + Kobuntura) is still more powerful than an average start rushing Exobots, and Exobots are not a no-brainer. OK.

I think this is good to merge, but playtesting by someone that doesn't like the PR a priori could be interesting.
Anyways, the research costs could be adjusted after merging into master.

**Comment by Oberlus** [comment]
Finally, I spotted a problem with this PR, specifically with the "Exobots adequate everywhere" part: they will be the preferred choice to colonize planets that are hostile for the (non-artificial) available species. And thus this makes Xenologic Hybridization somewhat pointless.

Possible solutions:

1. Make three different artificial species, with different tech prereqs and different environment preferences (that is, three versions of Exobots).
2. Make the Exobots of this PR poor on everywhere but self-sustaining. Need to do the math.

Edit: please note that something like this PR is still much necessary to help balance games. This is not a cosmetical change, it is needed for gameplay in general and especially for satisfactory player experience in multi-player games.

**Comment by l29ah** [comment]
We've play-tested the original patch with teamsmac w/o the tech tree adjustments in at least five games, and it seems to do quite a good job at helping players at disadvantaged starting positions.

**Comment by geoffthemedio** [comment]
Need to rebase on master

**Comment by Oberlus** [comment]
> Need to rebase on master

I messed it by doing weird merges (I think). After rebase, pull, push, etc. it still shows 114 changed files.

I'm closing this one and pushing a new branch without this problem.

**Comment by adrianbroher** [comment]
Just `rebase --onto master <oldest actual commit from this PR>` while having this PR checked out.

Then force push.

**Comment by Oberlus** [comment]
> Just `rebase --onto master <oldest actual commit from this PR>` while having this PR checked out.

Maybe I screwed it really bad, it gives me a lot of conflicts for manual resolution:

```
freeorion$ git rebase --onto master 4d5ea37
dropping 57fdb8307a1ac697f5506ddc0cab0c0a1370a6ff typos -- patch contents already upstream
dropping a136f1635ef04b3e9ed1dcac59c35903cf18e7d5 Gifting SitReps -- patch contents already upstream
dropping cafcbf2f7c178f9fe10ae948e253d7a629b29c13 Don't overwrite ship design with same ID. -- patch contents already upstream
dropping b6fad6f9758c30e956ad7fd0651772e786f284ef -Remove unnecessary Source conditions from activation conditions -- patch contents already upstream
Auto-merging default/python/AI/freeorion_tools/extend_freeorion_AI_interface.py
CONFLICT (content): Merge conflict in default/python/AI/freeorion_tools/extend_freeorion_AI_interface.py
error: could not apply 1fd7aacd6... Expose empire stat records to python API. Additional Python-side glue code probably needed for usability.
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 1fd7aacd6... Expose empire stat records to python API. Additional Python-side glue code probably needed for usability.
```

I'm closing this one in favor of #2931

**Comment by l29ah** [comment]
You should have force-pushed this existing branch to avoid creating a new PR.

**Comment by o01eg** [comment]
I suppose it better to end up using #2932

**Pull request closed without merging**
