### PR TITLE
Update last turn received for empire after message sent

### PR DESCRIPTION
**Pull request by o01eg**
Callback implementation of updating last turn received info for empire.

### CODE REVIEW

**Comment by o01eg** [comment]
@geoffthemedio I've tried to rewrite it to signal implementation as it was mentioned in https://github.com/freeorion/freeorion/pull/4507#pullrequestreview-1411332272 but it looks like I cannot send it to `PlayerConnection::HandleMessageWrite` through `boost::bind` because signal is non-copyable.

**Comment by geoffthemedio** [comment]
I thought the single signal object would be a member of serverapp or PlayerConnection or some other networking class and you'd call it with some parameters to identify the message that completed sending...

**Comment by o01eg** [comment]
I looks like with signal I need to send context about empire and turn to functions instead of attaching it to callback.

**Comment by o01eg** [comment]
Implemented in #4552

**Pull request closed without merging**
