### PR TITLE
Tweak species likes for stealth/disconnected empires

### PR DESCRIPTION
**Pull request by MichaelCourtney**

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
@agrrr3

**Review by agrrr3 — CHANGES_REQUESTED** [review]
thematically fine

no_supply like is probably ok balance-wise

i am not convinced about balance of stealth specials; the clouds etc will be on every planet if done via stealth tech, so basically that is a +3 stability on every planet. thats basically a full step of stability species traits and it is not hard to research.

forum discussion?

**Comment by MichaelCourtney** [comment]
> i am not convinced about balance of stealth specials; the clouds etc will be on every planet if done via stealth tech, so basically that is a +3 stability on every planet. thats basically a full step of stability species traits and it is not hard to research.

not sure either. For gyschae it'd pretty much be stability neutral, as adding "interstellar infrastructure" is a near guaranteed -2 and the stealth special an easy +2.

> 
> forum discussion?

https://www.freeorion.org/forum/viewtopic.php?f=6&t=12473&#p112549

**Comment by geoffthemedio** [comment]
needs rebase, and there was a stringtable linter failure for which the logs have expired...

**Comment by MichaelCourtney** [comment]
> needs rebase, and there was a stringtable linter failure for which the logs have expired...

I'll rebase, I suspect the linter failure was from a time all pull requests failed the checks. This can wait (or be closed) as some changes may be contentious.

@agrrr3 - regarding it being +2 stability at a small research cost, this is a bit like the "good stability trait", just delayed/conditional. It's ok as long as the species in question need a way to boost stability (I suspect Etty do) and could push players towards researching planet stealth techs. Possibly needs deciding with Individual species balance in mind?

**Comment by agrrr3** [comment]
> It's ok as long as the species in question need a way to boost stability (I suspect Etty do) and could push players towards researching planet stealth techs. Possibly needs deciding with Individual species balance in mind?

@MichaelCourtney that's the way

**Comment by Vezzra** [comment]
@MichaelCourtney, closed as abandoned, superseded, invalid...?

**Comment by MichaelCourtney** [comment]
There seemed a lack of agreement on the changes. It's simple enough to script this or something similar at a later stage.

**Comment by Vezzra** [comment]
Ok, I guess that means abandoned...

**Pull request closed without merging**
