### PR TITLE
 Raise C++ language version to C++14

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR raises the C++ version to C++14.

This enables various goodies, but for me the generic lambda, lambda capture expressions and the deprecated attribute are the most important one.

### CODE REVIEW

**Comment by adrianbroher** [comment]
Poke

**Comment by geoffthemedio** [comment]
@Vezzra Would this cause any issues for you?

**Comment by Vezzra** [comment]
Unfortunately it does cause issues. No problems on Windows, but on Mac I get build errors.

I've zipped up the build logs:
[logs_20200121-191850-754615.zip](https://github.com/freeorion/freeorion/files/4093540/logs_20200121-191850-754615.zip)

**Comment by adrianbroher** [comment]
Can you upload this as a gist?

**Comment by Vezzra** [comment]
Yep: https://gist.github.com/Vezzra/9689e2d1b63e3a7e7782e2efa16882fc

There are two files, the actual build log, and I also included the output of the cmake command as a separate file.

**Comment by geoffthemedio** [comment]
Might need a boost version bump?

https://github.com/chriskohlhoff/asio/commit/68df16d560c68944809bb2947360fe8035e9ae0a

This issue's comments suggest 1.69 https://trac.macports.org/ticket/57645

**Comment by o01eg** [comment]
> Might need a boost version bump?

SDK has boost 1.70 in `master`.

**Comment by geoffthemedio** [comment]
gist incidates @Vezzra is using 1.66

**Comment by o01eg** [comment]
@geoffthemedio Yes, `master` isn't yet released.

**Comment by Vezzra** [comment]
In case you need more input from me, can it wait until after the release? I'm swamped...

**Comment by adrianbroher** [comment]
> Might need a boost version bump?

That's odd. If that would be the case he Mac OS CI would fail, which it doesn't.  Is it picking up a platform installation of boost?

**Comment by Vezzra** [comment]
>  Is it picking up a platform installation of boost?

Not that I'm aware of. I just checked, I can't find any platform installation of Boost - I wouldn't know how to do one on macOS anyway. It's not like Linux, where you can install Boost from the distro repo...

But you're right, it's definitely odd that the macOS CI succeeds, but on my system the build fails. I just do not have the time right now to dig into that issue. I'll try to find time for this after the release.

**Comment by adrianbroher** [comment]
> Not that I'm aware of.

I'm talking about the CI runner.

**Comment by Vezzra** [comment]
> I'm talking about the CI runner.

Oh, ok, of course... sorry, apparently I've been a bit distracted, your statement has been quite clear actually. 😊

**Comment by adrianbroher** [comment]
@Vezzra when can I expect the integration of this PR?

**Comment by Vezzra** [comment]
Depends very much on if I can build this PR with an SDK based on the latest master of the SDK repo. I'm currently trying to do just that. If everything goes smoothly, I can approve this PR today.

Otherwise we need to figure out what goes wrong on macOS...

**Comment by Vezzra** [comment]
Good news and bad news: The good news is, with a SDK based on the latest master of the SDK repo I do not get the build errors I got before.

However, the build still fails in one of the post build phases, when trying to compile the application package:
```
PhaseScriptExecution CMake\ PostBuild\ Rules /Users/user/SoftwareProjekte/FO/main/build/FreeOrion.build/Release/freeorion.build/Script-8B9B9C05A9BC44FE8C652B4F.sh
    cd /Users/user/SoftwareProjekte/FO/main/src
    /bin/sh -c /Users/user/SoftwareProjekte/FO/main/build/FreeOrion.build/Release/freeorion.build/Script-8B9B9C05A9BC44FE8C652B4F.sh
/Applications/CMake.app/Contents/bin/cmake -E make_directory /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../Executables
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/Release/freeorionca /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../Executables
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/Release/freeoriond /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../Executables
/Applications/CMake.app/Contents/bin/cmake -E make_directory /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/Release/libfreeorioncommon.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/Release/libfreeorionparse.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/Release/libGiGi.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/Release/libGiGiSDL.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_atomic.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_chrono.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_date_time.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_filesystem.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_iostreams.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_locale.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_log.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_log_setup.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/user/SoftwareProjekte/FO/main/build/dep/lib/libboost_regex.dylib /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
/Applications/CMake.app/Contents/bin/cmake -E copy_if_different  /Users/user/SoftwareProjekte/FO/main/build/Release/FreeOrion.app/Contents/MacOS/../SharedSupport
CMake Error: cmake version 3.14.5
Usage: /Applications/CMake.app/Contents/bin/cmake -E <command> [arguments...]
Available commands: 
  capabilities              - Report capabilities built into cmake in JSON format
  chdir dir cmd [args...]   - run command in a given directory
  compare_files [--ignore-eol] file1 file2
                              - check if file1 is same as file2
  copy <file>... destination  - copy files to destination (either file or directory)
  copy_directory <dir>... destination   - copy content of <dir>... directories to 'destination' directory
  copy_if_different <file>... destination  - copy files if it has changed
  echo [<string>...]        - displays arguments as text
  echo_append [<string>...] - displays arguments as text but no new line
  env [--unset=NAME]... [NAME=VALUE]... COMMAND [ARG]...
                            - run command in a modified environment
  environment               - display the current environment
  make_directory <dir>...   - create parent and <dir> directories
  md5sum <file>...          - create MD5 checksum of files
  sha1sum <file>...         - create SHA1 checksum of files
  sha224sum <file>...       - create SHA224 checksum of files
  sha256sum <file>...       - create SHA256 checksum of files
  sha384sum <file>...       - create SHA384 checksum of files
  sha512sum <file>...       - create SHA512 checksum of files
  remove [-f] <file>...     - remove the file(s), use -f to force it
  remove_directory dir      - remove a directory and its contents
  rename oldname newname    - rename a file or directory (on one volume)
  server                    - start cmake in server mode
  sleep <number>...         - sleep for given number of seconds
  tar [cxt][vf][zjJ] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args...]    - run command and display elapsed time
  touch file                - touch a file.
  touch_nocreate file       - touch a file but do not create it.
  create_symlink old new    - create a symbolic link new -> old

make: *** [freeorion_buildpart_0] Error 1
Command /bin/sh failed with exit code 2
```
The obvious issue here is that the last `cmake -E copy_if_different` command fails because it's missing the file argument of the file to copy. As far as I could narrow it down, the lines in question are these in the root `CMakeLists.txt`:
```
        COMMAND
           ${CMAKE_COMMAND} -E copy_if_different "${Boost_PYTHON_LIBRARY}" "$<TARGET_FILE_DIR:freeorion>/../SharedSupport"
```
These are lines 677&678. Apparently `"${Boost_PYTHON_LIBRARY}"` resolves to an empty string, causing the error (and of course resulting in a broken application package).

No idea why `"${Boost_PYTHON_LIBRARY}"` is emtpy though... 😕

**Comment by o01eg** [comment]
There was some changes in #2751 . I suppose some parts of CMake script was left intact.

**Comment by Vezzra** [comment]
The problem is not with changes to the cmake build scripts for FO itself, because I can still build master just fine with v10 of the SDK.

However, if I try to build master with a SDK based on the latest master of the SDK repo, I get the above error. Which means that that error isn't caused by something this PR here introduced.

**Comment by o01eg** [comment]
I suppose it happened because old boost didn't have a suffix for boost-python 2.7.

**Comment by Vezzra** [comment]
#2776 fixes the issue with boost library symbols not correctly set. I'll do another test with this PR once #2776 gets merged and this PR can be rebased to master with those fixes incorporated.

**Comment by Vezzra** [comment]
👍 Now it works 😃 I can build and run this PR _when I use a SDK based on the latest SDK master_. It still _does not_ work with the latest release of the SDK of course.

Which means, to get back to the original question when the integration of this PR can be expected: once we can release a new SDK. This is currently blocked by freeorion/freeorion-sdk#58.

Aside from that, this PR is good to go, as far as macOS is concerned. Has anyone tested this on Windows?

**Comment by geoffthemedio** [comment]
Should I be able to build the SDK on Windows?

At least the AppVeyor build test already passes...

**Comment by Vezzra** [comment]
@geoffthemedio, yes, of course, as per the instructions of the [README.md](https://github.com/freeorion/freeorion-sdk/blob/master/README.md) of the SDK repo. Did that, works fine.

**Comment by geoffthemedio** [comment]
With the old SDK, I think this is fine for Windows, in that it doesn't change anything relevant... By default, all the latest stuff supported by whatever MSVC version is being used is enabled. That includes all C++14 stuff in MSVC2017 and almost all of it in MSVC2015. Things appear compile fine with or without this or changing the C++ version to 14 explicitly in each project separately.

**Comment by geoffthemedio** [comment]
@Vezzra does this work for you now as well?

**Comment by Vezzra** [comment]
Yes. I can build and run FO with this PR.

**Comment by adrianbroher** [comment]
@geoffthemedio This PR explicitly blocks/fails on build environments, which do not provide a compiler capable of C++14.  This only sets a minimum requirement, nothing more.   Also I haven't updated the documentation as it seems.

**Pull request merged**
