### PR TITLE
Make changes in MaxPopulation affect growth without delay

### PR DESCRIPTION
**Pull request by Grummel7**
I always considered it a minor issue that populations started to grow only in the second turn after a new tech or exported resource increased a planet's MaxPopulation. Now I learned the reason and found it is rather easy to fix.

### CODE REVIEW

**Comment by agrrr3** [comment]
you use the immediate value at priority 40; did you check the priorities of the SetTargetPopulation effects? some hints probably here: https://freeorion.org/index.php/EffectsGroup_Priority_Standard_Values

another question - is the growth prediction correct with your changes?

**Comment by Grummel7** [comment]
> you use the immediate value at priority 40; did you check the priorities of the SetTargetPopulation effects? some hints probably here: https://freeorion.org/index.php/EffectsGroup_Priority_Standard_Values
> 
> another question - is the growth prediction correct with your changes?

The Wiki Page is outdated, plus I did not change the priority, but it seems okay: In fact priorities.macros specifies, that Effects that do SetTargetPopulation shall have priorities between 1 and 30.

I must however use Value() also in the other 4 places where TargetPopulation is accessed in the formula. Which means the PR gets a merge conflict with the other. Well, this one needs a little more closer inspection, I guess.

Forecasts are fine.

**Comment by agrrr3** [comment]
> The Wiki Page is outdated, plus I did not change the priority,

if you do not use the immediate value (Value), priority is not so important, because last turns value will be used anyway

> but it seems okay: In fact priorities.macros specifies, that Effects that do SetTargetPopulation shall have priorities between 1 and 30.

so using the immediate value at 40 should work in principle.

**Comment by Grummel7** [comment]
rebased on master

**Comment by Grummel7** [comment]
@geoffthemedio I think this should go into 0.5, can you please merge it?

**Comment by geoffthemedio** [comment]
I suspect there will be glitchy situations with this, but we can try it...

**Comment by geoffthemedio** [comment]
thanks for patience...

**Pull request merged**
