### PR TITLE
Add docstrings to python wrapper

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Its bad to have code and docs in different places. 

I copy paste docs for section `Free Functions` from here: http://freeorion.org/index.php/AI_Python_API and fix some.

After merge of this PR I plan to move other docs and remove API reference from this page.

PS. I don't compile game. And I don't know about c++ style and how to format long lines. 

PPS.  In example of python docstrings produces by boost I see that it is possible to have variable name in python:

http://www.boost.org/doc/libs/1_54_0/libs/python/doc/v2/docstring_options.html

```
foo1( (int)i) -> int : foo1 doc
C++ signature:
    foo1(int i) -> int
```

Freeorion code does not have variable name in docstrings:

```
C++ signature:
        boost::python::list userStringList(std::string)
```

It will be great to have one.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
As that page notes, there are separate options to show the C++, python, and user signatures. Do you actually want the C++ signatures? They can be quite verbose, eg:

```
    validShipDesign(...)
        validShipDesign( (str)arg1, (StringVec)arg2) -> bool :

            C++ signature :
                bool validShipDesign(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >)
```

**Comment by geoffthemedio** [comment]
This commit enables the non-C++ autogenerated docstrings...
https://github.com/freeorion/freeorion/commit/cea8bc27c9f83b26d5206cadd1db44741bd7fbc4
which look like:

```
 |  population(...)
 |      population( (empire)arg1) -> float
 |  
 |  productionCostAndTime(...)
 |      productionCostAndTime( (empire)arg1, (productionQueueElement)arg2) -> object
 |  
```

Not really proper parameter names, but at least it gives the types...

**Comment by Cjkjvfnby** [comment]
Arguments names can be specified. I think we can try this.

**Comment by Vezzra** [comment]
> This commit enables the non-C++ autogenerated docstrings...
> cea8bc2

This certainly looks reasonable. Attention: I'm going to rebase that branch and merge.

**Comment by Vezzra** [comment]
Done, b2764c7a142dc7fc462ab3d0ccc0340ea6e8dd85.

**Comment by Vezzra** [comment]
> Its bad to have code and docs in different places.  

Why? AFAIK that's actually "common standard", reference manuals are exactly that - a documentation outside the code. And while I'm very much in favor of adding these docstrings to the Python interface, I certainly don't want to remove the Python API reference wiki page (without a proper replacement, that is).

That said, I _do_ see the hassles with trying to maintain two sets of documentation (the one in the source code and the one on the wiki page). AFAIK there are tools which can compile reference docs out of the docstrings in Python code, if we can somehow incorporate such autogenerated docs into our wiki page, or at least put them somewhere where we can link to from the wiki page, that would be fine too.

Just don't provide the reference documentation for the Python API by Python docstrings _only_. I'm a person who prefers to have reference docs open in a separate (browser) window (or even printed out on paper!), not buried in some source code or only accessible by pop-ups in my IDE. I'm sure there are others like me out there. :wink:

**Comment by Vezzra** [comment]
Ok, I get a compile error on OSX I don't know how to resolve. It's these two calls to `def` in `EmpireWrapper.cpp`:

```
        def("techs",                                make_function(
                                                        boost::bind(TechNamesMemberFunc, &(GetTechManager())),
                                                        return_value_policy<return_by_value>(),
                                                        boost::mpl::vector<std::vector<std::string> >()
                                                    ), "Returns the names of all techs (StringVec).");
        def("techsInCategory",                      make_function(
                                                        boost::bind(TechNamesCategoryMemberFunc, &(GetTechManager()), _1),
                                                        return_value_policy<return_by_value>(),
                                                        boost::mpl::vector<std::vector<std::string>, const std::string&>()
                                                    ), "Returns the names of all techs (StringVec) in the indicated tech category name (string).");
```

Of those that get a docstring as the last parameter, these are the only ones which use `make_function`, so it looks like `def` doesn't like getting passed a string in that case. The error I get is:

```
In file included from /Users/user/SoftwareProjekte/FO/src/python/EmpireWrapper.cpp:10:
In file included from /Users/user/SoftwareProjekte/FO/src/python/SetWrapper.h:7:
In file included from /Users/user/SoftwareProjekte/FO/src/Xcode/dep/include/boost/python.hpp:18:
In file included from /Users/user/SoftwareProjekte/FO/src/Xcode/dep/include/boost/python/class.hpp:17:
In file included from /Users/user/SoftwareProjekte/FO/src/Xcode/dep/include/boost/python/data_members.hpp:15:
/Users/user/SoftwareProjekte/FO/src/Xcode/dep/include/boost/python/make_function.hpp:76:11: error: no matching function for call to 'get_signature'
        , detail::get_signature(f)
          ^~~~~~~~~~~~~~~~~~~~~
```

Anyone any ideas...?

**Comment by Vezzra** [comment]
Ok, looks like we're dealing with a limitation in Boost Python here, see here:
https://stackoverflow.com/questions/15625065/define-a-boostfunction-with-a-docstring-boostpython

Apparently, `def` does not support passing a docstring this way when using `make_function`. There are some cumbersome workarounds however, will try something when I get around to it.

**Comment by Vezzra** [comment]
Found a solution that builds and runs on OSX, committed to the PR branch.

**Comment by adrianbroher** [comment]
> Why? AFAIK that's actually "common standard", reference manuals are exactly that - a documentation outside the code. And while I'm very much in favor of adding these docstrings to the Python interface, I certainly don't want to remove the Python API reference wiki page (without a proper replacement, that is).

I don't know what you're meaning with reference manuals, but most projects I use and maintain create their API and high level documentation from in code documentation. If it is about publishing the results on a web page/wiki it should be no issue in adding a make target for that.

**Comment by Cjkjvfnby** [comment]
> Why? AFAIK that's actually "common standard", reference manuals are exactly that - a documentation outside the code

Documentation support. You will not update documentation on wiki after API changes: `This page was last modified on 10 April 2012, at 16:55.` 

I don't know how to put generated docs to wiki, but I know how to make docs page on https://readthedocs.org/. If you want I can do some examples.

**Comment by adrianbroher** [comment]
@Cjkjvfnby:

I know it's a little bit offtopic but I'm curious: how do you extract the docstrings after all? Calling the server/client with some magic parameter?

**Comment by Cjkjvfnby** [comment]
@adrianbroher, with magic :)

Run game with function that collect interface objects and pass it to inspector.
All I need is main module, but for classes it is better to have instance to collect more information. 

 https://github.com/Cjkjvfnby/freeorion/blob/master/default/AI/freeorion_debug/handlers/inspect_freeOrionAIInterface.py

Here is description how to lunch it.
https://github.com/Cjkjvfnby/freeorion/blob/master/default/AI/freeorion_debug/handlers/README.md

**Comment by Vezzra** [comment]
> I don't know what you're meaning with reference manuals

E.g. this: https://docs.python.org/2.7/library/index.html

> most projects I use and maintain create their API and high level documentation from in code documentation. If it is about publishing the results on a web page/wiki it should be no issue in adding a make target for that.

This. What I definitely do _not_ want is to just move all the API reference documentation into docstrings, which after all get specified and passed to Python in C++ code. Without further processing they are not of much use there, and most certainly no adequate replacement for the wiki page.

But if we can devise a workflow by which we can generate reference documentation out of this in-code documentation, that's certainly fine, and far better than the current situation.

If you know a way how to generate wiki page content (which we could simply paste into our wiki) from these Python docstrings, that would be an solution I'd prefer.

**Comment by Vezzra** [comment]
> Documentation support. You will not update documentation on wiki after API changes

Of course that's a big problem, I won't contest that. But, as I said in my reply to @adrianbroher above, unless we can generate documentation we can provide elsewhere out of these docstrings, still better than having _only_ the docstrings.

> I don't know how to put generated docs to wiki, but I know how to make docs page on https://readthedocs.org/.

That could work too, although I'd prefer something we could paste into our wiki pages. However, if we can't do that, readthedocs.org is probably worth a try.

**Comment by Vezzra** [comment]
Please don't remove anything from the wiki pages until we've found a solution for providing auto-generated reference documentation.

**Comment by Vezzra** [comment]
As this discussion actually belongs on the forums, I've opened a thread:

http://freeorion.org/forum/viewtopic.php?f=4&t=9968

Please continue the discussion there.

**Comment by Vezzra** [comment]
I've opened issue #501 to keep a reminder for us to implement the auto-generated reference documentation. The current wiki pages should only be removed once this is done.

**Comment by Cjkjvfnby** [comment]
New docstrings looks fine, I have updated my code to parse them.

**Comment by adrianbroher** [comment]
@Cjkjvfnby 

> Run game with function that collect interface objects and pass it to inspector.

I followed the (incomplete) README you linked and there is no result seen anywhere.

How is the document extraction tool invoked properly and where can I see the resulting output?

**Comment by Cjkjvfnby** [comment]
@adrianbroher, if you launch it properly, game should quit at first turn to main menu.
result is stored in `default/AI/freeorion_debug/ide_tools/result/freeOrionAIInterface.py` you see it in AI log.

Here is my command to run it from game folder
`FreeOrion.exe --ai-config F:\projects\freeorion\default\AI\freeorion_debug\handlers\inspect_interface_config.ini`

**Pull request merged**
