### PR TITLE
Re-organize sources layout

### PR DESCRIPTION
**Pull request by o01eg**
Re-organizes sources in the next folders:

- src/ - all sources
- - src/server/ - sources for server-side binaries (AI and server)
- - - src/server/ai/ - sources for `freeorionca`
- - - src/server/server/ - sources for `freeoriond`
- - src/client/ - sources for clients
- - - src/client/gigi - sources for GG-based client
- - src/common/ - common sources

### CODE REVIEW

**Review by Vezzra — COMMENTED** [review]
While I understand why you'd want to group the AI client sources together with the server sources from a "deployment point of view", IMO it does not make sense from the "sourcecode point of view".

The AI client is a _client_, _not_ a server component. AFAIK, the AI client does not share any code/modules with the server the human client doesn't share also, but there is code/there are modules the AI and the human client share with each other, but not with the server.

Therefore IMO the current layout makes sense, and should be left as it is.

No opinion on moving the GiGi sources into the client tree.

However, I defer decision on that to @adrianbroher and @geoffthemedio.

**Comment by geoffthemedio** [comment]
@adrianbroher reportedly has some plans for source code reorganization, so I'd probably leave it to him to make such re-arrangements...

**Comment by o01eg** [comment]
As I see @adrianbroher did something with GG in the September

**Comment by o01eg** [comment]
> AFAIK, the AI client does not share any code/modules with the server the human client doesn't share also

@Vezzra Python wrappers. At least we aren't going to use python at the client.

**Comment by o01eg** [comment]
Rebased.

**Comment by Vezzra** [comment]
> Python wrappers. At least we aren't going to use python at the client.

Ah yes, forgot about those. Although, if we go ahead and replace FOCS with Python at some point, the human client too will include the Python wrappers.

**Comment by o01eg** [comment]
If we won't use YAML to replace FOCS.

**Comment by Vezzra** [comment]
That's another option. However, personally I lean towards keeping the required frameworks/parsers for the various config/script files to a minimum. If we can do everything properly with Python, then lets do everything with Python.

Less dependencies to maintain.

**Comment by o01eg** [comment]
I had idea not to execute python from data but use it as parser so server's and AI's code for python couldn't be used here.

**Comment by Vezzra** [comment]
@o01eg, closed as abandoned/invalid/superseded/merged...?

**Comment by o01eg** [comment]
Yes, it's abandoned.

**Pull request closed without merging**
