### PR TITLE
Initialize python parser on Android

### PR DESCRIPTION
**Pull request by o01eg**
Based on #3309 and https://github.com/freeorion/freeorion/pull/3367 to demonstrate working Python parser on mobile devices.

[freeorion-godot.log.zip](https://github.com/freeorion/freeorion/files/6234496/freeorion-godot.log.zip)

### CODE REVIEW

**Review by Vezzra — CHANGES_REQUESTED** [review]
I can build this PR, but trying to run FO results in a CTD, with this error message dumped to the command line:
```
main() caught exception(std::runtime_error): ERROR: Tech "LRN_NASCENT_AI" requires a missing or malformed tech "LRN_ALGO_ELEGANCE" as its prerequisite.
GUIController failed to setup or run the GUI.
Segmentation fault: 11
```

**Comment by o01eg** [comment]
Do you have other errors in log? Could be some issue from https://github.com/freeorion/freeorion/pull/3309

**Comment by Vezzra** [comment]
These are the last lines of `freeorion.log`:
```
19:53:44.340904 {0x000070000afe0000} [error] client : Pending.h:78 : Parsing of "common" failed with error: The state of the promise has already been set.
19:53:44.352019 {0x000070000ae57000} [warn] client : NamedValueRefManager.h:259 : NamedValueRefManager::GetValueRef found no registered double valueref for "DISCONNECTED_FROM_CAPITAL_AND_REGIONAL_ADMIN_STABILITY_PENALTY". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
19:53:44.352080 {0x000070000ae57000} [debug] client : NamedValueRefManager.h:117 : NamedRef<T>::NamedRefInitInvariants() could not find value ref, will sleep a bit and retry.
19:53:44.364050 {0x000070000b26f000} [debug] timer : ScopedTimer.cpp:48 : Ship Designs Parsing time:      262 ms
19:53:44.369393 {0x000070000b1ec000} [debug] timer : ScopedTimer.cpp:48 : Ship Designs Parsing time:      267 ms
19:53:44.373547 {0x000070000af5d000} [debug] timer : ScopedTimer.cpp:48 : Fields Parsing time:      276 ms
19:53:44.433055 {0x000070000aeda000} [debug] timer : ScopedTimer.cpp:48 : Encyclopedia Parsing time:      335 ms
19:53:44.473878 {0x000070000b063000} [debug] timer : ScopedTimer.cpp:48 : parse_file "SP_ABADDONI.focs.txt" time:      365 ms
19:53:44.552787 {0x000070000ae57000} [debug] timer : ScopedTimer.cpp:48 : parse_file "CONFEDERATION.focs.txt" time:      205 ms
19:53:44.702191 {0x000070000ae57000} [debug] timer : ScopedTimer.cpp:48 : Policies Parsing time:      605 ms
19:53:45.089053 {0x000070000acce000} [error] client : PythonCommon.cpp:104 : Traceback (most recent call last):
19:53:45.089109 {0x000070000acce000} [error] client : PythonCommon.cpp:104 :   File "<string>", line 1, in <module>
19:53:45.089126 {0x000070000acce000} [error] client : PythonCommon.cpp:104 : ImportError: __import__ not found
19:53:45.089148 {0x000070000acce000} [debug] timer : ScopedTimer.cpp:48 : parse_file "ORBITAL_HAB.focs.py" time:      184 ms
19:53:45.090074 {0x000070000acce000} [error] client : PythonCommon.cpp:104 : Traceback (most recent call last):
19:53:45.090122 {0x000070000acce000} [error] client : PythonCommon.cpp:104 :   File "<string>", line 1, in <module>
19:53:45.090141 {0x000070000acce000} [error] client : PythonCommon.cpp:104 : ImportError: __import__ not found
19:53:45.090164 {0x000070000acce000} [debug] timer : ScopedTimer.cpp:48 : Techs Parsing time:      965 ms
19:53:45.153875 {0x000070000add4000} [debug] timer : ScopedTimer.cpp:48 : Buildings Parsing time:     1056 ms
19:53:45.554708 {0x00000001122545c0} [debug] client : Pending.h:60 : WaitForPendingUnlocked another wait_for round
19:53:45.554784 {0x00000001122545c0} [debug] client : Pending.h:73 : Retrieve result of parsing "policies".
19:53:45.554800 {0x00000001122545c0} [debug] client : Pending.h:75 : Retrieved result of parsing "policies".
19:53:45.571824 {0x00000001122545c0} [debug] client : Pending.h:60 : WaitForPendingUnlocked another wait_for round
19:53:45.571886 {0x00000001122545c0} [debug] client : Pending.h:73 : Retrieve result of parsing "techs".
19:53:45.571955 {0x00000001122545c0} [debug] client : Pending.h:75 : Retrieved result of parsing "techs".
19:53:45.572033 {0x00000001122545c0} [error] client : Tech.cpp:509 : ERROR: Tech "LRN_NASCENT_AI" requires a missing or malformed tech "LRN_ALGO_ELEGANCE" as its prerequisite.
19:53:45.588142 {0x00000001122545c0} [debug] client : GGHumanClientApp.cpp:388 : GGHumanClientApp exited cleanly.
19:53:45.603597 {0x00000001122545c0} [error] client : chmain.cpp:305 : main() caught exception(std::runtime_error): ERROR: Tech "LRN_NASCENT_AI" requires a missing or malformed tech "LRN_ALGO_ELEGANCE" as its prerequisite.
```
The entire logfile: 
[freeorion.log.zip](https://github.com/freeorion/freeorion/files/6255079/freeorion.log.zip)

**Comment by o01eg** [comment]
It maybe because I didn't move fixes from main python parsers PRs to this experimental one. Could you test #3309 and #3373 instead?

**Review by Vezzra — COMMENTED** [review]
> Could you test #3309 and #3373 instead?

Already done, so guess we're ok here?

**Comment by o01eg** [comment]
@Vezzra Yes, but this PR not intended for merge until both base PR merged.

**Comment by Vezzra** [comment]
@o01eg, ok, I understand. That's fine, I only needed to know if you still needed me to test this PR on macOS.

**Comment by o01eg** [comment]
Close in favor  #3568

**Pull request closed without merging**
