### PR TITLE
Stop ancient guardians triggering xenophobic malus

### PR DESCRIPTION
**Pull request by MichaelCourtney**
Ancient guardians triggering xenophobic malus on Trith just causes frustration

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
Main thread:

https://www.freeorion.org/forum/viewtopic.php?t=12283

Secondary thread:

https://www.freeorion.org/forum/viewtopic.php?t=12697

**Comment by agrrr3** [comment]
this was supposed to be fixed in november(?) b48e57b115370c5672c3a00f498af50d2acc99bc
edit: it seems that was not merged because of a linter issue...

**Comment by agrrr3** [comment]
@MichaelCourtney  would you consider #4310 more useful?

**Comment by MichaelCourtney** [comment]
> @MichaelCourtney would you consider #4310 more useful?

4310 is the same, with a distance based pop malus? Fair enough I didn't realize it was there. Yeah, probably 4310 instead.

**Comment by MichaelCourtney** [comment]
Superseded by #4310

**Pull request closed without merging**
