### PR TITLE
Fixes for Interactions with Giving, Conquering, Scrapping, and Invading

### PR DESCRIPTION
**Pull request by geoffthemedio**
This should address issues in #4345 relating to giving planets that are conquered and similar situations for scrapping ships or invading or colonizing and giving fleets.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
@o01eg @Oberlus @Blue-Award can you test this meaningfully? otherwise I guess I'll just merge it as is...

**Comment by o01eg** [comment]
@geoffthemedio I've just tested https://github.com/freeorion/freeorion/issues/4345 with that PR and now A invades planet of C.

**Comment by geoffthemedio** [comment]
> @geoffthemedio I've just tested #4345 with that PR and now A invades planet of C.

Which is how it's expected to work?

**Comment by o01eg** [comment]
Yes,

> Expected Result
> Either I should keep the planet (gift order cancelled after successful invasion), or the invasion should not happen (as if gifting happened first, and then invasion gets cancelled as I can't invade at-peace planet)

That the case with successful invasion and canceled gifting.

**Comment by Vezzra** [comment]
~~@geoffthemedio, can you cherry pick the 3 commits of this PR to the release branch? When I tried to cherry pick the first one (bc6b0ef843a6c8f999e1d4c47c6a4f366cb71cc8 in master), I got merge conflicts.~~

_EDIT_: Sorry, forget it - I totally overlooked that this is the PR we aready cherry picked to the release branch... 😉

**Pull request merged**
