### PR TITLE
Translate a few strings into spanish

### PR DESCRIPTION
**Pull request by rsf92**
Just a few more strings translated

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@Vezzra , do you know who could help with a review?

**Comment by rsf92** [comment]
> @Vezzra , do you know who could help with a review?

I think last time it was @Oberlus  who checked the spanish strings

**Comment by rsf92** [comment]
I pushed some more translations, that will be all, aside from corrections based on feedback, i'll do until this is merged, to keep the pull request size low

**Comment by geoffthemedio** [comment]
@Oberlus I think you're Spanish? Any comment?

**Comment by Oberlus** [comment]
The translations are correct, this is good to merge.

**Pull request merged**
