### PR TITLE
Allow specials on gas giants and asteroids

### PR DESCRIPTION
**Pull request by MichaelCourtney**
Draft version. Untested

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Related to https://freeorion.org/forum/viewtopic.php?f=6&t=12262 ?

**Comment by MichaelCourtney** [comment]
> Related to https://freeorion.org/forum/viewtopic.php?f=6&t=12262 ?

yes

**Comment by MichaelCourtney** [comment]
Tested. Fixed Parser Errors.

**Comment by MichaelCourtney** [comment]
Needs a rewrite anyway

**Pull request closed without merging**
