### PR TITLE
dump species info to trace log after parsing

### PR DESCRIPTION
**Pull request by geoffthemedio**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
[freeorion log with species parse dumps.zip](https://github.com/freeorion/freeorion/files/13060495/freeorion.log.with.species.parse.dumps.zip)

**Comment by Cjkjvfnby** [comment]
Can we make it disabled by default?  For example some config variable.  I don't think that it will be usefull for development except some specific cases, like mine.

This is  123K lines, which is hard to live this in regular life.   It's not only hard to scroll, but also it will put some performance tall for each game run.  

Could you also add a line at the end: `End  dumping FOCS Species`. It would be easier to parse them.

**Comment by geoffthemedio** [comment]
> Can we make it disabled by default? 

It logs at Trace priority, so will not be output unless you have set the `parsing` logger threshold to trace level.

> Could you also add a line at the end: `End dumping FOCS Species`. It would be easier to parse them.

The log should have a line with `Species Parsing time:` in it after the last species dump.

**Comment by Cjkjvfnby** [comment]
> It logs at Trace priority, so will not be output unless you have set the parsing logger threshold to trace level.

That is great.  

Could you check the performance of this code:

```cpp
for (auto& [sp_name, sp] : species_)
            TraceLogger(parsing) << sp_name << " : " << sp.GetCheckSum() << "\n" << sp.Dump();
```

It's recommended to use conditions around logging, to avoid executing code, that might be resource-consuming.  This code is doing some job, producing 123_000 lines of text, and this time added to all game runs.  

```cpp
if  log.level <= TRACE {
    TraceLogger(parsing) << "FOCS + Python Species: " << species_.size();
        for (auto& [sp_name, sp] : species_)
            TraceLogger(parsing) << sp_name << " : " << sp.GetCheckSum() << "\n" << sp.Dump();
     }
```

**Comment by geoffthemedio** [comment]
As far as I have been able to find out, over many attempts over numerous years, there's no way to write something like `if (LogLevel() >= TRACE) {...}` with Boost.Log.

However, it's not really necessary to do so, since `Logger(...)` calls short circuit evaluation if it determines internally that the appropriate log level threshold isn't met. In that case, the function to the right won't be called, and nothing will be output to the log. This can be verified by adding a `std::cout << ...` line within `Species::GetCheckSum`, which doesn't output anything to standard out if the client parsing log level is below trace, but does at trace level. That means it doesn't generate the text, rather than generating and discarding it.

If this didn't already work, then the *many* places in the code with trace level logging would already be slowing things down and bloating the log files drastically...

That said, the logging calls do slow things down a bit, as it has to check the log level every time there's a logger call, and there are lots of them, and I think does a global resource lock every time due to how Boost.Log is implemented for safety when logging in multiple threads simultaneously. This is in some cases one of the main limits on how fast conditions evaluations run (which are otherwise run by a thread pool in parallel). But it's not related to generating lots of text that doesn't end up being output, since the functions to do that are actually never called.

If you want an idea of how much logging is discarded due to the thresholds normally, try switching condition and effect logging to trace in the options menu before starting a game, and play a few turns and look at the logs... With quickstart settings and effect and condition logging at trace level, I get about 60k logging lines per turn in the server log.

That all said, with trace logging on:
`23:12:21.936183 {0x000062b4} [debug] timer : ScopedTimer.cpp:67 : Species Parsing time:     1831 ms`

With debug logging threshold:
`23:14:01.873191 {0x00001d48} [debug] timer : ScopedTimer.cpp:67 : Species Parsing time:     1611 ms`

With the Species parsing `TraceLogger(parsing)` calls commented out:
`23:16:33.270800 {0x00001ed8} [debug] timer : ScopedTimer.cpp:67 : Species Parsing time:     1646 ms`

So it doesn't make a huge difference compared to the parsing itself if the uydbt logs are generated or if the log lines are executed, particularly if the threshold is lower than trace.

**Comment by Cjkjvfnby** [comment]
> However, it's not really necessary to do so, since Logger(...) calls short circuit evaluation if it determines internally that the appropriate log level threshold isn't met. In that case, the function to the right won't be called, and nothing will be output to the log.

That is cool. In Python, a short circuit is implemented only for the `and` and `or` expressions. So for logging it doesn't do such optimizations.

**Comment by Cjkjvfnby** [comment]
Binaries from this build work for me, I can see logs.  I'll do checks tomorrow.

Thank you.

**Comment by geoffthemedio** [comment]
Any reason not to merge this? Should similar logging be added to the other content parsers?

**Comment by Cjkjvfnby** [comment]
> Any reason not to merge this? 

No

> Should similar logging be added to the other content parsers?

I'd say not yet.

**Review by Cjkjvfnby — APPROVED** [review]

**Pull request merged**
