### PR TITLE
Run CI build only to push into specific branches

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
@o01eg , could you review, please? Please estimate possible conflicts with your other changes on CI,  this branch should have the least priority, I could rebase or wait until something will be merged.
@geoffthemedio , as I recall you have some personal workflow, so this might break something for you. Workflow is pretty flexible, so I could adapt it to your needs.
@Vezzra , I don't expect any input from you but want to keep you in the loop. For example, you could just add a smile to this description, that you have seen it.

This PR is reducing the number of events that trigger CI.

Reasons to do it:
- Reduce the number of queued builds, since we have a limited number of simultaneous workers when exceeding jobs will be queued. This will slow down overall check time.
- Reduce the GitHub of resources Freeorion consumes
- Reduce carbon footprint

Change log:
- Workflows that runs on push are triggered only for `master` and sometimes `weekly-test-builds` if it's mentioned in the workflow
- Workflow with heavy jobs is triggered on pull-request only when it targets to master
- Reduce the number of events that trigger the workflow
  - [opened][opened]
  - [reopened][reopened]
  - [synchronize][synchronize]

[opened]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
[reopened]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=reopened#pull_request
[synchronize]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
37 items in a queue right now.

изображение

**Comment by Cjkjvfnby** [comment]
To speed up a queue you could just go to action (for PR, or global + filtering) and cancel some jobs you don't care.

**Review by o01eg — APPROVED** [review]
Looks fine. Shouldn't conflict with my changes as I lines I change placed much lower in files.

**Comment by geoffthemedio** [comment]
> To speed up a queue you could just go to action (for PR, or global + filtering) and cancel some jobs you don't care.

I do that often, but it's awkward and annoying since it reloads the page (taking time) and scrolls up to the top (losing place in list) for every cancelled job.

**Comment by geoffthemedio** [comment]
> @geoffthemedio , as I recall you have some personal workflow, so this might break something for you.

Not triggering on pushes to branches without a pull request is OK, as I can (continue to) make pull requests for branches I want builds to run when pushed.

**Comment by Cjkjvfnby** [comment]
> I do that often, but it's awkward and annoying since it reloads the page (taking time) and scrolls up to the top (losing place in list) for every cancelled job.

It's a bit more convenient to cancel via checks on the PR page.

I have already joined Python tests and linter workflows to a single workflow, so they could be canceled together. 
I thinking about joining other workflows together as well.  If you have some ideas about groups, please share.

https://github.com/freeorion/freeorion/actions/runs/4777929167
изображение

**Comment by geoffthemedio** [comment]
I just got
`RuntimeError: default/stringtables/en.txt: git blame did not collect any matching author times for key DESC_MODE_NUMBER_OF`
Is that related to this?

**Pull request merged**
