### PR TITLE
Remove Artficial Minds References

### PR DESCRIPTION
**Pull request by geoffthemedio**
Removes references to removed tech Artificial Minds for AIs and strintables.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@geoffthemedio, you have removed the 5th element in the tech list, now it should be also removed from the enqueue order.

So you need to remove 5th economy (self.economy) tech from self.enqueue  for the classes `TechGroup3A(TechGroup3)` `TechGroup3B(TechGroup3)` , `TechGroup3Sparse(TechGroup3)`.   

Here is a sample link (in master!)
https://github.com/freeorion/freeorion/blob/30894ea25087ac8606f199704da643901d7d901a/default/python/AI/TechsListsAI.py#L552

**Comment by Cjkjvfnby** [comment]
@geoffthemedio please fix tests: See description https://github.com/freeorion/freeorion/pull/3308#issuecomment-778742611 or sample code https://github.com/freeorion/freeorion/pull/3440/files

**Comment by Vezzra** [comment]
@geoffthemedio, @Cjkjvfnby, superseded by #3440 I assume?

**Comment by Cjkjvfnby** [comment]
> @geoffthemedio, @Cjkjvfnby, superseded by #3440 I assume?

Yes, suppressed by  #3440 and #3448

**Pull request closed without merging**
