### PR TITLE
Add automatic deploy of Windows binaries archive

### PR DESCRIPTION
**Pull request by o01eg**
Follows #4120 which produces correct file names.

### CODE REVIEW

**Review by Vezzra — COMMENTED** [review]
More or less what I said commenting on #4120. AFAICT, at least for the python script stuff, looks fine. Can't say much regarding the cmake scripts and the github action scripts.

Any ways in which you want me to test this...? How can I trigger the building and pushing of the binary only archives to SF with the branch of this PR?

**Comment by o01eg** [comment]
@Vezzra Should be triggered with push to branch `weekly-test-builds` in any repository where secret `DEPLOY_SSH_PASSWORD` was correctly set. I wrote in the forum which value should be set.

**Comment by Vezzra** [comment]
> @Vezzra Should be triggered with push to branch `weekly-test-builds` in any repository where secret `DEPLOY_SSH_PASSWORD` was correctly set. I wrote in the forum which value should be set.

But as the changes of this PR are not yet in master, wouldn't `weekly-test-builds` have to be rebased on the branch of this PR for a test run?

@agrrr3, what happens if I rebase and push `weekly-test-builds` onto the branch of this PR? How far is the building and deployment of the weekly test build snap automated? I don't think a test run like this should create a weekly test build snap...?

**Comment by o01eg** [comment]
@Vezzra I could try it on my repository.

**Comment by o01eg** [comment]
I've started Github Action with it: https://github.com/o01eg/freeorion/runs/8291409048

**Comment by o01eg** [comment]
@Vezzra I forgot it should work on Windows without rsync. Last try https://github.com/o01eg/freeorion/runs/8292530135 successfully put binaries at https://sourceforge.net/projects/freeorion/files/FreeOrion/Test/

**Review by Vezzra — COMMENTED** [review]
AFAICT, everything looks and works fine now. The test was successful, I've downloaded the archive that has been uploaded, and the contents seems ok.

LGTM, as far as I am concerned.

**Comment by Cjkjvfnby** [comment]
Pushing artifacts to GitHub was useful for me.  

I'll research if I can add workflow with manual triggers.

**Pull request merged**
