### PR TITLE
Add missing pedia links in some descriptions

### PR DESCRIPTION
**Pull request by Ouaz**

### CODE REVIEW

**Comment by MatGB** [comment]
This appears to be an excellent job, question and minor concern, firstly have you confirmed adding all the links into the ship description macro doesn't break it (I'm constantly breaking macros and can't test this myself on this machine).

Qualm: "Most advanced technology of ship [[encyclopedia SHIELDS_TITLE]]" reads badly to me, clunky English, "Most advanced version of [[encyclopedia SHIELDS_TITLE]] technology" would be better English.

**Comment by Ouaz** [comment]
"firstly have you confirmed adding all the links into the ship description macro doesn't break it"

What does that mean? (sorry, I'm not a programmer ^^)
In the UI, everything looks OK:

ship-stats

and the FO log is fine.

Qualm: "Most advanced technology of ship [[encyclopedia SHIELDS_TITLE]]" reads badly to me, clunky English, "Most advanced version of [[encyclopedia SHIELDS_TITLE]] technology" would be better English."

For the clunky english, my bad, my written english is weak. I don't know how to modify these lines in the actual PR (I have to close it and open a new one?). Maybe the contributor who will merge it can modify it?

**Comment by MatGB** [comment]
That screenshot is perfect, it's basically what I'm asking (I sometimes forget I can be unclear to non-native speakers). For the latter, a new one is preferred, however it's a minor gripe that doesn't matter hugely so I'll merge this and then do more updates with the patch I'm working on (which does some stuff to some of the areas you've touched anyway so duplication is pointless and this is a Good Thing (if you fancy doing more, the colony buildings descriptions would benefit from links to the species descriptions for each building, I keep looking at the workload and deciding something else is more important ;-) )

**Comment by Ouaz** [comment]
Thanks!

"if you fancy doing more, the colony buildings descriptions would benefit from links to the species descriptions for each building"

Actually, I added missing pedia links from line 1 to 8606, as I check that when I translate the FR file, and then, bring the modifications to en.txt in one time.

I start this week the french translation of the Buildings part, so I will continue to check if pedia links are missing or could be useful in descriptions (I take note for each species Colony building though, thanks!).

**Pull request merged**
