### PR TITLE
Fix typo 'acceptible'

### PR DESCRIPTION
**Pull request by TheTypoMaster**
Hi! I'm a bot that checks GitHub for spelling mistakes, and I found one in your repository. When it
should be 'acceptable', you typed 'acceptible'. I created this pull request to fix it!

If you think there is anything wrong with this pull request or just have a question, be kind to mail me 
at thetypomaster@hotmail.com (professional email, huh?). I’ll try to address the problem as soon as
I’m aware of it.

Looking for the source code of this bot? Well, you have to be patient! The bot is under development
and I will publish the source code as soon as I’m finished with it.

If you decide to close this pull request, pleace specify why before doing so.

With kind regards,
TheTypoMaster

### CODE REVIEW

**Comment by MatGB** [comment]
Not actually in the stringtable, one's in a comment,t he other's a variable name so I leave it to those who actually grok the code ;-)

**Comment by Vezzra** [comment]
> If you think there is anything wrong with this pull request or just have a question, be kind to mail me
> at thetypomaster@hotmail.com (professional email, huh?). I’ll try to address the problem as soon as
> I’m aware of it.

Ok, in this paragraph, is this now the author of the bot speaking, or is that an invitation to take part in some kind of turing test...? :wink:

**Comment by geoffthemedio** [comment]
looks fine, builds...

**Comment by TheTypoMaster** [comment]
@Vezzra Haha! Good point.

**Pull request merged**
