### PR TITLE
Separate focs base class declarations into dedicated header files

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR moves the ScriptingContext, ValueRef, Condition and Effect base class declarations into seperate headers and removes the `Base` suffix.

### CODE REVIEW

**Comment by adrianbroher** [comment]
This PR needs some adoption of the MSVC project files by one of the maintainers.

**Comment by o01eg** [comment]
I suppose test changes are also required:
```
[ 91%] Building CXX object test/parse/CMakeFiles/fo_unittest_parse.dir/main.cpp.o
In file included from /freeorion/test/parse/main.cpp:7:0:
/freeorion/test/parse/CommonTest.h:9:10: fatal error: universe/ValueRefFwd.h: No such file or directory
 #include "universe/ValueRefFwd.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by geoffthemedio** [comment]
I'll probably merge the https://github.com/freeorion/freeorion/pull/2045 Government branch before this due to likelihood of substantial conflicts. I was waiting a bit during the pre-release period, but if you're going to be this productive with pull requests reorganizing things so much, then probably I'll need to go ahead soon regardless...

**Comment by geoffthemedio** [comment]
I don't know what the pull request creation interface did when I tried to make one, but https://github.com/adrianbroher/freeorion/pull/1/commits/4fdd77c5fbe7af00cb53dbcdd98f565069384534 is supposed to do the MSVC project file adaptation that was requested.

**Comment by adrianbroher** [comment]
It creates a PR on my repo.

**Comment by geoffthemedio** [comment]
Which doesn't appear to be the branch that this pull request was, despite me attempting to put that branch into the box to pick what to base off of...

**Comment by adrianbroher** [comment]
How about checking out branch pr/2702 and pushing on top of it?

**Comment by adrianbroher** [comment]
If that doesn't work I can cherry-pick it.

**Comment by geoffthemedio** [comment]
I wasn't aware there was a branch created for pull requests separate from the branch the request wants to merge from, which is shown on this page as `adrianbroher:separate-focs-base-classes` and I didn't think I could push into one of your branches without making another pull request.

Also, my local version of your branch has a merge commit in it, which it seems like I probably shouldn't push into your branch, even if I could.

**Comment by adrianbroher** [comment]
Fixed the branch and pulled in the updates project files.

**Comment by geoffthemedio** [comment]
I've pulled these changes, fixed additional MSVC project file issues, resolved the conflicts and pushed directly to master.

**Pull request closed without merging**
