### PR TITLE
Automatically verify checksums.

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This PR automatically verifies checksums and reports a warning in the log if there is a mismatch.
It does not do checksums for the single player client, since the server and client are started from a common directory so there can be no mismatch.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
The SP server can be run from a different location when desired...

**Comment by geoffthemedio** [comment]
`--force-external-server`

**Comment by LGM-Doyle** [comment]
Thanks for the additional information.

I've added a server startup flag `--skip-checksum`, which is added when a single player game is started and `--force-external-server` is false.

**Comment by geoffthemedio** [comment]
Why skip it ever?

**Comment by LGM-Doyle** [comment]
The checksum takes a noticeable amount of time and delays startup.

It is not skipping the check.  It is determining that it trivially passes without doing the work.

This method tells the server, "I know that the checksum will pass, so don't waste time computing it"

Another method would be for a local connection to checksum the directory first and then if that is not the same, checksum the contents.

**Comment by LGM-Doyle** [comment]
Rebased.

**Comment by geoffthemedio** [comment]
Any idea what's up with the OSC build error...?
````
/Users/travis/build/freeorion/freeorion/python/EnumWrapper.cpp:215:13: error: expected expression

            .value("toggle",        GameRules::TOGGLE)
            ^
````

**Comment by o01eg** [comment]
Need to rebase over latest commit in `master`:

https://github.com/freeorion/freeorion/commit/98625c0743266d7fcf9cb70bcb23cef0e2822fa8 intoduced this typo
https://github.com/freeorion/freeorion/commit/aaee5e34bd79917e200d8cd7bcd275f57260db9f fixed it

**Comment by LGM-Doyle** [comment]
Thanks @o01eg I did not realize that I rebased onto a broken master.

This is now rebased.

**Comment by geoffthemedio** [comment]
Started a hostless server, and the client with --force-external-server. Joined the server, added an AI, and started the game. In the client log, I see
````
12:57:03.680965 [error] FSM : HumanClientFSM.cpp:115 : A CheckSum event was not handled by any of these states : [struct WaitingForMPJoinAck].  It is being ignored.
````

**Comment by LGM-Doyle** [comment]
The master branch has the same error, so it is **not** caused by this PR.

The issue is that the `WaitingForJoinAck` state on the client does not handle the checksum response.

I've added a commit to **this** PR to sawp the order of the join ACK and checksum in the server, which fixes the issue.

**Comment by o01eg** [comment]
@geoffthemedio If you start hostless server you shouldn't try to become its host with `--force-external-server`. Did you successfully gain control on the server?

**Comment by geoffthemedio** [comment]
I joined the server from the multiplayer join dialog, so I assume `--force-external-server` was actually irrelevant.

**Comment by geoffthemedio** [comment]
After joining a multiplayer server (running hostless on same machine), I don't get any checksum check messages in the log. What makes it happen?

**Comment by LGM-Doyle** [comment]
For some reason, I did not change the MPLobby checksum to use VerifyCheckSum().  I have fixed that.

I've also generalized the checksum so that the AI and human clients use the same code.

The message received when the checksum is good  is:
````Checksum received from server matches client checksum.````

**Pull request merged**
