### PR TITLE
[AI] Move references to a separate module

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This is the proposal. 

I want to isolate working with references in a separate module. 

- This will help to track all constants usage.
- Expose the convenient API for users.
- Collect all missed references in one place, so it will be easy to find what is missed. 

Some boilerplate is required, but I am ok with it since the number of references is not so huge. 

if it's possible to expose the method that gives all references in the game, I could add some validator. 

All are under discussion:  module name, function names schema.

### CODE REVIEW

**Review by Grummel7 — COMMENTED** [review]
I planned to do something like that after the release.

But instead of:
```
def get_policy_diversity_threshold() -> int:
    return get_named_int("PLC_DIVERSITY_THRESHOLD")
```
I would simply write:
```
policy_diversity_threshold = get_named_int("PLC_DIVERSITY_THRESHOLD")
```

Writing it that way means every named value is evaluated exactly once when the AI starts.
This is not only efficient, it also means that when one of this values no longer exists (or there is a typo), you get an error exactly once and you get it right at the beginning, no matter if the value is used immediately, or would only be used a hundred turns later.

**Comment by Cjkjvfnby** [comment]
```python
policy_diversity_threshold = get_named_int("PLC_DIVERSITY_THRESHOLD")
```

This is executed during the import, which might not work. 

Let's move this thing together first and later try to make it better.  I think I could do some lazy wrapper about it, or init them on same game_event (startNewGame, resumeLoadedGame).

**Comment by Grummel7** [comment]
> ```python
> policy_diversity_threshold = get_named_int("PLC_DIVERSITY_THRESHOLD")
> ```
> 
> This is executed during the import, which might not work.
> 
> Let's move this thing together first and later try to make it better. I think I could do some lazy wrapper about it, or init them on same game_event (startNewGame, resumeLoadedGame).

It works now, I've tested it. That was exactly the idea behind #3936

**Comment by Cjkjvfnby** [comment]
> It works now, I've tested it. That was exactly the idea behind https://github.com/freeorion/freeorion/pull/3936


Pushed some samples. 

The error message looks like that:
```
23:26:18.261087 {0x00003298} [error] python : value_references.py:48 : 'references.value_references' contains references to the value refs, that does not exist: ['BBBBBBBB', 'ZZZ'], please remove them
``` 

Some thoughts: 
- in case of error here, the game will crash, without saying something nice to the user.   All out game entry points are wrapped to try/catch.
- error message is in the middle of spam entry logs, nobody sees it.  But I have a couple of ideas on how to deal with it.

**Comment by Grummel7** [comment]
Of course writing the errors only to the log was not what I intended. But I missed the fact that error() only produces a chat message once the game has started. Checking _missed_references at the start of the game at a point where it produces chat error messages should fix this.

There would be no error if someone calls get_named_int afterwards, but the function could call error and append it to the list to avoid this.

**Comment by Cjkjvfnby** [comment]
This branch got conflicts, I'd prefer to remove it. Will recreate changes from scratch.

**Pull request closed without merging**
