### PR TITLE
Cleanup string files.

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This pull request does next thing:
- remove keys that present in translation but removed form en.txt
- remove values with exact match with `en.txt` values on same key
- sort keys in same order as in `en.txt`
- add comments form `en.txt`

This work done by the script.  I can't check all files myself. I fully checked `ru.txt` (since it is already was cleaned in this way it has small diff)  I make only quick check for other languages.

Translation still contains many untranslated values that was already changed.

### CODE REVIEW

**Comment by adrianbroher** [comment]
Please use a commit message, that documents what the commit did.

**Comment by Dilvish-fo** [comment]
for some files, like de.txt, there are so many changes that GitHub doesn't show a diff for it, and I didn't see a way to get to it here-- I tried just following the branch for the branch compare view, but it was the same and didn't seem to offer any extra options for seeing the diff.  I could probably pull up a plaintext diff ok, but that's not as helpful.  Any suggestions on what to do in this kind of case?  Just download a diff to use a better viewer on my local machine (or use a git gui)?
From what I could see, though, the PR seems ok, so I'll go ahead and merge it.

**Comment by Cjkjvfnby** [comment]
Github has limit for diff in UI.

You can see whole commit diff by adding .diff or .patch https://github.com/Cjkjvfnby/freeorion/commit/658ee13872c336aed5825d3c4cd097ddeec0988b.diff

**Comment by Dilvish-fo** [comment]
Yes, I said I knew I could pull up a plaintext diff like that, but those aren't nearly as useful to review.  I guess I'll look into reviewing such things from a git gui other than the github web interface.

**Comment by Cjkjvfnby** [comment]
@Dilvish-fo I just copy content to text editor(Sublime Text) and see colored diff.

**Pull request merged**
