### PR TITLE
Tech short desc

### PR DESCRIPTION
**Pull request by Grummel7**
Some polishing, many tech short descriptions were outdated, especially some said theoretical prerequisite, also the tech did unlock something now.

This is not complete and I am not even sure its the right thing to do. There are lots of technologies that do something and also unlock a policy.
Does it make sense to have a short description like this?
`Increases Starlane Speed & Unlocks Policy`

### CODE REVIEW

**Comment by geoffthemedio** [comment]
If the policy primarily also increases speed, then it doesn't need to separate mention the unlocking.

But in general, I think the "main" effect can be mentioned in the short description, even if there are other effects omitted.

**Comment by Grummel7** [comment]
> If the policy primarily also increases speed, then it doesn't need to separate mention the unlocking.
> 
> But in general, I think the "main" effect can be mentioned in the short description, even if there are other effects omitted.

Well, maybe we can just keep the rest as it is. With this PR:
- There should be no more "Theoretical Prerequisites" that actually give something
- All Techs that give a policy slot have it in their short description.

**Comment by geoffthemedio** [comment]
needs rebase due to tech moved to python. otherwise seems OK

**Comment by Grummel7** [comment]
@geoffthemedio Can you merge this now? If you keep waiting, Oleg will move more techs and I'll have to rebase again...

**Pull request merged**
