### PR TITLE
Flak Description

### PR DESCRIPTION
**Pull request by geoffthemedio**
Hopefully correct flak function description to fix https://github.com/freeorion/freeorion/issues/2666

### CODE REVIEW

**Comment by Vezzra** [comment]
@geoffthemedio, is there a reason why you made this PR against the release branch instead of master...? Especially since you tagged it as "cherry pick for release"...?

@everyone: Are the proposed changes ok? Can we merge this?

**Comment by geoffthemedio** [comment]
> a reason?

Not really.

**Comment by Oberlus** [comment]
> @everyone: Are the proposed changes ok? Can we merge this?

Good for me

**Comment by agrrr3** [comment]
Good to merge

**Comment by o01eg** [comment]
@geoffthemedio Should it be cherry-picked to `master`?

**Comment by geoffthemedio** [comment]
I think so

**Comment by Vezzra** [comment]
Cherry picking done: 8d8040c9147f1b6220ff654b065d4739db4d2f89

**Pull request merged**
