### PR TITLE
Added Scrying Sphere building

### PR DESCRIPTION
**Pull request by geoffthemedio**
A species-neutral effect, similar to the shared vision within the George species in https://github.com/freeorion/freeorion/pull/477

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Note that this presently only reveals the planets containing scrying spheres, not any buildings on those planets (including the scrying sphere itself).

**Comment by Vezzra** [comment]
Now that's a cool idea... :smiley:

**Comment by MatGB** [comment]
Playing with both of these, bit weird, you only see the planet's existence, not even the system proper so no knowledge of star type, other planets, etc, and the map merely shows a ? where the system is, no name even though if you click it it'll display the system and the planet name.

Basic idea very good though, not sure about this specific special but it's nice to have the effects to play with. And almost certainly a better way of handling the Derelict Scout.

Hmm, another potential use: when you conquer an imperial capital, get visibility of everything they'd scouted?

**Comment by Vezzra** [comment]
Hm, maybe also grant at least partial visibility of the containing system and all its planets?

**Comment by geoffthemedio** [comment]
Made it reveal buildings, planets, and the system where another scrying sphere is located.

**Comment by geoffthemedio** [comment]
Any further comments / objections for this special / building?

**Comment by Vezzra** [comment]
Did not get around to test it yet, and it might take me a while before I get to that, so if you don't want to wait any longer, go ahead an merge, no objections. I don't expect any issues, and even if there should arise some, it shouldn't be too hard to make the required adjustments.

**Comment by MatGB** [comment]
Have finally run a test game where I got a sphere early enough for the recent changes to be apparent, I like it, and vote merge as is.

**Pull request merged**
