### PR TITLE
 WIP: Add new GG::Measure class to enable UI scaling 

### PR DESCRIPTION
**Pull request by rah2501**
This is the approach I've come up with to supporting UI scaling, adding a new class to handle static UI measurements and scaling them according to font size.  There's still a lot of classes that need changing to make use of it but I wanted to get feedback before I continue.

### CODE REVIEW

**Comment by adrianbroher** [comment]
There is no need to define a dedicated type, X and Y have a 1:1 pixel size relation only by convention and there is no reason to handle them as arbitary screen coordinates with a non one to one mapping towards the pixels.  The scaling should happen at rendering level and rely only on the target display HiDPI capabilities.

**Comment by rah2501** [comment]
> The scaling should happen at rendering level

Could you say a bit more about what you mean by "rendering level"?  There are OpenGL calls everywhere, there doesn't seem to be any distinct area of the code where rendering is done.  Are you saying all of the OpenGL rendering calls should have scaling involved?  Assuming so, I've never touched OpenGL before, could you say a little more about that could be achieved?

> and rely only on the target display HiDPI capabilities.

I disagree with this; display HiDPI capability is not the only reason to want to scale the UI.

**Comment by adrianbroher** [comment]
> Assuming so, I've never touched OpenGL before, could you say a little more about that could be achieved?

OpenGL or rendering API in general allows to set a transformation matrix or a stack of matrices to manipulate the viewport during a drawing operation.

**Comment by rah2501** [comment]
> set a transformation matrix or a stack of matrices to manipulate the viewport during a drawing operation

Could you possibly say how that's done?  Again, I've never touched OpenGL.  Could you provide an example?

**Pull request closed without merging**
