### PR TITLE
Big pictures of species (Trenchers, Abaddoni, Scylior, Ugmors, Banforo, Phinnert).

### PR DESCRIPTION
**Pull request by Bestary**
Big illustrations of: Trenchers, Abaddoni, Scylior, Ugmors, Banforo, Phinnert, Gysache, Chato, Happybirthdays, Trith.
Also updated stringtables to insert images to articles.

<s>Unfortunatly, they looks not very good now. My dream was do wrapping on the right side, where are a lot of free space, but I'm not a programmer. ^^' Geoff said, there are no specific tools for it at this moment</s>.

Thanks Ouaz for all awesome answers. :)

[Forum topic is here.](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11095)

### CODE REVIEW

**Comment by Bestary** [comment]
@Ouaz, your advices was very good! I replied you at the forum, and also updated this PR. ^^

**Comment by Ouaz** [comment]
Perfect, exactly what I had in mind.

I thought it would have been a little bit tedious to crop some images (for example, the Trenchers), but I see you had an other version for them (or you modified it purposely), so all is good.

Nice work!

**Comment by Bestary** [comment]
Phinnert added. I don't now, why there are Banforo art affected too, maybe I edited it some time earlier and forgot. :)

**Comment by Bestary** [comment]
Added Gysache.

**Comment by Bestary** [comment]
Chato'matou added.
Oh, I was too dizzy when uploaded last two pictures. One name error, and forgot gray line in two preview. Resolved. :)

**Comment by Ouaz** [comment]
Geoff made a PR (#2378) that dynamically resizes the species image, when the pedia panel size changed.

With this new feature, I think we should increase the default size for both the banners and the full artworks. See my https://github.com/freeorion/freeorion/pull/2378#issuecomment-462138889 about this.

**Comment by Bestary** [comment]
Previews was resized and converted to JPGs according to last UI updates by Geoff. ^_^

**Comment by geoffthemedio** [comment]
Ugh. I need to apologize; the support for loading JPG files was removed a few years ago in ee533357e0b3d4a5b52230f2d0f34ca54a3f8327. I'll see about adding it back, but until then the banners won't load in game.

**Comment by Bestary** [comment]
@geoffthemedio :D No problem!

**Comment by adrianbroher** [comment]
Eh, don't use this crappy format for textures. Also you're really complaining about 184MB of images?  For reference: Moo2 has an install size of 350MB.  Get your scale and expectations right.

**Comment by geoffthemedio** [comment]
@adrianbroher To be clear, these aren't textures in the sense of being rendered to a triangles with perspective; they are just displayed as scaled images.

They also have lots of detail that doesn't compress well as PNG, but which isn't visibly degraded by minimal to moderate JPG compression. Many people still have metered, capped, or just slow internet connections, so I don't consider saving ~100 MB from a download that is currently about ~130 MB to be pointless.

JPG is also one of the most commonly used image formats, so for ease of modability and just for testing, it's useful to support.

**Comment by adrianbroher** [comment]
> To be clear, these aren't textures in the sense of being rendered to a triangles with perspective; they are just displayed as scaled images.

I'm aware where the textures are used and don't try to reinvent terminology for the sake of fitting with your argument.

Do whatever you like. Fortunately this time there are at least some real source assets available to fix your misdecisions in the future.

**Comment by Bestary** [comment]
@adrianbroher, JPG in good quality have no visual differences with PNG (exept not supporting transparancy). It's about common raster illustrations (and most textures too), not pixels or vectors (turned to raster), of course.

**Comment by Vezzra** [comment]
Discussions about image formats aside, is there any reason not to finally merge this PR...?

**Comment by geoffthemedio** [comment]
> Discussions about image formats aside, is there any reason not to finally merge this PR...?

No, but the image format is the reason not to merge it now. All the jpg files in the articles won't appear since GG doesn't know how to load them.

Adding JPEG support isn't trivial, unfortunately, particularly (for me) within the CMake framework.

**Comment by Bestary** [comment]
Happy Birthdays integrated.

**Comment by Bestary** [comment]
@geoffthemedio, maybe It will be better to return PNG-previews (with small resolution)? Because of that it will be possible to merge, without problems with JPEG format.

**Comment by geoffthemedio** [comment]
Until JPG support is available, probably yes.

**Comment by Bestary** [comment]
Trith art + changed all previews to PNG, edited stringtables files.

**Comment by Bestary** [comment]
Sad, I uploaded wrong previews :( Not lined and too big... Edited. Sorry ^^'

**Comment by Vezzra** [comment]
>> Discussions about image formats aside, is there any reason not to finally merge this PR...?

> No, but the image format is the reason not to merge it now. All the jpg files in the articles won't appear since GG doesn't know how to load them.

As all the images have been switched back to PNG, is there any reason left not to merge this?

**Comment by Bestary** [comment]
Hooray!!! Thanks everybody so much! =^___^=

**Comment by TheSilentOne1** [comment]
Thanks for your great work!

**Pull request merged**
