### PR TITLE
AI: starlaneSpeed to speed

### PR DESCRIPTION
**Pull request by Morlic-fo**
in compliance with the recent renaming.

### CODE REVIEW

**Comment by Morlic-fo** [comment]
Most likely not compatible with 950b8cd3fd91609959b1f623c6ff357431d9084e but this should be trivial to apply.

**Comment by Cjkjvfnby** [comment]
You can do TODO in python/PythonUniverseWrapper.cpp line 449 too.

**Comment by Dilvish-fo** [comment]
Yes, as Cj noted, these lines are the only content that the TODO referred to, so it (and the following line) should be taken out at the same time.  

And my git software tells me Mo is right, even though these two commits have no direct conflicts they appear to modify the local context too much for the git merge code to figure it out properly.  Since the other PR is much more important than this one, and I don't want this to interfere with anyone trying out the other one, let's put this one on hold until the other is resolved.

**Comment by Morlic-fo** [comment]
Done in 032fece.

I also changed `hull.starlaneSpeed` to `hull.speed`. My IDE did not find any use of it in the existing AI code so this should cause no trouble, I suppose.

**Comment by genestack-solomatin** [comment]
@Dilvish-fo
Why not merge it now?  Morlic will update other PR. For testing you can merge it locally. 

@Morlic-fo create local branch merge both branches there and you will know if it is compatible.

**Comment by Morlic-fo** [comment]
I just squashed the two commits into one.

**Comment by Dilvish-fo** [comment]
rather than wait for Morlic to do the conflict resolution process in his branch, after merging the other (conflicting) branch I just put this bit of cleanup in directly, and so am closing this PR.

**Pull request closed without merging**
