### PR TITLE
restore default capacity effects for Flak

### PR DESCRIPTION
**Pull request by geoffthemedio**
Possibly was omitted from d9015ec26

Might address #4636

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
> Possibly was omitted from [d9015ec](https://github.com/freeorion/freeorion/commit/d9015ec2682a12d562c2154f3403491d5178a42b)
> 
> Might address #4636

Tested. Yes, works.

**Comment by agrrr3** [comment]
Was omitted intentionally in order to get rid of damage scaling.
Will comment later when back at the computer

Geoff ***@***.***> schrieb am Sa., 22. Juli 2023, 23:56:

**Comment by agrrr3** [comment]
Main point for making flak cannon NoDefaultCapacity was so that it always has a (dummy) damage of 1 to stress that it does actually no real damage. This damage is shown in the part description and may be used in the AI.

@wobbly @Cjkjvfnby do you know if the part damage gets used to assess the value for the AI?

One thing for simplification would be to check if we can set the (ship) damage of Flak to zero while still shooting down fighters and being correctly assessed by AI. In that case Flak could have the standard/default effects and would not need any specific effects.

If we want to have content which is not able to attack with damage zero (e.g. defensive/chaff drone swarm), we still have the target conditions to script such; this means we do not need to rely on damage zero to signal this case.

Note Obstruction etc is already fine as it uses CanDamageShips.

**Comment by MichaelCourtney** [comment]
As far as I can tell the ship designer handles ship, fighter and planet damage separately:

https://github.com/freeorion/freeorion/blob/master/default/python/AI/ShipDesignAI.py#L312-L320

and then proceeds to completely ignore the value flak_shots. It rates military ships on damage vs shields/structure/shields and carriers with same + a fighter value

**Comment by MichaelCourtney** [comment]
I'm seeing similar in the rest of the AI, tracks damage against ships, damage against planets, flak_shots then ignore flak_shots and estimates a fighter survival rate of 0.2

**Comment by MichaelCourtney** [comment]
On the other hand it is almost certainly misevaluating single round weapons

**Comment by agrrr3** [comment]
I think it should be easy to override the calc for the close range weapons
(currently the lance). OTOH it could make sense to query
TotalMaxStructureDamage and TotalMaxFighterDestruction (at least for
unknown weapon content).
Those values only ignores the alpha component (shooting first is usually
better). Of course it would be nice if the ship designer could handle
assassin designs (stealth+close range weapons)

Michael Courtney ***@***.***> schrieb am Fr., 28. Juli 2023,
10:42:

**Comment by MichaelCourtney** [comment]
> I think it should be easy to override the calc for the close range weapons (currently the lance). 

Its also in its threat assessment for monsters. The jaws on a kraken for instance

**Comment by geoffthemedio** [comment]
What's the status of this? Superceded by another pull request or will be, or should this be merged and something else implemented later?

**Comment by agrrr3** [comment]
should be superceded by (non-merged) #4638

**Pull request closed without merging**
