### PR TITLE
Test Debian sid i386 on CI

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by o01eg** [comment]
@Cjkjvfnby Is there a way to test it before merge to `master`?

**Comment by geoffthemedio** [comment]
seems to wrok on your branch...

**Comment by o01eg** [comment]
I works on stable but fails on sid Debian

**Comment by geoffthemedio** [comment]
> I works on stable but fails on sid Debian

I mean the tests run and give similar results.

**Comment by hifron** [comment]
Is this only gcc thing or also in clang?

**Comment by o01eg** [comment]
@hifron I suppose it is gcc-13 thing.

**Comment by hifron** [comment]
What about https://github.com/freeorion/freeorion/pull/4455

**Comment by o01eg** [comment]
@hifron It should be compatible with python from Debian oldstable up to Debian sid.

**Comment by o01eg** [comment]
It was fixed after #4758 https://github.com/o01eg/freeorion/actions/runs/6391545185/job/17347049186

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/actions/runs/6392109231/job/17348722718

````
CMake Error at CMakeLists.txt:52 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
````

**Comment by o01eg** [comment]
Ubuntu's issue I'll fix in other PR

**Comment by o01eg** [comment]
Picked in 6571ae6d27eb9a79666aeed79f665affb55cd4db to release branch.

**Pull request merged**
