### PR TITLE
Fix bug #1732 pathfinder not cleared in universe clear

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This PR may fix bug #1732.  I was not able to replicate the bug, but I think that I understand it from the AddressSantizer dump in the bug report.

The problem is that the hostless improvement violates assumptions in the server code about the persistence of objects, in this specific case the `Pathfinder`.  While the new universe is being created the pathfinder is used with references to the old galaxy topology.

This PR:
- merges `Universe::ResetUniverse()` into `Universe::Clear()`
- adds creation of a new `Pathfinder` to `Clear()`

This PR will need to be tested by someone who can replicate the problem, preferably with a back trace if it crashes. I suspect that there are other bugs with the same symptom, crashing when starting a second hostless game, because a universe sub object is assuming a persistence that the hostless modification has removed.  The backtrace will determine if it is causes by the `Pathfinder` or some other component.

### CODE REVIEW

**Comment by Vezzra** [comment]
@o01eg, you reported #1732, can you check if this PR fixes the issue for you?

**Comment by o01eg** [comment]
I couldn't reproduce old issue but somehow found new another.

Another issue I cann't catch on `master` branch but it happens on this PR while backtrace unrelated with changed files.

**Comment by geoffthemedio** [comment]
If it doesn't break anything, and is considered better, then go ahead anyway...

**Comment by o01eg** [comment]
Looks like #1732 will be fixed with it as that issue happened at game start.

**Pull request merged**
