### PR TITLE
Use pyupgrade

### PR DESCRIPTION
**Pull request by Cjkjvfnby**

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
@Grummel7 [pyupgrade ](https://github.com/asottile/pyupgrade) is a Python tool that updates code automatically according to language improvements. 

The changes id done look good. So I think we could integrate it into our codebase.   I plan to introduce it in two stages:
the first one commits the most of changes in code, probably in a couple of steps.  I want to avoid any conflict with your current changes.   The second one is pre-commit and CI things.

Since changes are done automatically, this work is not in hurry, conflict won't affect me a lot.

**Comment by Grummel7** [comment]
Changes look good and I don't think this tool will break anything.

I actually think we should merge this before the release, to avoid have hundreds of small differences immediately afterwards, making it hard to merge any bug fixes. Or we wait with merging this until we expect no further fixes to be done.

**Comment by Cjkjvfnby** [comment]
> Changes look good and I don't think this tool will break anything.

Do you have something big in the progress?  Should we merge it now? (feel free to press merge)

**Comment by Vezzra** [comment]
This PR should either me merged before the creation of the release branch, or put on hold until the release is out (for the reasons cited above). So, please, if this should go into the release, merge it within the next few hours (before 3pm UTC), or post a request for postponing the creation of the release branch on the [0.5 release thread](https://freeorion.org/forum/viewtopic.php?f=4&t=12040&sid=a98f99b4e9f29bdd42e28b9012021b1d) on the forum.

**Comment by Vezzra** [comment]
👍

**Pull request merged**
