### PR TITLE
Move game UID generation into C++ code

### PR DESCRIPTION
**Pull request by Vezzra**
Correct generation  of the game UID should not depend on user customizable scripts, therefore moved game UID generation from the universe generation Python scripts to the C++ code (`ServerApp::GenerateUniverse`).

See [this discussion](https://github.com/freeorion/freeorion/pull/1997#discussion_r215929419) in the comment section of #1997.

### CODE REVIEW

**Comment by Vezzra** [comment]
@o01eg, please review.

**Review by o01eg — APPROVED** [review]
Looks good and more consistent. OK for me.

**Review by geoffthemedio — COMMENTED** [review]
There are probably dedicated and better UUID generators... I think the ShipDeaign codes use one already...

**Comment by Vezzra** [comment]
> There are probably dedicated and better UUID generators

Ah yes, good idea. Fixed.

**Comment by o01eg** [comment]
What about to sync it with serialization code?

**Comment by Vezzra** [comment]
@o01eg, what do you mean?

**Comment by Vezzra** [comment]
Yep, sounds reasonable: b0d65477ac6231564f05ea8c71ebc43d6cf7e6d6.

**Pull request merged**
