### PR TITLE
Start the server with Godot client

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by o01eg** [comment]
@geoffthemedio No, only about c++ code.

**Comment by geoffthemedio** [comment]
I'm not sure how to build / test this. I ran the CMake build:
````
cmake .. -G "Visual Studio 16 2019" -T v141 -A Win32 -DBUILD_TESTING=On -DCMAKE_C_FLAGS=/MP -DCMAKE_CXX_FLAGS=/MP -DBUILD_CLIENT_GODOT=On
cmake --build . --config "Release" -- /maxcpucount > build.log
````
But get errors like:
````
  CMake Error at CMakeLists.txt:172 (add_library):
    Syntax error in cmake code when parsing string
  
      C:/Users/g_top/Desktop/FOSDK12_unbootstrapped/FreeOrion/build/godot-cpp-build\src\gen\GlobalConstants.cpp
  
    Invalid character escape '\s'.
  
  
  CMake Error at CMakeLists.txt:172 (add_library):
    Syntax error in cmake code when parsing string
  
      C:/Users/g_top/Desktop/FOSDK12_unbootstrapped/FreeOrion/build/godot-cpp-build\src\gen\ARVRAnchor.cpp
  
    Invalid character escape '\s'.
````
[build.log](https://github.com/freeorion/freeorion/files/6462401/build.log)

**Comment by o01eg** [comment]
@geoffthemedio Fix Windows it's need https://github.com/godotengine/godot-cpp/pull/536 to be merged.

**Comment by o01eg** [comment]
@geoffthemedio Should work for windows now.

**Comment by geoffthemedio** [comment]
Not sure if it worked... get some "error" in the log 
[build.log](https://github.com/freeorion/freeorion/files/6493520/build.log)
but also a .dll and some .exe files:
````
 Directory of C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\build\Release

2021-05-17  12:43 PM        17,501,184 FreeOrion.exe
2021-05-17  12:43 PM         2,849,884 FreeOrion.exp
2021-05-17  12:43 PM         4,746,588 FreeOrion.lib
2021-05-17  12:43 PM        13,562,368 FreeOrionCA.exe
2021-05-17  12:43 PM         2,850,196 FreeOrionCA.exp
2021-05-17  12:43 PM         4,754,218 FreeOrionCA.lib
2021-05-17  12:43 PM        15,342,592 FreeOrionD.exe
2021-05-17  12:43 PM         2,884,859 FreeOrionD.exp
2021-05-17  12:43 PM         4,809,518 FreeOrionD.lib
2021-05-17  12:42 PM        12,345,344 freeoriongodot.dll
2021-05-17  12:42 PM         2,850,329 freeoriongodot.exp
2021-05-17  12:42 PM         4,766,250 freeoriongodot.lib
````

**Comment by o01eg** [comment]
Not sure what error you get if all binaries are built.

**Comment by geoffthemedio** [comment]
How do I actually test this? I've tried rereading the [forum thread](https://www.freeorion.org/forum/viewtopic.php?p=105773#p105773), but it doesn't seem to apply any more... There is no `FreeOrion/godot/client` directory. I have the Godot engine executable, but no idea how to proceed.

**Comment by o01eg** [comment]
Godot project moved in `godot/` directory and CMake copies library here in `bin/windows.{32,64}/`

**Comment by geoffthemedio** [comment]
Do I need to edit gdcpptest.gdnlib and if so, where is it and what do I put in it?
Where do I put Godot_v3.2.3-stable_win64.exe or Godot_v3.2.3-stable_win32.exe?
Should I update to the 3.3.1 version or stick with 3.2.3 or 3.2.4?
How do I run it (what do specifiy with --path) ?

**Comment by o01eg** [comment]
> Do I need to edit gdcpptest.gdnlib and if so, where is it and what do I put in it?

I forgot to add links to `godot/freeoriongodot.gdnlib` so yes, you should edit it.

Put here

```toml
[entry]
Windows.64="res://bin/windows.64/freeoriongodot.dll"
Windows.32="res://bin/windows.32/freeoriongodot.dll"
```

> Where do I put Godot_v3.2.3-stable_win64.exe or Godot_v3.2.3-stable_win32.exe?

Not sure about windows. I suppose to put it to the same directory as `freeoriond.exe`.

> Should I update to the 3.3.1 version or stick with 3.2.3 or 3.2.4?

Should be compatible and work with newer 3.x Godot.

> How do I run it (what do specifiy with --path) ?

Try to set absolute path to Godot client project.

**Comment by o01eg** [comment]
It looks like Windows CI couldn't launch FreeOrionD.exe but at least successfully loads freeoriongodot.dll library.

**Comment by geoffthemedio** [comment]
I built the latest version, put the Godot engine executables in the /build/Release/ directory with the .exe files, then tried running it and pointing to the /godot directory a few different ways, but just get error messages. I suspect I need more specific or explicit instructions...
````
C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\build\Release>Godot_v3.3.2-stable_win32.exe --path ../../godot/
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1650 SUPER/PCIe/SSE2
OpenGL ES Batching: ON

ERROR: Failed to get modified time for: C:/Users/g_top/Desktop/FOSDK12_unbootstrapped/FreeOrion/godot/assets/fonts/Roboto-Regular.ttf.
   At: drivers/windows/file_access_windows.cpp:345
ERROR: No loader found for resource: res://assets/image/frames/FOWindowFrame2.png.
   At: core/io/resource_loader.cpp:290
ERROR: poll: res://FOWindow.tscn:5 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/image/frames/FOWindowFrame2.png
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://FOWindow.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://FOWindow.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
ERROR: poll: res://GameSetup.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://FOWindow.tscn
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://GameSetup.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://GameSetup.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://GameSetup.tscn
          At: res://FreeOrionClient.gd:13
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
ERROR: No loader found for resource: res://assets/audio/artificial_intelligence_v3.ogg.
   At: core/io/resource_loader.cpp:290
ERROR: poll: res://FreeOrionClient.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/audio/artificial_intelligence_v3.ogg
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://FreeOrionClient.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://FreeOrionClient.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
ERROR: Failed loading scene: res://FreeOrionClient.tscn
   At: main/main.cpp:1961
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2132
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:66

C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\build\Release>Godot_v3.3.2-stable_win64.exe --path ../../godot/
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1650 SUPER/PCIe/SSE2
OpenGL ES Batching: ON

ERROR: Failed to get modified time for: C:/Users/g_top/Desktop/FOSDK12_unbootstrapped/FreeOrion/godot/assets/fonts/Roboto-Regular.ttf.
   At: drivers/windows/file_access_windows.cpp:345
ERROR: No loader found for resource: res://assets/image/frames/FOWindowFrame2.png.
   At: core/io/resource_loader.cpp:290
ERROR: poll: res://FOWindow.tscn:5 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/image/frames/FOWindowFrame2.png
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://FOWindow.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://FOWindow.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
ERROR: poll: res://GameSetup.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://FOWindow.tscn
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://GameSetup.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://GameSetup.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://GameSetup.tscn
          At: res://FreeOrionClient.gd:13
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
ERROR: No loader found for resource: res://assets/audio/artificial_intelligence_v3.ogg.
   At: core/io/resource_loader.cpp:290
ERROR: poll: res://FreeOrionClient.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/audio/artificial_intelligence_v3.ogg
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://FreeOrionClient.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://FreeOrionClient.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
ERROR: Failed loading scene: res://FreeOrionClient.tscn
   At: main/main.cpp:1961
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2132
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:66

C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion>C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\build\Release\Godot_v3.3.2-stable_win32.exe --path godot/
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1650 SUPER/PCIe/SSE2
OpenGL ES Batching: ON

ERROR: Failed to get modified time for: C:/Users/g_top/Desktop/FOSDK12_unbootstrapped/FreeOrion/godot/assets/fonts/Roboto-Regular.ttf.
   At: drivers/windows/file_access_windows.cpp:345
ERROR: No loader found for resource: res://assets/image/frames/FOWindowFrame2.png.
   At: core/io/resource_loader.cpp:290
ERROR: poll: res://FOWindow.tscn:5 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/image/frames/FOWindowFrame2.png
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://FOWindow.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://FOWindow.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
ERROR: poll: res://GameSetup.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://FOWindow.tscn
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://GameSetup.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://GameSetup.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://GameSetup.tscn
          At: res://FreeOrionClient.gd:13
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
ERROR: No loader found for resource: res://assets/audio/artificial_intelligence_v3.ogg.
   At: core/io/resource_loader.cpp:290
ERROR: poll: res://FreeOrionClient.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/audio/artificial_intelligence_v3.ogg
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://FreeOrionClient.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://FreeOrionClient.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
ERROR: Failed loading scene: res://FreeOrionClient.tscn
   At: main/main.cpp:1961
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2132
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:66
````

**Comment by o01eg** [comment]
1. Set `git config core.symlinks true`
2. Call checkout to generate links
3. Enter to `godot/` directory
4. Launch `../build/Release/Godot...exe` with `-e` argument to generate import files.
5. Launch `../build/Release/Godot...exe` with arguments to start client.

**Comment by geoffthemedio** [comment]
When trying to revert changes and pull again, I'm getting errors with a symlink:
````
Revert
Revert failed:
error: unable to create symlink godot/assets/audio/artificial_intelligence_v3.ogg: Permission denied
Fail (156 ms @ 2021-05-26 9:27:47 AM)
````
Resetting to master, then trying to fetch and rebase gets me a big error popup:
symlinks git error

Setting `git config core.symlinks false` seems to fix it, though.

**Comment by o01eg** [comment]
> Not sure how to fix it...

Not sure how it works on CI, but it looks like git should be run in Administrator console to create links.

**Comment by geoffthemedio** [comment]
> it looks like git should be run in Administrator console to create links.

I don't think that's a viable solution...

**Comment by o01eg** [comment]
I'll try to replace all files symlinks to directories symlinks so on Windows git could use junction without Administrator rights

**Comment by o01eg** [comment]
@geoffthemedio What if I just made required links manually with CMake? At least it works on both Linux and Windows.

**Comment by geoffthemedio** [comment]
I checked out again and rebuilt, then ran as above:
````
C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\godot>C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\build\Release\Godot_v3.3.2-stable_win32.exe -e
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1650 SUPER/PCIe/SSE2
OpenGL ES Batching: ON

ERROR: No loader found for resource: res://addons/gut/icon.png.
   At: core/io/resource_loader.cpp:290
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://addons/gut/icon.png
          At: res://addons/gut/gut_plugin.gd:7
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
WARNING: BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead.
     At: scene/gui/base_button.cpp:329
````
The Godot dev environment window also opened and seemed to hang for ~1 min while importing stuff, but then started responding, but has an error message:
godot -e error

**Comment by o01eg** [comment]
@geoffthemedio addon error is OK. It solved with next Godot launch

**Comment by geoffthemedio** [comment]
I ran:
````
C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\godot>C:\Users\g_top\Desktop\FOSDK12_unbootstrapped\FreeOrion\build\Release\Godot_v3.3.2-stable_win32.exe
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1650 SUPER/PCIe/SSE2
OpenGL ES Batching: ON

WARNING: BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead.
     At: scene/gui/base_button.cpp:329
[2021-05-26 13:51:54.224570] [0x00006274] [info]    Resources directory C:/Users/g_top/Desktop/FOSDK12_unbootstrapped/FreeOrion/godot/default from config.xml missing or does not contain expected files. Resetting to default.
[2021-05-26 13:51:54.225571] [0x00006274] [info]    Refreshed ResDir
[2021-05-26 13:52:27.787818] [0x00004b84] [info]    Client connection disconnected, due to connection reset from server.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2132
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:66
````
I clicked single player and the galaxy setup appeared, then OK, but nothing happened. I quiet the program. The log is attached...
[freeorion-godot.log](https://github.com/freeorion/freeorion/files/6546463/freeorion-godot.log)

**Comment by o01eg** [comment]
```
13:52:18.594720 {0x0000721c} [debug] godot : Message.cpp:877 : ExtractGameStartMessage universe deserialization time     1784 µs
13:52:18.594720 {0x0000721c} [debug] godot : FreeOrionNode.cpp:193 : Extracted GameStart message for turn: 1 with empire: 1
```

It's OK. I'm not yet copied galaxy map code.

**Comment by geoffthemedio** [comment]
anything else I should test?

**Pull request merged**
