### PR TITLE
Disable in-C++ fuel regeneration while stationary.

### PR DESCRIPTION
**Pull request by geoffthemedio**
So the regeneration can be moved into effects / FOCS.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Shall I / we merge this into master?

**Comment by Vezzra** [comment]
Not unless there is also a patch which provides the necessary FOCS scripts replacing the current hardcoded fuel regeneration. Otherwise ships that run out of fuel are stranded indefinitely.

Of course that's not _that_ big of an issue, and maybe an incentive for the rest of us to provide said FOCS scripts. Personally I'd do these two together, but others may have different preferences.

**Comment by adrianbroher** [comment]
I agree with Vezzra, this PR should only be merged when a complete replacement is available.

**Comment by MatGB** [comment]
Thirded.

However, without checking IIRC Dilvish added a macro to all ships that currently does stuff when they're unowned, as a quick hack that could be adapted until someone has time to update all the FOCS files for every ship and decide which lines get what regen, etc.

This is going to be a very useful change when I/we go through and rebalance the hull lines again, probably after Fighters is done, it'll be nice to, for example, let Organic ships refuel rates reflect the star type of the system they're in, etc.

**Comment by dbenage-cx** [comment]
Initial [FOCS additions](https://github.com/freeorion/freeorion/compare/master...dbenage-cx:903_FOCS_base_fuel_regen), currently based on master 81ab0c6.

I did not commit directly to this branch, as I thought it might be rude with an open PR.
I recall seeing PR to a branch was undesired, which is preferred? (maybe a good test for projects?)

**Comment by Vezzra** [comment]
> I did not commit directly to this branch, as I thought it might be rude with an open PR.

Usually a branch in the main repo means that all committers can work on it. However, @geoffthemedio never uses branches in his own clone of the main repo for PRs, so branches he creates in the main repo for his PRs are a bit different - check back with him if it's ok to commit to this branch.

> I recall seeing PR to a branch was undesired

Hm, I'd say creating a PR to a branch is perfectly fine, and has already been done on rare occasions.

**Comment by geoffthemedio** [comment]
Feel free to commit if it's in the main repo.

**Comment by geoffthemedio** [comment]
Any objections to merging this now that the FOCS-based regen is in place?

Seems to work, although the next turn value predictions in the fleet panel / fleet window don't yet show it.

**Comment by geoffthemedio** [comment]
Lacking any objections, I'll merge.

**Comment by Vezzra** [comment]
> Seems to work, although the next turn value predictions in the fleet panel / fleet window don't yet show it.

Weird... now that this is done by FOCS like all the other similar stuff, why do the value predictions work for them but not for this? Need to keep an eye on it and open an issue I think...

**Comment by geoffthemedio** [comment]
My assumption is that the relevant tooltip is different. Started looking into it, but got busy / distracted.

**Pull request merged**
