### PR TITLE
Stpa master

### PR DESCRIPTION
**Pull request by st-pa-fo**
My very first pull request, it seems. I've tried to post on the forum about what I've done: census statistics new column with number of populated worlds.

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
First off, let me note, "Welcome new Contributor!" :smiley: 

Based on description without actually compiling and running yet, the number of worlds display does sound a little interesting, I am wondering if perhaps a little more functionality could be added to make it more worth taking up the UI space-- while this currently proposed world count display may slightly facilitate a decision about "I want more planets for species X to assure that I have them securely available in my empire", at the point where that is a significant decision the player is probably already quite aware that they have only one or very few planets for that species (which would also be somewhat suggested by the population numbers already displayed, and can also be had by consulting the Objects window).  Did you see some other use-cases for the information?

A bit of related functionality that might make that feature much more powerful would be to add something akin to when clicking on the unused PP icon-- perhaps if the census icon were left-clicked then the census window could be displayed as a semi-persistent window that itself can be clicked rather than just as a tooltip, and then successive clicks on any of the lines could cycle the MapWnd focus across the successive systems/planets that contribute to the respective line.  Again that capability is already had easily within the objects window, but it useful enough that it might be worth adding, perhaps here, or perhaps as a later PR.

Let me also mention a census feature you might be interested in working on, that has either been previously proposed on the forum or just that I've been considering.  Specifically, that rather than simply show the various current population totals, they would also show the respective total target, in a current/target manner, so like
```
        Species
Human    21/23

        Characteristics
Organic  21/23
```
That extra info would facilitate making decisions about using growth focus (and possibly about choice of growth techs)

@geoffthemedio looking through the README and [CONTIRBUTING.md](https://github.com/freeorion/freeorion/blob/master/CONTRIBUTING.md) I see references to FO source being licensed under GPLv2, but I am not seeing anything explicitly akin to our old requirement for new contributors to explicitly state that their contributions are so licensed.  Are we just leaving it implicit now?

Anyways, st-pa, I will get around to testing out your PR sometime later this week.  Thanks for joining us.

**Comment by Dilvish-fo** [comment]
Also, st-pa, I feel I have to mention that your branch naming suggests you are doing this dev work in your master branch.  You have renamed it somewhat, so that could work out, but just to be sure, please keep in mind that you should also keep a plain 'master' that purely tracks the main repo master, to facilitate being able to rebase your branch and whatnot.  It would probably be helpful for you to read through our [Github thread on our forums](http://www.freeorion.org/forum/viewtopic.php?f=9&t=9366)

**Comment by adrianbroher** [comment]
@Dilvish-fo 
> Are we just leaving it implicit now?

No, the contributor must state that he releases his contributions under the terms of the project. The placement where and how to state this is AFAIK dubious.  I'm sure there were explicit forum posts for that but I can't find them. @Vezzra *ping*

Also this is maybe a good point to introduce a formal Developer Certificate of Origin (DCO)?

@st-pa-fo 
On top of the license agreement you need to fix your indentation before any review can occur. Convert all tabs to 4 space indentations.

**Comment by geoffthemedio** [comment]
@adrianbroher could you clarify what that means?

**Comment by adrianbroher** [comment]
@geoffthemedio 
The DCO? It's a statement that needs to be posted by a contributor before accepting the contribution to a project.  The Linux Foundation formalized this:

https://developercertificate.org/

**Comment by adrianbroher** [comment]
Probably the best idea would be to insert this into a commit message so this can't be tampered by deleting a forum or issue comment.  But that should be discussed in another Issue maybe?

**Comment by st-pa-fo** [comment]
my first pull request in living memory, so I tried a couple of things 
before I got it to produce an actual pull request … so I'm gonna read 
through the guidelines and try to comply

Am 12.03.18 um 18:09 schrieb Dilvish-fo:

**Comment by st-pa-fo** [comment]
yeah sorry, I thought that was implicit in me trying to contribute, so 
here it is as explicit as I could find it using forum search: I'm 
licencing all code & contributions under GPL v2 (or compatible licence, 
at the discretion of the FreeOrion team) and also I release this work 
under the Creative Commons licence FO uses and I can repeat that 
statement in every commit message or whereever you need it.

the indentation will be corrected and the branch renamed and so on and 
I'll probably make more minor typo corrections as I go along – so how 
does it work, do I create new pull requests for every little thing and 
retract the ones that do not comply with the guidelines I have yet to read?

Am 12.03.18 um 18:53 schrieb Marcel Metz:

**Comment by geoffthemedio** [comment]
You don't need to close pull requests and delete branches before merging to make updates. Just push to your branch again; the pull request page (here) will be updated with the changes.

**Comment by st-pa-fo** [comment]
Yeah I had more functionality in mind, too, being aware of the possibility to find what I needed using the Objects window. But it is just ugly Imop and I need to get to know the codebase and what is done how and so that seemed like an easy entry point … I like the reports windows in FreeCol and I thought of map overlays to show additional information on the big map and I want a little universe map that shows me where I am, and yeah those are good ideas about the target values and about pinning the tooltip down as window with more clickable functions, I will look into that. And just wait with testing the PR, there will be more commits soon. i've now renamed the branch "census" to be as concise as possible and I will merge the master branch into it regularly to avoid conflicts later. I've set XCode to 4 spaces instead of tabs. I do not like rewriting history and rebasing branches and am used to working with git, just not to working on github yet.
What I also need to do is reduce clicks needed and make the gui easier to use with a touchpad … my digits start getting rigid from too much play(test)ing …

**Comment by geoffthemedio** [comment]
>  I will merge the master branch into it regularly to avoid conflicts later

Do not merge master into your branch. You should instead rebase against master.

**Comment by st-pa-fo** [comment]
okay so I undid that merge and just to be clear, you want me to rebase all changes from the census branch onto the master branch in my fork?

**Comment by geoffthemedio** [comment]
Yes

**Comment by Vezzra** [comment]
> I will merge the master branch into it regularly to avoid conflicts later. [...] I do not like rewriting history and rebasing branches and am used to working with git, just not to working on github yet.

To expand a bit on @geoffthemedio's very concise reply: It is explicit project policy to *never* merge master into feature branches. Instead, to solve conflicts, feature branches are *always* to be rebased onto master.

We are aware of the different preferences concerning merging vs. rebasing, but the general consensus and decision for this project has been to adopt the rebase approach.

**Comment by Vezzra** [comment]
@adrianbroher (well, and everyone else)

> But that should be discussed in another Issue maybe?

Actually, as a discussion about something which should be considered project policy, that needs to take place on our forum. I [opened a corresponding thread](http://freeorion.org/forum/viewtopic.php?f=4&t=10914), please continue the above discussion about license statements there.

**Comment by Vezzra** [comment]
@st-pa-fo, do you plan to reopen this PR, or do you want to create a new one with the updated branch? Need to know this to tag the PR properly.

**Comment by st-pa-fo** [comment]
i'll make a new one with the properly named branch rebased on my forked 
master as soon as i'm ready – if there is a release schedule I need to 
be aware of? – otherwise couple days to get acquainted with things and 
then at least let me finish geoff's and who-was-its'es wishes about the 
census tooltip/window. and - is there some i18n-workflow I'm breaking by 
correcting typos directly in those string files?

Am 16.03.18 um 14:15 schrieb Vezzra:

**Comment by Vezzra** [comment]
> if there is a release schedule I need to be aware of?

No. It's a nice feature, but it is not essential for the upcoming 0.4.8 release. If it's completed in time, it will get in, otherwise it will get into the next release. Take all the time you need. 😉 

> is there some i18n-workflow I'm breaking by correcting typos directly in those string files?

If you are talking about correcting typos in the stringtables, not that I'm aware of. However, if the stringtable entries you correct have no relation to your PR, you should break them out into a separate PR (which would just be a typo fix PR then). Don't mix unrelated things in a feature branch/PR. See [CONTRIBUTING.md](https://github.com/freeorion/freeorion/blob/master/CONTRIBUTING.md):

> The PR IS concise on the topic it addresses. If you want to address different topics create different branches and PRs for them. If the topics/PRs relate to each other document so in the PR message.

**Comment by Vezzra** [comment]
@st-pa-fo: When you close a PR because you want to replace it with another (for whatever reason), the closed PR needs to be tagged with the label "status:superseded" and a comment with a reference to the superseding PR should be added.

I's also recommend to add a reference to the superseded PR in the description of the superseding PR.

See the [description of the "status:superseded" label](https://github.com/freeorion/freeorion/blob/master/.github/labels.md#label-statussuperseded):

> **Label status:superseded**
>
> The PR discussion showed that the proposed implementation is insufficient in some way or the PR in itself is malformed. Usually not required as we prefer rebasing within the same PR to update the implementation. When applying this label reference the superseding PR number in the superseded one, add a comment why the superseded PR requires a follow up and close the PR.

I'll do this for you this time 😉

**Comment by Vezzra** [comment]
Superseded by #2055.

**Pull request closed without merging**
