### PR TITLE
make_versioncpp.py: don't get pissed at commit signatures

### PR DESCRIPTION
**Pull request by l29ah**
that get shown by default if user desires so in their gitconfig

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Could you elaborate on what issue this fixes?

**Comment by l29ah** [comment]
https://github.com/github/hub/issues/1379

**Comment by Vezzra** [comment]
This can be potentially problematic for people who (for whatever reasons) use a very old version of git (2.4.0 or older):

https://github.com/golang/go/issues/26844

That aside, the link you, @l29ah, provided, didn't really really make it clear to me what the issue is. Does `make_versioncpp.py` fail or break in any way if users set that option in their gitconfig?

**Comment by l29ah** [comment]
Yes, it stops the compilation, otherwise i wouldn't have bothered to fix it.

**Comment by geoffthemedio** [comment]
OK then...

**Pull request merged**
