### PR TITLE
Introduce python parser

### PR DESCRIPTION
**Pull request by o01eg**
Preparation for using python's parser.

Moves minimal python initialization and finalization to common library.

Should be usable in both cases if we use python ast or python interpretation.

Follows #3342

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Don't see a point to this, and some points against, unless transitioning to a new parser, so not likely to merge on its own...

**Comment by o01eg** [comment]
Rebased and left only common code which will be used either Python AST will be used or Python execution.

**Comment by agrrr3** [comment]
> > Waiting only for the NamedValueRefParser won't suffice though - you/we need to wait for all the parsers which may parse valuerefs to finish.
> 
> I only re-implemented current `WaitForPending` in more multi-thread solution.

I am not sure what you mean. 

You added the ability to wait for the asynchronous calculation wrapped inside of Pending to finish, didnt you?
I am not sure about the multithreading part (must have a fresh look at it tomorrow), the shared state thingy in std::future is not completely clear to me.

I am not sure why you would only need to wait for the named_values.focs.txt parsing. All the other main parsers contribute named values refs concurrently. So e.g. the NamedValueRefManager checksums can still be wrong and we do not know when it is safe to initialize invariants.

edit1: ah now i think i understand what you meant. You refactored that WaitForPending(named_value_ref_parser_future) away.

**Comment by o01eg** [comment]
Suddenly found out it fails with original cmake 3.10.2 on Ubuntu 18.04. Travis CI somehow uses 3.12.

```
CMake Error at CMakeLists.txt:432 (target_link_libraries):
  Object library target "freeorionparseobj" may not link to anything.
```

**Review by Vezzra — APPROVED** [review]
As usual, can't comment much on the code, but builds and runs ok on Mac.

**Comment by geoffthemedio** [comment]
needs rebase

**Comment by geoffthemedio** [comment]
starts up OK, after resolving merge conflicts

**Comment by o01eg** [comment]
Rebased

**Comment by geoffthemedio** [comment]
6bdf65962deac3cbe639360fcf00d6182423904d hangs at startup.

**Comment by o01eg** [comment]
@geoffthemedio Nice, could you bisect it from 385860ea14536d46440233bfb535df056987f5c0 ?

**Comment by geoffthemedio** [comment]
> @geoffthemedio Nice, could you bisect it from [385860e](https://github.com/freeorion/freeorion/commit/385860ea14536d46440233bfb535df056987f5c0) ?

6bdf65962deac3cbe639360fcf00d6182423904d hangs

683d79293a9ae0bdc90eeb1f6afb196a068fa581 with 6bdf65962deac3cbe639360fcf00d6182423904d cherry picked hangs

683d79293a9ae0bdc90eeb1f6afb196a068fa581 build fails

ca82ca67252ab47cd8d3342fb7439af237c24f84 with 6bdf65962deac3cbe639360fcf00d6182423904d cherry picked hangs

11d988d95288d5bc1e23638d8b06c4021d081ab0 works

05e5fb11d169bf928ff09f4c31405a36b38d68ed works

385860ea14536d46440233bfb535df056987f5c0 works

**Comment by o01eg** [comment]
> > @geoffthemedio Nice, could you bisect it from [385860e](https://github.com/freeorion/freeorion/commit/385860ea14536d46440233bfb535df056987f5c0) ?
> 
> [6bdf659](https://github.com/freeorion/freeorion/commit/6bdf65962deac3cbe639360fcf00d6182423904d) hangs

But it only fixes MSVC project and changes literally nothing.

**Comment by o01eg** [comment]
I see ca82ca6 is a culprit.

**Comment by o01eg** [comment]
Could you test the latest commit of https://github.com/freeorion/freeorion/pull/3379 if it isn't `set_exception_at_thread_exit` issue?

**Comment by geoffthemedio** [comment]
714cf3f6f313e5f0c50c61c9bed16f52288b7d07 starts

**Review by Vezzra — APPROVED** [review]
Builds and runs, no immediately obvious issues on macOS.

**Comment by Vezzra** [comment]
Same as [here](https://github.com/freeorion/freeorion/pull/3265#issuecomment-830798606).

**Pull request merged**
