### PR TITLE
[AI] Refactor ship design

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Extract some code from the ship design to a separate module.

### CODE REVIEW

**Review by Grummel7 — COMMENTED** [review]
This is probably fine, but I cannot test it now. I suggest to merge this after the release.

**Comment by Cjkjvfnby** [comment]
> This is probably fine, but I cannot test it now. I suggest to merge this after the release.

I am ok with this.  

What is the currently planned date for that?

**Comment by Grummel7** [comment]
> What is the currently planned date for that?

No specific date yet, though maybe we can agree on one in the next dev meeting.

**Comment by Cjkjvfnby** [comment]
Replaced by https://github.com/freeorion/freeorion/pull/4214

**Pull request closed without merging**
