### PR TITLE
Convert ScopedTimer,  GG and remaining to std::chrono.

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This PR converts everything not associated with `boost::asio` to use `std::chrono`.

The only useful feature that we are giving up is time short form unit formatting,  (ms, µs and s).

### CODE REVIEW

**Comment by geoffthemedio** [comment]
> The only useful feature that we are giving up is time short form unit formatting, (ms, µs and s).

were you able to work around that, or is there a loss of formatting functionality in the resulting logs?

**Comment by LGM-Doyle** [comment]
I just added those 3 labels by hand in the `ScopedTimer`.  Add it is my preference, the `std::` library uses the full words milliseconds, with no option to use a short form.

Balancing that one case vs the increased consistency of `std::chrono` everywhere.  I chose `std::chrono` everywhere.

**Comment by geoffthemedio** [comment]
````
6>..\..\client\human\chmain.cpp(218): error C3083: 'this_thread': the symbol to the left of a '::' must be a type
6>     1>
6>..\..\client\human\chmain.cpp(218): error C2039: 'sleep_for': is not a member of 'std'
6>         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\fstream(13): note: see declaration of 'std'
6>     1>
6>..\..\client\human\chmain.cpp(218): error C3861: 'sleep_for': identifier not found
6>     1>
6>..\..\client\human\chmain.cpp(222): error C3083: 'this_thread': the symbol to the left of a '::' must be a type
6>     1>
6>..\..\client\human\chmain.cpp(222): error C2039: 'sleep_for': is not a member of 'std'
6>         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\fstream(13): note: see declaration of 'std'
6>     1>
6>..\..\client\human\chmain.cpp(222): error C3861: 'sleep_for': identifier not found
6>     1>
6>..\..\client\human\chmain.cpp(226): error C3083: 'this_thread': the symbol to the left of a '::' must be a type
6>     1>
6>..\..\client\human\chmain.cpp(226): error C2039: 'sleep_for': is not a member of 'std'
6>         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\fstream(13): note: see declaration of 'std'
6>     1>
6>..\..\client\human\chmain.cpp(226): error C3861: 'sleep_for': identifier not found
````

**Comment by adrianbroher** [comment]
Seems like `chmain.cpp` is missing the `<thread>` include.

**Comment by LGM-Doyle** [comment]
I added the `<thread>` and `<chrono>` headers.

**Comment by geoffthemedio** [comment]
builds, seems to run OK

**Comment by adrianbroher** [comment]
Can you remove boost_chrono from the build systems?  It shouldn't be required anymore.

**Comment by LGM-Doyle** [comment]
Yes, I can remove `boost::chrono` from the build when this PR and #1374 are merged.

**Pull request merged**
