### PR TITLE
add new molecular cloud image with clearer border

### PR DESCRIPTION
**Pull request by TheSilentOne1**
Adds new graphic for molecular cloud with clearer outline.

mol_cloud_example

### CODE REVIEW

**Comment by geoffthemedio** [comment]
seems reasonable

**Comment by Bestary** [comment]
Wow, looks so fresh! :D

**Comment by geoffthemedio** [comment]
Some debate on the forums? 

https://www.freeorion.org/forum/viewtopic.php?p=96703#p96703

**Comment by geoffthemedio** [comment]
@TheSilentOne1 What's the status of this? There's some ongoing discussion on the forum, but is this particular change still being debated?

Also, can / should you squash into one commit?

**Comment by TheSilentOne1** [comment]
Labgnome had some suggestion to make the image more realistic, but my primary concern is to have the image give some sense of its gameplay effects, and a clear border. So this is final as far as I'm concerned.

**Pull request merged**
