### PR TITLE
add tech turn requirement and turn cost to unresearched techs

### PR DESCRIPTION
**Pull request by TheSilentOne1**
also increase tech panel width and decrease (standard) horizontal distance between techs:
tech_screen

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Doesn't fit in the available space with closer-to-current-default font size.

**Comment by TheSilentOne1** [comment]
I think the turn/RP cost really should be on the panel. Solutions to a larger font size would be:
- variable panel width/spacing depending on font size
- place cost label under tech name, increase panel height with font size:
  tech_panel

**Comment by geoffthemedio** [comment]
Could also put it at the bottom-right, like on the queue panels.

**Comment by Deepsloth** [comment]
Bottom-right sounds like a good idea.

**Comment by TheSilentOne1** [comment]
Currently caught up IRL, but I'll get back to this soon.

**Comment by TheSilentOne1** [comment]
I corrupted my branch of this pull-request, so I created a new one here:
https://github.com/freeorion/freeorion/pull/791

**Pull request closed without merging**
