### PR TITLE
Spanish translation update (partial)

### PR DESCRIPTION
**Pull request by Oberlus**

### CODE REVIEW

**Comment by Oberlus** [comment]
~~This in intended for merge as is. Let me know if it won't be merged.~~

**Comment by Vezzra** [comment]
Anyone any objections to merging this? I guess there are no other Spanish native speakers who could provide a meaningful review...

**Comment by geoffthemedio** [comment]
It fails the stringtable lint.

**Comment by Oberlus** [comment]
> It fails the stringtable lint.

I'll look into it sometime next week. No rush to merge.

**Comment by adrianbroher** [comment]
> It fails the stringtable lint.

That's probably because st-tool has a bug, #2844 contains 25f6dd63241282196d60025eb680c71a7d90f863 with a bugfix.

**Comment by Oberlus** [comment]
> > It fails the stringtable lint.
> 
> That's probably because st-tool has a bug, #2844 contains [25f6dd6](https://github.com/freeorion/freeorion/commit/25f6dd63241282196d60025eb680c71a7d90f863) with a bugfix.

I used the version before 25f6dd6 to do the sync, but the es.txt file I pushed has been edited with that commit merged.

I've tried check (against en.txt), format and sync. None made any difference. Here is the output:
```
freeorion$ ./check/st-tool.py check -r default/stringtables/en.txt default/stringtables/es.txt 
freeorion$ ./check/st-tool.py format default/stringtables/es.txt > default/stringtables/es_formated.txt
freeorion$ diff default/stringtables/es.txt default/stringtables/es_formated.txt
freeorion$ ./check/st-tool.py sync default/stringtables/en.txt default/stringtables/es.txt > default/stringtables/es_resynced.txt
freeorion$ diff default/stringtables/es.txt default/stringtables/es_resynced.txt 
freeorion$ 
```

Edit: maybe I'm doing something wrong with my branches...

**Comment by Oberlus** [comment]
OK, I have just pushed the right es.txt file, the one that produces the output in my previous comment.
I have tried the very same command that is returning an error in the travis-CI build and I'm not getting the error.

I don't know what else to do.

**Comment by adrianbroher** [comment]
This PR can probably be merged, am I right?

**Comment by Oberlus** [comment]
> This PR can probably be merged, am I right?

I'll be doing some more translation in next hours and update this.

**Comment by Oberlus** [comment]
I won't update this for now because of an [issue](https://github.com/freeorion/freeorion/pull/2844#issuecomment-616668406) I found using the st-too edit command, which I hadn't spotted previously and that has introduced some problems in the latest updates (namely, it has replaced reference keys by the actual values, which is not OK).
I'll have to review the work done up to know and I won't have time for it in the near future.

Can anyone set this as work in progress?

**Comment by Oberlus** [comment]
@geoffthemedio this can be merged
Still a long way to go that I can commit to in the near future, but at least we've got some more work done for v0.4.10.

**Pull request merged**
