### PR TITLE
Fixes for Godot deb packaging

### PR DESCRIPTION
**Pull request by o01eg**
Some fixes I made to prepare .deb packages

Branch with deb package files is https://github.com/o01eg/freeorion/tree/ppa-godot

It builds for Ubuntu 20.04 Focal LTS but I'm not yet tested it.

### CODE REVIEW

**Comment by o01eg** [comment]
Made it working on Devuan Chimaera.

**Comment by o01eg** [comment]
@agrrr3 I will try to build snap here with CI

**Comment by o01eg** [comment]
@agrrr3 Could you test if this PR produce correct snap?

**Review by Vezzra — COMMENTED** [review]
I'm afraid I don't know what kind of helpful input I could or am supposed to provide - sorry.

I assume the changes you made are fine, that the parts you removed are sufficiently covered by the additions.

**Comment by o01eg** [comment]
@Vezzra Yes, mostly I want you to test is removed dependencies. It still works for me, but not sure if it works for you.

**Comment by agrrr3** [comment]
@o01eg i tried to build the revision from your repository (so not the PR) on snapcraft.io/../builds and there are multiple errors

https://snapcraft.io/freeorion/builds/1370317

```Building freeorion 
+ sed -i.bak -e 's|Icon=freeorion$|Icon=${SNAP}/meta/gui/icon.png|g' ../src/packaging/org.freeorion.FreeOrion.desktop
+ sed -i.bak -e 's|="res://bin/linux.*/libfreeoriongodot.so"|="/usr/local/lib/freeorion/libfreeoriongodot.so"|g' ../src/godot/client/gdcpptest.gdnlib
+ mkdir -p home/
+ mkdir -p /build/freeorion/parts/freeorion/install/usr/local/share/freeorion/
++ pwd
+ HOME=/build/freeorion/parts/freeorion/build/home
+ godot3-server --path ../src/godot/client --export-pack Linux/X11 /build/freeorion/parts/freeorion/install/usr/local/share/freeorion/freeorion.pck
Godot Engine v3.2.stable.custom_build - https://godotengine.org
 
ERROR: get_language_code: Invalid locale 'C'.
   At: core/translation.cpp:945.
ERROR: set_locale: Unsupported locale 'C', falling back to 'en'.
   At: core/translation.cpp:969.
ERROR: open_dynamic_library: Can't open dynamic library: /usr/local/lib/freeorion/libfreeoriongodot.so. Error: /usr/bin/../lib/libfreeoriongodot.so: cannot open shared object file: No such file or directory
   At: drivers/unix/os_unix.cpp:424.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: init_library: No nativescript_init in "/usr/local/lib/freeorion/libfreeoriongodot.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506.
```

and

```
import: begin: Import Scene steps: 104
	import: step 0: Importing Scene...
	import: step 2: Running Custom Script...
	import: step 104: Saving...
ERROR: store_buffer: Condition "!p_src" is true.
   At: drivers/unix/file_access_unix.cpp:278.
```

and 

```
reimport: end
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: terminate: No valid library handle, can't terminate GDNative object
   At: modules/gdnative/gdnative.cpp:388.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```

**Comment by o01eg** [comment]
I suppose those errors are fine if it produces correct package.

**Comment by o01eg** [comment]
@agrrr3 Could you try again? I tried to fix `freeoriond` placement and command line parser.

**Comment by o01eg** [comment]
Also I've added log for missing default directory if it was the case.

**Comment by agrrr3** [comment]
Note that I ran the package (and commented on that in #3399). 

> @agrrr3 Could you try again? I tried to fix `freeoriond` placement and command line parser.

just started a rebuild. if it completes, it should be published in about 50 minutes in latest/edge

note that you are working on generated code (the snapcraft.yaml is expanded from `snap/local/20210308_core20_unexpanded__snapcraft.yaml` via `snapcraft expand-extensions --enable-experimental-extensions`).

also i saw that you moved /share/freeorion to /usr/local/share/freeorion (which is probably a good thing). i do not completely understand the paths work there. but the unchanged `freeorion` command still works (while the godot one does not seem to find the correct default directory).

**Comment by agrrr3** [comment]
> Also I've added log for missing default directory if it was the case.

ok, i cancelled the previous build. with that log statement is building in https://snapcraft.io/freeorion/builds/1371437

**Comment by agrrr3** [comment]
this is better. 

it still cant start a game. symlinking did not completely work. libfreeoriongodot.so is directly at the target location (so symlink should not be necessary). the symlinks are not in the /snap/ directory, but i think they should be created at runtime in a temporary fs layer (not sure how to look at this). Anyway it should be `/usr/bin/freeoriond: symlink...` instead of `$SNAP/usr/bin/freeoriond: symlink...`

```$ freeorion-godot 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
 
Systems from optionsDB 150
execv failed: /snap/freeorion_edge/195/usr/bin/freeoriond: No such file or directory
i965: Failed to submit batchbuffer: No such file or directory
```

edit1: can confirm that the symlink is messed up by running `snap run --shell freeorion`
```bash-5.0$ ls -la /snap/freeorion/195/usr/bin/freeoriond 
lrwxrwxrwx. 1 root root 44 Apr 12 23:12 /snap/freeorion/195/usr/bin/freeoriond -> /snap/freeorion/195/usr/local/bin/freeoriond
```

**Comment by o01eg** [comment]
@agrrr3 

I suppose without stable symlink to `libfreeoriongodot.so` Godot won't be able to find it.

```
execv failed: /snap/freeorion_edge/195/usr/bin/freeoriond: No such file or directory
```

It should be placed in the same directory as `godot3-runner` so binary search directory will find it. Could you tell if you find something in `freeorion-godot.log`?

**Comment by o01eg** [comment]
> note that you are working on generated code (the snapcraft.yaml is expanded from `snap/local/20210308_core20_unexpanded__snapcraft.yaml` via `snapcraft expand-extensions --enable-experimental-extensions`).

How does `snapcraft` find `snap/local/20210308_core20_unexpanded__snapcraft.yaml`? I suppose I need to add it to CI.

**Comment by o01eg** [comment]
@agrrr3 Is it possible `godot3-runner` and freeorion's files are placed in different `/snap/freeorion_edge/` folder?

**Comment by agrrr3** [comment]
> @agrrr3 Is it possible `godot3-runner` and freeorion's files are placed in different `/snap/freeorion_edge/` folder?

no, that freeorion_edge is only because i have installed multiple versions of freeorion in parallel (and the edge channel as freeorion_edge) and the godot3-runner is in the /snap/freeorion_edge on my machine. i usually strip that part out because i did not have any issues with parallel snaps at all - it also binds the 195 (edge) revision in /snap/freeorion inside of the edge container, so the /snap/freeorion/195 do actually work (actually i think it should ignore /snap/freeorion_edge inside the snap completely). i am pretty sure the symlink change will fix finding freeoriond.

**Comment by agrrr3** [comment]
> @agrrr3
> 
> I suppose without stable symlink to `libfreeoriongodot.so` Godot won't be able to find it.
> 
> It should be placed in the same directory as `godot3-runner` so binary search directory will find it. Could you tell if you find something in `freeorion-godot.log`?

```
bash-5.0$ find /snap/freeorion/195 -iname "*godot*" 
/snap/freeorion/195/meta/gui/freeorion-godot.desktop
/snap/freeorion/195/usr/bin/godot3-runner
/snap/freeorion/195/usr/local/lib/freeorion/libfreeoriongodot.so
/snap/freeorion/195/usr/share/doc/godot3-runner
bash-5.0$ find /snap/freeorion/195 -iname "*freeoriond*" 
/snap/freeorion/195/usr/bin/freeoriond
/snap/freeorion/195/usr/local/bin/freeoriond
```

i can see it starts up and parsed content in the log file. what functionality is inside libfreeoriongodot.so ?

**Comment by o01eg** [comment]
>  what functionality is inside libfreeoriongodot.so ?

It's a proxy between freeorion common and parser libraries and Godot scripts.

Did you managed to run server with symlink fix?

**Comment by agrrr3** [comment]
> > what functionality is inside libfreeoriongodot.so ?
> 
> It's a proxy between freeorion common and parser libraries and Godot scripts.
> 
> Did you managed to run server with symlink fix?

No
```
$ LANG=en_US.UTF-8 freeorion_edge.freeorion-godot 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
 
[2021-04-13 11:15:13.231165] [0x00007fd92d7a5a40] [info]    Not found freeoriond in the same directory as /snap/freeorion_edge/196/usr/bin/godot3-runner
```
The freeorion binaries are in `/snap/freeorion/196/usr/local/bin/`, the symlink is there `/usr/bin/freeoriond -> /snap/freeorion/196/usr/local/bin/freeoriond`.

The godot3-runner does not exist in /usr/bin/ . Could you put the executable in $SNAP/usr/local/bin (or maybe link and run the godot3-runner from /usr/bin)?

**Comment by o01eg** [comment]
@agrrr3 I expected previous approach to link `/snap/freeorion/196/usr/bin/freeoriond -> /snap/freeorion/196/usr/local/bin/freeoriond` so it will be together with `/snap/freeorion_edge/196/usr/bin/godot3-runner`.

If I link godot3-runner, what I should set in command instead of `usr/bin/godot3-runner` ?

**Comment by o01eg** [comment]
Also, what if install freeorion data info `/usr` instead of `/usr/local`?

**Comment by agrrr3** [comment]
> > note that you are working on generated code (the snapcraft.yaml is expanded from `snap/local/20210308_core20_unexpanded__snapcraft.yaml` via `snapcraft expand-extensions --enable-experimental-extensions`).
> 
> How does `snapcraft` find `snap/local/20210308_core20_unexpanded__snapcraft.yaml`? I suppose I need to add it to CI.

Not all, generating the code is currently a manual step. I dont think we can really put generation into CI as it has to be part of the commit.  
When that expansion is not experimental anymore it will become part of the snapcraft.io build infrastructure, then it wont be necessary.

**Comment by o01eg** [comment]
@agrrr3 Could you test it again?

**Comment by o01eg** [comment]
If this approach won't work I could try to add option with path to `freeoriond` binary and set it in the command-line.

**Comment by agrrr3** [comment]
The older cpp build (56b8053d353eee061ffacf43d17bac85) was broken because of changed parsing interface with promise, will restart the build.

**Comment by o01eg** [comment]
@agrrr3 Which commit is it? I have fixed it in base PR in https://github.com/freeorion/freeorion/pull/3235/commits/34e6ad5e9baa65500d91b554aef1f0ac44c265a4 and then rebased this PR.

**Comment by agrrr3** [comment]
> @agrrr3 Which commit is it? I have fixed it in base PR in [34e6ad5](https://github.com/freeorion/freeorion/commit/34e6ad5e9baa65500d91b554aef1f0ac44c265a4) and then rebased this PR.

The older cpp build (56b8053d353eee061ffacf43d17bac85) was broken because of changed parsing interface with promise, will restart the build.

**Comment by agrrr3** [comment]
5b4069a built fine and went up as revision 198 and is currently available as latest/edge
Could run a normal freeorion game.

godot client started, starting a game seems to spawn a freeoriond and some ai processes which get terminated.

```
bash-5.0$ ls -la /snap/freeorion/198/usr/bin/
total 57581
drwxr-xr-x. 2 root root      163 Apr 15 09:16 .
drwxr-xr-x. 6 root root       89 Apr 15 09:16 ..
-rwxr-xr-x. 1 root root 11946312 Apr 15 09:15 freeorion
-rwxr-xr-x. 1 root root  5717888 Apr 15 09:08 freeorionca
-rwxr-xr-x. 1 root root  7838336 Apr 15 09:10 freeoriond
-rwxr-xr-x. 1 root root    14328 Nov 24  2018 glxdemo
-rwxr-xr-x. 1 root root    26712 Nov 24  2018 glxgears
-rwxr-xr-x. 1 root root    14328 Nov 24  2018 glxheads
-rwxr-xr-x. 1 root root    63696 Nov 24  2018 glxinfo
-rwxr-xr-x. 1 root root 33339520 Mär 25  2020 godot3-runner
lrwxrwxrwx. 1 root root        1 Feb  8  2020 X11 -> .
```

looks good :)

**Comment by o01eg** [comment]
@Vezzra Looks like Linux distributives are covered.

**Comment by o01eg** [comment]
@agrrr3 You could try to rotate camera with holding and moving mouse cursor and move camera back with mouse wheel to see systems and even fleet.

**Comment by geoffthemedio** [comment]
don't think there is anything for me ro comment on in this...

**Comment by Vezzra** [comment]
@o01eg,

> mostly I want you to test is removed dependencies. It still works for me, but not sure if it works for you.

Well, as mentioned already elsewhere, I don't have a Godot dev environment on my Mac, so I can't do any Godot tests on Mac. I only have Godot set up on my Linux system, and IIRC you're on Linux yourself (even Ubuntu as I am), so I'm not sure what additional tests I can do that you didn't do already yourself...?

**Comment by o01eg** [comment]
Merged to https://github.com/freeorion/freeorion/pull/3235

**Pull request closed without merging**
