### PR TITLE
Add common/opinion.macros for liberty/conformance dislike scaling effects

### PR DESCRIPTION
**Pull request by Oberlus**
Fixes duplicated key in buildings/policies/common.happiness.macros

### CODE REVIEW

**Comment by Oberlus** [comment]
This needs debate, maybe.
I chose to keep a single macro definition in a single file for the three use cases, instead of giving three different names to the same macro declared in three different files.

I added a new macros file because it seems incorrect to reuse any of the others (including unrelated stuff).

And I included that macros file in the three original macros files. I didn't find other uses of macros including macros, but it seems to work: Quickstarted a human game, got Liberty and Protection focus, the default malus for disliked focus (-2) was doubled (-4).

**Comment by geoffthemedio** [comment]
> didn't find other uses of macros including macros

You mean like https://github.com/freeorion/freeorion/blob/master/default/scripting/ship_hulls/organic/organic.macros#L32 ?

**Comment by Oberlus** [comment]
> > didn't find other uses of macros including macros
>
> You mean like https://github.com/freeorion/freeorion/blob/master/default/scripting/ship_hulls/organic/organic.macros#L32 ?

Yes. So it was meant to work OK.

Well, this is ready to merge, unless you prefer some other place to put the macro.

**Comment by geoffthemedio** [comment]
I think you forgot to add and commit the new file

**Comment by Oberlus** [comment]
Fixed.

**Pull request merged**
