### PR TITLE
fix 4952 fix nest eradicator

### LINKED ISSUE #4952: Nest Eradicator doesn't eradicate nest if monster spawns
This happens on recent builds but dunno since when - maybe eradication wasn't all that popular for people to notice.

Essentially you build nest eradicator, and next turn you expect sitrep message that the nest is gone, and nest being gone. But if on that following turn monster spawn also triggers, then the nest doesn't get eradicated.

Looks to be issue with Nest Eradicator's effect having the same stackinggroup as the nest itself: `stackinggroup = "@1@_NEST_STACK"  // groups with @1@_NEST_SPECIAL`

When I remove that stackinggroup part from NEST_ERADICATOR.focs.txt, the nest gets eradicated. It seems that with "always spawn wild", the wild monster doesn't spawn, either. With setting turn off, seems you still get the tamed monster.

Dunno how that works exactly, but looks to me like there should be a different stacking group for nest eradication so the nest actually does get eradicated.

Maybe putting those effects on same stacking group was meant to prevent monster spawn if nest is eradicated, and who knows, maybe it used to work like that, but certainly now it works other way around = prevents nest from eradication, and the monster spawns. Note that while it makes sense for monster not to spawn when nest gets eradicated, it's more important to actually have the nest eradicated, never mind if monster spawns or not

I'm attaching savegames with eradication set up (and random reseeding turned off, but not exactly sure if that helps). Turn 23 is when I build eradicator on Niyat Alpha I. Turn 24 when it completes. Turn 25 when it supposed to eradicate the nest, but it failed, cause a monster (snowflake in this case) spawned

[nest_eradication.zip](https://github.com/user-attachments/files/15586952/nest_eradication.zip)

### PR DESCRIPTION
**Pull request by agrrr3**
another implementation to fix #4952
( based on #4957  )

### CODE REVIEW

**Comment by agrrr3** [comment]
currently completely untested

**Comment by agrrr3** [comment]
works as intended with #4968

**Comment by geoffthemedio** [comment]
> works as intended with #4968

but not without  #4968 ?

**Comment by agrrr3** [comment]
> > works as intended with #4968
> 
> but not without #4968 ?

it should fix the issue without #4968  (skipping activation is the same with or without that PR; but did not playtest). 

just the doing-the-perfect meter estimation in UI is not possible without that PR, as the second round of meter evaluation overwrites the correct result. And that I checked to work with #4968

**Pull request merged**
