### PR TITLE
Add analytics

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Looks like it is easy to measure AI by collecting issued orders.  You don't need to touch actual code.
Here is a sample PR with code. 

Now I print only minimum information (order count).  Later we could build a more sophisticated framework on top of it.  

Here is a sample output.

```
Issuing orders analytics for turn 6
=======================================================
| Order                     | Issued | Failed | Total |
=======================================================
| AdoptPolicy               |        |        |       |
| Aggression                |        |        |     6 |
| AllowStockpileProduction  |      1 |        |     6 |
| Bombard                   |        |        |       |
| ChangeFocus               |      2 |        |    13 |
| ChangeProductionQuantity  |        |        |       |
| Colonize                  |        |        |       |
| CreateShipDesign          |        |        |     1 |
| DeadoptPolicy             |        |        |       |
| DequeueProduction         |        |        |       |
| DequeueTech               |        |        |       |
| EnqueueBuildingProduction |        |        |     1 |
| EnqueueShipProduction     |        |        |     3 |
| EnqueueTech               |        |        |   140 |
| FleetMove                 |      3 |        |    18 |
| FleetTransfer             |        |        |       |
| GiveObjectToEmpire        |        |        |       |
| Invade                    |        |        |       |
| NewFleet                  |        |        |       |
| PauseProduction           |        |        |       |
| Rename                    |        |        |     1 |
| RequeueProduction         |        |        |     1 |
| Scrap                     |        |        |       |
=======================================================
|                           |      6 |      0 |   190 |
=======================================================
```

### CODE REVIEW

**Comment by geoffthemedio** [comment]
What do I*, F*, Turn*, and Total* indicate?

**Comment by Cjkjvfnby** [comment]
> What do I*, F*, Turn*, and Total* indicate?

- Issued succesfuly this turn
- Failed this turn
- Total this turn
- Total for the current session



`*` are added at the table bottom with full names, I just forget to include them to the sample. 

I have aready simplified this table a bit, but haven't test this code yet.

**Comment by hifron** [comment]
Could have impact in diplomacy relations...

**Comment by geoffthemedio** [comment]
@Cjkjvfnby what is the status of this?

**Comment by Cjkjvfnby** [comment]
> Could have impact in diplomacy relations...

It should not, it just counts issues ordered. 

> what is the status of this?

Draft.  This looks like a promising way to measure AI performance.

**Comment by Cjkjvfnby** [comment]
This PR is outdated, closing it.

**Pull request closed without merging**
