### PR TITLE
[AI] Cleanup: update log output

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This should be merged via squash.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
For stuff like this, I think you could just push it yourself without bothering with a pull request, but I don't deal with Python code much myself, so maybe it's preferred otherwise?

**Comment by Vezzra** [comment]
What @geoffthemedio said. @Cjkjvfnby, you're currently pretty much the only active AI dev left, so it's essentially your call. I've taken a quick glance at the changes, they look fine to me, for what it's worth.

**Comment by Cjkjvfnby** [comment]
It is common for me to make some stupid mistakes, so I prefer to make review once again after some times come.

**Comment by Vezzra** [comment]
> It is common for me to make some stupid mistakes

Well, welcome to the club 😉 I'm definitely prone to that too. With simple changes like this however, I'd say just commit it, and worst case, if there is a stupid mistake, fix it with another commit - did that often enough...

**Pull request merged**
