### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This PR is new version of https://github.com/freeorion/freeorion/pull/299
I create it because @evzorge on weekend and cant update to RC1

@evzorge changes have some typos, I fix them and many others.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
It is not final form.  I need to sleep a little.
I will to compare its keys with en.txt
I will create new PR to release branch if release and master have different keys for en.txt

**Comment by geoffthemedio** [comment]
Should probably add evzorge to credits.xml. Feel free to include that in the pull request.

**Comment by Cjkjvfnby** [comment]
This pr is ready to be merged to master.  

What should I do with release 0.4.5? Cherry-pick all commits?

**Comment by geoffthemedio** [comment]
Can you squash into a single commit?

**Comment by Cjkjvfnby** [comment]
Done.

**Pull request merged**
