### PR TITLE
Fix bugged meters on outposts from environmentalism and checkpoints policies

### PR DESCRIPTION
**Pull request by MichaelCourtney**

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
https://github.com/freeorion/freeorion/issues/4885

No other policies charge influence on outposts and outposts do not have influence meter growth/decay.

Tested.

**Comment by MichaelCourtney** [comment]
Damn. Same problem is on environmentalism, I'll have to go check them all.

Environmentalism

**Comment by MichaelCourtney** [comment]
Looked through them all, and could only spot those 2

**Comment by geoffthemedio** [comment]
I guess it's debatable if an unpopulated but terraformed planet should cost the empire influence when environmentalism is adopted, but I suppose this is OK for now.

**Pull request merged**
