### PR TITLE
Reduced shield strengths and costs

### PR DESCRIPTION
**Pull request by MatGB**
~shield strengths equalised with unrefined weapon of each type
~costs reduced propostionately

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
You need to fix hardcoded values in AI code too: https://github.com/freeorion/freeorion/blob/master/default/AI/AIstate.py#L778

**Comment by MatGB** [comment]
GAH! I thought the point of the capacity system was we'd removed the need for hardcoding values. OK, since I still barely read Python, is it just amending those lines of numbers?

**Comment by Dilvish-fo** [comment]
That's one place where we hadn't yet gotten around to changing things over-- I wasn't expecting to need it just quite yet.

**Comment by Morlic-fo** [comment]
https://github.com/freeorion/freeorion/pull/93

**Pull request merged**
