### PR TITLE
Fix Godot Windows URL

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
seems to work

**Comment by Vezzra** [comment]
@o01eg, I get a merge conflict when trying to cherry pick this. Apparently `_build-windows.yaml` has been deleted from the release branch (at least that's how I understood the merge conflict error message I got).

Question is, do we really need to backport this to the release branch? The Godot client is an experimental feature, I see no need to backport adjustments there to the release branch. Unless not doing so might break some build processes...?

**Comment by o01eg** [comment]
Oh, where was refactoring of CI in master but not in release. I'll make it myself.

**Comment by Vezzra** [comment]
Ok. Don't forget to clear the "cherry pick for release" status label once you've done that.

**Pull request merged**
