### PR TITLE
Swap research order of domesticated monsters and nest eradication

### PR DESCRIPTION
**Pull request by MichaelCourtney**

### CODE REVIEW

**Comment by MichaelCourtney** [comment]
tested

**Comment by Blue-Award** [comment]
BTW should this come with some changes to AI, so it prioritizes the new tech in place of the old tech, or does it prioritize, say, organic hulls, and then it knows automatically whatever prereqs are for that?

**Comment by MichaelCourtney** [comment]
> BTW should this come with some changes to AI, so it prioritizes the new tech in place of the old tech, or does it prioritize, say, organic hulls, and then it knows automatically whatever prereqs are for that?

It'll queue the prerequisite when it queues organic hull.
Domesticated Mega Fauna isn't in the tech list, but there's a bit of scripting that inserts it in the queue if the AI has a nest.

**Comment by MichaelCourtney** [comment]
> > BTW should this come with some changes to AI, so it prioritizes the new tech in place of the old tech, or does it prioritize, say, organic hulls, and then it knows automatically whatever prereqs are for that?
> 
> It'll queue the prerequisite when it queues organic hull. Domesticated Mega Fauna isn't in the tech list, but there's a bit of scripting that inserts it in the queue if the AI has a nest.

Note: here is the relevant scripting for fast-forwarding DMF:
https://github.com/freeorion/freeorion/blob/master/default/python/AI/ResearchAI.py#L247-L258

and here you can see where Nascent AI (artificial minds) is in the research tree:
https://github.com/freeorion/freeorion/blob/master/default/python/AI/TechsListsAI.py#L112-L155

so there is potential for it to queue DMF "too early" in terms of it's pre-requisite tech costs

**Pull request merged**
