### PR TITLE
Fixed the Italian language.

### PR DESCRIPTION
**Pull request by LordStephen77**
Correcting existing strings, and completing new strings that were not previously translated.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Thanks for the contribution. Could you please make an explicit statement that you release you changes under the CC-BY-SA 3.0 license? See: https://github.com/freeorion/freeorion/blob/master/default/COPYING

**Comment by LordStephen77** [comment]
@geoffthemedio Thank you. I declare that my contribution is licensed under CC-BY-SA 3.0
I especially love the FreeOrion project, I plan to contribute in the long run. I am at your complete disposal. Thanks so much.

**Comment by Vezzra** [comment]
> I plan to contribute in the long run

Well, in this case, welcome aboard! 😃 

Currently the only translation which is actively maintained is French (by @Ouaz). So, if you plan to stay long term, Italian would be the second one we could keep current.

You might want to get in touch with @Ouaz, he has already been doing the maintain-a-translation thing for quite a while, so he should be able to help you with the process.

Anyway, if you decide to stay with us long term, please also join our [forum](http://freeorion.org/forum/index.php), which is our "main communication hub". There is also an (old) [thread regarding the Italian translation](http://freeorion.org/forum/viewtopic.php?f=27&t=7497).

Last but not least, with becoming a contributor comes the honor of being listed in the credits. 😉 Unless you want us to use a different nick for that than the one you used here (LordStephen77), please let us know. Please also provide your real name, unless you don't want to disclose it and prefer to get listed under your nick only.

**Comment by LordStephen77** [comment]
@Vezzra Thank you. I will be happy to enter the official forum (I found only the freeorion wiki). I am intent on keeping the Italian translation in the long run, with the last commit I improved the corrections a lot and completed new strings that were not translated into Italian. I put my real name in the it.txt file of the translation under the previous user who started the translation of the Italian language. My name is Stefano Peris, I'm 40, and since 1984 I'm dedicated to technology for passion (then also for work as a small independent developer). I'm very attached to the old and glorious C-64 and Commodore Amiga. So FreeOrion for me represents a dive into the heart. I'm going to join the forum so I can introduce myself in a better way and describe my experiences and ideas. Thanks so much. I'm happy to be among you guys :D

**Comment by Vezzra** [comment]
> Thanks so much. I'm happy to be among you guys :D

You're very welcome 😃

**Comment by Ouaz** [comment]
Hi @LordStephen77, and welcome on board!

If you're going to translate FO in italian in the long run, here's how I maintain the FR translation: 

http://freeorion.org/forum/viewtopic.php?f=27&t=9463#p77199

I wrote it for a chinese contributor, but maybe it has been afraid, because it has no more contributed since then. ^^

The biggest part of the work is to catching up the en.txt file when your language file has not been maintained (i.e translated from english) since ages (for italian, since May 2013).

Good luck!

**Pull request merged**
