### PR TITLE
Display current value for troop parts in ship articles

### PR DESCRIPTION
**Pull request by dbenage-cx**
Corrects display of troops in pedia articles.
master:
fo_troop-master

PR:
fo_troop-pr

### CODE REVIEW

**Comment by geoffthemedio** [comment]
When / why is this distinction necessary?

**Comment by dbenage-cx** [comment]
With current master, viewing the pedia page for a ship containing troop parts displays `Troops: 0` on each entry.  Other code expects `Ship::TroopCapacity` to return sum of `InitialPartMeterValue`. (bit short on time atm, will update with screenshots later if needed)

**Comment by dbenage-cx** [comment]
Updated with simpler change.

The "initial" value for parts meters of the temporary ships in this listing will be 0, as the meter has not gone through a turn update.

**Comment by geoffthemedio** [comment]
should do the same for colony capacity

**Comment by dbenage-cx** [comment]
Added

**Pull request merged**
