### PR TITLE
Add pierced description for combat log

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This PR changes the combat log description for fighter attacks so that the shield strength is reported as `pierced`.  This makes the fighter shield piercing ability more visible/discoverable.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
I'm a bit concerned this could be annoying clutter after the initial discovery benefit wears off...

**Comment by LGM-Doyle** [comment]
It replaces the shield strength number in the expanded portion of the display.  It will only show when the player has expanded a Fighter attack report to see how the damage breaks down.

I tried to attach an example image, but github balked.  Here is some ascii art of an expanded fighter combat log report, before this PR:

``````
````>> Fighter attacks AD Griffin Mk3 and does 5 damages
       Weapon: Fighter Weapon  Strength: 5 Shields: 3 Damage: 5````
``````

and after this PR:

``````
````>> Fighter attacks AD Griffin Mk3 and does 5 damages
       Weapon: Fighter Weapon  Strength: 5 Shields: pierced Damage: 5````
``````

Otherwise, it reports the shield strength with no indication that the shields are bypassed.

**Comment by MatGB** [comment]
I think this is a good idea myself, having a shield strength shown when it's not going to do anything is going to confuse and this isn't really clutter given it's a collapsed line rarely looked at.

**Comment by geoffthemedio** [comment]
ok then

**Pull request merged**
