### PR TITLE
Made Acirema home star blue

### LINKED ISSUE #592: Acirema should have a blue star
"Portal is a Radiated world close to an unusually bright Blue Giant Star"

### PR DESCRIPTION
**Pull request by matt474**
Fixes #592 by changing giving the Acirema an effect to make their star blue at the start of a game.

### CODE REVIEW

**Comment by MatGB** [comment]
Have you tested this to see if it causes any weird problems? I can't think of any it would but I never had the time to set up a few games and just run them through to make sure it was fine.

**Comment by matt474** [comment]
I did some testing and I do not see any obvious problems. The script is also very similar to one used for phototropic species in the population macros so I do not think this will result in any new problems.

**Comment by MatGB** [comment]
Yeah, that's what I expect, the only possible issue is having them both turn up in the same system, but that theoretically can't happen as photrophe natives don't do the changing anymore. Cool, thanks.

**Comment by Vezzra** [comment]
@matt474, do you want to provide a real name for the credits, or should I just add you under your nick?

**Comment by matt474** [comment]
I would prefer to use just my nickname for now.

**Pull request merged**
