### PR TITLE
Split Ground Troops species trait into Defensive Ground Troops and Of…

### PR DESCRIPTION
**Pull request by Deepsloth**
…fensive Ground Troops.

### CODE REVIEW

**Comment by Deepsloth** [comment]
As discussed here: http://www.freeorion.org/forum/viewtopic.php?f=15&t=9418

**Comment by geoffthemedio** [comment]
Presumably requires AI adjustments?

**Comment by MatGB** [comment]
Yup, quite significant ones which is why it was put back to post release, it's a really cool feature building on your capacity work but it's going to need some work on the AIs so they don't, eg, build troop ships with Setinon crew but also going to need some work balancing overall. It'll be nice to have species traits that can be used to balance off some of the species and/or give them more flavour though.

**Comment by Dilvish-fo** [comment]
It will be a while till I can spare any time for this.  @Cjkjvfnby @Morlic-fo if either of you care to take this on and make corresponding AI adaptations, you could put those into a PR for Sloth's branch, and then he could accept those so they then become part of this PR.

**Comment by Morlic-fo** [comment]
This should cover the AI as far as offensive traits are concerned (currently untested, will do soon):

https://github.com/Deepsloth/freeorion/pull/3

Is there actually anything related to defensive traits which needs to be updated?

**Comment by Deepsloth** [comment]
The Defensive Ground Troop traits were just renamed, but didn't change.

**Comment by Dilvish-fo** [comment]
Sloth, I think the conflicts here are just minor ones with the stringtable entries, so you should be able to clean them up fairly easily.  Then after you merge in Morlic's PR into your branch, please test it all out some and confirm here that it's all still working fine (at least as far as you can see).  Thanks.

> Is there actually anything related to defensive traits which needs to be updated?

It's my recollection that on the defensive side it's all handled by just checking the actual MaxTroops meter, currently no projections requiring knowledge of the underlying techs (although, on a related note, now that techs affect troop regen, there probably should be a planning adjustment regarding that, which I don't recall adding yet, but it won't be affected by this PR).

**Comment by Deepsloth** [comment]
I'm on vacation at the moment and will be for the next week. Maybe Morlic is willing to create a new clean PR that also includes the AI adjustments?

**Comment by Deepsloth** [comment]
I'm back and created a clean version including Morlics AI changes. The AI looks fine, it managed to conquer natives with the right amount of troop ships (even with bad offensive troop species).

I would create a new PR with everything bundled up as a single commit. Is that acceptable?

**Comment by MatGB** [comment]
Ideally Morlic's commit would be separate so he gets the credit but that's merely ideal, if that's not easy to do (and I've never tried to resolve conflicts so no idea if it is) then a single commit is good.

**Pull request closed without merging**
