### PR TITLE
Fix small issues in CMake for Godot project

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
````
C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\util\OrderSet.h(61,10): error C2039: 'string': is not a member of 'std' [C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\freeorioncommon.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\set(23): message : see declaration of 'std' [C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\freeorioncommon.vcxproj]
C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\util\OrderSet.h(61,25): error C3646: 'Dump': unknown override specifier [C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\freeorioncommon.vcxproj]
C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\util\OrderSet.h(61,25): error C2059: syntax error: '(' [C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\freeorioncommon.vcxproj]
C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\util\OrderSet.h(61,33): error C2238: unexpected token(s) preceding ';' [C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\freeorioncommon.vcxproj]
C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\util\OrderSet.cpp(18,23): error C2039: 'Dump': is not a member of 'OrderSet' [C:\Users\g_top\Desktop\FOSDK11_Godot\FreeOrion\build\freeorioncommon.vcxproj]
````
etc.

**Comment by o01eg** [comment]
It was fixed in https://github.com/freeorion/freeorion/pull/3409 which isn't yet merged.

**Comment by o01eg** [comment]
@geoffthemedio Rebased.

**Comment by geoffthemedio** [comment]
builds without errors for me

**Pull request merged**
