### PR TITLE
Use correct auto aggression icon for new fleet aggression button tooltip

### LINKED ISSUE #1759: Automatic Aggression Tooltip Uses Passive Icon
In the fleets window, the new fleet drop target has an icon that can be switched between passive, aggressive, or automatic determination of new fleet aggression. The passive and aggressive modes show the corresponding icons in the tooltip, but automatic shows the passive icon. It should probably show the automatic icon.
auto_aggression_icon

### PR DESCRIPTION
**Pull request by adrianbroher**
Works for me, tested by looking at default and cycling through aggression options.

Fixes #1759

### CODE REVIEW

**Review by Vezzra — APPROVED** [review]
Fixes #1759 on my Mac.

**Comment by geoffthemedio** [comment]
Bit busy today; if it works for Vezzra it's probly fine.

**Comment by adrianbroher** [comment]
@Vezzra feel free to cherry-pick.

**Comment by Vezzra** [comment]
Done, 4c9cf778e6b0d03ccf1b0a0893ef827f951b5796.

**Pull request merged**
