### PR TITLE
Fix some bugs in AI calculation of max population

### PR DESCRIPTION
**Pull request by Morlic-fo**
Partial progress to #2167.

### CODE REVIEW

**Review by Dilvish-fo — COMMENTED** [review]
Subject to the minor logging correction, looks good

**Comment by Vezzra** [comment]
@Morlic-fo, can you please do the cherry picking? I get a conflict when trying to cherry pick 753419c51ab5ea99685dc045f7e431e5bd67e4c5. I *guess* that `test_calc_max_pop` function has been just a temporary thing for debugging purposes and can probably just removed to clear the conflict, but I usually refrain from performing such corrections on mere assumptions... :wink:

**Comment by Morlic-fo** [comment]
I cherry-picked the first four commits that do the actual bugfixing and ignored the last two which just enhance some debugging functionality not present in the release branch.

**Comment by Vezzra** [comment]
Ah ok, that's been the reason for the conflict. Thanks!

**Pull request merged**
