### PR TITLE
Added the new field Accretion Disc. It reduces supply of all planets …

### PR DESCRIPTION
**Pull request by Deepsloth**
…by -1. They spawn in most black hole systems and in systems where a nebula collapses into a new star.

### CODE REVIEW

**Comment by Deepsloth** [comment]
Discussion: http://www.freeorion.org/forum/viewtopic.php?f=15&t=9693

Next Release Milestone

Could do with an AI update that takes the discs into account when planning supply connectivity of new colonies.

**Comment by Dilvish-fo** [comment]
Sloth, as noted in my PR to your branch (repeating here for other's reference):

> Sloth, this does not actually adapt the AI for the field as you have it currently written.  There may be some reasonably efficient way I don't know about for the AI to determine which planets lie within such a field, but as far as I can see the AI would have to individually check every object to see if it is in the field.  That is surely something we need to change at some point, but I'm not up for that right now.
> 
> So, if you are game to change the structure here so that your field applies a "ACCRETION_DISC_EFFECTS" special to the system (or to the planets if you prefer, but not to both), then this PR should handle it fine.  Theoretically you could leave the actual effects with the Field, and have the special be essentially just a flag for the AI, but for future maintenance between the AI and the special it would probably be best for the actual effects to be in the special.

**Comment by Dilvish-fo** [comment]
Not that this AI adaptation will probably show up as a AIDependencies.py file conflict with that for #322, but it's not what I would call a 'real' conflict; resolving it should be trivially easy.

**Comment by Deepsloth** [comment]
I will add a system special that handles the supply effect. The field will just be a visual representation with right click support.
Concerning the conflict with PR #322, it would be nice if it could be merged soonish, then i can create a new clean PR for the Accretion Disc that doesn't need another update.

**Pull request closed without merging**
