### PR TITLE
Prevent copying by using references, also fixes warnings

### PR DESCRIPTION
**Pull request by rsf92**
I couldn't run the tests (don't know how) but I think this changes ought to be safe

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Most of these are probably pointless or actually counter productive. Eg. a structured binding to two int variables. There should be no substantial extra copying occurring since they are small built in trivial types. If the references are implemented as a separately allocated pointer or multiple pointers, then that would be as big or bigger (8 bytes or more if multiple ponters are used) than the two ints. In practice I'd expect the generated code to be the same anyway.

Cases where the bound object is something substantially bigger than a pointer are different, though.

**Comment by rsf92** [comment]
Well, it reported the warning and now it doesn't.  I figured that somebody with more knowledge than me could potentially see some hiccups with the change.

Maybe it's better to close this PR

**Comment by jlumb-gc** [comment]
> There should be no substantial extra copying occurring since they are small built in trivial types. If the references are implemented as a separately allocated pointer or multiple pointers, then that would be as big or bigger (8 bytes or more if multiple ponters are used) than the two ints. In practice I'd expect the generated code to be the same anyway.

Agreed that there won't be a whole tonne of extra work done, but there will likely be some extra work done which will make the generated instructions slightly less efficient. Iterating over the map's elements by value causes the compiler to copy the pair's elements onto the stack even at a high optimisation level - even for trivial types.
If we instead iterate via const-ref it seems that the compiler can elide this copy and optimize its algo to run directly on the container in-place.

Example with diff on Clang 15 with -O3 using C++20 (using a std::map instead of flat_map. stdout used to ensure our example data / instructions aren't optimised out.)
https://godbolt.org/z/hMYEddEod

**Comment by geoffthemedio** [comment]
reasonable evidence of benefit, so OK

**Pull request merged**
