### PR TITLE
[AI] Update skeleton generator

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
- Code that calculate line where value was yield from is now handle `yield from` and show line of yielded value, not yield form itself.
- Changed species that was used for getting instance.  For some reasons `fo.getSpecies("SP_ABADDONI")` returned None.   This species is also absent in playable races.  Not sure if this is an option in config  that disables it, some mismatch between repo version and binary versions or a bug (this species is in py file and other that worked in FOCS).
- Update skeletons to recent changes.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
Is it ok that "Dockerized Linux / Docker fedora-rawhide (push)" failed?

**Comment by o01eg** [comment]
@Cjkjvfnby You can rebase PR over recent `master` where it was fixed.

**Comment by Cjkjvfnby** [comment]
@o01eg , do you have any ideas why `fo.getSpecies("SP_ABADDONI")` stopped working for this build?

**Comment by o01eg** [comment]
I can only hope it not related to `SP_ABADDONI` was rewritten in Python FOCS.

**Comment by o01eg** [comment]
@Cjkjvfnby How to reproduce issue with `SP_ABADDONI` locally?

**Comment by Cjkjvfnby** [comment]
I'd recommend to use debug chat:

image

**Comment by Cjkjvfnby** [comment]
Or add a lines to the universe generator and check freeoriond.log

```python
    print("Print_all_species")
    for s in fo.get_all_species():
        print("!!!", s)
```

```
20:36:24.039802 {0x0000000203343600} [debug] python : universe_generator.py:203 : Print_all_species
20:36:24.039834 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_ACIREMA
20:36:24.039855 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_ANCIENT_GUARDIANS
20:36:24.039875 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_BANFORO
20:36:24.039895 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_BEIGEGOO
20:36:24.039915 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_CELESTEPHYTE
20:36:24.039935 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_CHATO
20:36:24.039955 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_CRAY
20:36:24.039974 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_CYNOS
20:36:24.039994 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_DERTHREAN
20:36:24.040014 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_EAXAW
20:36:24.040033 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_EGASSEM
20:36:24.040053 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_ETTY
20:36:24.040073 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_EXOBOT
20:36:24.040093 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_EXPERIMENTOR
20:36:24.040112 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_FIFTYSEVEN
20:36:24.040132 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_FULVER
20:36:24.040151 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_FURTHEST
20:36:24.040171 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_GEORGE
20:36:24.040191 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_GISGUFGTHRIM
20:36:24.040211 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_GYSACHE
20:36:24.040230 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_HAPPY
20:36:24.040250 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_HHHOH
20:36:24.040269 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_HUMAN
20:36:24.040289 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_KHAKTURIAN
20:36:24.040309 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_KILANDOW
20:36:24.040328 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_KOBUNTURA
20:36:24.040348 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_LAENFA
20:36:24.040368 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_LEMBALALAM
20:36:24.040387 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_MISIORLA
20:36:24.040407 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_MUURSH
20:36:24.040427 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_NIGHTSIDERS
20:36:24.040446 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_NYMNMN
20:36:24.040466 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_OURBOOLS
20:36:24.040486 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_PHINNERT
20:36:24.040505 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_RAAAGH
20:36:24.040525 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_REPLICON
20:36:24.040545 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_SCYLIOR
20:36:24.040564 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_SETINON
20:36:24.040584 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_SILEXIAN
20:36:24.040604 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_SLEEPERS
20:36:24.040623 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_SLY
20:36:24.040643 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_SSLITH
20:36:24.040663 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_SUPER_TEST
20:36:24.040683 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_TAEGHIRUS
20:36:24.040702 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_THENIAN
20:36:24.040722 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_TRENCHERS
20:36:24.040742 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_TRITH
20:36:24.040761 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_UGMORS
20:36:24.040781 {0x0000000203343600} [debug] python : universe_generator.py:205 : !!! SP_VOLP
```

**Comment by o01eg** [comment]
@Cjkjvfnby I've tried it locally and Abaddoni are shown in log. Could you check if it even parsed? You should get line like:
```
23:37:21.133632 {0x00007f72d74a9100} [debug] timer : ScopedTimer.cpp:48 : parse_file "SP_ABADDONI.focs.py" time:     20.7 ms
```

**Comment by Cjkjvfnby** [comment]
@o01eg , I don't see this entry.  I don't even have "Executing module file" for the species, but could see other python files being parsed.  

I am running compiled build for MacOS "v0.5 [build 2023-01-10.cce1021] CMake" with latest master.  I'll do extra testings when I'll get a new build.

**Comment by Cjkjvfnby** [comment]
@o01eg, I don't see this race on my windows machine too.

Build:  v0.5 [build 2023-01-22.cd421b4] MSVC 2022
Repo version:  195b4a10cda185c5f2c1290841371c67acffa323

**Comment by o01eg** [comment]
Looks strange as I test it on your branch with clean build. Could you post full log of the server?

**Comment by Cjkjvfnby** [comment]
Finally, it's back, now I can see it.

**Pull request merged**
