### PR TITLE
Use Github Actions for Ubuntu builds

### PR DESCRIPTION
**Pull request by o01eg**

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Can you make the various Ubuntu builds have names that appear more different at the start of the names, so they are more distinct in lists where the ends are truncated?
ubuntu builds in list

**Comment by geoffthemedio** [comment]
And could we leave the TravisCI builds running for a bit, so I can get a sense of how they compare?

**Comment by o01eg** [comment]
@geoffthemedio It takes name from workflow name and adds jobs name

I could make it something like "Ubuntu / 18.04 Build FreeOrion ..." and "Ubuntu / 20.04 Build FreeOrion ...".

**Comment by geoffthemedio** [comment]
> I could make it something like "Ubuntu / 18.04 Build FreeOrion ..." and "Ubuntu / 20.04 Build FreeOrion ...".

Looks like it would do what I want.

**Comment by o01eg** [comment]
@geoffthemedio Chaged it.

**Comment by geoffthemedio** [comment]
Are you manually cancelling the AppVeyor builds for some reason...?

otherwise seems fine...

**Comment by o01eg** [comment]
@geoffthemedio Yes, because it unparalleled and slows down check for other PRs.

**Pull request merged**
