### PR TITLE
Start industry and research growth only if happiness is at least five

### PR DESCRIPTION
**Pull request by agrrr3**
This PR delays getting industry/research benefits directly after invasion.

[forum discussion](https://www.freeorion.org/forum/viewtopic.php?t=11355#p97347)

* Apply normal industry and research growth only if happiness is at least five
* Apply force energy structure industry and research growth only if happiness is at least five

This should be playtested - especially xenophobes and also concentration camps. Also not sure if the AI would need to know about this.

### CODE REVIEW

**Comment by TheSilentOne1** [comment]
There needs to be some indication for the player why production and research aren't rising; maybe make use of the planet status indicator.

**Comment by geoffthemedio** [comment]
@agrrr3 status update?

**Comment by agrrr3** [comment]
Need to find time to work on the status indicator if that is a merge blocker.

**Comment by agrrr3** [comment]
I guess the stringtable changes fix the status indicator, because I can simply piggyback on the usually no-colonisation-below-five-happiness status indicator. I just can not verify this currently as my dev setup is not working due to the python3 migration.

**Comment by TheSilentOne1** [comment]
Seems fine to me, so industry and research meters now only start growing once the population treshold has been reached?

**Comment by agrrr3** [comment]
Yes, it works, my compile works again and the text is helpful. 

No playtesting done for xenophobes / concentration camps though.

**Comment by agrrr3** [comment]
Did a short code review to check how xenos and concentration camps work. I think the changes of this PR will not affect the two. xenos scripts do not set industry or research. concentration camps do directly set the industry regardless of the current value. Should be fine. So please remove the work-in-progress, this can be merged.

**Comment by urshmost** [comment]
Some indication in the Industry tooltip for the planet would be helpful, I had been troubleshooting this 'issue' and was about to file a report on it when I found this thread.
**'Conquered Colony Strife -99'** or something

**Pull request merged**
