### PR TITLE
Remove initFreeOrionAI

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
This function have no sense since same can be done at import so just remove it. 
- I did not tested if it works 
- it should be merged close to test build
- need to update wiki after merge

### CODE REVIEW

**Comment by Vezzra** [comment]
AFAICT you have a point here, `initFreeOrionAI` isn't strictly necessary. Looking at the C++ code I can't think of anything that could only be done in this function and not during import of `FreeOrionAI.py`.

I think `initFreeOrionAI` has been provided as an optional, convenient place where AI scripters can run some code that does some basic initialization of the AI client, before the actual game is initialized.

If there aren't any objections, I guess we can remove it. Comments, opinions anyone? @freeorion/ai-team in particular?

**Comment by ghost** [comment]
Tested.  Works.  This function can be safely removed.

**Comment by Vezzra** [comment]
@Cjkjvfnby, please resolve conflicts and rebase. Feel free to merge when done.

**Comment by Cjkjvfnby** [comment]
@Vezzra, done

**Pull request merged**
