### PR TITLE
Add EXTERNAL_RESERVED messages for external applications

### PR DESCRIPTION
**Pull request by o01eg**
Reserves message type so other application like web-server could interact with freeoriond server without changes in the protocol.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
What is the rationale for a gerneric external source message type? Why not have various messages that can be (somehow) sent from an external program, which do specific things?

**Comment by o01eg** [comment]
New messages require protocol changes, don't they? I have no such external applications yet but when I'll get them I'll prefer to use them without waiting for new stable release.

**Comment by geoffthemedio** [comment]
Probably, but a generic message doesn't make much sense to me...  If the new message is the highest enum value , it might not affect the others anyway...

**Comment by o01eg** [comment]
Rebased. Fixed collisions.

**Comment by geoffthemedio** [comment]
Delay is not related to merge conflicts...

**Comment by geoffthemedio** [comment]
I think external application messaging would be better done by extending the UDP discovery server, rather than having an external application connect as a player by TCP. One can already set up, for example, a Python script to send a UDP message to the IP and port of a freeoriond process, with the server inquiry message, and can get back the UDP reply message. The discovery server can be extended to supply an interface for other queries.
 
In the Python interpreter:
````
>>> import socket
>>> UDP_IP = '127.0.0.1'
>>> UDP_PORT = 12345
>>> MESSAGE = 'Yo, can I play Free-O here, dog?'.encode('utf-8')
>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.sendto(MESSAGE, (UDP_IP, UDP_PORT))
32
>>> data, addr = s.recvfrom(1024, 0)
>>> print(data)
b'Word!Fiona'
````

In freeoriond log:
````
15:02:10.061132 {0x00003020} [debug] network : ServerNetworking.cpp:432 : Discovery server received from: 127.0.0.1:50434
message: Yo, can I play Free-O here, dog?
replied: Word!Fiona
````

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/pull/2536 probably supercedes this

**Pull request closed without merging**
