### PR TITLE
fix terraform queue

### PR DESCRIPTION
**Pull request by ghost**
Don't allow multiple terraforming to be queued, or on worlds with Gaiaform.

### CODE REVIEW

**Comment by MatGB** [comment]
I dislike blocking multiple terraformers being built at once, in my recent work I balanced the costs taking into account that you can queue multiples _and_ the current system substantially reduces the micromanagement annoyance of going back to queue the next one repeatedly.  We are hoping to come up with/script a better terraforming system (that probably involves focus settings and is enabled by a single terraforming command center somewhere), in the meantime blocking the use of several at once merely adds to frustration of doing it at all.

Blocking the rest of them, specifically not having the terraform/gaia clash is a very good idea though.

**Comment by Vezzra** [comment]
@spikethehobbitmage, can you edit this PR acording to @MatGB's suggestions?

**Comment by ghost** [comment]
Focus is over abused as it is.
A colony management screen would be much better.

**Comment by ghost** [comment]
This pull request borked somehow.  I'm going to delete and re-create it.  :/

**Comment by MatGB** [comment]
I would love a colony management screen (or even a big extension or Objects and allowing queueing from there), but it's way outside my remit, I go with what I can script.

**Comment by geoffthemedio** [comment]
So this just fixes a couple line endings now? Please adjust the pull request name if that's all it's doing...

**Comment by MatGB** [comment]
There appears to be some confusion, Spike created a PR from his master, I merged it, now his master is doing something else but this (old) PR is showing those changes instead.

There was a different PR in which fixed some linebreak issues Ouaz introduced accidentally by directly uploading a file.  Git's weird.

**Pull request closed without merging**
