### PR TITLE
[AI] Add getters for inner colonization variables

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Colonization module give public access to variables that store some important game state.
I suggest to restrict access to variables directly and use getters instead.

@Dilvish-fo, this changes will be useful  for new ResearchAI.  I did not update `ResearchAI.py` to avoid conflicts.

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
To whatever extent we were really concerned about this, it seems to me the better approach would be to use the @property decorator (as had been done in the now-defunct AITarget class).  (A module like ColonisationAI is still derived from object and so is compatible with @property, I believe.)    For the particular ones you've actually covered here, I have no special concern about them since these are all just scalar values and so there is not really any chance of them being accidentally modified by some client code, but I wouldn't object to them being @propertied.

ColonisationAI attributes that have a more complex value, where there really could be some risk of client code accidentally modifying it, and therefor be some real protection to be had from @property, include things like pilot_ratings (a dict which is also used by ProductionAI), colony_status (a dict which is also also used by PriorityAI), and a number of other non-scalar attributes like that.  So I guess for those things we could have the getter return a copy of the underlying object, to protect it from accidental change.

**Comment by genestack-solomatin** [comment]
Module does not support `property` decorator.  

I don't want to replace all variables to getters now, since it will take a lot of time. I am already have big branch with Research and don't want to have two big projects at one time.

**Comment by Dilvish-fo** [comment]
> Module does not support property decorator. 

Ah, yeah, at least not without [some extra glue](http://www.dr-josiah.com/2013/12/properties-on-python-modules.html) (and note, I mean the direct code, not using his mprop package), which might not be worth it for us to hassle with, although it really doesn't seem too bad to me.

> I don't want to replace all variables to getters now, since it will take a lot of time.

OK, sure, I didn't think I was suggesting that we replace them all; I was simply saying that the ones where getters seemed useful to me were different than the ones you are proposing.  Did my reasoning make sense to you?

**Comment by Cjkjvfnby** [comment]
We already have some magic in `extend_free_orion_AI_interface.py`.  It is quite common python magic, but still can confuse coders.  Module properties magic is much confusing. It change default python behavior.

**Comment by geoffthemedio** [comment]
@Dilvish-fo so is this OK to merge, or rejected, or needs some minor updates...?

**Comment by geoffthemedio** [comment]
given lack of follow up comments and seeming harmlessness of changes, will merge...

**Comment by Dilvish-fo** [comment]
Ah, ok, thanks for clearing up those lingering PRs; I had been checking up
on things on our forum boards but had been forgetting to check my github
notices.

**Pull request merged**
