### PR TITLE
Fix pylint warnings part 2

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
Fixed almost all pylint warning except old imports (looks like it is not required) and zero division (will do it in the next PR).

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
I don't understand whan happen in tests.

```
17:54:39.935399 {0x00007f82419ab740} [debug] python : <string>:3 : Python current directory set to /freeorion/default/python/chat
17:54:39.935547 {0x00007f82419ab740} [info] python : chat.py:41 : Chat : [[PLAYER_ENTERED_GAME,TestPlayer]] <freeorion.GGColor object at 0x7f82417f5d00>
17:54:39.936003 {0x00007f7eddffb700} [error] network : ClientNetworking.cpp:514 : ClientNetworking::NetworkingThread() : Networking thread will be terminated due to unhandled exception error #9 "Bad file descriptor"
17:54:40.732595 {0x00007f7eed4a3480} [error] test : ClientAppFixture.cpp:115 : Disconnected
/freeorion/test/system/SmokeTestHostless.cpp:148: error: fatal error: in "SmokeTestHostless/hostless_server": critical check ProcessMessages(start_time, MAX_WAITING_SEC) has failed
17:54:40.732748 {0x00007f7eed4a3480} [debug] test : Process.cpp:271 : Process::Impl::Kill calling kill(m_process_id, SIGKILL)
17:54:40.732780 {0x00007f7eed4a3480} [debug] test : Process.cpp:273 : Process::Impl::Kill calling waitpid(m_process_id, &status, 0)
17:54:40.740534 {0x00007f7eed4a3480} [debug] test : Process.cpp:275 : Process::Impl::Kill done
17:54:40.740836 {0x00007f7eed4a3480} [debug] test : Universe.cpp:161 : Reset id allocators with highest object id = -1 and highest design id = 296

*** 1 failure is detected in the test module "FreeOrion unit/coverage tests game"

    Start 4: TestButton
4/4 Test #4: TestButton .......................   Passed    0.02 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) =  47.19 sec

The following tests FAILED:
	  3 - SmokeTestHostless (Failed)
```

**Comment by o01eg** [comment]
> I don't understand whan happen in tests.

I suppose "Bad file descriptor" is a Travis CI-only spontaneous bug, so in this case it is better to re-try job.

**Comment by geoffthemedio** [comment]
> in this case it is better to re-try job.

Meaning the person who submitted or modified the pull request or commit should log in and re-start the tests, or the tests should be modified to automatically retry a few times if that particular error happens?

**Comment by o01eg** [comment]
> Meaning the person who submitted or modified the pull request or commit should log in and re-start the tests, or the tests should be modified to automatically retry a few times if that particular error happens?

It would be nice to re-try tests if they failed on CI.

**Comment by geoffthemedio** [comment]
> > Meaning the person who submitted or modified the pull request or commit should log in and re-start the tests, or the tests should be modified to automatically retry a few times if that particular error happens?
> 
> It would be nice to re-try tests if they failed on CI.

Same question...

**Comment by Cjkjvfnby** [comment]
This execution time kills me. 

Looks like I got new errors.

image

**Comment by Cjkjvfnby** [comment]
@Morlic-fo , this PR can be reviewed.

**Review by Morlic-fo — APPROVED** [review]
LGTM

**Pull request merged**
