### PR TITLE
shiphulls without slots in shipdesigns - optional shipparts

### PR DESCRIPTION
**Pull request by banduri**
- making shipparts optional for the parser so it accepts shipdesigns
  containing a shiphull that does not have any slots and so no parts
- storing custom shipdesigns will only write out shipparts if present

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
shiphull without slots, Why?

**Comment by MatGB** [comment]
The existing decoy/comsat model is an example of that, if we do go towards parts for upkeep not hulls then having some decoys around in battle even aggressively might sometimes make tactical sense (I wouldn't, but some would)

**Comment by banduri** [comment]
sometimes i get stuck in the early game. Esp. if the system with the same planet type as the homeplanet is occupied by a monster i cannot defeat right now. Then it would be nice to have a similar effect like the logistic hull which would refill my scouts. Binding that effect to a ship part would make fuel an obsoleted concept since every ship could just have that ship part and be done with the problem.

Advanced tactics could allow some sort of supply relays or moveable area effects like merchant ships that cannot protection them self. Ambassador or sabotage ship are other game elements that IMHO should not have any additional ship parts.

**Comment by geoffthemedio** [comment]
This is misleadingly described and probably incomplete.

It's already possible to script a ship design with no parts by putting "" for each of the required parts.

This does nothing about making it more possible to have a hull with no slots.

It also doesn't do anything about the existing code in ShipDesign::ShipDesign which will fill up a design's parts with "" for any missing parts, meaning the modified ShipDesign::Dump code probably won't work as expected.

**Comment by Vezzra** [comment]
@geoffthemedio, any point of keeping that PR? Judging by your last reply, it's incomplete at best and useless at worst in its current state, and there hasn't been any response by @banduri since.

Otherwise we could just close it.

**Pull request closed without merging**
