### PR TITLE
Advanced Ground Troop Pod and Troops balancing

### PR DESCRIPTION
**Pull request by Deepsloth**
1. Nanotech Cybernetics unlocks the ship part "Advanced Ground Troop Pod", which has twice the cost and twice the capacity of the regular one.
2. The Self Defense tech (a starting tech) will grant a bonus of 0.2 troops per population instead of a flat 2.
3. The Cyborgs tech will grant an additional bonus of 0.2 per population.
4. Natives will have troops calculated by 10 + 0.2 per pop (instead of a flat 12).

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
Sloth, it looks like you set this up without making a special branch for it, so if you make any more commits to your local master branch before this pull request gets merged/closed, those commits would automatically get made part of this pull request (if I'm understanding stuff right, at least ;-) ).

So Mat, if you're going to test it out then be sure later to double check for any last minute changes before merging.

**Comment by Deepsloth** [comment]
Dilvish, i don't think that is the case. If i understand Git correctly, the pull request is just for the one commit.

But i will be on vacation for the next 2 weeks anyway, so no danger of new commits by me.

**Comment by Dilvish-fo** [comment]
from [github help](https://help.github.com/articles/using-pull-requests/#sending-the-pull-request)  

"After your pull request is sent, any new commits pushed to your branch will automatically be added to the pull request. This is especially useful if you need to make more changes."

**Comment by MatGB** [comment]
Quite happy with how this plays overall, think we can still do more to make troops work better and for good/bad troops to be more interesting, but this is an improvement.

**Pull request merged**
