### PR TITLE
Compile Fixes GCC11 MSVC2019

### PR DESCRIPTION
**Pull request by geoffthemedio**
-Parse game rules into GameRulesTypeMap instead of incomplete type GameRules, hopefully fixing compile issues with GCC11 and MSVC2019 (v142) toolset
-Add MSVC2019 project files, updated to v142 toolset

### CODE REVIEW

**Comment by o01eg** [comment]
I suppose we could backport https://github.com/freeorion/freeorion/pull/3496 too

**Comment by geoffthemedio** [comment]
> I suppose we could backport #3496 too

sure; that at least shouldn't require half re-implementing a bunch of changes...

**Comment by geoffthemedio** [comment]
@o01eg can you confirm whether this works on GCC11?

**Comment by o01eg** [comment]
Yes, it works with gcc11.

**Pull request merged**
