### PR TITLE
German translation (ships, monsters, buildings, specials)

### PR DESCRIPTION
**Pull request by PaddiLu**
Added german translations for the following categories:
- Monsters
- Buildings
- Specials
- Ship parts
- Ship hulls
- Premade ship designs
- Macros

The names and descriptions in these categories are now fully translated, except for the hull SH_EXP_OUTPOST_HULL which I wasn't sure what to do with (I suspect the english name and description to be outdated).

I also updated, fixed and in a few cases reworked existing translations in the above categories. Lastly, I added myself to the list of translators.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
> the hull SH_EXP_OUTPOST_HULL which I wasn't sure what to do with (I suspect the english name and description to be outdated).

The [Experimontor Outpost Hull strings](https://github.com/freeorion/freeorion/blob/master/default/stringtables/en.txt#L14233) are still used for [the hull](https://github.com/freeorion/freeorion/blob/master/default/scripting/ship_hulls/monster/SH_EXP_OUTPOST_HULL.focs.txt) in scripted content definitions. The description is intentionally story-related, not functional. Why do you think it is out of date in the english stringtable?

**Comment by PaddiLu** [comment]
> Why do you think it is out of date in the english stringtable?

I was confused because the hull is described as part of a transport vessel, while the ship it belongs to (Experiment Zero) is described as a guard vessel.

Anyways, I just translated it after all. And while I was at it, I noticed that I missed the colony buildings and translated them as well.

**Comment by geoffthemedio** [comment]
I've been waiting for comments re: [this post](https://www.freeorion.org/forum/viewtopic.php?p=95446#p95446) but there haven't been any yet...

**Comment by geoffthemedio** [comment]
With this stringtable, I get a few errors in the client log:
````
09:26:10.558711 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'KRAKEN_NEST_SPECIAL_DESC' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
09:26:10.558711 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'KRAKEN_NEST_SPECIAL_DESC' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
09:26:10.567747 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'BLD_SOL_ACCEL' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
09:26:10.567747 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'BLD_SOL_ACCEL_DESC' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
09:26:10.578727 [error] client : StringTable.cpp:214 : Unresolved key expansion: BLD_GAS_GIANT_GENERATOR in: C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt.
````

There are also a bunch of debug messages about strings not being in the primary stringtable, but being gotten from the backup / default english one.

**Comment by Vezzra** [comment]
Can any of our German native speakers take a look at this? I can't, don't have the time...

> There are also a bunch of debug messages about strings not being in the primary stringtable, but being gotten from the backup / default english one.

If I understand correctly, German translation was only done for the categories cited in the OP. So I'd expect missing strings.

**Comment by geoffthemedio** [comment]
There was a follow up forum post that reacted posatively...

**Comment by PaddiLu** [comment]
> With this stringtable, I get a few errors in the client log:
> 
> ```
> 09:26:10.558711 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'KRAKEN_NEST_SPECIAL_DESC' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
> 09:26:10.558711 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'KRAKEN_NEST_SPECIAL_DESC' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
> 09:26:10.567747 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'BLD_SOL_ACCEL' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
> 09:26:10.567747 [error] client : StringTable.cpp:134 : Duplicate string ID found: 'BLD_SOL_ACCEL_DESC' in file: 'C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt'.  Ignoring duplicate.
> 09:26:10.578727 [error] client : StringTable.cpp:214 : Unresolved key expansion: BLD_GAS_GIANT_GENERATOR in: C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt.
> ```

Should be fixed now.

> There are also a bunch of debug messages about strings not being in the primary stringtable, but being gotten from the backup / default english one.

I only translated part of the stringtable. Even with these additions, there are still thousands of strings missing.

**Comment by geoffthemedio** [comment]
````
10:50:32.169177 [error] client : StringTable.cpp:214 : Unresolved key expansion: STAR_ORANDE in: C:\Users\Geoff\Desktop\FreeOrionSDK9\FreeOrionAlt2\default\stringtables\de.txt.
````

**Pull request merged**
