### PR TITLE
Reject pointer selection for hidden windows

### LINKED ISSUE #652: Hidden child windows intermittently obstruct interaction
When a child window is hidden, the area under it is not always completely intractable until the window is fully brought into focus.

For me, this is mostly apparent when using a large 'pedia window in the research screen (and this is ~90% reproducible here):
- Open research screen
- Resize 'Pedia to fill a majority of the area.
- Hide the 'Pedia window
- Hover over a tech that would have been under the 'Pedia window (tooltip shows)
- Attempt to double click on the same tech (fails to add to queue, hover text no longer shows)
- Click on an area outside of the 'Pedia window area.
- Double click on same tech (succeeds) 

Production screen is not reliably reproducible (there is less interaction with map view), the common occurrences appear to happen on the first instance of viewing the production screen.

### PR DESCRIPTION
**Pull request by dbenage-cx**
Fixes #652

### CODE REVIEW

**Comment by dbenage-cx** [comment]
Minimum change for the issue.  If you'd rather, this might be handled in GG::Wnd and then re-checked in any overriden InWindow.

**Comment by geoffthemedio** [comment]
A modification of this sort just for CUIWnd seems rather odd and prone to causing unexpected behaviour. I'm not sure what the base GG code is assuming InWindow function will do. I think a better fix would be to check the visibility in places where a child Wnd's InWindow is directly called, and not bother checking InWindow in cases where a non-visible Wnd shouldn't be checked.

**Comment by dbenage-cx** [comment]
Ty Geoff

**Comment by geoffthemedio** [comment]
looks reasonable and simple enough, though probably has unexpected consequence, but I suppose we'll just have to figure out what those are...

**Pull request merged**
