### PR TITLE
Removes TechType, which is essentially unused.

### PR DESCRIPTION
**Pull request by geoffthemedio**
Not sure if there is any impact on the AI, or if anyone would object to removing this...

### CODE REVIEW

**Comment by Vezzra** [comment]
There is probably no reason to have a dedicated enum for that in the backend code, but the _concept_ of the theory - application - refinement classification of techs is a sound one IMO, and we should keep it.

**Comment by geoffthemedio** [comment]
Could add tags to techs, similar to ship parts and hulls, for purposes of making such classifications in-game, such as a species liking it when empires research a lot of theories vs. non-theoretical stuff.

**Comment by Vezzra** [comment]
It's more than that. Each tech used to display if it is a theory, application or refinement to the player, I think that's important to know at a quick glance if a tech is a theoretical prerequisite (which normally will just unlock a branch of the tech tree without giving you something), an application or refinement.

That's probably retained anyway, I'm just not sure by looking at the code changes...

**Comment by geoffthemedio** [comment]
There is presently no visual indication of that, other than the recently-added but not complete set of icons on tech panels.

**Comment by Vezzra** [comment]
Maybe I'm misunderstanding what you're talking about, but what I meant was this:

techtype

**Comment by geoffthemedio** [comment]
"Theoeretical Prerequisite" in that is determined by

```
    short_description = "THEORY_SHORT_DESC"
```

and has nothing to do with

```
    techtype = Theory
```

in the tech script.

**Comment by Vezzra** [comment]
Ah yes, see, that's what I haven't been sure about. So, as long as these indicators remain, fine with me.

Builds and runs ok on OSX and Linux.

**Pull request merged**
