### PR TITLE
Save AI state right after start of a game

### PR DESCRIPTION
**Pull request by Grummel7**
This is a partial fix for #3800. AI now calls setSaveStateString right after starting up.
@geoffthemedio: If you delay the initial autosave until all AIs have called it, that should do.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Delaying the initial autosave seems tricky to get right... It's initiated by the human client, which would thus need to know how long to wait... Or the server could wait after getting the message, but depending how long the AIs take to send in info, other messages could arrive during the wait, and it would require setting up something on the server to set a flag that it should do an autosave later when it gets more info, and to check for that flag whenever that info is received...

Also, just setting the AI state string on the AI client doesn't communicate that to the server, so some additional network message will be needed, unless the server queries the AIs for state info during the autosave... perhaps just in cases when it doesn't already have info from them...?

**Comment by Grummel7** [comment]
I wonder if this is even the right way to tackle the issue.

The Max aggression is stored with the game settings, isn't it? Couldn't we just start the AIs as if it was a new game when the same game is from turn 1 and they haven't stored a status yet?

**Comment by geoffthemedio** [comment]
Depending how aggression is picked given the max aggression, picking a new aggression when loading would potentially result in a different assignment of aggressions to AIs on each reload.

**Comment by Morlic-fo** [comment]
> Depending how aggression is picked given the max aggression, picking a new aggression when loading would potentially result in a different assignment of aggressions to AIs on each reload.

Sorry, your discussion happened while I was reading source code for initial issue. Current implementation appears to be properly seeded by saved values. I don't think there is a strong argument to consider future implementations that may not properly seed their RNG...

**Comment by Grummel7** [comment]
Well, even if the aggression level changes, it is just as random as before. When somebody reloads a turn 1 save game, the AIs have not yet done anything after all.

**Comment by Vezzra** [comment]
@Grummel7, closed as abandoned, invalid, ...?

**Comment by Grummel7** [comment]
> @Grummel7, closed as abandoned, invalid, ...?

This idea for a fix was too complicated, see Geoffs comment.
The discussion is ongoing in the linked issue.

**Pull request closed without merging**
