### PR TITLE
Add right click context for production wnd pedia

### PR DESCRIPTION
**Pull request by dbenage-cx**
Adds a right click context for production window pedia lookup.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Doesn't seem to work for me... I get no pedia option in the production item list when right clicking on an item...

**Comment by dbenage-cx** [comment]
Added to queue as well (just in case), sorry for the wasted effort.
I don't see anything hindering cross-platform outright, will start a build on windows tonight and figure out what I missed.

**Comment by dbenage-cx** [comment]
Working here?
prod_3

**Comment by geoffthemedio** [comment]
Seems to work for me now. Would be good to also have pedia lookup on tech queue items as well.

Also, some handling of a case where the item.build_type isn't one of the two cases you've handled would be good. Add an error line to the log and abort?

**Pull request merged**
