### PR TITLE
[FOCS] Rename scripting common to macroses

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
There is an inconvenience when you want to use IDE to work with AI and scripts, both use folders with name common. In runtime, it's okay, since the folder is different, but IDE provides autocomplete only for one of them. This makes coding a bit complicated.

The solution is to rename either scrips/common (like in this PR) or python/common.

@geoffthemedio , @o01eg  what do you think?

### CODE REVIEW

**Comment by o01eg** [comment]
Looks fine. I also think having two `common` is issue.

**Comment by geoffthemedio** [comment]
`macroses` -> `macros`

**Comment by Cjkjvfnby** [comment]
Forcepashed it.  


Included: 
- https://github.com/freeorion/freeorion/pull/4800
- https://github.com/freeorion/freeorion/pull/4796
Only Python files are moved.  I'd prefer to make it in two steps.

**Comment by Cjkjvfnby** [comment]
It looks like it's some python path is missing.  @o01eg could you help me with that?

```
 2: [2023-12-09 22:43:32.712342] [0x00007ff84ce1a700] [info]    Couldn't find file for module spec focs
2: [2023-12-09 22:43:32.712444] [0x00007ff84ce1a700] [info]    parse_file "Categories.inf.py" time:     1225 µs
2: [2023-12-09 22:43:32.713783] [0x00007ff84ce1a700] [info]    Couldn't find file for module spec macros
2: [2023-12-09 22:43:32.713995] [0x00007ff84ce1a700] [info]    Traceback (most recent call last):
2: [2023-12-09 22:43:32.714030] [0x00007ff84ce1a700] [info]      File "<string>", line 1, in <module>
2: [2023-12-09 22:43:32.714037] [0x00007ff84ce1a700] [info]    ModuleNotFoundError: No module named 'macros'
2: [2023-12-09 22:43:32.714043] [0x00007ff84ce1a700] [info]    Unable to parse data file /Users/runner/work/freeorion/freeorion/test-scripting/techs/learning/ALGO_ELEGANCE.focs.py
2: [2023-12-09 22:43:32.714661] [0x00007ff84ce1a700] [info]    Couldn't find file for module spec macros
2: [2023-12-09 22:43:32.714747] [0x00007ff84ce1a700] [info]    Traceback (most recent call last):
2: [2023-12-09 22:43:32.714756] [0x00007ff84ce1a700] [info]      File "<string>", line 1, in <module>
2: [2023-12-09 22:43:32.714776] [0x00007ff84ce1a700] [info]    ModuleNotFoundError: No module named 'macros'
2: [2023-12-09 22:43:32.714785] [0x00007ff84ce1a700] [info]    Unable to parse data file /Users/runner/work/freeorion/freeorion/test-scripting/techs/growth/ORBITAL_HAB.focs.py
2: [2023-12-09 22:43:32.714795] [0x00007ff84ce1a700] [info]    Techs Parsing time:     3596 µs
2: [2023-12-09 22:43:32.714817] [0x00007ff84ce1a700] [info]    WaitForPendingUnlocked another wait_for round
2: [2023-12-09 22:43:32.714823] [0x00007ff84ce1a700] [info]    Retrieve result of parsing "techs".
```

**Comment by o01eg** [comment]
It fails on `test-scripting\buildings\ART_BLACK_HOLE.focs.py` while there no such file. Could you rebase it over recent `master`?

Also it doesn't seemed to fix `Duplicate module named "multiplier"`.

**Comment by Cjkjvfnby** [comment]
>It fails on test-scripting\buildings\ART_BLACK_HOLE.focs.py while there no such file. Could you rebase it over recent master?

Done

> Also it doesn't seemed to fix Duplicate module named "multiplier".

This problem arises when it's two modules with the same name.  And one of them should be renamed.  After merging this, I'll take a look.

**Comment by o01eg** [comment]
Now checks are passed. But it's better to make history linear with real rebase before.

**Comment by Cjkjvfnby** [comment]
> Now checks are passed. But it's better to make history linear with real rebase before.

Is this rebase is good enough?

изображение

**Comment by o01eg** [comment]
I expected actual `git rebase master` locally. I did it myself although.

**Comment by Cjkjvfnby** [comment]
> I expected actual git rebase master locally. I did it myself although.

Can we merge it?

**Pull request merged**
